Map.Api=function(b){this.executeWithPush=!1;this.map=b};Map.Api.prototype=new Map;"string"==typeof thisversion&&map.checkVersion(thisversion)?map.Api=new Map.Api(map):alert("Map.Api incompatible !");Map.Api.prototype.setMapFeatures=function(b){this.map.setFeatures(b)};Map.Api.prototype.getMapFeatures=function(){return this.map.getFeatures()};Map.Api.prototype.setMapLocal=function(b,c){for(var d=c.split("|"),e=0;e<d.length;e++)loadSVGIncludes(null,b,d[e])};
Map.Api.prototype.setLocalString=function(b,c){this.map.Dictionary.replace(b,c)};Map.Api.prototype.setBookmark=function(){try{var b=this.map.Zoom.getBox(),c=this.map.Scale.getMapCoordinate(b.x,b.y),d=this.map.Scale.getMapCoordinate(b.x+b.width,b.y+b.height);bookmarkList.createBookmark(null,"MinBoundX='"+c.x+"' MaxBoundX='"+d.x+"' MinBoundY='"+d.y+"' MaxBoundY='"+c.y)}catch(e){alert("Bookmark could not be set !")}};Map.Api.prototype.gotoBookmark=function(b){try{bookmarkList.exec(b)}catch(c){alert("Bookmarks could not be found !")}};
Map.Api.prototype.clearBookmarks=function(){try{bookmarkList.clear()}catch(b){alert("Bookmarks could not be deleted !")}};Map.Api.prototype.getMapBox=function(){return new box(this.map.Scale.mapPosition.x/this.map.Scale.normalX(1),this.map.Scale.mapPosition.y/this.map.Scale.normalX(1),this.map.Scale.bBox.width/this.map.Scale.normalX(1),this.map.Scale.bBox.height/this.map.Scale.normalX(1))};Map.Api.prototype.resizeCanvas=function(b,c,d,e,g){return this.map.Scale.resizeCanvas(b,c,d,e,g)};
Map.Api.prototype.doZoomMapToFullExtend=function(){this.map.Zoom.doZoomMapToLayer("maplayer")};Map.Api.prototype.doZoomMap=function(b,c){return this.map.Zoom.doZoomMap(b,c)};Map.Api.prototype.doPanMap=function(b,c){this.map.Zoom.setNewPan(b,c)};Map.Api.prototype.doZoomMapToWidgetRect=function(b){this.map.Zoom.doZoomMapToWidgetRect(b)};Map.Api.prototype.doCenterMapToGeoPosition=function(b,c){this.map.Zoom.doCenterMapToGeoPosition(b,c)};
Map.Api.prototype.doCenterMapToGeoBounds=function(b,c,d,e){this.map.Zoom.doCenterMapToGeoBounds(b,c,d,e)};Map.Api.prototype.doZoomMapToGeoBounds=function(b,c,d,e){this.map.Zoom.doZoomMapToGeoBounds(b,c,d,e)};Map.Api.prototype.doSetMapToGeoBounds=function(b,c,d,e){180>e-c&&(fPreserveMapRatio=!1);this.map.Zoom.doSetMapToGeoBounds(b,c,d,e);setTimeout("fPreserveMapRatio = true;",5E3)};Map.Api.prototype.doZoomMapToView=function(b,c){this.map.Zoom.doZoomMapToView(b,c)};
Map.Api.prototype.getCenterOfMapInGeoPosition=function(){return this.map.Zoom.getCenterOfMapInGeoPosition()};Map.Api.prototype.getBoundsOfMapInGeoBounds=function(){return this.map.Zoom.getBoundsOfMapInGeoBounds()};Map.Api.prototype.pendingNewGeoBounds=function(){return fPendingNewGeoBounds};Map.Api.prototype.setVisibility=function(b){var c=new MapTool(evt,"nothing");"invisible"==b?c.hideLayer(evt):c.showLayer(evt)};Map.Api.prototype.hideOverviewMap=function(){this.map.Zoom.hideOverviewMap()};
Map.Api.prototype.showOverviewMap=function(){this.map.Zoom.showOverviewMap()};Map.Api.prototype.hideNorthArrow=function(){this.map.Viewport.hideNorthArrow()};Map.Api.prototype.showNorthArrow=function(){this.map.Viewport.showNorthArrow()};Map.Api.prototype.backwards=function(){zoomAndPanHistory.backwards()};Map.Api.prototype.forwards=function(){zoomAndPanHistory.forwards()};Map.Api.prototype.toggleThemeValues=function(b){try{this.map.Themes.toggleThemeValues(null,b)}catch(c){}};
Map.Api.prototype.toggleThemeLegends=function(b){try{this.map.Themes.toggleThemeLegends(null,b)}catch(c){}};Map.Api.prototype.minimizeThemeLegends=function(){try{this.map.Themes.minimizeThemeLegends(null)}catch(b){}};Map.Api.prototype.changeObjectScaling=function(b){this.map.Layer.changeObjectScaling(null,b)};Map.Api.prototype.changeLabelScaling=function(b){this.map.Layer.changeLabelScaling(null,b)};Map.Api.prototype.changeLineScaling=function(b){this.map.Layer.changeLineScaling(null,b)};
Map.Api.prototype.getScaleParam=function(){return this.map.Scale.getScaleParam()};Map.Api.prototype.setScaleParam=function(b){this.map.Scale.setScaleParam(b)};Map.Api.prototype.changeRotation=function(b){this.map.Scale.changeRotation(null,b)};Map.Api.prototype.setRotation=function(b){this.map.Scale.setRotation(null,b)};Map.Api.prototype.setMapBackgroundColor=function(b){this.map.Viewport.setBackgroundColor(b)};Map.Api.prototype.togglePanBorder=function(){this.map.Viewport.togglePanBorder()};
Map.Api.prototype.setPrintScaling=function(){this.map.Event.doPrintZoom()};Map.Api.prototype.froozeMap=function(b){fFroozeDynamicContent=b};Map.Api.prototype.setMapClip=function(b){this.map.Viewport.clipMap(b)};Map.Api.prototype.setLayerClip=function(b,c){this.map.Viewport.clipLayer(b,c)};Map.Api.prototype.switchLayer=function(b,c){this.map.Layer.switchLayer(null,b,null,c)};Map.Api.prototype.getLayer=function(){return this.map.Layer.listA};Map.Api.prototype.getLayerDependency=function(){return this.map.Layer.depListA};
Map.Api.prototype.setMapTool=function(b){setMapTool(b)};Map.Api.prototype.getMapTool=function(){return getMapTool()};Map.Api.prototype.isMapTool=function(b){return"overviewmap"==b&&this.map.Zoom.overviewThumbObj||szMapToolType==b?"yes":"no"};Map.Api.prototype.isNotMapTool=function(b){return"no"==this.isMapTool(b)?"yes":"no"};
Map.Api.prototype.switchMapTheme=function(b,c){if(b)if(c=c||(this.map.Layer.isLayerOn(b)?"off":"on"),map.Legend){var d=SVGDocument.getElementById("legend:"+c+":this:item:"+b);d?this.map.Legend.execLegendMouseClickOnItem(null,d,"legend:"+c+":this:item:"+b):"on"==c?(this.map.Layer.switchLayer(null,b,null,!0),map.Legend.switchLegendCheckBox(null,b,"inline")):(this.map.Layer.switchLayer(null,b,null,!1),map.Legend.switchLegendCheckBox(null,b,"none"))}else"on"==c?this.map.Layer.switchLayer(null,b,null,
!0):this.map.Layer.switchLayer(null,b,null,!1)};Map.Api.prototype.getMapTheme=function(b){var c=b.split("#")[0].split(":")[0];"legend"==c&&(c=b.split(":")[2]);return this.map.Layer.listA[c]};Map.Api.prototype.getMapThemeRendererField=function(b){return(b=this.getMapTheme(b))?b.szRenderer:null};Map.Api.prototype.getMapThemeDataRow=function(b,c){var d=map.Themes.getTheme(b);return d?map.Themes.getDataRow(c,d):null};
Map.Api.prototype.getMapThemeChart=function(b,c,d,e){return(b=map.Themes.getTheme(b))?map.Themes.getChart(c,d,e,b):null};Map.Api.prototype.getMapThemeHistogram=function(b,c,d,e){return(c=map.Themes.getTheme(b))?map.Themes.getHistogram(b,d,e,c):null};Map.Api.prototype.executeJavascriptWithMessage=function(b,c,d){b&&typeof("undefined"!=b)&&(this.map.pushAction("map.Api.executeWithPush = true;"),this.map.pushAction('executeWithMessage("'+b.replace(/\"/gi,'\\"')+'","'+c+'",'+d+")"),this.map.pushAction("map.Api.executeWithPush = false;"))};
Map.Api.prototype.displayMessage=function(b,c,d){displayMessage(b,c,d)};
Map.Api.prototype.flipLegend=function(){var b=getMatrix(this.map.Scale.offsetNode);b[4]=0==b[4]?this.map.Scale.viewBox.width-this.map.Scale.bBox.width:this.map.Scale.viewBox.width-(this.map.Scale.mapPosition.x+this.map.Scale.bBox.width);setMatrix(this.map.Scale.offsetNode,b);this.map.Scale=new Map.Scale;this.map.Viewport=new Map.Viewport(evt);var c=SVGDocument.getElementById("legend:group");c&&(b=getMatrix(c),0==b[4]?(this.map.Dom.getBox(c),b[4]=this.map.Scale.mapPosition.x+this.map.Scale.bBox.width):
b[4]=0,setMatrix(c,b),displayScale(evt,"bottom"),this.map.Toolbar.refresh(evt))};var __nLegendSpace=0;
Map.Api.prototype.extendMap=function(){var b=getMatrix(this.map.Scale.offsetNode);if(__nLegendSpace=b[4]){b[4]=0;setMatrix(this.map.Scale.offsetNode,b);this.map.Zoom.doPanMap(__nLegendSpace/this.map.Scale.normalX(1)/2,0);this.map.Scale.reset();this.map.Viewport.reformat();try{this.map.Legend.hide()}catch(c){}try{HTMLWindow.ixmaps.htmlgui_onMapResize(window)}catch(d){this.map.Viewport.reformat()}}else fInitLegendOff=!0};
Map.Api.prototype.normalMap=function(){if(!(0>=__nLegendSpace)){var b=getMatrix(this.map.Scale.offsetNode);b[4]=__nLegendSpace;setMatrix(this.map.Scale.offsetNode,b);this.map.Zoom.doPanMap(-__nLegendSpace/this.map.Scale.normalX(1)/2,0);this.map.Scale.reset();this.map.Viewport.reformat();try{this.map.Legend.show()}catch(c){}try{HTMLWindow.ixmaps.htmlgui_onMapResize(window)}catch(d){this.map.Viewport.reformat()}}};
Map.Api.prototype.hideLegend=function(){var b=SVGDocument.getElementById("legend:group");b&&b.style.setProperty("display","none","")};Map.Api.prototype.showLegend=function(){var b=SVGDocument.getElementById("legend:group");b&&b.style.setProperty("display","inline","")};Map.Api.prototype.clearAll=function(){this.map.clearAll()};Map.Api.prototype.clearAllCharts=function(){this.map.Themes&&this.map.Themes.removeAllCharts()};Map.Api.prototype.clearAllChoroplethe=function(){this.map.Themes&&this.map.Themes.removeAllChoroplethe()};
Map.Api.prototype.clearAllOverlays=function(){SVGPopupGroup&&SVGToolsGroup.fu.clear();SVGPopupGroup&&SVGFixedGroup.fu.clear();SVGPopupGroup&&SVGPopupGroup.fu.clear();SVGPopupGroup&&SVGMessageGroup.fu.clear();this.map.Themes&&this.map.Themes.removeAllSelections()};Map.Api.prototype.getActualEnvelopeString=function(){return this.map.Zoom.getEnvelopeString()};Map.Api.prototype.getActualEnvelopeCoordinates=function(){return this.map.Zoom.getEnvelope()};
Map.Api.prototype.printActualEnvelope=function(){var b=this.map.Zoom.getBox(),c=this.map.Scale.getMapCoordinate(b.x,b.y),b=this.map.Scale.getMapCoordinate(b.x+b.width,b.y+b.height);szPrint='<ENVELOPE minx="'+c.x+'"\n';szPrint+='          maxx="'+b.x+'"\n';szPrint+='          miny="'+b.y+'"\n';szPrint+='          maxy="'+c.y+'" name="Initial_Extent" />';try{htmlgui_prettyPrintXML("Actual zoom Envelope (for SVGGIS XML)",szPrint+"\n")}catch(d){alert(szEnvelope)}};
Map.Api.prototype.createTextLink=function(b,c,d){b=this.map.Dom.newGroup(b);var e=null;d.match(/javascript/)?(e=this.map.Dom.constructNode("a",b,{"xlink:href":""}),c=this.map.Dom.newText(e,0,this.map.Scale.normalY(.75*nNormalFontSize),"font-family:arial;font-size:"+this.map.Scale.normalY(.75*nNormalFontSize)+"px;fill:blue;",c),e=this.map.Dom.newShape("rect",e,0,0,this.map.Scale.normalX(10*nNormalFontSize),this.map.Scale.normalY(nNormalFontSize+3),"fill:#fffff0;stroke:#000000;opacity:0"),c&&(e.setAttributeNS(null,
"onclick",d),e.setAttributeNS(null,"onmousedown","this.map.Event.stopMouseEvent(evt)"),e.setAttributeNS(null,"onmouseup","this.map.Event.stopMouseEvent(evt)"))):(e=this.map.Dom.constructNode("a",b,{"xlink:href":d}),this.map.Dom.newText(e,0,this.map.Scale.normalY(.75*nNormalFontSize),"font-family:arial;font-size:"+this.map.Scale.normalY(.75*nNormalFontSize)+"px;fill:blue;",c));return b};
Map.Api.prototype.createInfoBubble=function(b,c,d){if(b&&c){d||(d=1);var e="bubble:"+String(Math.random()+":movable");c=createTextGrid(SVGDocument,SVGFixedGroup,e,c,d);d=new point(this.map.Scale.normalX(-10),this.map.Scale.normalY(15));var g=this.map.Scale.getScreenPosition(b),h=this.map.Scale.clipWidgetObjectToSVG(c,g,d);c.fu.setPosition(h.x,h.y);b=null;b=this.map.Dom.getBox(c);(new Button(c,"xx","BUTTON","#delete_button","this.map.Dom.removeElementById('"+e+"')","","remove")).setPosition(b.width,
this.map.Scale.normalY(9));b.width+=this.map.Scale.normalY(9);szPeek=h.y==g.y+d.y?"top":"bottom";szPeek=h.x==g.x+d.x?szPeek+"left":szPeek+"right";this.map.Scale.normalX(15);var e=this.map.Scale.normalX(5),g=this.map.Scale.normalX(5),h=this.map.Scale.normalX(5),k=d.y,l=this.map.Scale.normalX(15);d=-d.x-e-g;var f="M"+b.x+","+b.y+" ",f=f+("m"+g+",0 ");"topleft"==szPeek?(f=f+("l"+e+",0 ")+("l"+d+","+-k+" "),f+="l"+(-d+l)+","+ +k+" ",f+="l"+(b.width-2*g-e-l)+",0 "):"topright"==szPeek?(f+="l"+(b.width-
2*g-e-l)+",0 ",f+="l"+(-d+l)+","+-k+" ",f+="l"+d+","+ +k+" ",f+="l"+e+",0 "):f+="l"+(b.width-2*g)+",0 ";f+="q"+g+",0 "+g+","+h+" ";f+="l0,"+(b.height-2*h)+" ";f+="q0,"+h+" "+-g+","+h+" ";"bottomright"==szPeek?(f+="l"+-e+",0 ",f+="l"+-d+","+k+" ",f+="l"+(+d-l)+","+-k+" ",f+="l"+(-b.width+2*g+e+l)+",0 "):"bottomleft"==szPeek?(f+="l"+(-b.width+2*g+e+l)+",0 ",f+="l"+(d-l)+","+k+" ",f+="l"+-d+","+-k+" ",f+="l"+-e+",0 "):f+="l"+(-b.width+2*g)+",0 ";f+="q"+-g+",0 "+-g+","+-h+" ";f+="l0,"+(-b.height+2*h)+
" ";f+="q0,"+-h+" "+g+","+-h+" ";f+="z";b=this.map.Dom.newShape("path",c,f,"fill:white;stroke:grey");c.style.setProperty("filter","url(#DropShadowFilterTools)","");b.parentNode.insertBefore(b,b.parentNode.firstChild)}};
Map.Api.prototype.createInfoContainer=function(b,c,d,e,g,h){if(b&&c)return h||(h="fix"),d=new point(e,g),e=new point(0,0),h=new InfoContainer(SVGDocument,SVGPopupGroup,b+":more"+(h.match(/pointer/)?"":":movable"),d,e,h),b=createTextGrid(SVGDocument,h.workspaceNode,b+":more:textgrid",c,2),this.map.Dictionary.applyToNode(b),h.reformat(),this.map.Event.stopMouseEvent(evt),h};Map.Api.prototype.getContextMenuTarget=function(){return this.map.Event.contextMenuObj};Map.Api.prototype.getMapToolShape=function(){return mapToolList.toolShape};
Map.Api.prototype.getShapePoints=function(b){if("path"==b.nodeName){var c=[],d=null,e=new point(0,0);b=b.getAttributeNS(null,"d");b=b.substr(1,b.length-2);szDA=b.split(" ");for(b=0;b<szDA.length;b++)if("l"==szDA[b]||"L"==szDA[b])d=szDA[b];else{var g=szDA[b].split(",");c[c.length]="l"==d?new point(e.x+Number(g[0]),e.y+Number(g[1])):new point(Number(g[0]),Number(g[1]));e=c[c.length-1]}return c}return null};
Map.Api.prototype.getShapeCoordinates=function(b){if("path"==b.nodeName&&(b=this.getShapePoints(b))){var c=null,c=null,d=[];for(a in b)c=this.map.Scale.getMapPosition(b[a].x,b[a].y),c=this.map.Scale.getMapCoordinate(c.x,c.y),d[d.length]=new point(c.x,c.y);return d}return null};Map.Api.prototype.getSurface=function(b){if(b){if("g"==b.parentNode.nodeName){var c=b.parentNode.getAttributeNS(szMapNs,"area");if(c&&c.length)return Number(c)}if(b=this.getShapePoints(b))return __doGetPolygonSurface(b)}return null};
Map.Api.prototype.printSurface=function(b){if(b){var c=this.getSurface(b);if(c)return c=this.map.Scale.formatSurfaceString(c)+"  ",this.createInfoBubble(b,Array(c),1)}};Map.Api.prototype.displayContextMenuTargetInfo=function(){var b=this.map.Event.contextMenuObj;b&&displayInfoDelayed(null,b,10)};Map.Api.prototype.removeContextMenuTarget=function(){this.map.Event.contextMenuObj&&(this.map.Dom.clearGroup(SVGToolsGroup),mapToolList.clear())};
Map.Api.prototype.removeContextMapTool=function(){var b=this.map.Event.contextMenuObj;if(b)for(;b;b=b.parentNode)if(b.getAttributeNS(null,"id").match(/maptoolnode/)){mapToolList.removeMapTool(b);break}};
Map.Api.prototype.createContextMenuTargetBuffer=function(){var b=this.map.Event.contextMenuObj;if(b){b=new MapObject(b);if(b.szId.match(/legend:setactive/))var c=b.szId.split("legend:setactive:")[1],d=c.split("::")[0],c=c.split("::")[1],e=this.map.Layer.getLayerObjOfNode(b.objNode);this.map.Themes.newTheme2(d,e.szRenderer,"","type:CHART|BUFFER;align:center;colorscheme:#aa4400;ranges:"+c+";buffersize:1000;opacity:0.3;label:Ripetitore","Buffer (1 km)","Ripetitore")}};
Map.Api.prototype.createTheme=function(b,c,d,e,g,h,k){return this.map.Themes.newTheme(b,c,d,e,g,h,k)};Map.Api.prototype.newMapTheme=function(b,c,d,e,g,h){if(this.map.Zoom.fExternalZoom)this.map.pushAction('map.Api.newMapTheme("'+b+'","'+c+'","'+d+'","'+e+'","'+g+'","'+h+'")');else if(this.executeWithPush)this.map.pushAction('map.Themes.newTheme2("'+b+'","'+c+'","'+d+'","'+e+'","'+g+'","'+h+'")');else return this.map.Themes.newTheme2(b,c,d,e,g,h)};Map.Api.prototype.newMapThemeByObj=function(b){return this.map.Themes.newThemeByObj(b)};
Map.Api.prototype.changeContextThemeStyle=function(b,c){var d=new MapObject(b);this.map.Themes.changeThemeStyle(null,d.szId,c)};Map.Api.prototype.changeThemeStyle=function(b,c,d){this.map.Themes.changeThemeStyle(null,b,c,d)};Map.Api.prototype.showThemeClass=function(b,c,d){this.map.Themes.showClass(null,b,c,d)};Map.Api.prototype.hideThemeClass=function(b,c,d){this.map.Themes.hideClass(null,b,c,d)};Map.Api.prototype.markThemeClass=function(b,c,d){this.map.Themes.markClass(null,b,c,d)};
Map.Api.prototype.unmarkThemeClass=function(b,c,d){this.map.Themes.unmarkClass(null,b,c,d)};Map.Api.prototype.filterThemeItems=function(b,c,d){this.map.Themes.filterItems(null,b,c,d)};Map.Api.prototype.selectFilterItems=function(b){this.map.Themes.selectFilterItems(null,b)};Map.Api.prototype.popupThemeStyleMenu=function(b){this.map.Themes.chartTypeMenu(null,b)};Map.Api.prototype.nextClipFrame=function(b){this.map.Themes.nextClipFrame(b)};
Map.Api.prototype.setClipFrame=function(b,c){this.map.Themes.setClipFrame(b,c)};Map.Api.prototype.pauseClip=function(b){this.map.Themes.pauseClip(b)};Map.Api.prototype.startClip=function(b){this.map.Themes.startClip(b)};Map.Api.prototype.getTheme=function(b){return this.map.Themes.getTheme(b)};Map.Api.prototype.getAllThemes=function(){return this.map.Themes.getAllThemes()};Map.Api.prototype.getMapThemeDefinitionStrings=function(){return this.map.Themes.getAllThemeDefinitionStrings()};
Map.Api.prototype.getMapThemeStyleString=function(b){return this.map.Themes.getMapThemeStyleString(b)};Map.Api.prototype.getMapThemeDefinitionObj=function(b){return this.map.Themes.getMapThemeDefinitionObj(b)};Map.Api.prototype.removeTheme=function(b){this.map.Themes.removeTheme(null,b)};Map.Api.prototype.removeAllThemes=function(){this.map.Themes.removeAll()};Map.Api.prototype.getThemeId=function(b){return b?b.szId:null};
Map.Api.prototype.setThemeExternalData=function(b,c,d){c&&(this._dataObj=c,eval(d+" = this._dataObj"));this.map.Themes.fWaitingforData=!1;this.map.Themes.execute()};Map.Api.prototype.removeElementById=function(b){(b=SVGDocument.getElementById(b))&&b.parentNode&&b.parentNode.removeChild(b)};Map.Api.prototype.getShapeId=function(b){return(b=new MapObject(b))?b.szId:null};Map.Api.prototype.getShapeLayerObj=function(b){return(b=this.map.Layer.getLayerObjOfNode(b))?b:null};
Map.Api.prototype.getShapeLayerName=function(b){return(b=this.map.Layer.getLayerObjOfNode(b))?b.szName:null};Map.Api.prototype.getShapeMetadataArray=function(b){var c=this.map.Dom.getAttributeByNodeOrParents(b,szMapNs,"info"),d="";(b=new MapObject(b))&&(d=this.map.Dom.getAttributeByNodeOrParents(b.objNode.parentNode,szMapNs,"info"));if(d&&c&&(szTitleA=d.split("|"),szDataA=c.split("|"),szTitleA.length&&szDataA.length)){c=[];for(d=0;d<szTitleA.length;d++)c[szTitleA[d]]=szDataA[d];return c}return null};
