Map.Api=function(b){this.executeWithPush=!1;this.map=b};Map.Api.prototype=new Map;"string"==typeof thisversion&&map.checkVersion(thisversion)?map.Api=new Map.Api(map):alert("Map.Api incompatible !");Map.Api.prototype.setMapFeatures=function(b){this.map.setFeatures(b)};Map.Api.prototype.getMapFeatures=function(){return this.map.getFeatures()};Map.Api.prototype.setMapLocal=function(b,d){for(var e=d.split("|"),f=0;f<e.length;f++)loadSVGIncludes(null,b,e[f])};
Map.Api.prototype.setLocalString=function(b,d){this.map.Dictionary.replace(b,d)};
Map.Api.prototype.setMapLayer=function(b){if(map.fInitializing||map.isLoading())this.map.pushAction('map.Api.setMapLayer("'+b+'"');else for(l in b=JSON.parse(b),b){b[l].display&&"none"==b[l].display&&this.switchLayer(String(l),!1);if(b[l].off)for(c in b[l].off)this.switchLayer(l+"::"+b[l].off[c],!1);if(b[l].on){var d=this.getLayer()[l].categoryA;if(d){for(x in d)this.switchLayer(l+"::"+x,!1);for(c in b[l].on)b[l].on[c].length&&this.switchLayer(l+"::"+b[l].on[c],!0)}}}};Map.Api.prototype.loadMap=function(b){this.map.loadMap(b)};
Map.Api.prototype.setBookmark=function(){try{var b=this.map.Zoom.getBox(),d=this.map.Scale.getMapCoordinate(b.x,b.y),e=this.map.Scale.getMapCoordinate(b.x+b.width,b.y+b.height);bookmarkList.createBookmark(null,"MinBoundX='"+d.x+"' MaxBoundX='"+e.x+"' MinBoundY='"+e.y+"' MaxBoundY='"+d.y)}catch(f){alert("Bookmark could not be set !")}};Map.Api.prototype.gotoBookmark=function(b){try{bookmarkList.exec(b)}catch(d){alert("Bookmarks could not be found !")}};Map.Api.prototype.clearBookmarks=function(){try{bookmarkList.clear()}catch(b){alert("Bookmarks could not be deleted !")}};
Map.Api.prototype.getMapBox=function(){return new box(this.map.Scale.mapPosition.x/this.map.Scale.normalX(1),this.map.Scale.mapPosition.y/this.map.Scale.normalX(1),this.map.Scale.bBox.width/this.map.Scale.normalX(1),this.map.Scale.bBox.height/this.map.Scale.normalX(1))};Map.Api.prototype.resizeCanvas=function(b,d,e,f,h){return this.map.Scale.resizeCanvas(b,d,e,f,h)};Map.Api.prototype.doZoomMapToFullExtend=function(){this.map.Zoom.doZoomMapToLayer("maplayer")};
Map.Api.prototype.doZoomMap=function(b,d){return this.map.Zoom.doZoomMap(b,d)};Map.Api.prototype.doPanMap=function(b,d){this.map.Zoom.setNewPan(b,d)};Map.Api.prototype.doZoomMapToWidgetRect=function(b){this.map.Zoom.doZoomMapToWidgetRect(b)};Map.Api.prototype.doCenterMapToGeoPosition=function(b,d){this.map.Zoom.doCenterMapToGeoPosition(b,d)};Map.Api.prototype.doCenterMapToGeoBounds=function(b,d,e,f){this.map.Zoom.doCenterMapToGeoBounds(b,d,e,f)};
Map.Api.prototype.doZoomMapToGeoBounds=function(b,d,e,f){this.map.Zoom.doZoomMapToGeoBounds(b,d,e,f)};Map.Api.prototype.doSetMapToGeoBounds=function(b,d,e,f){180>f-d&&(fPreserveMapRatio=!1);this.map.Zoom.doSetMapToGeoBounds(b,d,e,f);setTimeout("fPreserveMapRatio = true;",5E3)};Map.Api.prototype.doZoomMapToView=function(b,d){this.map.Zoom.doZoomMapToView(b,d)};Map.Api.prototype.getCenterOfMapInGeoPosition=function(){return this.map.Zoom.getCenterOfMapInGeoPosition()};
Map.Api.prototype.getBoundsOfMapInGeoBounds=function(){return this.map.Zoom.getBoundsOfMapInGeoBounds()};Map.Api.prototype.getMapScale=function(){return String(Math.floor(map.Scale.nTrueMapScale*map.Scale.nZoomScale))};Map.Api.prototype.pendingNewGeoBounds=function(){return fPendingNewGeoBounds};Map.Api.prototype.setVisibility=function(b){var d=new MapTool(null,"nothing");"invisible"==b?d.hideLayer(null):d.showLayer(null)};Map.Api.prototype.hideOverviewMap=function(){};
Map.Api.prototype.showOverviewMap=function(){};Map.Api.prototype.hideNorthArrow=function(){this.map.Viewport.hideNorthArrow()};Map.Api.prototype.showNorthArrow=function(){this.map.Viewport.showNorthArrow()};Map.Api.prototype.backwards=function(){zoomAndPanHistory.backwards()};Map.Api.prototype.forwards=function(){zoomAndPanHistory.forwards()};Map.Api.prototype.toggleThemeValues=function(b){try{this.map.Themes.toggleThemeValues(null,b)}catch(d){}};
Map.Api.prototype.toggleThemeLegends=function(b){try{this.map.Themes.toggleThemeLegends(null,b)}catch(d){}};Map.Api.prototype.minimizeThemeLegends=function(){try{this.map.Themes.minimizeThemeLegends(null)}catch(b){}};Map.Api.prototype.changeObjectScaling=function(b){this.map.Layer.changeObjectScaling(null,b)};Map.Api.prototype.changeLabelScaling=function(b){this.map.Layer.changeLabelScaling(null,b)};Map.Api.prototype.changeLineScaling=function(b){this.map.Layer.changeLineScaling(null,b)};
Map.Api.prototype.getScaleParam=function(){return this.map.Scale.getScaleParam()};Map.Api.prototype.setScaleParam=function(b){this.map.Scale.setScaleParam(b)};Map.Api.prototype.changeRotation=function(b){this.map.Scale.changeRotation(null,b)};Map.Api.prototype.setRotation=function(b){this.map.Scale.setRotation(null,b)};Map.Api.prototype.setMapBackgroundColor=function(b){this.map.Viewport.setBackgroundColor(b)};Map.Api.prototype.togglePanBorder=function(){this.map.Viewport.togglePanBorder()};
Map.Api.prototype.setPrintScaling=function(){this.map.Event.doPrintZoom()};Map.Api.prototype.froozeMap=function(b){fFroozeDynamicContent=b};Map.Api.prototype.setMapClip=function(b){this.map.Viewport.clipMap(b)};Map.Api.prototype.setLayerClip=function(b,d){this.map.Viewport.clipLayer(b,d)};Map.Api.prototype.switchLayer=function(b,d){this.map.Layer.switchLayer(null,b,null,d)};Map.Api.prototype.getLayer=function(){return this.map.Layer.listA};Map.Api.prototype.getLayerDependency=function(){return this.map.Layer.depListA};
Map.Api.prototype.getTileInfo=function(){return this.map.Tiles};Map.Api.prototype.setMapTool=function(b){setMapTool(b)};Map.Api.prototype.getMapTool=function(){return szMapToolType};Map.Api.prototype.isMapTool=function(b){return szMapToolType==b?"yes":"no"};Map.Api.prototype.isNotMapTool=function(b){return"no"==this.isMapTool(b)?"yes":"no"};
Map.Api.prototype.switchMapTheme=function(b,d){if(b)if(d=d||(this.map.Layer.isLayerOn(b)?"off":"on"),map.Legend){var e=SVGDocument.getElementById("legend:"+d+":this:item:"+b);e?this.map.Legend.execLegendMouseClickOnItem(null,e,"legend:"+d+":this:item:"+b):"on"==d?(this.map.Layer.switchLayer(null,b,null,!0),map.Legend.switchLegendCheckBox(null,b,"inline")):(this.map.Layer.switchLayer(null,b,null,!1),map.Legend.switchLegendCheckBox(null,b,"none"))}else"on"==d?this.map.Layer.switchLayer(null,b,null,
!0):this.map.Layer.switchLayer(null,b,null,!1)};Map.Api.prototype.getMapTheme=function(b){var d=b.split("#")[0].split(":")[0];"legend"==d&&(d=b.split(":")[2]);return this.map.Layer.listA[d]};Map.Api.prototype.getMapThemeRendererField=function(b){return(b=this.getMapTheme(b))?b.szRenderer:null};Map.Api.prototype.getMapThemeDataRow=function(b,d){var e=map.Themes.getTheme(b);return e?map.Themes.getDataRow(d,e):null};
Map.Api.prototype.getMapThemeItemPosition=function(b,d){var e=map.Themes.getTheme(b);return e?(e=e.getItemNodes(d),map.Scale.getScreenPosition(e[0])):null};Map.Api.prototype.getMapThemeChart=function(b,d,e,f){return(b=map.Themes.getTheme(b))?map.Themes.getChart(d,e,f,b):null};Map.Api.prototype.getMapThemeHistogram=function(b,d,e,f){return(d=map.Themes.getTheme(b))?map.Themes.getHistogram(b,e,f,d):null};
Map.Api.prototype.executeJavascriptWithMessage=function(b,d,e){b&&typeof("undefined"!=b)&&(this.map.pushAction("map.Api.executeWithPush = true;"),this.map.pushAction('executeWithMessage("'+b.replace(/\\/gi,"\\\\").replace(/\"/gi,'\\"')+'","'+d+'",'+e+")"),this.map.pushAction("map.Api.executeWithPush = false;"))};Map.Api.prototype.displayMessage=function(b,d,e){displayMessage(b,d,e)};
Map.Api.prototype.flipLegend=function(){var b=getMatrix(this.map.Scale.offsetNode);b[4]=0==b[4]?this.map.Scale.viewBox.width-this.map.Scale.bBox.width:this.map.Scale.viewBox.width-(this.map.Scale.mapPosition.x+this.map.Scale.bBox.width);setMatrix(this.map.Scale.offsetNode,b);this.map.Scale=new Map.Scale;this.map.Viewport=new Map.Viewport(evt);var d=SVGDocument.getElementById("legend:group");d&&(b=getMatrix(d),0==b[4]?(this.map.Dom.getBox(d),b[4]=this.map.Scale.mapPosition.x+this.map.Scale.bBox.width):
b[4]=0,setMatrix(d,b),displayScale(evt,"bottom"),this.map.Toolbar.refresh(evt))};var __nLegendSpace=0;
Map.Api.prototype.extendMap=function(){var b=getMatrix(this.map.Scale.offsetNode);if(__nLegendSpace=b[4]){b[4]=0;setMatrix(this.map.Scale.offsetNode,b);this.map.Zoom.doPanMap(__nLegendSpace/this.map.Scale.normalX(1)/2,0);this.map.Scale.reset();this.map.Viewport.reformat();try{this.map.Legend.hide()}catch(d){}try{HTMLWindow.ixmaps.htmlgui_onMapResize(window)}catch(e){this.map.Viewport.reformat()}}else fInitLegendOff=!0};
Map.Api.prototype.normalMap=function(){if(!(0>=__nLegendSpace)){var b=getMatrix(this.map.Scale.offsetNode);b[4]=__nLegendSpace;setMatrix(this.map.Scale.offsetNode,b);this.map.Zoom.doPanMap(-__nLegendSpace/this.map.Scale.normalX(1)/2,0);this.map.Scale.reset();this.map.Viewport.reformat();try{this.map.Legend.show()}catch(d){}try{HTMLWindow.ixmaps.htmlgui_onMapResize(window)}catch(e){this.map.Viewport.reformat()}}};
Map.Api.prototype.hideLegend=function(){var b=SVGDocument.getElementById("legend:group");b&&b.style.setProperty("display","none","")};Map.Api.prototype.showLegend=function(){var b=SVGDocument.getElementById("legend:group");b&&b.style.setProperty("display","inline","")};Map.Api.prototype.clearAll=function(){this.map.Themes.fWaitingforData=!0;this.map.clearAll()};Map.Api.prototype.clearAllCharts=function(){this.map.Themes&&this.map.Themes.removeAllCharts()};
Map.Api.prototype.clearAllChoropleth=function(){this.map.Themes&&this.map.Themes.removeAllChoropleth()};Map.Api.prototype.clearAllOverlays=function(){SVGPopupGroup&&SVGToolsGroup.fu.clear();SVGPopupGroup&&SVGFixedGroup.fu.clear();SVGPopupGroup&&SVGPopupGroup.fu.clear();SVGPopupGroup&&SVGMessageGroup.fu.clear();this.map.Themes&&this.map.Themes.removeAllSelections()};Map.Api.prototype.getActualEnvelopeString=function(){return this.map.Zoom.getEnvelopeString()};
Map.Api.prototype.getActualEnvelopeCoordinates=function(){return this.map.Zoom.getEnvelope()};
Map.Api.prototype.printActualEnvelope=function(){var b=this.map.Zoom.getBox(),d=this.map.Scale.getMapCoordinate(b.x,b.y),b=this.map.Scale.getMapCoordinate(b.x+b.width,b.y+b.height);szPrint='<ENVELOPE minx="'+d.x+'"\n';szPrint+='          maxx="'+b.x+'"\n';szPrint+='          miny="'+b.y+'"\n';szPrint+='          maxy="'+d.y+'" name="Initial_Extent" />';try{htmlgui_prettyPrintXML("Actual zoom Envelope (for SVGGIS XML)",szPrint+"\n")}catch(e){alert(szEnvelope)}};
Map.Api.prototype.createTextLink=function(b,d,e){b=this.map.Dom.newGroup(b);var f=null;e.match(/javascript/)?(f=this.map.Dom.constructNode("a",b,{"xlink:href":""}),d=this.map.Dom.newText(f,0,this.map.Scale.normalY(.75*nNormalFontSize),"font-family:arial;font-size:"+this.map.Scale.normalY(.75*nNormalFontSize)+"px;fill:blue;",d),f=this.map.Dom.newShape("rect",f,0,0,this.map.Scale.normalX(10*nNormalFontSize),this.map.Scale.normalY(nNormalFontSize+3),"fill:#fffff0;stroke:#000000;opacity:0"),d&&(f.setAttributeNS(null,
"onclick",e),f.setAttributeNS(null,"onmousedown","this.map.Event.stopMouseEvent(evt)"),f.setAttributeNS(null,"onmouseup","this.map.Event.stopMouseEvent(evt)"))):(f=this.map.Dom.constructNode("a",b,{"xlink:href":e}),this.map.Dom.newText(f,0,this.map.Scale.normalY(.75*nNormalFontSize),"font-family:arial;font-size:"+this.map.Scale.normalY(.75*nNormalFontSize)+"px;fill:blue;",d));return b};
Map.Api.prototype.createInfoBubble=function(b,d,e){if(b&&d){e||(e=1);var f="bubble:"+String(Math.random()+":movable");d=createTextGrid(SVGDocument,SVGFixedGroup,f,d,e);e=new point(this.map.Scale.normalX(-10),this.map.Scale.normalY(15));var h=this.map.Scale.getScreenPosition(b),k=this.map.Scale.clipWidgetObjectToSVG(d,h,e);d.fu.setPosition(k.x,k.y);b=null;b=this.map.Dom.getBox(d);(new Button(d,"xx","BUTTON","#delete_button","this.map.Dom.removeElementById('"+f+"')","","remove")).setPosition(b.width,
this.map.Scale.normalY(9));b.width+=this.map.Scale.normalY(9);szPeek=k.y==h.y+e.y?"top":"bottom";szPeek=k.x==h.x+e.x?szPeek+"left":szPeek+"right";this.map.Scale.normalX(15);var f=this.map.Scale.normalX(5),h=this.map.Scale.normalX(5),k=this.map.Scale.normalX(5),m=e.y,n=this.map.Scale.normalX(15);e=-e.x-f-h;var g="M"+b.x+","+b.y+" ",g=g+("m"+h+",0 ");"topleft"==szPeek?(g=g+("l"+f+",0 ")+("l"+e+","+-m+" "),g+="l"+(-e+n)+","+ +m+" ",g+="l"+(b.width-2*h-f-n)+",0 "):"topright"==szPeek?(g+="l"+(b.width-
2*h-f-n)+",0 ",g+="l"+(-e+n)+","+-m+" ",g+="l"+e+","+ +m+" ",g+="l"+f+",0 "):g+="l"+(b.width-2*h)+",0 ";g+="q"+h+",0 "+h+","+k+" ";g+="l0,"+(b.height-2*k)+" ";g+="q0,"+k+" "+-h+","+k+" ";"bottomright"==szPeek?(g+="l"+-f+",0 ",g+="l"+-e+","+m+" ",g+="l"+(+e-n)+","+-m+" ",g+="l"+(-b.width+2*h+f+n)+",0 "):"bottomleft"==szPeek?(g+="l"+(-b.width+2*h+f+n)+",0 ",g+="l"+(e-n)+","+m+" ",g+="l"+-e+","+-m+" ",g+="l"+-f+",0 "):g+="l"+(-b.width+2*h)+",0 ";g+="q"+-h+",0 "+-h+","+-k+" ";g+="l0,"+(-b.height+2*k)+
" ";g+="q0,"+-k+" "+h+","+-k+" ";g+="z";b=this.map.Dom.newShape("path",d,g,"fill:white;stroke:grey");d.style.setProperty("filter","url(#DropShadowFilterTools)","");b.parentNode.insertBefore(b,b.parentNode.firstChild)}};
Map.Api.prototype.createInfoContainer=function(b,d,e,f,h,k){if(b&&d)return k||(k="fix"),e=new point(f,h),f=new point(0,0),k=new InfoContainer(SVGDocument,SVGPopupGroup,b+":more"+(k.match(/pointer/)?"":":movable"),e,f,k),b=createTextGrid(SVGDocument,k.workspaceNode,b+":more:textgrid",d,2),this.map.Dictionary.applyToNode(b),k.reformat(),this.map.Event.stopMouseEvent(evt),k};Map.Api.prototype.getContextMenuTarget=function(){return this.map.Event.contextMenuObj};Map.Api.prototype.getMapToolShape=function(){return mapToolList.toolShape};
Map.Api.prototype.getShapePoints=function(b){if("path"==b.nodeName){var d=[],e=null,f=new point(0,0);b=b.getAttributeNS(null,"d");b=b.substr(1,b.length-2);szDA=b.split(" ");for(b=0;b<szDA.length;b++)if("l"==szDA[b]||"L"==szDA[b])e=szDA[b];else{var h=szDA[b].split(",");d[d.length]="l"==e?new point(f.x+Number(h[0]),f.y+Number(h[1])):new point(Number(h[0]),Number(h[1]));f=d[d.length-1]}return d}return null};
Map.Api.prototype.getShapeCoordinates=function(b){if("path"==b.nodeName&&(b=this.getShapePoints(b))){var d=null,d=null,e=[];for(a in b)d=this.map.Scale.getMapPosition(b[a].x,b[a].y),d=this.map.Scale.getMapCoordinate(d.x,d.y),e[e.length]=new point(d.x,d.y);return e}return null};Map.Api.prototype.getSurface=function(b){if(b){if("g"==b.parentNode.nodeName){var d=b.parentNode.getAttributeNS(szMapNs,"area");if(d&&d.length)return Number(d)}if(b=this.getShapePoints(b))return __doGetPolygonSurface(b)}return null};
Map.Api.prototype.printSurface=function(b){if(b){var d=this.getSurface(b);if(d)return d=this.map.Scale.formatSurfaceString(d)+"  ",this.createInfoBubble(b,Array(d),1)}};Map.Api.prototype.displayContextMenuTargetInfo=function(){var b=this.map.Event.contextMenuObj;b&&displayInfoDelayed(null,b,10)};Map.Api.prototype.removeContextMenuTarget=function(){this.map.Event.contextMenuObj&&(this.map.Dom.clearGroup(SVGToolsGroup),mapToolList.clear())};
Map.Api.prototype.removeContextMapTool=function(){var b=this.map.Event.contextMenuObj;if(b)for(;b;b=b.parentNode)if(b.getAttributeNS(null,"id").match(/maptoolnode/)){mapToolList.removeMapTool(b);break}};
Map.Api.prototype.createContextMenuTargetBuffer=function(){var b=this.map.Event.contextMenuObj;if(b){b=new MapObject(b);if(b.szId.match(/legend:setactive/))var d=b.szId.split("legend:setactive:")[1],e=d.split("::")[0],d=d.split("::")[1],f=this.map.Layer.getLayerObjOfNode(b.objNode);this.map.Themes.newTheme(e,f.szRenderer,"","type:CHART|BUFFER;align:center;colorscheme:#aa4400;ranges:"+d+";buffersize:1000;opacity:0.3;label:Ripetitore","Buffer (1 km)","Ripetitore")}};
Map.Api.prototype.createTheme=function(b,d,e,f,h,k,m){return this.map.Themes.newTheme(b,d,e,f,h,k,m)};Map.Api.prototype.newMapTheme=function(b,d,e,f,h,k){if(this.map.Zoom.fExternalZoom)this.map.pushAction('map.Api.newMapTheme("'+b+'","'+d+'","'+e+'","'+f.replace(/\\/gi,"\\\\").replace(/\"/gi,'\\"')+'","'+h+'","'+k+'")');else if(this.executeWithPush)this.map.pushAction('map.Themes.newTheme("'+b+'","'+d+'","'+e+'","'+f+'","'+h+'","'+k+'")');else return this.map.Themes.newTheme(b,d,e,f,h,k)};
Map.Api.prototype.newMapThemeByObj=function(b){return this.map.Themes.newThemeByObj(b)};Map.Api.prototype.refreshTheme=function(b){this.map.Themes.refreshTheme(b)};Map.Api.prototype.changeContextThemeStyle=function(b,d){var e=new MapObject(b);this.map.Themes.changeThemeStyle(null,e.szId,d)};Map.Api.prototype.changeThemeStyle=function(b,d,e){this.map.Themes.changeThemeStyle(null,b,d,e)};Map.Api.prototype.showThemeClass=function(b,d,e){this.map.Themes.showClass(null,b,d,e)};
Map.Api.prototype.hideThemeClass=function(b,d,e){this.map.Themes.hideClass(null,b,d,e)};Map.Api.prototype.markThemeClass=function(b,d,e){this.map.Themes.markClass(null,b,d,e)};Map.Api.prototype.unmarkThemeClass=function(b,d,e){this.map.Themes.unmarkClass(null,b,d,e)};Map.Api.prototype.filterThemeItems=function(b,d,e){this.map.Themes.filterItems(null,b,d,e)};Map.Api.prototype.selectFilterItems=function(b){this.map.Themes.selectFilterItems(null,b)};
Map.Api.prototype.popupThemeStyleMenu=function(b){this.map.Themes.chartTypeMenu(null,b)};Map.Api.prototype.highlightThemeItems=function(b,d,e){this.map.Themes.doHighlightItems(b,d,e)};Map.Api.prototype.clearHighlightThemeItems=function(b){this.map.Themes.clearHighlightItems(null,b)};Map.Api.prototype.zoomToTheme=function(b){this.map.Themes.zoomTo(null,b)};Map.Api.prototype.nextClipFrame=function(b){this.map.Themes.nextClipFrame(b)};
Map.Api.prototype.setClipFrame=function(b,d){this.map.Themes.setClipFrame(b,d)};Map.Api.prototype.pauseClip=function(b){this.map.Themes.pauseClip(b)};Map.Api.prototype.startClip=function(b){this.map.Themes.startClip(b)};Map.Api.prototype.getTheme=function(b){return this.map.Themes.getTheme(b)};Map.Api.prototype.getAllThemes=function(){return this.map.Themes.getAllThemes()};Map.Api.prototype.getMapThemeDefinitionStrings=function(){return this.map.Themes.getAllThemeDefinitionStrings()};
Map.Api.prototype.getMapThemeStyleString=function(b){return this.map.Themes.getMapThemeStyleString(b)};Map.Api.prototype.getMapThemeDefinitionObj=function(b){return this.map.Themes.getMapThemeDefinitionObj(b)};Map.Api.prototype.removeTheme=function(b){this.map.Themes.removeTheme(null,b)};Map.Api.prototype.removeAllThemes=function(){this.map.Themes.removeAll()};Map.Api.prototype.getThemeId=function(b){return b?b.szId:null};
Map.Api.prototype.setThemeExternalData=function(b,d,e){d&&(this._dataObj=d,eval(e+" = this._dataObj"));this.map.Themes.fWaitingforData=!1;this.map.Themes.execute()};Map.Api.prototype.removeElementById=function(b){(b=SVGDocument.getElementById(b))&&b.parentNode&&b.parentNode.removeChild(b)};Map.Api.prototype.getShapeId=function(b){return(b=new MapObject(b))?b.szId:null};Map.Api.prototype.getShapeLayerObj=function(b){return(b=this.map.Layer.getLayerObjOfNode(b))?b:null};
Map.Api.prototype.getShapeLayerName=function(b){return(b=this.map.Layer.getLayerObjOfNode(b))?b.szName:null};Map.Api.prototype.getShapeMetadataArray=function(b){var d=this.map.Dom.getAttributeByNodeOrParents(b,szMapNs,"info"),e="";(b=new MapObject(b))&&(e=this.map.Dom.getAttributeByNodeOrParents(b.objNode.parentNode,szMapNs,"info"));if(e&&d&&(szTitleA=e.split("|"),szDataA=d.split("|"),szTitleA.length&&szDataA.length)){d=[];for(e=0;e<szTitleA.length;e++)d[szTitleA[e]]=szDataA[e];return d}return null};
Map.Api.prototype.highlightItem=function(b){b=SVGDocument.getElementById(b);b=map.Layer.getLayerItemNodes(b);highLightList.unlock();highLightList.removeAll();for(var d=0;d<b.length;d++)highLightList.removeItem(b[d]),highLightList.addItem(b[d]);highLightList.lock()};Map.Api.prototype.clearHighlight=function(){highLightList.unlock();highLightList.removeAll()};Map.Api.prototype.getLayerLegendSVG=function(b){alert(b)};
