Map.Api=function(a){this.executeWithPush=!1;this.map=a};Map.Api.prototype=new Map;"string"==typeof thisversion&&map.checkVersion(thisversion)?map.Api=new Map.Api(map):alert("Map.Api incompatible !");Map.Api.prototype.setMapFeatures=function(a){this.map.setFeatures(a)};Map.Api.prototype.getMapFeatures=function(){return this.map.getFeatures()};Map.Api.prototype.setMapLocal=function(a,b){for(var c=b.split("|"),d=0;d<c.length;d++)loadSVGIncludes(null,a,c[d])};
Map.Api.prototype.setLocalString=function(a,b){this.map.Dictionary.replace(a,b)};
Map.Api.prototype.setMapLayer=function(a){if(map.fInitializing||map.isLoading())this.map.pushAction('map.Api.setMapLayer("'+a+'"');else{a=JSON.parse(a);for(var b in a){a[b].display&&"none"==a[b].display&&this.switchLayer(String(b),!1);if(a[b].off)for(var c in a[b].off)this.switchLayer(b+"::"+a[b].off[c],!1);if(a[b].on){var d=this.getLayer()[b].categoryA;if(d){for(var g in d)this.switchLayer(b+"::"+g,!1);for(c in a[b].on)a[b].on[c].length&&this.switchLayer(b+"::"+a[b].on[c],!0)}}}}};
Map.Api.prototype.loadMap=function(a){map.fInitializing||map.isLoading()?this.map.pushAction('map.Api.loadMap("'+a+'"'):this.map.loadMap(a)};Map.Api.prototype.setBookmark=function(){try{var a=this.map.Zoom.getBox(),b=this.map.Scale.getMapCoordinate(a.x,a.y),c=this.map.Scale.getMapCoordinate(a.x+a.width,a.y+a.height);bookmarkList.createBookmark(null,"MinBoundX='"+b.x+"' MaxBoundX='"+c.x+"' MinBoundY='"+c.y+"' MaxBoundY='"+b.y)}catch(d){alert("Bookmark could not be set !")}};
Map.Api.prototype.gotoBookmark=function(a){try{bookmarkList.exec(a)}catch(b){alert("Bookmarks could not be found !")}};Map.Api.prototype.clearBookmarks=function(){try{bookmarkList.clear()}catch(a){alert("Bookmarks could not be deleted !")}};Map.Api.prototype.getMapBox=function(){return new box(this.map.Scale.mapPosition.x/this.map.Scale.normalX(1),this.map.Scale.mapPosition.y/this.map.Scale.normalX(1),this.map.Scale.bBox.width/this.map.Scale.normalX(1),this.map.Scale.bBox.height/this.map.Scale.normalX(1))};
Map.Api.prototype.resizeCanvas=function(a,b,c,d,g){return this.map.Scale.resizeCanvas(a,b,c,d,g)};Map.Api.prototype.doZoomMapToFullExtend=function(){this.map.Zoom.doZoomMapToLayer("maplayer")};Map.Api.prototype.doZoomMap=function(a,b){return this.map.Zoom.doZoomMap(a,b)};Map.Api.prototype.doPanMap=function(a,b){this.map.Zoom.setNewPan(a,b)};Map.Api.prototype.doZoomMapToWidgetRect=function(a){this.map.Zoom.doZoomMapToWidgetRect(a)};
Map.Api.prototype.doCenterMapToGeoPosition=function(a,b){this.map.Zoom.doCenterMapToGeoPosition(a,b)};Map.Api.prototype.doCenterMapToGeoBounds=function(a,b,c,d){this.map.Zoom.doCenterMapToGeoBounds(a,b,c,d)};Map.Api.prototype.doZoomMapToGeoBounds=function(a,b,c,d){this.map.Zoom.doZoomMapToGeoBounds(a,b,c,d)};Map.Api.prototype.doSetMapToGeoBounds=function(a,b,c,d){180>d-b&&(fPreserveMapRatio=!1);this.map.Zoom.doSetMapToGeoBounds(a,b,c,d);setTimeout("fPreserveMapRatio = true;",5E3)};
Map.Api.prototype.doZoomMapToView=function(a,b){this.map.Zoom.doZoomMapToView(a,b)};Map.Api.prototype.getCenterOfMapInGeoPosition=function(){return this.map.Zoom.getCenterOfMapInGeoPosition()};Map.Api.prototype.getBoundsOfMapInGeoBounds=function(){return this.map.Zoom.getBoundsOfMapInGeoBounds()};Map.Api.prototype.getMapScale=function(){return String(Math.floor(map.Scale.nTrueMapScale*map.Scale.nZoomScale))};Map.Api.prototype.pendingNewGeoBounds=function(){return fPendingNewGeoBounds};
Map.Api.prototype.setVisibility=function(a){var b=new MapTool(null,"nothing");"invisible"==a?b.hideLayer(null):b.showLayer(null)};Map.Api.prototype.hideOverviewMap=function(){};Map.Api.prototype.showOverviewMap=function(){};Map.Api.prototype.hideNorthArrow=function(){this.map.Viewport.hideNorthArrow()};Map.Api.prototype.showNorthArrow=function(){this.map.Viewport.showNorthArrow()};Map.Api.prototype.backwards=function(){zoomAndPanHistory.backwards()};Map.Api.prototype.forwards=function(){zoomAndPanHistory.forwards()};
Map.Api.prototype.toggleThemeValues=function(a){try{this.map.Themes.toggleThemeValues(null,a)}catch(b){}};Map.Api.prototype.toggleThemeLegends=function(a){try{this.map.Themes.toggleThemeLegends(null,a)}catch(b){}};Map.Api.prototype.minimizeThemeLegends=function(){try{this.map.Themes.minimizeThemeLegends(null)}catch(a){}};Map.Api.prototype.changeObjectScaling=function(a){this.map.Layer.changeObjectScaling(null,a)};
Map.Api.prototype.changeLabelScaling=function(a){this.map.Layer.changeLabelScaling(null,a)};Map.Api.prototype.changeLineScaling=function(a){this.map.Layer.changeLineScaling(null,a)};Map.Api.prototype.getScaleParam=function(){return this.map.Scale.getScaleParam()};Map.Api.prototype.setScaleParam=function(a){this.map.Scale.setScaleParam(a)};Map.Api.prototype.changeRotation=function(a){this.map.Scale.changeRotation(null,a)};Map.Api.prototype.setRotation=function(a){this.map.Scale.setRotation(null,a)};
Map.Api.prototype.setMapBackgroundColor=function(a){this.map.Viewport.setBackgroundColor(a)};Map.Api.prototype.togglePanBorder=function(){this.map.Viewport.togglePanBorder()};Map.Api.prototype.setPrintScaling=function(){this.map.Event.doPrintZoom()};Map.Api.prototype.froozeMap=function(a){fFroozeDynamicContent=a};Map.Api.prototype.setMapClip=function(a){this.map.Viewport.clipMap(a)};Map.Api.prototype.setLayerClip=function(a,b){this.map.Viewport.clipLayer(a,b)};
Map.Api.prototype.switchLayer=function(a,b){this.map.Layer.switchLayer(null,a,null,b)};Map.Api.prototype.getLayer=function(){return this.map.Layer.listA};Map.Api.prototype.getLayerDependency=function(){return this.map.Layer.depListA};Map.Api.prototype.getTileInfo=function(){return this.map.Tiles};Map.Api.prototype.setMapTool=function(a){setMapTool(a)};Map.Api.prototype.getMapTool=function(){return szMapToolType};Map.Api.prototype.isMapTool=function(a){return szMapToolType==a?"yes":"no"};
Map.Api.prototype.isNotMapTool=function(a){return"no"==this.isMapTool(a)?"yes":"no"};
Map.Api.prototype.switchMapTheme=function(a,b){if(a)if(b=b||(this.map.Layer.isLayerOn(a)?"off":"on"),map.Legend){var c=SVGDocument.getElementById("legend:"+b+":this:item:"+a);c?this.map.Legend.execLegendMouseClickOnItem(null,c,"legend:"+b+":this:item:"+a):"on"==b?(this.map.Layer.switchLayer(null,a,null,!0),map.Legend.switchLegendCheckBox(null,a,"inline")):(this.map.Layer.switchLayer(null,a,null,!1),map.Legend.switchLegendCheckBox(null,a,"none"))}else"on"==b?this.map.Layer.switchLayer(null,a,null,
!0):this.map.Layer.switchLayer(null,a,null,!1)};Map.Api.prototype.getMapTheme=function(a){var b=a.split("#")[0].split(":")[0];"legend"==b&&(b=a.split(":")[2]);return this.map.Layer.listA[b]};Map.Api.prototype.getMapThemeRendererField=function(a){return(a=this.getMapTheme(a))?a.szRenderer:null};Map.Api.prototype.getMapThemeDataRow=function(a,b){var c=map.Themes.getTheme(a);return c?map.Themes.getDataRow(b,c):null};
Map.Api.prototype.getMapThemeItemPosition=function(a,b){var c=map.Themes.getTheme(a);return c?(c=c.getItemNodes(b),map.Scale.getScreenPosition(c[0])):null};Map.Api.prototype.zoomMapToItem=function(a){this.map.Zoom.doZoomMapToItem(a)};Map.Api.prototype.getMapThemeChart=function(a,b,c,d){return(a=map.Themes.getTheme(a))?map.Themes.getChart(b,c,d,a):null};Map.Api.prototype.getMapThemeHistogram=function(a,b,c,d){return(b=map.Themes.getTheme(a))?map.Themes.getHistogram(a,c,d,b):null};
Map.Api.prototype.executeJavascriptWithMessage=function(a,b,c){a&&typeof("undefined"!=a)&&(this.map.pushAction("map.Api.executeWithPush = true;"),this.map.pushAction('executeWithMessage("'+a.replace(/\\/gi,"\\\\").replace(/\"/gi,'\\"')+'","'+b+'",'+c+")"),this.map.pushAction("map.Api.executeWithPush = false;"))};Map.Api.prototype.displayMessage=function(a,b,c){displayMessage(a,b,c)};
Map.Api.prototype.flipLegend=function(){var a=getMatrix(this.map.Scale.offsetNode);a[4]=0===a[4]?this.map.Scale.viewBox.width-this.map.Scale.bBox.width:this.map.Scale.viewBox.width-(this.map.Scale.mapPosition.x+this.map.Scale.bBox.width);setMatrix(this.map.Scale.offsetNode,a);this.map.Scale=new Map.Scale;this.map.Viewport=new Map.Viewport;var b=SVGDocument.getElementById("legend:group");b&&(a=getMatrix(b),0===a[4]?(this.map.Dom.getBox(b),a[4]=this.map.Scale.mapPosition.x+this.map.Scale.bBox.width):
a[4]=0,setMatrix(b,a),displayScale(null,"bottom"),this.map.Toolbar.refresh())};var __nLegendSpace=0;
Map.Api.prototype.extendMap=function(){var a=getMatrix(this.map.Scale.offsetNode);if(__nLegendSpace=a[4]){a[4]=0;setMatrix(this.map.Scale.offsetNode,a);this.map.Zoom.doPanMap(__nLegendSpace/this.map.Scale.normalX(1)/2,0);this.map.Scale.reset();this.map.Viewport.reformat();try{this.map.Legend.hide()}catch(b){}try{HTMLWindow.ixmaps.htmlgui_onMapResize(window)}catch(c){this.map.Viewport.reformat()}}else fInitLegendOff=!0};
Map.Api.prototype.normalMap=function(){if(!(0>=__nLegendSpace)){var a=getMatrix(this.map.Scale.offsetNode);a[4]=__nLegendSpace;setMatrix(this.map.Scale.offsetNode,a);this.map.Zoom.doPanMap(-__nLegendSpace/this.map.Scale.normalX(1)/2,0);this.map.Scale.reset();this.map.Viewport.reformat();try{this.map.Legend.show()}catch(b){}try{HTMLWindow.ixmaps.htmlgui_onMapResize(window)}catch(c){this.map.Viewport.reformat()}}};
Map.Api.prototype.hideLegend=function(){var a=SVGDocument.getElementById("legend:group");a&&a.style.setProperty("display","none","")};Map.Api.prototype.showLegend=function(){var a=SVGDocument.getElementById("legend:group");a&&a.style.setProperty("display","inline","")};Map.Api.prototype.clearAll=function(){this.map.clearAll()};Map.Api.prototype.clearAllCharts=function(){this.map.Themes&&this.map.Themes.removeAllCharts()};Map.Api.prototype.clearAllChoropleth=function(){this.map.Themes&&this.map.Themes.removeAllChoropleth()};
Map.Api.prototype.clearAllOverlays=function(){SVGPopupGroup&&SVGToolsGroup.fu.clear();SVGPopupGroup&&SVGFixedGroup.fu.clear();SVGPopupGroup&&SVGPopupGroup.fu.clear();SVGPopupGroup&&SVGMessageGroup.fu.clear();this.map.Themes&&this.map.Themes.removeAllSelections()};Map.Api.prototype.getActualEnvelopeString=function(){return this.map.Zoom.getEnvelopeString()};Map.Api.prototype.getActualEnvelopeCoordinates=function(){return this.map.Zoom.getEnvelope()};
Map.Api.prototype.printActualEnvelope=function(){var a=this.map.Zoom.getBox(),b=this.map.Scale.getMapCoordinate(a.x,a.y),a=this.map.Scale.getMapCoordinate(a.x+a.width,a.y+a.height),c='<ENVELOPE minx="'+b.x+'"\n',c=c+('          maxx="'+a.x+'"\n'),c=c+('          miny="'+a.y+'"\n'),c=c+('          maxy="'+b.y+'" name="Initial_Extent" />');try{htmlgui_prettyPrintXML("Actual zoom Envelope (for SVGGIS XML)",c+"\n")}catch(d){alert(c)}};
Map.Api.prototype.createTextLink=function(a,b,c){a=this.map.Dom.newGroup(a);var d=null;c.match(/javascript/)?(d=this.map.Dom.constructNode("a",a,{"xlink:href":""}),b=this.map.Dom.newText(d,0,this.map.Scale.normalY(.75*nNormalFontSize),"font-family:arial;font-size:"+this.map.Scale.normalY(.75*nNormalFontSize)+"px;fill:blue;",b),d=this.map.Dom.newShape("rect",d,0,0,this.map.Scale.normalX(10*nNormalFontSize),this.map.Scale.normalY(nNormalFontSize+3),"fill:#fffff0;stroke:#000000;opacity:0"),b&&(d.setAttributeNS(null,
"onclick",c),d.setAttributeNS(null,"onmousedown","this.map.Event.stopMouseEvent(evt)"),d.setAttributeNS(null,"onmouseup","this.map.Event.stopMouseEvent(evt)"))):(d=this.map.Dom.constructNode("a",a,{"xlink:href":c}),this.map.Dom.newText(d,0,this.map.Scale.normalY(.75*nNormalFontSize),"font-family:arial;font-size:"+this.map.Scale.normalY(.75*nNormalFontSize)+"px;fill:blue;",b));return a};
Map.Api.prototype.createInfoBubble=function(a,b,c){if(a&&b){c||(c=1);var d="bubble:"+String(Math.random()+":movable");b=createTextGrid(SVGDocument,SVGFixedGroup,d,b,c);c=new point(this.map.Scale.normalX(-10),this.map.Scale.normalY(15));var g=this.map.Scale.getScreenPosition(a),f=this.map.Scale.clipWidgetObjectToSVG(b,g,c);b.fu.setPosition(f.x,f.y);a=null;a=this.map.Dom.getBox(b);(new Button(b,"xx","BUTTON","#delete_button","this.map.Dom.removeElementById('"+d+"')","","remove")).setPosition(a.width,
this.map.Scale.normalY(9));a.width+=this.map.Scale.normalY(9);d=null;d=f.y==g.y+c.y?"top":"bottom";d=f.x==g.x+c.x?d+"left":d+"right";this.map.Scale.normalX(15);var g=this.map.Scale.normalX(5),f=this.map.Scale.normalX(5),h=this.map.Scale.normalX(5),k=c.y,l=this.map.Scale.normalX(15);c=-c.x-g-f;var e="M"+a.x+","+a.y+" ",e=e+("m"+f+",0 ");"topleft"==d?(e=e+("l"+g+",0 ")+("l"+c+","+-k+" "),e+="l"+(-c+l)+","+ +k+" ",e+="l"+(a.width-2*f-g-l)+",0 "):"topright"==d?(e+="l"+(a.width-2*f-g-l)+",0 ",e+="l"+(-c+
l)+","+-k+" ",e+="l"+c+","+ +k+" ",e+="l"+g+",0 "):e+="l"+(a.width-2*f)+",0 ";e+="q"+f+",0 "+f+","+h+" ";e+="l0,"+(a.height-2*h)+" ";e+="q0,"+h+" "+-f+","+h+" ";"bottomright"==d?(e+="l"+-g+",0 ",e+="l"+-c+","+k+" ",e+="l"+(+c-l)+","+-k+" ",e+="l"+(-a.width+2*f+g+l)+",0 "):"bottomleft"==d?(e+="l"+(-a.width+2*f+g+l)+",0 ",e+="l"+(c-l)+","+k+" ",e+="l"+-c+","+-k+" ",e+="l"+-g+",0 "):e+="l"+(-a.width+2*f)+",0 ";e+="q"+-f+",0 "+-f+","+-h+" ";e+="l0,"+(-a.height+2*h)+" ";e+="q0,"+-h+" "+f+","+-h+" ";e+=
"z";a=this.map.Dom.newShape("path",b,e,"fill:white;stroke:grey");b.style.setProperty("filter","url(#DropShadowFilterTools)","");a.parentNode.insertBefore(a,a.parentNode.firstChild)}};
Map.Api.prototype.createInfoContainer=function(a,b,c,d,g,f){if(a&&b)return f||(f="fix"),c=new point(d,g),d=new point(0,0),f=new InfoContainer(SVGDocument,SVGPopupGroup,a+":more"+(f.match(/pointer/)?"":":movable"),c,d,f),a=createTextGrid(SVGDocument,f.workspaceNode,a+":more:textgrid",b,2),this.map.Dictionary.applyToNode(a),f.reformat(),this.map.Event.stopMouseEvent(),f};Map.Api.prototype.getContextMenuTarget=function(){return this.map.Event.contextMenuObj};Map.Api.prototype.getMapToolShape=function(){return mapToolList.toolShape};
Map.Api.prototype.getShapePoints=function(a){if("path"==a.nodeName){var b=[],c=null,d=new point(0,0);a=a.getAttributeNS(null,"d");a=a.substr(1,a.length-2);a.replace("M","M ");a=a.split(" ");for(var g=0;g<a.length;g++)if("l"==a[g]||"L"==a[g])c=a[g];else if(a[g]&&a[g].length){var f=a[g].split(",");b[b.length]="l"==c?new point(d.x+Number(f[0]),d.y+Number(f[1])):new point(Number(f[0]),Number(f[1]));d=b[b.length-1]}return b}return null};
Map.Api.prototype.getShapeCoordinates=function(a){if("path"==a.nodeName&&(a=this.getShapePoints(a))){var b=null,b=null,c=[],d;for(d in a)b=this.map.Scale.getMapPosition(a[d].x,a[d].y),b=this.map.Scale.getMapCoordinate(b.x,b.y),c[c.length]=new point(b.x,b.y);return c}return null};
Map.Api.prototype.getShape=function(a,b,c){c=[];c.push(a);for(var d in c)if(a=SVGDocument.getElementById(c[d])){c=null;for(d=a;!(c=d.getAttribute("style"))&&d.parentNode;)d=d.parentNode;d=a.cloneNode(1E3);d.setAttribute("style",c);d.fu=new Methods(d);a.fu=new Methods(a);a=a.fu.getBox();c=Math.min(4E3/a.width,4E3/a.height);d.fu.setPosition(-a.x*c,-a.y*c-3E3);d.fu.scale(c,c);d.style.setProperty("stroke-width",20/c+"px");b.appendChild(d);break}};
Map.Api.prototype.getSurface=function(a){if(a){if("g"==a.parentNode.nodeName){var b=a.parentNode.getAttributeNS(szMapNs,"area");if(b&&b.length)return Number(b)}if(a=this.getShapePoints(a))return __doGetPolygonSurface(a)}return null};Map.Api.prototype.printSurface=function(a){if(a){var b=this.getSurface(a);if(b)return b=this.map.Scale.formatSurfaceString(b)+"  ",this.createInfoBubble(a,Array(b),1)}};
Map.Api.prototype.displayContextMenuTargetInfo=function(){var a=this.map.Event.contextMenuObj;a&&displayInfoDelayed(null,a,10)};Map.Api.prototype.removeContextMenuTarget=function(){this.map.Event.contextMenuObj&&(this.map.Dom.clearGroup(SVGToolsGroup),mapToolList.clear())};Map.Api.prototype.removeContextMapTool=function(){var a=this.map.Event.contextMenuObj;if(a)for(;a;a=a.parentNode)if(a.getAttributeNS(null,"id").match(/maptoolnode/)){mapToolList.removeMapTool(a);break}};
Map.Api.prototype.createContextMenuTargetBuffer=function(){var a=this.map.Event.contextMenuObj;if(a){a=new MapObject(a);if(a.szId.match(/legend:setactive/))var b=a.szId.split("legend:setactive:")[1],c=b.split("::")[0],b=b.split("::")[1],d=this.map.Layer.getLayerObjOfNode(a.objNode);this.map.Themes.newTheme(c,d.szRenderer,"","type:CHART|BUFFER;align:center;colorscheme:#aa4400;ranges:"+b+";buffersize:1000;opacity:0.3;label:Ripetitore","Buffer (1 km)","Ripetitore")}};
Map.Api.prototype.createTheme=function(a,b,c,d,g,f,h){return this.map.Themes.newTheme(a,b,c,d,g,f,h)};Map.Api.prototype.newMapTheme=function(a,b,c,d,g,f){if(this.map.Zoom.fExternalZoom)this.map.pushAction('map.Api.newMapTheme("'+a+'","'+b+'","'+c+'","'+d.replace(/\\/gi,"\\\\").replace(/\"/gi,'\\"')+'","'+g+'","'+f+'")');else if(this.executeWithPush)this.map.pushAction('map.Themes.newTheme("'+a+'","'+b+'","'+c+'","'+d+'","'+g+'","'+f+'")');else return this.map.Themes.newTheme(a,b,c,d,g,f)};
Map.Api.prototype.newMapThemeByObj=function(a){return this.map.Themes.newThemeByObj(a)};Map.Api.prototype.refreshTheme=function(a){this.map.Themes.refreshTheme(a)};Map.Api.prototype.changeContextThemeStyle=function(a,b){var c=new MapObject(a);this.map.Themes.changeThemeStyle(null,c.szId,b)};Map.Api.prototype.changeThemeStyle=function(a,b,c){this.map.Themes.changeThemeStyle(null,a,b,c)};Map.Api.prototype.showThemeClass=function(a,b,c){this.map.Themes.showClass(null,a,b,c)};
Map.Api.prototype.hideThemeClass=function(a,b,c){this.map.Themes.hideClass(null,a,b,c)};Map.Api.prototype.markThemeClass=function(a,b,c){this.map.Themes.markClass(null,a,b,c)};Map.Api.prototype.unmarkThemeClass=function(a,b,c){this.map.Themes.unmarkClass(null,a,b,c)};Map.Api.prototype.setThemeTimeFrame=function(a,b,c){this.map.Themes.setTimeFrame(null,a,b,c)};Map.Api.prototype.filterThemeItems=function(a,b,c){this.map.Themes.filterItems(null,a,b,c)};
Map.Api.prototype.selectFilterItems=function(a){this.map.Themes.selectFilterItems(null,a)};Map.Api.prototype.popupThemeStyleMenu=function(a){this.map.Themes.chartTypeMenu(null,a)};Map.Api.prototype.highlightThemeItems=function(a,b,c){this.map.Themes.doHighlightItems(a,b,c)};Map.Api.prototype.clearHighlightThemeItems=function(a){this.map.Themes.clearHighlightItems(null,a)};Map.Api.prototype.zoomToTheme=function(a){this.map.Themes.zoomTo(null,a)};Map.Api.prototype.nextClipFrame=function(a){this.map.Themes.nextClipFrame(a)};
Map.Api.prototype.setClipFrame=function(a,b){this.map.Themes.setClipFrame(a,b)};Map.Api.prototype.pauseClip=function(a){this.map.Themes.pauseClip(a)};Map.Api.prototype.startClip=function(a,b){this.map.Themes.startClip(a,b)};Map.Api.prototype.getTheme=function(a){return this.map.Themes.getTheme(a)};Map.Api.prototype.getAllThemes=function(){return this.map.Themes.getAllThemes()};Map.Api.prototype.getMapThemeDefinitionStrings=function(){return this.map.Themes.getAllThemeDefinitionStrings()};
Map.Api.prototype.getMapThemeStyleString=function(a){return this.map.Themes.getMapThemeStyleString(a)};Map.Api.prototype.getMapThemeDefinitionObj=function(a){return this.map.Themes.getMapThemeDefinitionObj(a)};Map.Api.prototype.showTheme=function(a){this.map.Themes.showTheme(null,a)};Map.Api.prototype.hideTheme=function(a){this.map.Themes.hideTheme(null,a)};Map.Api.prototype.toggleTheme=function(a){this.map.Themes.toggleTheme(null,a)};
Map.Api.prototype.removeTheme=function(a){this.map.Themes.removeTheme(null,a)};Map.Api.prototype.removeAllThemes=function(){this.map.Themes.removeAll()};Map.Api.prototype.getThemeId=function(a){return a?a.szId:null};Map.Api.prototype.setThemeExternalData=function(a,b,c){this.map.Themes.setExternalData(a,b,c)};Map.Api.prototype.removeElementById=function(a){(a=SVGDocument.getElementById(a))&&a.parentNode&&a.parentNode.removeChild(a)};
Map.Api.prototype.getShapeId=function(a){return(a=new MapObject(a))?a.szId:null};Map.Api.prototype.getShapeLayerObj=function(a){return(a=this.map.Layer.getLayerObjOfNode(a))?a:null};Map.Api.prototype.getShapeLayerName=function(a){return(a=this.map.Layer.getLayerObjOfNode(a))?a.szName:null};
Map.Api.prototype.getShapeMetadataArray=function(a){var b=this.map.Dom.getAttributeByNodeOrParents(a,szMapNs,"info"),c="";(a=new MapObject(a))&&(c=this.map.Dom.getAttributeByNodeOrParents(a.objNode.parentNode,szMapNs,"info"));if(c&&b&&(c=c.split("|"),b=b.split("|"),c.length&&b.length)){a=[];for(var d=0;d<c.length;d++)a[c[d]]=b[d];return a}return null};
Map.Api.prototype.highlightItem=function(a){var b=SVGDocument.getElementById(a);if(a.match(/:chart/))highLightList.unlock(),highLightList.removeAll(),highLightList.addItem(b,"circle");else{highLightList.unlock();highLightList.removeAll();for(a=0;a<c.length;a++)highLightList.removeItem(c[a]),highLightList.addItem(c[a],"circle");highLightList.lock();var c=map.Layer.getLayerItemNodes(b);highLightList.unlock();highLightList.removeAll();for(a=0;a<c.length;a++)highLightList.removeItem(c[a]),highLightList.addItem(c[a])}highLightList.lock()};
Map.Api.prototype.clearHighlight=function(){highLightList.unlock();highLightList.removeAll()};Map.Api.prototype.getLayerLegendSVG=function(a){alert(a)};Map.Api.prototype.newMapSelection=function(a,b,c,d){map.Selections.newSelection(a,b,c,d)};
