Map.Query=function(){this.themesA=[];this.infoThemesA=[];this.foundNodesA=[];this.searchRecursion=0};Map.Query.prototype=new Map;"string"==typeof thisversion&&map.checkVersion(thisversion)?map.Query=new Map.Query:alert("Map.Query incompatible !");
Map.Query.prototype.xgetThemes=function(){if(0===this.themesA.length&&SVGDocument){var a=SVGDocument.getElementById("mapzoomandpan");if(a)for(var a=a.childNodes,e=0;e<a.length;e++)"g"==a.item(e).nodeName&&(a.item(e).getAttributeNS(null,"id").match(/label/)||(this.themesA[this.themesA.length]=a.item(e).getAttributeNS(null,"id")))}return this.themesA};
Map.Query.prototype.getThemes=function(){if(0===this.themesA.length&&SVGDocument){var a=SVGDocument.getElementsByTagNameNS(szMapNs,"theme");if(a)for(var e=0;e<a.length;e++)this.themesA[this.themesA.length]=a.item(e).getAttributeNS(null,"name")}return this.themesA};
Map.Query.prototype.getThemesWithInfo=function(){if(0===this.infoThemesA.length&&SVGDocument){var a=SVGDocument.getElementsByTagNameNS(szMapNs,"theme");if(a)for(var e=0;e<a.length;e++)a.item(e).getAttributeNS(null,"flag").match(/info/)&&(this.infoThemesA[this.infoThemesA.length]=a.item(e).getAttributeNS(null,"name"))}return this.infoThemesA};
Map.Query.prototype.getThemesWithSelection=function(){if(0===this.infoThemesA.length&&SVGDocument){var a=SVGDocument.getElementsByTagNameNS(szMapNs,"theme");if(a)for(var e=0;e<a.length;e++)a.item(e).getAttributeNS(null,"selection").length&&(this.infoThemesA[this.infoThemesA.length]=a.item(e).getAttributeNS(null,"name"))}return this.infoThemesA};Map.Query.prototype.getActiveTheme=function(){return _activeTheme};
Map.Query.prototype.getFieldsOfTheme=function(a){var e=[];if(SVGDocument){var b=SVGDocument.getElementById(a);if(null==b&&map.Tiles&&0<map.Tiles.nCount)for(var d=0;d<map.Tiles.nCount&&null==b;d++)for(var c=0;c<map.Tiles.nCount&&null==b;c++)b=SVGDocument.getElementById(a+"#00"+String(d)+"00"+String(c));b&&(e=b.getAttributeNS(szMapNs,"info").split("|"))}return e};
Map.Query.prototype.getValuesOfFieldAndTheme=function(a,e,b){var d=[];if(null==a||null==e)return d;b||(b=1E5);if(SVGDocument){var c=SVGDocument.getElementById(a);if(null==c){c=map.Tiles.getTileNodes(a);for(a=0;a<c.length;a++){for(var f=this.getValuesOfFieldAndTheme(c[a].getAttributeNS(null,"id"),e,b),g=0;g<f.length;g++)d[d.length]=f[g];if(0>(b-=f.length))break}return d}if(c){var h=c.getAttributeNS(szMapNs,"info").split("|"),f=-1,g=null;for(a=0;a<h.length;a++)h[a]==e&&(f=a);if(0<=f){e=null;e=c.getElementsByTagName("g");
for(a=0;a<e.length;a++)if(1==e.item(a).nodeType&&(g=(e.item(a).getAttributeNS(szMapNs,"info")||"").split("|"),g.length>f&&g[f].length&&(d[d.length]=g[f],d.length>b)))return d;e=c.getElementsByTagName("path");for(a=0;a<e.length;a++)if(1==e.item(a).nodeType&&(g=(e.item(a).getAttributeNS(szMapNs,"info")||"").split("|"),g.length>f&&g[f].length&&(d[d.length]=g[f],d.length>b)))return d;e=c.getElementsByTagName("use");for(a=0;a<e.length&&!(1==e.item(a).nodeType&&(g=(e.item(a).getAttributeNS(szMapNs,"info")||
"").split("|"),g.length>f&&g[f].length&&(d[d.length]=g[f],d.length>b)));a++);}}}return d};Map.Query.prototype.getSelectionValuesOfTheme=function(a,e){var b=[];if(null==a)return b;e||(e=1E5);if(SVGDocument)for(var d=SVGDocument.getElementById(a),d=null==d?map.Tiles.getTileNodes(a):Array(d),c=0;c<d.length;c++)for(var f=d[c].getElementsByTagName("g"),g=0;g<f.length;g++){var h=map.Tiles.getMasterId(f.item(g).getAttributeNS(null,"id")).split(":");b.push(h.pop());if(b.length>e)return b}return b};
Map.Query.prototype.getValueOfFieldAndItem=function(a,e){if(SVGDocument){var b=SVGDocument.getElementById(a);null==b&&(b=map.Tiles.getTileNodes(a)[0]);if(b){var d=b.getAttributeNS(szMapNs,"info");if(!d||0===d.length)for(var c=b.childNodes,f=0;f<c.length;f++)1==c.item(f).nodeType&&(d=c.item(f).getAttributeNS(szMapNs,"info"));d=d.split("|");if((f=b.parentNode.getAttributeNS(szMapNs,"info"))&&f.length)for(b=f.split("|"),f=0;f<b.length;f++)if(b[f]==e)return d[f]}}return"?"};
Map.Query.prototype.getClassnameOfItem=function(a){var e=null;if(SVGDocument){var b=SVGDocument.getElementById(a);null==b&&(b=map.Tiles.getTileNodes(a)[0]);if(b){e=b.getAttributeNS(null,"class");if(!e||!e.length){a=b.childNodes();for(var d=0;d<a.length;d++){var c=a.item(d);if(1==c.nodeType&&(e=c.getAttributeNS(null,"class"))&&e.length)break}}if(!e||!e.length)for(a=b.childNodes(),d=0;d<a.length&&(c=a.item(d),1!=c.nodeType||!(e=c.getAttributeNS(szMapNs,"value"))||!e.length);d++);}}return e};
Map.Query.prototype.addFoundNode=function(a,e,b,d){var c=map.Tiles.getMasterId(a.parentNode.getAttributeNS(null,"id")),f=c.split(":")[0];if(f&&f.length&&c&&c.length){for(var g=0;g<this.foundNodesA.length;g++)if(this.foundNodesA[g].id==c&&this.foundNodesA[g].feature==e&&this.foundNodesA[g].item==b)return;this.foundNodesA[this.foundNodesA.length]={node:a,id:c,theme:f,feature:e,item:b,itemA:d}}};
Map.Query.prototype.searchItem=function(a,e,b){this.foundNodesA.length=0;if(0===a.length)return this.foundNodesA;this.szQuery=a;var d=a.toLowerCase(),c=a.toUpperCase(),f=a.substr(0,1).toUpperCase()+a.substr(1,a.length-1).toLowerCase(),g=[],g=f!=a?[a,f,d,c]:[a,d];this.szThemesA=b.split("|");d=[];c=map.Scale.canvasNode.getElementsByTagName("path");for(b=0;b<c.length;b++)d[d.length]=c.item(b);c=map.Scale.canvasNode.getElementsByTagName("use");for(b=0;b<c.length;b++)d[d.length]=c.item(b);for(b=0;b<d.length;b++)if(1==
d[b].nodeType){f=!1;if("all"==this.szThemesA[0])f=!0;else if((c=map.Tiles.getMasterId(d[b].parentNode.getAttributeNS(null,"id")))&&0!==c.length)for(var c=c.split(":")[0],h=0;h<this.szThemesA.length;h++)c==this.szThemesA[h]&&(f=!0);if(f){c=d[b].getAttributeNS(szMapNs,"info")||d[b].getAttributeNS(szMapNs,"tooltip");if(null==c||0===c.length)c=d[b].parentNode.getAttributeNS(szMapNs,"info")||d[b].parentNode.getAttributeNS(szMapNs,"tooltip");f=c.split("|");if("*"==a)this.addFoundNode(d[b],"*","*",f);else for(h=
0;h<f.length;h++)if(f[h].length&&this.isEqualA(g,e,f[h])){var k=map.Dom.getAttributeByNodeOrParents(d[b].parentNode,szMapNs,"info"),k=k.split("|"),c=map.Tiles.getMasterId(d[b].parentNode.getAttributeNS(null,"id"));c.split(":");this.addFoundNode(d[b],k[h],f[h],f)}}}return this.foundNodesA};Map.Query.prototype.isEqualA=function(a,e,b){for(var d=0;d<a.length;d++)if(this.isEqual(a[d],e,b))return!0;return!1};
Map.Query.prototype.isEqual=function(a,e,b){switch(e){case "any":return 0<=b.indexOf(a);case "begin":return 0===b.indexOf(a);case "whole":return b==a}return!1};
Map.Query.prototype.searchItemAdvanced=function(a,e){var b,d;0===this.searchRecursion&&(this.foundNodesA.length=0,this.szThemesA=Array(e));if(0===a.length)return this.foundNodesA;this.szQuery=a;var c=[],f=a.split(" ");c[c.length]="";for(b=0;b<f.length;b++)f[b].length&&(-1!="< == > <= <> >= and or like".indexOf(f[b])?(c[c.length]=f[b],c[c.length]=""):(c[c.length-1].length&&(c[c.length-1]+=" "),c[c.length-1]+=f[b]));if(3>c.length)return this.foundNodesA;for(b=1;b<c.length;b+=2)if(-1=="< == > <= <> >= and or like".indexOf(c[b]))return alert(c[b]+
" is not an operator"),this.foundNodesA;f=new _Query;f.newPart();for(b=0;b<c.length;b+=4)switch(f.actPart.addCondition(c[b],c[b+1],c[b+2]),c[b+3]){case "and":break;case "or":f.newPart();break;default:b=1E4}if(SVGDocument){var g=SVGDocument.getElementById(e);if(null==g){b=map.Tiles.getTileNodes(e);this.searchRecursion++;for(f=0;f<b.length;f++)this.searchItemAdvanced(a,b[f].getAttributeNS(null,"id"));this.searchRecursion=0;return this.foundNodesA}if(g){c=g.getAttributeNS(szMapNs,"info").split("|");
for(b=0;b<c.length;b++)c[c[b]]=b;var h=null,k=null;(h=g.getElementsByTagName("path"))&&h.length&&(k=h.item(0).getAttributeNS(szMapNs,"info"));if(null==k||0===k.length)h=g.getElementsByTagName("use");h&&h.length&&(k=h.item(0).getAttributeNS(szMapNs,"info"));if(null==k||0===k.length)h=g.getElementsByTagName("g");for(b=0;b<h.length;b++)if(1==h.item(b).nodeType)for(var k=h.item(b).getAttributeNS(szMapNs,"info").split("|"),g=f.partA.length,l=0;l<g;l++){for(var n=!0,p=f.partA[l].conditionA.length,m=0;m<
p;m++){d=c[f.partA[l].conditionA[m].szTopic];switch(f.partA[l].conditionA[m].szOperator){case "<":n=Number(k[d])<f.partA[l].conditionA[m].szValue;break;case "==":n=k[d]==f.partA[l].conditionA[m].szValue;break;case ">":n=Number(k[d])>f.partA[l].conditionA[m].szValue;break;case "<=":n=Number(k[d])<=f.partA[l].conditionA[m].szValue;break;case "<>":n=Number(k[d])!=f.partA[l].conditionA[m].szValue;break;case ">=":n=Number(k[d])>=f.partA[l].conditionA[m].szValue}if(!1===n)break}n&&(d=f.partA[0].conditionA[0].szTopic,
this.addFoundNode(h.item(b),d,null,k))}}}return this.foundNodesA};
Map.Query.prototype.searchItemByAttribute=function(a,e){this.foundNodesA.length=0;for(var b=[],d=SVGRootElement.getElementsByTagName("path"),c=0;c<d.length;c++)b[b.length]=d.item(c);d=SVGRootElement.getElementsByTagName("use");for(c=0;c<d.length;c++)b[b.length]=d.item(c);d=SVGRootElement.getElementsByTagName("g");for(c=0;c<d.length;c++)b[b.length]=d.item(c);for(c=0;c<b.length;c++){if(b[c].getAttributeNS(null,a)==e){d=b[c].getAttributeNS(szMapNs,"info");if(null==d||0===d.length)d=b[c].parentNode.getAttributeNS(szMapNs,
"info");d=d.split("|");this.addFoundNode(b[c],null,null,d)}if(b[c].getAttributeNS(szMapNs,a)==e){d=b[c].getAttributeNS(szMapNs,"info");if(null==d||0===d.length)d=b[c].parentNode.getAttributeNS(szMapNs,"info");d=d.split("|");this.addFoundNode(b[c],null,null,d)}}return this.foundNodesA};Map.Query.prototype.gotoFoundItem=function(a,e,b){map.Query&&("0"==e?map.Query.execGotoFoundItem(a,e,b):(displayMessage("please wait ...",500),setTimeout("map.Query.execGotoFoundItem("+a+",'"+e+"',"+b+")",100)))};
Map.Query.prototype.execGotoFoundItem=function(a,e,b){SVGPopupGroup&&SVGPopupGroup.fu.clear();if(null==e||"undefined"==e)e="3";if(0>a)if("select"==e)map.Selections.newSelection(this.szThemesA[0],this.foundNodesA,"type:queryresult",this.szQuery);else if("zoomto"==e){if(SVGDocument.getElementById("mapzoomandpan")){e=new point(1E5,1E5);var d=new point(-1E5,-1E5);for(b=0;b<this.foundNodesA.length;b++){a=map.Dom.getBox(this.foundNodesA[b].node);if(0===a.width||0===a.height){var c=getMatrix(this.foundNodesA[b].node);
a.x+=c[4];a.y+=c[5];a.width=map.Scale.viewBox.width/20;a.height=map.Scale.viewBox.height/20;a.x-=a.width/2;a.y-=a.height/2}c=map.Scale.getMapOffset(this.foundNodesA[b].node);a.x+=c.x;a.y+=c.y;e.x=Math.min(e.x,a.x);e.y=Math.min(e.y,a.y);d.x=Math.max(d.x,a.x+a.width);d.y=Math.max(d.y,a.y+a.height)}e=new box(e.x,e.y,d.x-e.x,d.y-e.y);e.scale(1.2);e=map.Zoom.clipArea(e);map.Zoom.setNewArea(e);1==this.foundNodesA.length&&displayInfoDelayed(null,this.foundNodesA[0].node,1E3)}}else{clearThemes();highLightList.removeAll();
for(b=0;b<this.foundNodesA.length;b++){if(!e.match(/info/)||!map.Themes.isNodePartOfAnyTheme(this.foundNodesA[b].node)){a=map.Layer.getLayerItemNodes(this.foundNodesA[b].node);for(c=0;c<a.length;c++)highLightList.addItem(a[c]);highLightList.startToggle()}e.match(/info/)&&displayInfo(null,this.foundNodesA[b].node,"add|fix")}setMapTool("info")}else if(a<this.foundNodesA.length){_activeItem=b=this.foundNodesA[a].node;_activeTheme=null;clearThemes();highLightList.removeAll();if(!map.Themes.isNodePartOfAnyTheme(b)){a=
map.Layer.getLayerItemNodes(b);for(c=0;c<a.length;c++)highLightList.addItem(a[c]);highLightList.startToggle()}if("0"==e&&1==map.Scale.nZoomScale)displayInfo(null,b);else{a=map.Dom.getBox(b);a=new box(a.x,a.y,a.width,a.height);if(0===a.width||0===a.height)d=map.Zoom.getBox(),c=getMatrix(b),a.x+=c[4],a.y+=c[5],a.width=Math.min(d.width,map.Scale.bBox.width/10),a.height=Math.min(d.height,map.Scale.bBox.height/10),a.x-=a.width/2,a.y-=a.height/2;c=map.Scale.getMapOffset(b);a.x+=c.x;a.y+=c.y;if("0"==e){if(map.Zoom.isVisibleBox(a)){displayInfo(null,
b);return}d=map.Zoom.getBox();c=Math.min(d.width/a.width,d.height/a.height);a.scale(c)}else a.scale(2);a=map.Zoom.clipArea(a);"0"==e?map.Zoom.setNewCenter(a):map.Zoom.setNewArea(a);displayInfoDelayed(null,b,1E3)}}};function _Query(){this.partA=[]}_Query.prototype.newPart=function(){this.partA[this.partA.length]=this.actPart=new _QueryPart};function _QueryPart(){this.conditionA=[]}_QueryPart.prototype.addCondition=function(a,e,b){this.conditionA[this.conditionA.length]=new _QueryCondition(a,e,b)};
function _QueryCondition(a,e,b){this.szTopic=a;this.szOperator=e;this.szValue=b};
