Map.Query=function(){this.themesA=[];this.infoThemesA=[];this.foundNodesA=[];this.searchRecursion=0};Map.Query.prototype=new Map;"string"==typeof thisversion&&map.checkVersion(thisversion)?map.Query=new Map.Query:alert("Map.Query incompatible !");
Map.Query.prototype.xgetThemes=function(){if(0==this.themesA.length&&SVGDocument){var a=SVGDocument.getElementById("mapzoomandpan");if(a)for(var a=a.childNodes,d=0;d<a.length;d++)"g"==a.item(d).nodeName&&(a.item(d).getAttributeNS(null,"id").match(/label/)||(this.themesA[this.themesA.length]=a.item(d).getAttributeNS(null,"id")))}return this.themesA};
Map.Query.prototype.getThemes=function(){if(0==this.themesA.length&&SVGDocument){var a=SVGDocument.getElementsByTagNameNS(szMapNs,"theme");if(a)for(var d=0;d<a.length;d++)this.themesA[this.themesA.length]=a.item(d).getAttributeNS(null,"name")}return this.themesA};
Map.Query.prototype.getThemesWithInfo=function(){if(0==this.infoThemesA.length&&SVGDocument){var a=SVGDocument.getElementsByTagNameNS(szMapNs,"theme");if(a)for(var d=0;d<a.length;d++)a.item(d).getAttributeNS(null,"flag").match(/info/)&&(this.infoThemesA[this.infoThemesA.length]=a.item(d).getAttributeNS(null,"name"))}return this.infoThemesA};
Map.Query.prototype.getThemesWithSelection=function(){if(0==this.infoThemesA.length&&SVGDocument){var a=SVGDocument.getElementsByTagNameNS(szMapNs,"theme");if(a)for(var d=0;d<a.length;d++)a.item(d).getAttributeNS(null,"selection").length&&(this.infoThemesA[this.infoThemesA.length]=a.item(d).getAttributeNS(null,"name"))}return this.infoThemesA};Map.Query.prototype.getActiveTheme=function(){return _activeTheme};
Map.Query.prototype.getFieldsOfTheme=function(a){var d=[];if(SVGDocument){var b=SVGDocument.getElementById(a);if(null==b&&map.Tiles&&0<map.Tiles.nCount)for(var e=0;e<map.Tiles.nCount&&null==b;e++)for(var c=0;c<map.Tiles.nCount&&null==b;c++)b=SVGDocument.getElementById(a+"#00"+String(e)+"00"+String(c));b&&(d=b.getAttributeNS(szMapNs,"info").split("|"))}return d};
Map.Query.prototype.getValuesOfFieldAndTheme=function(a,d,b){var e=[];if(null==a||null==d)return e;b||(b=1E5);if(SVGDocument){var c=SVGDocument.getElementById(a);if(null==c){c=map.Tiles.getTileNodes(a);for(t=0;t<c.length;t++){a=this.getValuesOfFieldAndTheme(c[t].getAttributeNS(null,"id"),d,b);for(f=0;f<a.length;f++)e[e.length]=a[f];if(0>(b-=a.length))break}return e}if(c){var g=c.getAttributeNS(szMapNs,"info").split("|"),h=-1,k=null;for(a=0;a<g.length;a++)g[a]==d&&(h=a);if(0<=h){d=null;d=c.getElementsByTagName("g");
for(a=0;a<d.length;a++)if(1==d.item(a).nodeType&&(k=(d.item(a).getAttributeNS(szMapNs,"info")||"").split("|"),k.length>h&&k[h].length&&(e[e.length]=k[h],e.length>b)))return e;d=c.getElementsByTagName("path");for(a=0;a<d.length;a++)if(1==d.item(a).nodeType&&(k=(d.item(a).getAttributeNS(szMapNs,"info")||"").split("|"),k.length>h&&k[h].length&&(e[e.length]=k[h],e.length>b)))return e;d=c.getElementsByTagName("use");for(a=0;a<d.length&&!(1==d.item(a).nodeType&&(k=(d.item(a).getAttributeNS(szMapNs,"info")||
"").split("|"),k.length>h&&k[h].length&&(e[e.length]=k[h],e.length>b)));a++);}}}return e};Map.Query.prototype.getSelectionValuesOfTheme=function(a,d){var b=[];if(null==a)return fieldsA;d||(d=1E5);if(SVGDocument){var e=SVGDocument.getElementById(a),e=null==e?map.Tiles.getTileNodes(a):Array(e);for(t=0;t<e.length;t++){var c=e[t].getElementsByTagName("g");for(tt=0;tt<c.length;tt++){var g=map.Tiles.getMasterId(c.item(tt).getAttributeNS(null,"id")).split(":");b.push(g.pop());if(b.length>d)return b}}}return b};
Map.Query.prototype.getValueOfFieldAndItem=function(a,d){if(SVGDocument){var b=SVGDocument.getElementById(a);null==b&&(b=map.Tiles.getTileNodes(a)[0]);if(b){var e=b.getAttributeNS(szMapNs,"info");if(!e||0==e.length){childsA=b.childNodes;for(var c=0;c<childsA.length;c++)1==childsA.item(c).nodeType&&(e=childsA.item(c).getAttributeNS(szMapNs,"info"))}e=e.split("|");if((c=b.parentNode.getAttributeNS(szMapNs,"info"))&&c.length)for(b=c.split("|"),c=0;c<b.length;c++)if(b[c]==d)return e[c]}}return"?"};
Map.Query.prototype.getClassnameOfItem=function(a){var d=null;if(SVGDocument){var b=SVGDocument.getElementById(a);null==b&&(b=map.Tiles.getTileNodes(a)[0]);if(b){d=b.getAttributeNS(null,"class");if(!d||!d.length){a=b.childNodes();for(var e=0;e<a.length;e++){var c=a.item(e);if(1==c.nodeType&&(d=c.getAttributeNS(null,"class"))&&d.length)break}}if(!d||!d.length)for(a=b.childNodes(),e=0;e<a.length&&(c=a.item(e),1!=c.nodeType||!(d=c.getAttributeNS(szMapNs,"value"))||!d.length);e++);}}return d};
Map.Query.prototype.addFoundNode=function(a,d,b,e){var c=map.Tiles.getMasterId(a.parentNode.getAttributeNS(null,"id")),g=c.split(":")[0];if(g&&g.length&&c&&c.length){for(var h=0;h<this.foundNodesA.length;h++)if(this.foundNodesA[h].id==c&&this.foundNodesA[h].feature==d&&this.foundNodesA[h].item==b)return;this.foundNodesA[this.foundNodesA.length]={node:a,id:c,theme:g,feature:d,item:b,itemA:e}}};
Map.Query.prototype.searchItem=function(a,d,b){this.foundNodesA.length=0;if(0===a.length)return this.foundNodesA;this.szQuery=a;var e=a.toLowerCase(),c=a.toUpperCase(),g=a.substr(0,1).toUpperCase()+a.substr(1,a.length-1).toLowerCase(),h=[],h=g!=a?[a,g,e,c]:[a,e];this.szThemesA=b.split("|");e=[];c=map.Scale.canvasNode.getElementsByTagName("path");for(b=0;b<c.length;b++)e[e.length]=c.item(b);c=map.Scale.canvasNode.getElementsByTagName("use");for(b=0;b<c.length;b++)e[e.length]=c.item(b);for(b=0;b<e.length;b++)if(1==
e[b].nodeType){g=!1;if("all"==this.szThemesA[0])g=!0;else if((c=map.Tiles.getMasterId(e[b].parentNode.getAttributeNS(null,"id")))&&0!==c.length)for(var c=c.split(":")[0],k=0;k<this.szThemesA.length;k++)c==this.szThemesA[k]&&(g=!0);if(g){c=e[b].getAttributeNS(szMapNs,"info")||e[b].getAttributeNS(szMapNs,"tooltip");if(null==c||0==c.length)c=e[b].parentNode.getAttributeNS(szMapNs,"info")||e[b].parentNode.getAttributeNS(szMapNs,"tooltip");g=c.split("|");if("*"==a)this.addFoundNode(e[b],"*","*",g);else for(k=
0;k<g.length;k++)if(g[k].length&&this.isEqualA(h,d,g[k])){var l=map.Dom.getAttributeByNodeOrParents(e[b].parentNode,szMapNs,"info"),l=l.split("|"),c=map.Tiles.getMasterId(e[b].parentNode.getAttributeNS(null,"id"));c.split(":");this.addFoundNode(e[b],l[k],g[k],g)}}}return this.foundNodesA};Map.Query.prototype.isEqualA=function(a,d,b){for(var e=0;e<a.length;e++)if(this.isEqual(a[e],d,b))return!0;return!1};
Map.Query.prototype.isEqual=function(a,d,b){switch(d){case "any":return 0<=b.indexOf(a);case "begin":return 0===b.indexOf(a);case "whole":return b==a}return!1};
Map.Query.prototype.searchItemAdvanced=function(a,d){var b,e;0==this.searchRecursion&&(this.foundNodesA.length=0,this.szThemesA=Array(d));if(0===a.length)return this.foundNodesA;this.szQuery=a;var c=[],g=a.split(" ");c[c.length]="";for(b=0;b<g.length;b++)g[b].length&&(-1!="< == > <= <> >= and or like".indexOf(g[b])?(c[c.length]=g[b],c[c.length]=""):(c[c.length-1].length&&(c[c.length-1]+=" "),c[c.length-1]+=g[b]));if(3>c.length)return this.foundNodesA;for(b=1;b<c.length;b+=2)if(-1=="< == > <= <> >= and or like".indexOf(c[b]))return alert(c[b]+
" is not an operator"),this.foundNodesA;g=new _Query;g.newPart();for(b=0;b<c.length;b+=4)switch(g.actPart.addCondition(c[b],c[b+1],c[b+2]),c[b+3]){case "and":break;case "or":g.newPart();break;default:b=1E4}if(SVGDocument){var h=SVGDocument.getElementById(d);if(null==h){b=map.Tiles.getTileNodes(d);this.searchRecursion++;for(t=0;t<b.length;t++)this.searchItemAdvanced(a,b[t].getAttributeNS(null,"id"));this.searchRecursion=0;return this.foundNodesA}if(h){c=h.getAttributeNS(szMapNs,"info").split("|");
for(b=0;b<c.length;b++)c[c[b]]=b;var k=null,l=null;(k=h.getElementsByTagName("path"))&&k.length&&(l=k.item(0).getAttributeNS(szMapNs,"info"));if(null==l||0==l.length)k=h.getElementsByTagName("use");k&&k.length&&(l=k.item(0).getAttributeNS(szMapNs,"info"));if(null==l||0==l.length)k=h.getElementsByTagName("g");for(b=0;b<k.length;b++)if(1==k.item(b).nodeType)for(l=k.item(b).getAttributeNS(szMapNs,"info").split("|"),anzParts=g.partA.length,h=0;h<anzParts;h++){anzConditions=g.partA[h].conditionA.length;
for(var m=0;m<anzConditions;m++){e=c[g.partA[h].conditionA[m].szTopic];switch(g.partA[h].conditionA[m].szOperator){case "<":fOK=Number(l[e])<g.partA[h].conditionA[m].szValue;break;case "==":fOK=l[e]==g.partA[h].conditionA[m].szValue;break;case ">":fOK=Number(l[e])>g.partA[h].conditionA[m].szValue;break;case "<=":fOK=Number(l[e])<=g.partA[h].conditionA[m].szValue;break;case "<>":fOK=Number(l[e])!=g.partA[h].conditionA[m].szValue;break;case ">=":fOK=Number(l[e])>=g.partA[h].conditionA[m].szValue}if(0==
fOK)break}fOK&&(e=g.partA[0].conditionA[0].szTopic,this.addFoundNode(k.item(b),e,null,l))}}}return this.foundNodesA};
Map.Query.prototype.searchItemByAttribute=function(a,d){this.foundNodesA.length=0;var b=[];childsA=SVGRootElement.getElementsByTagName("path");for(i=0;i<childsA.length;i++)b[b.length]=childsA.item(i);childsA=SVGRootElement.getElementsByTagName("use");for(i=0;i<childsA.length;i++)b[b.length]=childsA.item(i);childsA=SVGRootElement.getElementsByTagName("g");for(i=0;i<childsA.length;i++)b[b.length]=childsA.item(i);for(i=0;i<b.length;i++){if(b[i].getAttributeNS(null,a)==d){var e=b[i].getAttributeNS(szMapNs,
"info");if(null==e||0==e.length)e=b[i].parentNode.getAttributeNS(szMapNs,"info");e=e.split("|");this.addFoundNode(b[i],null,null,e)}if(b[i].getAttributeNS(szMapNs,a)==d){e=b[i].getAttributeNS(szMapNs,"info");if(null==e||0==e.length)e=b[i].parentNode.getAttributeNS(szMapNs,"info");e=e.split("|");this.addFoundNode(b[i],null,null,e)}}return this.foundNodesA};
Map.Query.prototype.gotoFoundItem=function(a,d,b){map.Query&&("0"==d?map.Query.execGotoFoundItem(a,d,b):(displayMessage("please wait ...",500),setTimeout("map.Query.execGotoFoundItem("+a+",'"+d+"',"+b+")",100)))};
Map.Query.prototype.execGotoFoundItem=function(a,d,b){SVGPopupGroup&&SVGPopupGroup.fu.clear();if(null==d||"undefined"==d)d="3";if(0>a)if("select"==d)map.Selections.newSelection(this.szThemesA[0],this.foundNodesA,"type:queryresult",this.szQuery);else if("zoomto"==d){if(SVGDocument.getElementById("mapzoomandpan")){d=new point(1E5,1E5);var e=new point(-1E5,-1E5);for(b=0;b<this.foundNodesA.length;b++){a=map.Dom.getBox(this.foundNodesA[b].node);if(0==a.width||0==a.height){var c=getMatrix(this.foundNodesA[b].node);
a.x+=c[4];a.y+=c[5];a.width=map.Scale.viewBox.width/20;a.height=map.Scale.viewBox.height/20;a.x-=a.width/2;a.y-=a.height/2}c=map.Scale.getMapOffset(this.foundNodesA[b].node);a.x+=c.x;a.y+=c.y;d.x=Math.min(d.x,a.x);d.y=Math.min(d.y,a.y);e.x=Math.max(e.x,a.x+a.width);e.y=Math.max(e.y,a.y+a.height)}d=new box(d.x,d.y,e.x-d.x,e.y-d.y);d.scale(1.2);d=map.Zoom.clipArea(d);map.Zoom.setNewArea(d);1==this.foundNodesA.length&&displayInfoDelayed(null,this.foundNodesA[0].node,1E3)}}else{clearThemes();highLightList.removeAll();
for(b=0;b<this.foundNodesA.length;b++){if(!d.match(/info/)||!map.Themes.isNodePartOfAnyTheme(this.foundNodesA[b].node)){a=map.Layer.getLayerItemNodes(this.foundNodesA[b].node);for(c=0;c<a.length;c++)highLightList.addItem(a[c]);highLightList.startToggle()}d.match(/info/)&&displayInfo(null,this.foundNodesA[b].node,"add|fix")}setMapTool("info")}else if(a<this.foundNodesA.length){_activeItem=b=this.foundNodesA[a].node;_activeTheme=null;clearThemes();highLightList.removeAll();if(!map.Themes.isNodePartOfAnyTheme(b)){a=
map.Layer.getLayerItemNodes(b);for(c=0;c<a.length;c++)highLightList.addItem(a[c]);highLightList.startToggle()}if("0"==d&&1==map.Scale.nZoomScale)displayInfo(null,b);else{a=map.Dom.getBox(b);a=new box(a.x,a.y,a.width,a.height);if(0==a.width||0==a.height)e=map.Zoom.getBox(),c=getMatrix(b),a.x+=c[4],a.y+=c[5],a.width=Math.min(e.width,map.Scale.bBox.width/10),a.height=Math.min(e.height,map.Scale.bBox.height/10),a.x-=a.width/2,a.y-=a.height/2;c=map.Scale.getMapOffset(b);a.x+=c.x;a.y+=c.y;if("0"==d){if(map.Zoom.isVisibleBox(a)){displayInfo(null,
b);return}e=map.Zoom.getBox();c=Math.min(e.width/a.width,e.height/a.height);a.scale(c)}else a.scale(2);a=map.Zoom.clipArea(a);"0"==d?map.Zoom.setNewCenter(a):map.Zoom.setNewArea(a);displayInfoDelayed(null,b,1E3)}}};function _Query(){this.partA=[]}_Query.prototype.newPart=function(){this.partA[this.partA.length]=this.actPart=new _QueryPart};function _QueryPart(){this.conditionA=[]}_QueryPart.prototype.addCondition=function(a,d,b){this.conditionA[this.conditionA.length]=new _QueryCondition(a,d,b)};
function _QueryCondition(a,d,b){this.szTopic=a;this.szOperator=d;this.szValue=b};
