var mapSelection=null;Map.Selections=function(){};Map.Selections.prototype=new Map;"string"==typeof thisversion&&map.checkVersion(thisversion)?map.Selections=new Map.Selections:alert("Map.Themes incompatible !");
Map.Selections.prototype.newSelection=function(b,a,f,c){if(null==a)return displayMessage("empty selection",1E3),null;var e=null;null==f&&(f="type:circle");if(e=(e=f.split("style="))&&1<e.length?__getStyleObj(e[1]):__getStyleObj(f)){"activeLayer"==b&&(b=getActiveTheme(),null==b&&map.Themes.activeTheme&&(b=map.Themes.activeTheme.szThemes));if(null==b)return displayMessage("please activate a layer",1E3),null;mapSelection=new MapSelection(b,a,"SELECTION|"+e.type,c);e.buffersize&&(mapSelection.nBufferSize=
e.buffersize)}mapSelection.parent=map.Themes;map.Themes.addTheme(mapSelection);mapSelection.fRealize=!0;executeWithMessage("map.Themes.execute()","please wait ...");return mapSelection};
function MapSelection(b,a,f,c){this.nSelected=this.nCount=0;this.szThemes=b;this.szThemesA=b.split("|");this.szSelectShape=a;this.highLightList=new HighLight;this.szTitle=c?c:"["+a+"] - "+b;this.szTitle=map.Dictionary.getLocalText(this.szTitle);this.szOrigFlag=this.szFlag=f?f:"";this.nRefreshTimeout=0;this.szId="theme"+String(Math.random());this.szShapeType="polygon"}
MapSelection.prototype.initValues=function(){this.nSelectedArea=this.nSelected=this.nThemeItems=this.nTested=this.nCount=this.nNodes=0;this.activeTheme=map.Themes.getTheme(this.szThemes)||map.Themes.getTheme();this.activeTheme.szThemes!=this.szThemes&&this.activeTheme.szId!=this.szThemes||!this.activeTheme.szFlag.match(/CHART/)||this.activeTheme.szFlag.match(/MULTIPLE/)||(this.szThemes="generic");this.themeNodesA=[];if("generic"==this.szThemes){var b=this.activeTheme;this.themeRootNodesA=b.filterNodesA&&
b.filterNodesA!=this.szSelectShape?myclone(b.filterNodesA):myclone(b.indexA);this.nCount=this.nNodes=this.nThemeItems=this.themeRootNodesA.length}else{this.themeRootNodesA=[];for(b=0;b<this.szThemesA.length;b++){var a=map.Layer.getLayerObj(this.szThemesA[b]);if(a&&a.szSelection&&0!==a.szSelection.length){this.szThemeType=a.szType;this.nThemeItems+=a.nItems;var f=[];a.szFlag.match(/tiled/)?f=map.Tiles.getTileNodes(this.szThemesA[b]):f[0]=SVGDocument.getElementById(a.szName);if(a.nRenderer&1&&a.szRenderer&&
a.szRenderer.length)for(a=0;a<f.length;a++)for(var c=f[a].childNodes,e=0;e<c.length;e++)1==c.item(e).nodeType&&c.item(e).hasChildNodes()&&(this.themeRootNodesA[this.themeRootNodesA.length]=c.item(e));else for(a=0;a<f.length;a++)this.themeRootNodesA[this.themeRootNodesA.length]=f[a]}}if(0===this.themeRootNodesA.length)return!1;for(b=0;b<this.themeRootNodesA.length;b++)this.nNodes+=this.themeRootNodesA[b].childNodes.length;this.nCount=this.nNodes}if("queryresult"==this.szSelectShape)return!0;if("object"==
typeof this.szSelectShape){this.queryResultA=this.szSelectShape;if("generic"==this.szThemes)for(b=0;b<this.szSelectShape.length;b++)this.themeRootNodesA[b]=this.szSelectShape[b];else for(b=0;b<this.szSelectShape.length;b++)this.themeRootNodesA[b]=this.szSelectShape[b].node.parentNode;this.nNodes=this.themeRootNodesA.length=this.szSelectShape.length;this.szSelectShape="queryresult";this.szSelectQuery=this.szTitle;this.markGroup||(this.markGroup=map.Dom.newGroup(map.Layer.objectGroup,this.szId+":markgroup"));
return!0}if("activeBuffer"==this.szSelectShape){f=map.Themes.activeBuffer;if(null!=f){a=[];b=f.chartGroup;c=b.getElementsByTagName("path");e=b.getElementsByTagName("circle");for(b=0;b<c.length;b++)a[a.length]=c.item(b);for(b=0;b<e.length;b++)a[a.length]=e.item(b);this.selectCenterA=[];for(b=0;b<a.length;b++)this.selectCenterA[this.selectCenterA.length]=map.Scale.getMapOffset(a[b]);this.selectBufferSize=f.nBufferSize/map.Scale.mapUnitsPPX;this.selectScale=f.nScale;this.markGroup||(this.markGroup=map.Dom.newGroup(map.Layer.objectGroup,
this.szId+":markgroup"));return!0}alert("error: no active theme/buffer to select with");return!1}if("mapbounds"==this.szSelectShape)b=map.Zoom.getBox(),this.selectCenterA=[],this.selectionCenter=new point(b.x,b.y),this.selectCenterA.push(this.selectionCenter),this.selectBufferSizeX=b.width,this.selectBufferSizeY=b.height,this.selectScale=1;else{this.selectCenterA=[];a=SVGDocument.getElementById(this.szSelectShape);if(!a)return!1;a.fu=new Methods(a);if(this.szFlag.match(/shape/))b=a.fu.getPosition(),
b=a.fu.getBox(),this.selectionCenter=new point(b.x+b.width/2,b.y+b.height/2),this.selectCenterA[this.selectCenterA.length]=this.selectionCenter,this.selectBufferSize=Math.max(b.width/2,b.height/2),this.selectBufferSize/=map.Scale.nZoomScale;else if(this.szFlag.match(/circle/)){b=a.fu.getPosition();b.x=Number(a.getAttributeNS(null,"cx"));b.y=Number(a.getAttributeNS(null,"cy"));this.selectionCenter=new point(b.x,b.y);this.selectCenterA[this.selectCenterA.length]=map.Scale.getMapPosition(b.x,b.y);map.Scale.getMapPosition(b.x,
b.y);this.selectBufferSize=a.getAttributeNS(null,"r");if(0===this.selectBufferSize)return!1;b=antiZoomAndPanList.getActualMatrix();this.selectBufferSize*=b[0]}else if(this.szFlag.match(/square/)){b=a.fu.getPosition();b.x=Number(a.getAttributeNS(null,"x"));b.y=Number(a.getAttributeNS(null,"y"));f=Number(a.getAttributeNS(null,"width"));a=Number(a.getAttributeNS(null,"height"));this.selectionCenter=new point(b.x+f/2,b.y+a/2);this.selectCenterA[this.selectCenterA.length]=map.Scale.getMapPosition(b.x+
f/2,b.y+a/2);map.Scale.getMapPosition(b.x+f/2,b.y+a/2);this.selectBufferSizeX=f/2;this.selectBufferSizeY=a/2;if(0===this.selectBufferSizeX||0===this.selectBufferSizeY)return!1;b=antiZoomAndPanList.getActualMatrix();this.selectBufferSizeX*=b[0];this.selectBufferSizeY*=b[0]}this.selectScale=map.Scale.nZoomScale;this.markGroup||(this.markGroup=map.Dom.newGroup(map.Layer.objectGroup,this.szId+":markgroup"))}return!0};
function __inRange(b,a,f,c){if(b&&a&&f){var e=a.x-b.x;b=a.y-b.y;return c?Math.abs(e)<=f&&Math.abs(b)<=c:Math.sqrt(e*e+b*b)<=f}return!1}
MapSelection.prototype.realize=function(){this.fShowProgressBar=!0;this.initValues()?(this.nSkipCount=this.nDoneCount=0,activeSelection=this,this.mapSleep=new Map.Sleep("activeSelection.selectShapes",100,map.Dictionary.getLocalText("do selection")),this.mapSleep.fShowProgressBar=!0,this.mapSleep.nCount=this.nCount,this.mapSleep.szCancel="activeSelection.cancel()",this.selectShapes()):(this.remove(),displayMessage("Selection could not be done",3E3))};MapSelection.prototype.realizeContinue=function(b){this.selectShapes(b)};
MapSelection.prototype.realizeDone=function(){this.nRefreshTimeout&&setTimeout("map.Themes.refreshTheme('"+this.szId+"')",this.nRefreshTimeout)};MapSelection.prototype.redraw=function(){};MapSelection.prototype.removeValues=function(){};MapSelection.prototype.disable=function(){};MapSelection.prototype.cancel=function(){this.fCancel=!0};activeSelection=null;
MapSelection.prototype.nextThemeNode=function(b){if("generic"==this.szThemes||"queryresult"==this.szSelectShape)return this.themeRootNodesA[b];if(0===b)return this.nRootIndex=0,this.actNode=this.themeRootNodesA[this.nRootIndex].firstChild;if(!this.actNode)return null;this.actNode=this.actNode.nextSibling;if(!this.actNode){if(++this.nRootIndex>=this.themeRootNodesA.length)return null;this.actNode=this.themeRootNodesA[this.nRootIndex].firstChild}return this.actNode};
function myclone(b){if(b){var a=b instanceof Array?[]:{},f;for(f in b)"clone"!=f&&(a[f]=b[f]&&"object"==typeof b[f]?myclone(b[f]):b[f]);return a}return null}
MapSelection.prototype.selectShapes=function(b){if(!b||0===b)if(b=0,this.testA=[],this.itemA=[],this.chartPosA=[],this.exactCountA=[],this.exactSizeA=[],this.activeTheme||(this.activeTheme=map.Themes.activeTheme),this.activeTheme&&this.szThemesA[0]+" == "+this.activeTheme.szThemesA[0]){this.nPartsA=myclone(this.activeTheme.nPartsA);this.partsA=myclone(this.activeTheme.partsA);this.origColorScheme=myclone(this.activeTheme.origColorScheme);this.colorScheme=myclone(this.activeTheme.colorScheme);this.szFieldsA=
myclone(this.activeTheme.szFieldsA);this.szLabelA=myclone(this.activeTheme.szLabelA);this.szLegendLabelA=myclone(this.activeTheme.szLegendLabelA);this.szXaxisA=myclone(this.activeTheme.szXaxisA);this.szSymbolsA=myclone(this.activeTheme.szSymbolsA);this.szRanges=this.activeTheme.szRanges;this.szSizeField=this.activeTheme.szSizeField;this.nMeanA=myclone(this.activeTheme.nMeanA);this.nMedianA=myclone(this.activeTheme.nMedianA);this.nDeviationA=myclone(this.activeTheme.nDeviationA);this.nFilterA=myclone(this.activeTheme.nFilterA);
this.nOrigSumA=myclone(this.activeTheme.nOrigSumA);this.szUnit=this.activeTheme.szUnit;this.formatValue=this.activeTheme.formatValue;this.nMin100=this.activeTheme.nMin100;this.nMax100=this.activeTheme.nMax100;this.nClipFrames=this.activeTheme.nClipFrames;this.nActualFrame=this.activeTheme.nActualFrame;this.sortIndexDown=this.activeTheme.sortIndexDown;this.sortIndexUp=this.activeTheme.sortIndexUp;this.shuffleArray=this.activeTheme.shuffleArray;this.removeDefinition=this.activeTheme.removeDefinition;
this.szValuesTextStyle=this.activeTheme.szValuesTextStyle;this.nOrigValuesSumA=[];this.nValuesSumA=[];this.nValuesMinA=[];this.nValuesMaxA=[];this.nExactCount=this.nCount=this.nSum=this.nSum100=0;this.nMin=Number.MAX_VALUE;this.nMax=-Number.MAX_VALUE;this.nMinSize=Number.MAX_VALUE;this.nMaxSize=-Number.MAX_VALUE;for(var a=this.nSumSize=0;a<this.activeTheme.szFieldsA.length;a++)this.nOrigValuesSumA[a]=0,this.nValuesSumA[a]=0,this.nValuesMinA[a]=Number.MAX_VALUE,this.nValuesMaxA[a]=-Number.MAX_VALUE;
for(var f=0;f<this.partsA.length;f++)this.partsA[f].nCount=0,this.partsA[f].nSum=0,this.exactSizeA[f]=0}if(this.nNodes){var c,e=null,k=null,h=this.selectBufferSize*this.selectScale,g=null;this.selectBufferSizeX&&(h=this.selectBufferSizeX*this.selectScale,g=this.selectBufferSizeY*this.selectScale);for(f=b;f<this.nNodes;f++){this.mapSleep.nDoneCount=this.nDoneCount;if(this.mapSleep.checkSleep(f,10))return;if("generic"==this.szThemes){b=this.nextThemeNode(f);this.nDoneCount++;var d=!1;if("queryresult"==
this.szSelectShape)d=!0;else for(c=0;c<this.selectCenterA.length;c++)if(__inRange(this.activeTheme.getNodePosition(b),this.selectCenterA[c],h,g)){d=!0;break}}else{e=this.nextThemeNode(f);this.nDoneCount++;if(!e||1!=e.nodeType)continue;if(e.getAttributeNS(null,"id").match(/:paint/))continue;b=map.Tiles.getMasterId(e.getAttributeNS(null,"id"));this.testA&&!this.testA[b]&&(this.testA[b]=e,this.nTested++);d=!1;if("queryresult"==this.szSelectShape)for(this.selectionCenter||(this.selectionCenter=new point(0,
0)),c=0;c<this.queryResultA.length;c++){if(this.queryResultA[c].node.parentNode==e){d=!0;(c=e.getAttributeNS(szMapNs,"center"))&&2<c.length&&(k=c.split(","),k=new point(Number(k[0].split(":")[1]),Number(k[1].split(":")[1])));k||(a=map.Dom.getBox(e),k=new point(a.x,a.y));a=map.Scale.mapCanvasCenter;c=map.Scale.getMapOffset(e);k.x+=a.x;k.y+=a.y;this.selectionCenter.x+=k.x/this.queryResultA.length;this.selectionCenter.y+=k.y/this.queryResultA.length;break}}else a=map.Dom.getBox(e),c=map.Scale.getMapOffset(e),
a.x+=c.x,a.y+=c.y,d=a.x>this.selectCenterA[0].x+h||a.y>this.selectCenterA[0].y+g||a.x+a.width<this.selectCenterA[0].x-h||a.y+a.height<this.selectCenterA[0].y-g?!1:!0}if(d){if("generic"==this.szThemes)this.itemA[b]=null,this.nSelected++;else{"point"==this.szThemeType&&(this.markGroup?map.Dom.newShape("circle",this.markGroup,k.x,k.y,map.Scale.normalX(1)*map.Scale.nZoomScale,"fill:yellow;stroke:none;"):e&&e.style.setProperty("opacity","0.0"));d=e.getAttributeNS(szMapNs,"area");if(this.itemA&&this.itemA[b])continue;
this.itemA[b]=e;this.nSelected++;this.nSelectedArea+=Number(d)}if(this.activeTheme)for(d=[],this.activeTheme.itemA[b]?d.push(this.activeTheme.itemA[b]):this.activeTheme.posItemA[b]&&(d=this.activeTheme.posItemA[b]),b=0;b<d.length;b++)if(c=d[b],1!=c.nValuesA.length||!(isNaN(c.nValuesA[0])||0===c.nValuesA[0]&!this.activeTheme.szFlag.match(/ZEROISVALUE/))){this.nCount++;for(a=0;a<c.nValuesA.length;a++)isNaN(c.nValuesA[a])||(this.nOrigValuesSumA[a]+=c.nOrigValuesA[a],this.nValuesSumA[a]+=c.nValuesA[a],
this.nValuesMinA[a]=Math.min(this.nValuesMinA[a],c.nValuesA[a]),this.nValuesMaxA[a]=Math.max(this.nValuesMaxA[a],c.nValuesA[a]),this.nMin=Math.min(this.nMin,c.nValuesA[a]),this.nMax=Math.max(this.nMax,c.nValuesA[a]),this.nMinSize=Math.min(this.nMinSize,c.nSize||this.nMinSize),this.nMaxSize=Math.max(this.nMaxSize,c.nSize||this.nMaxSize),this.nSumSize+=c.nSize);c.nValue100&&(this.nSum100+=c.nValue100);if(this.activeTheme.szFlag.match(/CATEGORICAL|AGGREGATE/))for(console.log(c),a=0;a<this.partsA.length;a++)this.partsA[a].nCount+=
c.nValuesA[a],this.partsA[a].nSum+=c.nValuesA[a],this.nSum+=c.nValuesA[a],this.nExactCount++,this.exactSizeA[a]+=c.nSize||1;else if(this.activeTheme.szFlag.match(/CATEGORICAL/))for(var l=0;l<c.nValuesA.length;l++)for(a=0;a<this.partsA.length;a++){if(c.nValuesA[l]==this.partsA[a].min){this.partsA[a].nCount++;this.partsA[a].nSum+=c.nValuesA[l];this.nSum+=c.nValuesA[l];this.nExactCount++;this.exactSizeA[a]+=c.nSize||1;break}}else if(this.activeTheme.szFlag.match(/SEQUENCE/)||this.activeTheme.szFlag.match(/CHART/))for(a=
0;a<this.partsA.length;a++)this.partsA[a].nCount++,this.partsA[a].nSum+=c.nValuesA[a],this.nSum+=c.nValuesA[a];else if(this.activeTheme.szFlag.match(/CLIP/)&&this.activeTheme.nClipFrames)this.nSum=this.nClipFrames==c.nValuesA.length?this.nSum+Number(c.nValuesA[this.nActualFrame]):this.nSum+Number(c.nValuesA[0]*(this.nClipFrames-this.nActualFrame)/this.nClipFrames+c.nValuesA[c.nValuesA.length-1]*this.nActualFrame/this.nClipFrames);else for(l=0;l<c.nValuesA.length;l++)for(a=0;a<this.partsA.length;a++)if(c.nValuesA[l]<
this.partsA[a].max){this.partsA[a].nCount++;this.partsA[a].nSum+=c.nValuesA[l];this.nSum+=c.nValuesA[l];break}}}if(this.fCancel){this.fShowProgressBar=!1;this.showInfo(!1);clearMessage();return}}}0===this.nThemeItems&&(this.nThemeItems=this.nTested);if("generic"!=this.szThemes&&"point"!=this.szThemeType)for(var m in this.itemA)if((f=map.Tiles.getTileNodes(m))&&f.length)for(var n in f)this.highLightList.addItem(f[n]),this.highLightList.lock();else this.highLightList.addItem(this.itemA[m]),this.highLightList.lock();
this.isVisible=!0;this.realizeDone();this.fShowProgressBar=!1;clearMessage();if(HTMLWindow.ixmaps.htmlgui_onSelection(this.szId))return null;this.showInfo(!0)};
MapSelection.prototype.showInfo=function(b){if(0===this.nCount)displayMessage("Selection: no values found !",1E3),this.remove();else if(0===this.nSelected)displayMessage("Selection is empty !",1E3),this.remove();else if(!this.widgetNode||this.fRedrawInfo){this.fRedrawInfo=!1;var a=this.szId+":display:widget",f=map.Dictionary.getLocalText("Selection");"undefined"==typeof b||b||(f+=" ("+map.Dictionary.getLocalText("incomplete")+"!)");this.selectionCenter||(this.selectionCenter=map.Scale.mapCanvasCenter);
this.widgetNode?(b=this.widgetNode,b.clear()):b=new InfoContainer(SVGDocument,SVGFixedGroup,a+":movable",this.selectionCenter,new point(-map.Scale.normalX(55),map.Scale.normalY(50)),"fixed|pointer",f);b.frameNode.style.setProperty("fill","#e8e8e8","");f=szTextGridStyle;szTextGridStyle="firstgray";this.widgetNode=b;b.fClipped=!1;var c=b.workspaceNode;b.setOnRemove("map.Themes.removeTheme(evt,'"+this.szId+"')");var e=this.szSelectShape,k=0;if("activeBuffer"==this.szSelectShape){var e=map.Themes.activeBuffer.szTitle,
h=[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected by"),map.Dictionary.getLocalText("selected items"),1==this.szThemesA.length?String(map.Layer.listA[this.szThemesA[0]].szLegendName):"(multiple)",String(e),String(this.nSelected)+" / "+String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"],g=Array(3);g[0]="font-weight:bold;fill:#ffffff;";g[1]="font-weight:bold;fill:#ffffff;";g[2]="font-weight:bold;fill:#ffffff;";k+=50}else"queryresult"==
this.szSelectShape?(e=this.szThemes,1<this.szThemesA.length?e="(multiple)":"generic"!=this.szThemes&&(e=String(map.Layer.listA[this.szThemesA[0]].szLegendName)),h=[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected by"),map.Dictionary.getLocalText("selected items"),e,this.szSelectQuery,String(this.nSelected)+" / "+String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"],g=Array(3),g[0]="font-weight:bold;fill:#ffffff;",g[1]="font-weight:bold;fill:#ffffff;",
g[2]="font-weight:bold;fill:#ffffff;",k+=50):(h="generic"==this.szThemes?[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected items"),"(generic)",String(this.nSelected)+" / "+String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"]:[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected items"),1==this.szThemesA.length?String(map.Layer.listA[this.szThemesA[0]].szLegendName):"(multiple)",String(this.nSelected)+" / "+
String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"],g=Array(2),g[0]="font-weight:bold;fill:#ffffff;",g[1]="font-weight:bold;fill:#ffffff;",k+=40);var d=map.Dom.newGroup(c,"");d.fu.setPosition(map.Scale.normalY(3),map.Scale.normalY(3));createTextGrid(SVGDocument,d,a+":textgrid",h,2,11,g,"fill:#bbbbbb;");e=[];if(this.activeTheme){h=d=null;k+=14;map.Dom.newText(c,map.Scale.normalX(3),map.Scale.normalY(k),"font-family:arial;font-weight:bold;font-size:"+map.Scale.normalY(11)+
"px;fill:#555555;pointer-events:none",map.Dictionary.getLocalText("Theme")+": "+this.activeTheme.szTitle);k+=8;d=map.Dom.newGroup(c,"");d.fu.setPosition(map.Scale.normalY(3),map.Scale.normalY(k));this.drawDonutText=this.activeTheme.drawDonutText;this.drawTextforOneQuadrant=this.activeTheme.drawTextforOneQuadrant;this.createTextLabel=this.activeTheme.createTextLabel;if(1==this.nValuesSumA.length){this.addItemValues=this.activeTheme.addItemValues;this.szFieldsA=this.activeTheme.szFieldsA;this.fField100=
this.activeTheme.fField100;var l=this.szFlag;this.szFlag=this.activeTheme.szFlag;this.itemA=[];h=[];for(g=0;g<this.nOrigValuesSumA.length;g++)h[g]=this.nOrigValuesSumA[g];this.addItemValues("selection",h,this.nSum100);this.szFlag=l;if(this.activeTheme.szFlag.match(/CATEGORICAL/))h=[map.Dictionary.getLocalText("selected items"),String(__formatValue(Number(this.nCount,2)))],g=Array(2),g[0]="font-weight:bold;fill:#7996D7;",g[1]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,
d,a+":textgrid",h,2,11,g),k+=d.fu.getBox().height/map.Scale.normalX(1)+5;else if(this.activeTheme.szAggregation&&this.activeTheme.szAggregation.match(/sum/)||this.activeTheme.szFlag.match(/SUM/)){if(h=[map.Dictionary.getLocalText("value of selection"),map.Dictionary.getLocalText("% of total value")," ",map.Dictionary.getLocalText("min"),map.Dictionary.getLocalText("max"),map.Dictionary.getLocalText("average"),String(__formatValue(Number(this.itemA.selection.nValuesA[0]),2))+" "+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/
Number(this.activeTheme.nOrigSumA[0])*100,2))+" %"," ",String(__formatValue(Number(this.nValuesMinA[0]),2))+" "+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+" "+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+" "+this.szUnit],g=Array(12),g[0]="font-weight:bold;fill:#7996D7;",g[6]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,d,a+":textgrid",h,2,11,g),k+=d.fu.getBox().height/map.Scale.normalX(1)+5,d=map.Dom.newGroup(c,""),
e.push(d),a=DonutCharts.newChart(SVGDocument,d,map.Scale.normalX(55),map.Scale.normalY(55),0,0),a.setRadInner(0),a.setRadOuter(map.Scale.normalX(55)),a.setCenter(map.Scale.normalX(80),map.Scale.normalY(100)),h=Number(this.nValuesSumA[0])/Number(this.activeTheme.nOrigSumA[0])*100,a.addPart(h,map.Scale.normalY(20),"#ddddee",0,this.formatValue(h,2)+"%","selection: "+this.formatValue(h,2)+"% of total value"),a.addPart(100-h,map.Scale.normalY(20),"#f8f8ff",0,this.formatValue(100-h,2)+"%",this.formatValue(100-
h,2)+"%"),a.realize(),map.Dom.newText(d,map.Scale.normalX(80),map.Scale.normalX(82),"font-size:"+map.Scale.normalX(10)/.66+"px;text-anchor:middle;baseline-shift:-60%;fill:darkgrey;stroke:none;pointer-events:none",this.formatValue(h,0)+" % of total"),this.activeTheme.szFlag.match(/BUBBLE/)||this.activeTheme.szFlag.match(/SQUARE/)||this.activeTheme.szFlag.match(/SYMBOL/))this.getOverviewChart=this.activeTheme.getOverviewChart,this.szOverviewChart=this.activeTheme.szOverviewChart,this.drawChart=this.activeTheme.drawChart,
this.getOverviewChart&&(a=map.Dom.newGroup(c,""),d=map.Dom.newGroup(a,""),e.push(a),a=this.szFlag,this.szFlag=this.activeTheme.szFlag,this.nOrigSumA=this.nOrigValuesSumA,this.nMaxA=this.nValuesMaxA,this.nMinA=this.nValuesMinA,this.szAggregation=this.activeTheme.szAggregation,this.getOverviewChart(d),this.szFlag=a,d.fu.scale(1.3,1.3),d.fu.setPosition(map.Scale.normalX(-35),map.Scale.normalY(35)))}else this.fField100?(h=[map.Dictionary.getLocalText("value of selection")," ",map.Dictionary.getLocalText("min value"),
map.Dictionary.getLocalText("max value"),map.Dictionary.getLocalText("mean value"),String(__formatValue(Number(this.itemA.selection.nValuesA[0]),2))+this.szUnit," ",String(__formatValue(Number(this.nValuesMinA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+this.szUnit],g=Array(10),g[0]="font-weight:bold;fill:#7996D7;",g[5]="font-weight:bold;fill:#000000;font-size:240px;"):this.activeTheme.szFlag.match(/DENSITY/)?
(h=[map.Dictionary.getLocalText("value of selection")," ",map.Dictionary.getLocalText("min value"),map.Dictionary.getLocalText("max value"),map.Dictionary.getLocalText("mean value"),String(__formatValue(Number(this.itemA.selection.nValuesA[0]),2))+this.szUnit," ",String(__formatValue(Number(this.nValuesMinA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+this.szUnit],g=Array(10),g[0]="font-weight:bold;fill:#7996D7;",
g[5]="font-weight:bold;fill:#000000;font-size:240px;"):(h=[map.Dictionary.getLocalText("mean value"),map.Dictionary.getLocalText(" "),map.Dictionary.getLocalText("min value"),map.Dictionary.getLocalText("max value"),String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+this.szUnit,map.Dictionary.getLocalText(" "),String(__formatValue(Number(this.nValuesMinA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+this.szUnit],g=Array(8),g[0]="font-weight:bold;fill:#7996D7;",
g[4]="font-weight:bold;fill:#000000;font-size:240px;"),createTextGrid(SVGDocument,d,a+":textgrid",h,2,11,g),k+=d.fu.getBox().height/map.Scale.normalX(1)+5;this.getOverviewChart=this.activeTheme.getOverviewChart;this.szOverviewChart=this.activeTheme.szOverviewChart;if(2<this.activeTheme.colorScheme.length||this.activeTheme.szFlag.match(/CATEGORICAL/)||!this.activeTheme.szFlag.match(/CHART/)&&!this.activeTheme.szFlag.match(/DOMINANT/))this.szOverviewChart=5<this.nOrigSumA.length?"BAR":"PIE";this.szOverviewChart&&
(d=map.Dom.newGroup(c,""),e.push(d),this.getOverviewChart(d),this.szOverviewChart.match(/PIE/)&&this.activeTheme.szAggregation.match(/sum/)&&(this.szOverviewChart+="|PERCENTOFVALUE",d=map.Dom.newGroup(c,""),e.push(d),this.getOverviewChart(d)));!this.activeTheme.szFlag.match(/CHART/)||this.activeTheme.szAggregation&&this.activeTheme.szAggregation.match(/sum/)||(this.getOverviewChart=this.activeTheme.getOverviewChart,this.szOverviewChart=null,this.drawChart=this.activeTheme.drawChart,this.getOverviewChart&&
(a=map.Dom.newGroup(c,""),d=map.Dom.newGroup(a,""),e.push(a),a=this.szFlag,this.szFlag=this.activeTheme.szFlag,this.nOrigSumA=this.nOrigValuesSumA,this.nMaxA=this.nValuesMaxA,this.nMinA=this.nValuesMinA,this.nOverrideMax=this.activeTheme.nMax,this.szAggregation=this.activeTheme.szAggregation,this.getOverviewChart(d),this.szFlag=a,this.activeTheme.szFlag.match(/BAR/)?(d.fu.scale(2.5,2.5),d.fu.setPosition(map.Scale.normalX(55),map.Scale.normalY(65))):(d.fu.scale(1.3,1.3),d.fu.setPosition(map.Scale.normalX(-35),
map.Scale.normalY(35))),a=this.szFlag,this.szFlag=this.activeTheme.szFlag,this.szOverviewChart+="|PERCENTOFVALUE",d=map.Dom.newGroup(c,""),e.push(d),this.getOverviewChart(d),this.szFlag=a))}else{if(this.activeTheme.szAggregation.match(/sum/)||this.activeTheme.szFlag.match(/SUM/))l=this.nSum100?this.nSum100:this.activeTheme.szFlag.match(/CATEGORICAL/)?this.nExactCount:this.nSum,h=this.activeTheme.nSum100?this.activeTheme.nSum100:this.activeTheme.szFlag.match(/CATEGORICAL/)?this.activeTheme.nExactCount:
this.activeTheme.nSum,h=[map.Dictionary.getLocalText("total of selection"),String(__formatValue(l,2))+" ("+String(__formatValue(Number(l)/Number(h)*100,2))+" %)"],g=Array(2),g[0]="font-weight:bold;fill:#7996D7;",g[1]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,d,a+":textgrid",h,2,11,g),k+=d.fu.getBox().height/map.Scale.normalX(1)+5;this.nSum100&&(l=this.nSum100,this.activeTheme.szFlag.match(/DOMINANT/)||this.activeTheme.szAggregation.match(/sum/)||(l/=this.nSelected),
h=this.activeTheme.nSum100,h=[map.Dictionary.getLocalText("total of selection"),String(__formatValue(l,2))+" ("+String(__formatValue(Number(l)/Number(h)*100,2))+" %)"],g=Array(2),g[0]="font-weight:bold;fill:#7996D7;",g[1]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,d,a+":textgrid",h,2,11,g),k+=d.fu.getBox().height/map.Scale.normalX(1)+5);this.drawChart=this.activeTheme.drawChart;this.getOverviewChart=this.activeTheme.getOverviewChart;this.szOverviewChart=this.activeTheme.szOverviewChart;
if(this.activeTheme.szFlag.match(/CATEGORICAL/)||!this.activeTheme.szFlag.match(/CHART/)&&!this.activeTheme.szFlag.match(/DOMINANT/))this.szOverviewChart="PIE";this.nOrigSumA=this.nOrigValuesSumA;this.nMaxA=this.nValuesMaxA;this.nMinA=this.nValuesMinA;l=this.szFlag;this.szFlag=this.activeTheme.szFlag;this.szAggregation=this.activeTheme.szAggregation;this.szOverviewChart?(d=map.Dom.newGroup(c,""),e.push(d),this.getOverviewChart(d),this.szOverviewChart.match(/PIE/)&&this.activeTheme.szAggregation.match(/sum/)&&
(this.szOverviewChart+="|PERCENTOFVALUE",d=map.Dom.newGroup(c,""),e.push(d),this.getOverviewChart(d))):(d=map.Dom.newGroup(c,""),this.nMin=this.activeTheme.nMin,this.nMax=this.activeTheme.nMax,c=1.8,this.szFlag.match(/DOMINANT/)&&(c=1.8),this.drawColorSchemeLegend=this.activeTheme.drawColorSchemeLegend,this.nOrigSumA=this.activeTheme.nOrigSumA,this.nSum=this.activeTheme.nSum,this.szField100=this.activeTheme.szField100,this.drawColorSchemeLegend(d,"test").fu.scale(.9/c,.9/c),h=map.Dom.getBox(d),0<
h.width&&0<h.height&&(d.fu.scale(c,c),d.fu.setPosition(map.Scale.normalX(10)-h.x*c,map.Scale.normalY(k)+map.Scale.normalY(5)-h.y*c),map.Dom.newText(d,h.x,h.y+h.height+map.Scale.normalX(6),"font-family:Arial;font-style:italic;font-size:"+map.Scale.normalY(6)+"px;fill:#888888;pointer-events:none",this.activeTheme.fField100||this.activeTheme.szAggregation.match(/sum/)?map.Dictionary.getLocalText("* summary over selected area"):map.Dictionary.getLocalText("* arithmetic mean over selected area"))))}this.szFlag=
l}__formatValue(100/this.nThemeItems*this.nSelected,2);__chartArrayReformat(e,map.Scale.normalX(k),2);b.reformat();szTextGridStyle=f}};
function __chartArrayReformat(b,a,f){for(var c=0,e=0,e=1E3,k=0,h=0,g=0,d=0;d<b.length;d++){var l=b[d];l.fu.scale(.8,.8);var m=l.fu.getBox(),e=Math.min(e,m.x),k=Math.min(k,m.y),h=Math.max(h,m.width)}e=a-k+40;for(d=0;d<b.length;d++)l=b[d],m=l.fu.getBox(),0===d?c=map.Scale.normalX(2)-0:f&&0===d%f&&(e+=map.Scale.normalX(20)+g,c=map.Scale.normalX(2)-m.x,g=0),g=Math.max(g,m.height),l.fu.setPosition(c,e),c+=h-map.Scale.normalX(10)}MapSelection.prototype.markClass=function(b){};
MapSelection.prototype.unmarkClass=function(b){};MapSelection.prototype.remove=function(b){this.parent.removeTheme(b,this.szId)};MapSelection.prototype.removeElements=function(b){this.markGroup&&(this.markGroup.style.setProperty("display","none",""),setTimeout("map.Dom.removeElementById('"+this.markGroup.getAttributeNS(null,"id")+"')",1E4));try{this.mapTool.remove()}catch(a){}this.highLightList.unlock();this.highLightList.removeAll()};MapSelection.prototype.getItemNodes=function(b){return[]};
MapSelection.prototype.getNodeArea=function(b){return this.nSelectedArea?this.nSelectedArea/1E6:1};
