var SVGDocument=null,rootGroup=null,nNodesCreated=0,fObjectPseudoShadow=!0,fEmbedScale=!1,fSVGEmbeded=!1,HTMLWindow=null,SVGRootElement=null,SVGToolsGroup=null,SVGThemeGroup=null,SVGFixedGroup=null,SVGPopupGroup=null,SVGNotifyGroup=null,SVGMessageGroup=null,SVGMenuGroup=null,SVGTltipGroup=null,SVGHiddenGroup=null,SVGTempGroup=null,SVGWidth=null,SVGHeight=null,SVGViewBox=null,SVGOrigViewBoxString=null,EmbedWidth=null,EmbedHeight=null,fTransparentMap=!1,fClipMap=!0,fClipMapDynamic=!1,fZoomByViewer=
!1,fPDFEmbed=!1,fAllIncluded=!1,fSwitchByCSS=!0,szViewer="Adobe3.0",fLocalHost=!1,fLoadIncludes=!0,fDynamicLayer=!0,fDynamicTiles=!0,fTilesLoaded=!1,fDiscardTiles="delayed",fLoadMultiTiles=!0,fMarkTiles=!1,fLoadingSilent=!1,fExecuteSilent=!1,fNotify=!1,szObjectGroupId="mapobjects",szShadowFilterId="DropShadowFilterObjects:antizoomandpan",szShadowFilterToolsId="DropShadowFilterTools:antizoomandpan",szShadowFilterShapeId="DropShadowFilterShape",fAntiZoomAndPan=!0,fFeatureScaling=!0,fObjectScaling=!0,
fSymbolScalingDynamic=!0,fFeatureScalingDynamic=!1,fAdaptLabelToScaling=!0,fCheckLabelOverlap=!0,fCheckLabelSpace=!1,nCheckLabelSpace=.8,fCheckLabelSqueeze=!0,fCheckLabelSize=!0,fKillOverlappingLabel=!1,fCheckLabelOnlyOne=!1,fCheckOverlapImplicit=!0,fCheckOverlapAllLayer=!0,fCheckOverlapClipOnTiles=!1,fTileTextNoClip=!1,fFeatureScalingByLayer=!0,fFroozeDynamicContent=!1,fPendingNewGeoBounds=!1,fPanByViewer=!1,fPanToolByViewer=!0,fPanHideTools=!0,fEndPan="normal",fRotateOnMouseMove=!1,fTriggerMouseMoveForPan=
!0,fPreserveMapRatio=!0,fInitLegendOff=!1,fMapBorder=!1,fMapBorder3D=!1,nMapBorderWidth=1,szMapBorderColor="#B6BAC0",szMapPanBorderStyle="fill:#E0E5F0;stroke:white",szMapPanBorderOnoverStyle="fill:#d0d5e0;stroke:white",szMapBackgroundStyle=null,szMapBackgroundColor=null,fClipMapToLegend=!1,fLegendToggleButtons=!1,fNorthArrow="rotatable",szNorthArrowPosition="INMAP",szLocalPopupAlignment=null,szMessagePosition="center",nToolMarginTop=0,nFixedInfoScale=1,fScaleBar=!0,fDebug=!1,fStatus=!1,fSetToolCursor=
!1,fActivateInfoOnClick=!1,szTextGridStyle="background:#dddddd",fCheckSublayerCollapse=!1,fCreatTextLink=!0,nClipTextLink=30,nInfoOffsetX=25,nInfoOffsetY=-25,szInfoTitleColor="#000000",szInfoTitleBgColor="#ffffff",szInfoBodyColor="#444444",szInfoBodyBgColor="#FFFFDD",nInfoRoundRect=2,fInfoShowShape=!1,fActiveThemeInfo=!1,fDecimalPointComma=!1,nNormalSymbolSize=20,nNormalButtonSize=10,nNormalFontSize=12,nHighlightToggle=0,fLoadExternalData=!1,fScaleToFullscreen=!1,fHighlightHint=!0,fAdaptMapScaleToSize=
!0,fLimitMapToExtent=!1,nStandardPPI=72,nScreenPPI=96,nInch=2.54,idTooltipTimeout=null,nTooltipTimeout=500,idInfoTimeout=null,nInfoTimeout=250,szMapToolType="",szSVG="http://www.w3.org/2000/svg",szMapNs="http://www.medienobjekte.de",szXlink="http://www.w3.org/1999/xlink",szHTTP="http://",szLinkTarget="_blank",szEmbedName="SVGMap",newShape=null,_legendIdent=null,_activeTheme=null,_activeItem=null,_tooltip=null;
if("undefined"==typeof printNode){var szFunct="function printNode(node){",szFunct=szFunct+"var serializer = new XMLSerializer();",szFunct=szFunct+"var xml = serializer.serializeToString(node);",szFunct=szFunct+"return xml;",szFunct=szFunct+"}";eval(szFunct)}
var map=null,antiZoomAndPanList=null,mouseObject=null,mapTool=null,mapTiles=null,bookmarkList=null,zoomAndPanHistory=null,highLightList=null,Map=function(){this.fInitializing=!1;this.Api=this.Viewport=this.Toolbar=this.Legend=this.Themes=this.Query=this.Zoom=this.Tiles=this.Layer=this.Scale=this.Event=null;this.mapRoot="";this.Loader=new SVGLoader;this.initActionA=[];this.initMessageA=[];this.actionA=[];this.messageA=[]};
Map.prototype.setFeatures=function(a){this.szFeatures=(this.szFeatures||"")+";"+a;a=a.split(";");for(var c in a){var b=a[c].split(":");switch(b[0]){case "featurescaling":"dynamic"==b[1]?fFeatureScalingDynamic=fFeatureScaling=!0:(fFeatureScaling="false"==b[1]?!1:b[1],fFeatureScalingDynamic=!1);break;case "objectscaling":fObjectScaling="dynamic"==b[1]?"dynamic":"false"==b[1]?!1:b[1];break;case "objectlayer":szObjectGroupId="belowlabel"==b[1]?"mapobjects_below_label":b[1];break;case "dynamiclabel":(fAdaptLabelToScaling=
"false"==b[1]?!1:b[1])?(fCheckLabelSqueeze=fCheckLabelSpace=fCheckLabelOverlap=!0,fCheckLabelOnlyOne=fKillOverlappingLabel=!1,b[1].match(/CHECKSPACE/)&&(fCheckLabelSpace=!0),b[1].match(/NOCHECKSPACE/)&&(fCheckLabelSpace=!1),b[1].match(/NOREPOSITIONING/)&&(fKillOverlappingLabel=fCheckLabelOverlap=!0),b[1].match(/CHECKOVERLAP/)&&(fCheckLabelOverlap=!0),b[1].match(/NOCHECKOVERLAP/)&&(fCheckLabelOverlap=!1),b[1].match(/ONLYONE/)&&(fCheckLabelOnlyOne=!0),b[1].match(/SQUEEZE/)&&(fCheckLabelSpace=!0),b[1].match(/NOSQUEEZE/)&&
(fCheckLabelSqueeze=!1),b[1].match(/SIZE/)&&(fCheckLabelSize=!0),b[1].match(/NOSIZE/)&&(fCheckLabelSize=!1),b[1].match(/CLIPONTILES/)&&(fCheckOverlapClipOnTiles=!0),b[1].match(/NOCLIPONTILES/)&&(fCheckOverlapClipOnTiles=!1)):fCheckLabelOnlyOne=fKillOverlappingLabel=fCheckLabelSize=fCheckLabelSqueeze=fCheckLabelSpace=fCheckLabelOverlap=!1;break;case "dynamiclayer":fDynamicLayer="false"==b[1]?!1:b[1];break;case "dynamictiles":fDynamicTiles="false"==b[1]?!1:b[1];break;case "discardtiles":fDiscardTiles=
"false"==b[1]?!1:b[1];break;case "loadmultitiles":fLoadMultiTiles="false"==b[1]?!1:b[1];break;case "loadexternaldata":fLoadExternalData="false"==b[1]?!1:b[1];break;case "loadincludes":fLoadIncludes="false"==b[1]?!1:b[1];break;case "loadsilent":fLoadingSilent="false"==b[1]?!1:b[1];break;case "worksilent":fExecuteSilent="false"==b[1]?!1:b[1];break;case "notify":fNotify="false"==b[1]?!1:b[1];break;case "fastpan":fPanToolByViewer="false"==b[1]?!1:b[1];break;case "fullscreen":fScaleToFullscreen="false"==
b[1]?!1:b[1];break;case "realtimerotate":fRotateOnMouseMove="false"==b[1]?!1:b[1];break;case "tooltipdelay":nTooltipTimeout=Number(b[1]);break;case "popupdelay":nInfoTimeout=Number(b[1]);break;case "popupgridstyle":szTextGridStyle=b[1];break;case "buttonsize":nNormalButtonSize=Number(b[1]);break;case "symbolsize":nNormalSymbolSize=Number(b[1]);break;case "panborder":fMapBorder=!0;nMapBorderWidth=Number(b[1]);break;case "sidebarbuttons":fLegendToggleButtons="false"==b[1]?!1:b[1];break;case "3Dborder":fMapBorder3D=
"false"==b[1]?!1:b[1];break;case "mapbackgroundstyle":szMapBackgroundStyle=b[1];break;case "mapbackgroundcolor":szMapBackgroundColor=b[1];break;case "transparent":case "transparentbackground":fTransparentMap=!0;break;case "mapopacity":this.nOpacity=parseFloat(b[1]);this.setOpacity(this.nOpacity,"absolute");break;case "clipmap":"dynamic"==b[1]?fClipMapDynamic=fClipMap=!0:(fClipMap="false"==b[1]?!1:b[1],fClipMapDynamic=!1);break;case "checklabeloverlap":fCheckLabelOverlap="false"==b[1]?!1:b[1];break;
case "onlyonelabel":fCheckLabelOnlyOne="false"==b[1]?!1:b[1];break;case "labelspace":nCheckLabelSpace=parseFloat(b[1]);break;case "decimalpoint":fDecimalPointComma=","==b[1]||"komma"==b[1]||"Komma"==b[1]||"comma"==b[1]?!0:!1;break;case "dynamicscale":fAdaptMapScaleToSize="false"==b[1]?!1:b[1];break;case "toolcursor":fSetToolCursor="false"==b[1]?!1:b[1];break;case "scalebar":fScaleBar="false"==b[1]?!1:b[1];break;case "northarrow":fNorthArrow="false"==b[1]?!1:b[1];break;case "northarrowposition":szNorthArrowPosition=
b[1];break;case "screenppi":(nScreenPPI=Number(b[1]))||(nScreenPPI=96);break;case "embedname":szEmbedName=b[1];break;case "debug":fDebug=b[1];break;case "marktiles":fMarkTiles=b[1];break;case "popupalignment":szLocalPopupAlignment=b[1];break;case "toolmargintop":nToolMarginTop=Number(b[1]);break;case "messageposition":szMessagePosition=b[1];break;case "maxThemeCharts":this.Themes.nMaxThemeCharts=Number(b[1]);break;case "maxShadowCharts":this.Themes.nMaxShadowCharts=Number(b[1]);break;case "flushPaintShape":this.Themes.nflushPaintShape=
Number(b[1]);break;case "flushChartDraw":this.Themes.nflushChartDraw=Number(b[1]);this.Themes.activeTheme&&(this.Themes.activeTheme.nflushChartDraw=Number(b[1]));break;case "flushLabelDraw":this.Label.nflushLabelDraw=Number(b[1]);break;case "activeThemeInfo":fActiveThemeInfo=b[1];break;case "fixedInfoScale":nFixedInfoScale=Number(b[1]);break;case "normalSizeScale":map.Scale.nNormalSizeScale=Number(b[1]);break;case "dynamicScalePow":map.Scale.nDynamicScalePow=Number(b[1])}}fClipMap&&!fClipMapDynamic||
map.Zoom.removeClipping()};Map.prototype.getFeatures=function(){return this.szFeatures+=";mapopacity:"+String(this.nOpacity||1)};Map.prototype.isLoading=function(){return this.Loader&&this.Loader.isWaiting()||this.mapLoader&&this.mapLoader.isWaiting()||map.Tiles&&map.Tiles.isLoading()||scriptLoaderPool.isLoading()?!0:!1};Map.prototype.isInitializing=function(){return this.fInitializing||this.Legend&&this.Legend.fInitializing||!this.Scale?!0:!1};
Map.prototype.isIdle=function(){return this.isInitializing()||this.isLoading()||0!==this.actionA.length||0!==this.initActionA.length?!1:!0};
Map.prototype.pushAction=function(a,c){if(a.match(/geobounds/i)){for(var b=0;b<this.actionA.length;b++)this.actionA[b].match(/geobounds/i)&&(this.actionA[b].slice(b,1),this.messageA[b]&&this.messageA[b].slice(b,1));fPendingNewGeoBounds=!0}if(a.match(/toview/i)){for(b=0;b<this.actionA.length;b++)this.actionA[b].match(/toview/i)&&(this.actionA[b].slice(b,1),this.messageA[b]&&this.messageA[b].slice(b,1));fPendingNewGeoBounds=!0}this.actionA.push(a);this.messageA.push(c);this.isInitializing()||1!=this.actionA.length||
setTimeout("map.popAction()",10)};Map.prototype.pushInitAction=function(a,c){this.initActionA.push(a);this.initMessageA.push(c);1==this.initActionA.length&&setTimeout("map.popInitAction()",10)};
Map.prototype.popAction=function(){if(0!==this.actionA.length)if(this.isLoading()||this.isInitializing())if(this.isLoading()?this.npopActionWaitInit=0:this.npopActionWaitInit++,100>this.npopActionWaitInit)setTimeout("map.popAction()",500);else{alert("Error at initializing !\nResource missing or corrupted ?\n");this.actionA.length=0;this.initActionA.length=0;this.fInitializing=!1;try{HTMLWindow&&HTMLWindow.ixmaps.htmlgui_onMapError(window)}catch(a){}}else{var c=this.actionA.shift(),b=this.messageA.shift();
b&&displayMessage(b,1E3);try{eval(c)}catch(d){d&&"undefined"!=typeof d&&d.description&&"undefined"!=typeof d.description&&alert("Error: "+d.description+":\n\n"+c)}setTimeout("map.popAction()",10)}};Map.prototype.popInitAction=function(){if(0===this.initActionA.length)map.npopActionWaitInit=0,map.popAction();else{if(!this.isLoading()){var a=this.initActionA.shift(),c=this.initMessageA.shift();c&&displayMessage(c,1E3);try{eval(a)}catch(b){}}setTimeout("map.popInitAction()",10)}};
Map.prototype.checkVersion=function(a){return null===a||a!=this.version?!1:!0};Map.prototype.fadeLogo=function(){var a=SVGDocument.getElementById("mapbackground:logo");a&&a.parentNode.removeChild(a)};Map.prototype.hideAll=function(){var a=SVGDocument.getElementById("mapcanvas");a&&a.style.setProperty("display","none","")};Map.prototype.showAll=function(){var a=SVGDocument.getElementById("mapcanvas");a&&a.style.setProperty("display","inline","")};
Map.prototype.hideMap=function(){if(!this.fHidden){var a=SVGDocument.getElementById("maplayer");a&&a.style.setProperty("display","none","");(a=SVGDocument.getElementById("mapobjects"))&&a.style.setProperty("display","none","");this.fHidden=!0}};Map.prototype.showMap=function(){if(this.fHidden){var a=SVGDocument.getElementById("maplayer");a&&a.style.setProperty("display","inline","");(a=SVGDocument.getElementById("mapobjects"))&&a.style.setProperty("display","inline","");this.fHidden=!1}};
Map.prototype.setOpacity=function(a,c){var b=SVGDocument.getElementById("maplayer");if(b)if("absolute"==c)b.style.setProperty("opacity",a,""),this.nOpacity=a;else{var d=b.style.getPropertyValue("opacity");if(null===d||0===d.length)d="1";d=parseFloat(d);this.nOpacity=d=Math.min(Math.max(d+a,0),1);b.style.setProperty("opacity",d,"")}};
Map.prototype.toggleOpacity=function(){var a=SVGDocument.getElementById("maplayer");if(a){var c=a.style.getPropertyValue("opacity");if(null===c||0===c.length)c="1";c=parseFloat(c);a.style.setProperty("opacity",1>c?1:0,"")}};Map.prototype.clearAll=function(){map.Dom.clearGroup(SVGToolsGroup);map.Dom.clearGroup(SVGFixedGroup);map.removeAllHighlights();map.Themes.removeAll();setMapTool("");this.Scale.nObjectScaling=1};
Map.prototype.loadMap=function(a){this.mapLoader||(this.mapLoader=new SVGLoaderMap);if(this.mapLoader.importSVGFile(a,SVGDocument)){try{HTMLWindow.ixmaps.loadingMap=a}catch(c){}a.match(/http/)?(a=a.split(/\//),a.splice(-1),a=a.join("/"),this.mapRoot=a+"/"):this.mapRoot="";map.Themes=new Map.Themes;map.Dom.clearGroup(map.Layer.objectGroup)}};var thisversion="0.91",map=new Map;map.version=thisversion;
function initAll(a,c){console.log("*** iXMaps mapscript version: "+map.version);console.log("*** some .svg or .js files may not be found, this is normal and due to hierarchical location files ***");setSVGDocument(a,null);setTimeout("delayedInitAll(null,'"+c+"')",10)}var init=0;
function delayedInitAll(a,c){if(!map.fInitializing){map.fInitializing=!0;setSVGDocument(a,null);map.hideAll();map.Dom=new Map.Dom(a);SVGRootElement=SVGDocument.documentElement;if(fSVGEmbeded){var b=map.Dom.newNode("g",SVGRootElement);b.setAttribute("id","embed");b.setAttribute("name",c)}rootGroup=map.Dom.newGroup(SVGRootElement,"objects:antizoomandpan");SVGToolsGroup=map.Dom.newGroup(rootGroup,"ToolsGroup");SVGFixedGroup=map.Dom.newGroup(rootGroup,"FixedGroup");SVGThemeGroup=map.Dom.newGroup(rootGroup,
"ThemeGroup");SVGThemeGroup.style.setProperty("display","none","");SVGPopupGroup=map.Dom.newGroup(rootGroup,"PopupGroup");SVGNotifyGroup=map.Dom.newGroup(rootGroup,"NotifyGroup");SVGMessageGroup=map.Dom.newGroup(rootGroup,"MessageGroup");SVGMenuGroup=map.Dom.newGroup(rootGroup,"MenuGroup");SVGTltipGroup=map.Dom.newGroup(rootGroup,"TltipGroup");SVGHiddenGroup=map.Dom.newGroup(rootGroup,"HiddenGroup");SVGHiddenGroup.style.setProperty("display","none","");SVGTempGroup=map.Dom.newGroup(rootGroup,"TempGroup");
SVGWidth=parseInt(SVGRootElement.getAttribute("width"));SVGHeight=parseInt(SVGRootElement.getAttribute("height"));SVGOrigViewBoxString=SVGRootElement.getAttribute("viewBox");SVGViewBox=SVGRootElement.getAttribute("viewBox").split(" ");SVGViewBox[0]=Number(SVGViewBox[0]);SVGViewBox[1]=Number(SVGViewBox[1]);SVGViewBox[2]=Number(SVGViewBox[2]);SVGViewBox[3]=Number(SVGViewBox[3]);map.Scale=new Map.Scale;if(map.Scale.scaleNode&&map.Scale.extentNode){map.Scale.superclass=map;if(fAllIncluded||fPDFEmbed)map.Scale.createWidgetStyles(),
map.Scale.normalizeSymbols(SVGDocument.getElementById("symbolstore")),map.Scale.normalizeButtons(SVGDocument.getElementById("widgetstore")),map.Event=new Map.Event,map.Event.initUseNodes(SVGDocument.getElementById("widgetstore"));else{map.pushAction("map.Scale.createWidgetStyles()");map.pushAction('map.Scale.normalizeSymbols(SVGDocument.getElementById("symbolstore"))');map.pushAction('map.Scale.normalizeButtons(SVGDocument.getElementById("widgetstore"))');try{"undefined"!=typeof HTMLWindow.ixmaps.SVGResources_includePath?
map.Loader.importSVGFile(HTMLWindow.ixmaps.SVGResources_includePath+"/maplocal.svg",SVGDocument,SVGTempGroup,null):map.Loader.importSVGFile("../../resources/svg/maplocal.svg",SVGDocument,SVGTempGroup,null)}catch(d){}}if(!SVGDocument.getElementById(szShadowFilterToolsId)){var e=map.Dom.newNode("filter",rootGroup);e.setAttributeNS(null,"id",szShadowFilterToolsId);e.setAttributeNS(null,"filterUnits","objectBoundingBox");e.setAttributeNS(null,"x","-50%");e.setAttributeNS(null,"y","-50%");e.setAttributeNS(null,
"width","200%");e.setAttributeNS(null,"height","200%");b=map.Dom.newNode("feGaussianBlur",e);b.setAttributeNS(null,"stdDeviation","50");b.setAttributeNS(null,"result","BlurAlpha");b=map.Dom.newNode("feOffset",e);b.setAttributeNS(null,"in","BlurAlpha");b.setAttributeNS(null,"dx","20");b.setAttributeNS(null,"dy","20");b.setAttributeNS(null,"result","OffsetBlurAlpha");b=map.Dom.newNode("feColorMatrix",e);b.setAttributeNS(null,"in","OffsetBlurAlpha");b.setAttributeNS(null,"type","matrix");b.setAttributeNS(null,
"values","0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.3 0");b.setAttributeNS(null,"result","matrixOut");b=map.Dom.newNode("feMerge",e);e=map.Dom.newNode("feMergeNode",b);e.setAttributeNS(null,"in","matrixOut");e=map.Dom.newNode("feMergeNode",b);e.setAttributeNS(null,"in","SourceGraphic")}szViewer.match(/Firefox/i)&&(map.pushAction('map.Scale.normalizeSymbols(SVGDocument.getElementById("symbolstore"))'),map.pushAction('map.Scale.normalizeButtons(SVGDocument.getElementById("widgetstore"))'));init++;fLoadIncludes&&
("delayed"==fLoadIncludes?map.pushInitAction("load_includes()"):load_includes());fAllIncluded||fPDFEmbed?doInitAll_2():map.pushInitAction("doInitAll_2(null)"," ... ")}else alert("SVG source not valid SVGGIS map !")}}
function doInitAll_2(a){HTMLWindow&&map.pushInitAction("HTMLWindow.ixmaps.htmlgui_onMapInit(window)");map.Event=new Map.Event;SVGRootElement.setAttribute("onmouseover","map.Event.defaultMouseOver(evt)");SVGRootElement.setAttribute("onmouseout","map.Event.defaultMouseOut(evt)");SVGRootElement.setAttribute("onmousedown","map.Event.defaultMouseDown(evt)");SVGRootElement.setAttribute("ontouchstart","map.Event.defaultMouseDown(evt)");SVGRootElement.setAttribute("onmouseup","map.Event.defaultMouseUp(evt)");
SVGRootElement.setAttribute("ontouchend","map.Event.defaultMouseUp(evt);map.Event.defaultMouseClick(evt)");SVGRootElement.setAttribute("onmousemove","map.Event.defaultMouseMove(evt)");SVGRootElement.setAttribute("ontouchmove","map.Event.defaultMouseUp(evt);map.Event.defaultMouseMove(evt);HTMLWindow.ixmaps.htmlgui_onSVGPointerIdle()");SVGRootElement.setAttribute("onclick","map.Event.defaultMouseClick(evt)");SVGRootElement.setAttribute("onkeydown","map.Event.defaultKeyDown(evt)");SVGRootElement.setAttribute("onkeyup",
"map.Event.defaultKeyUp(evt)");"function"==typeof map.Event.doDefaultZoom&&(SVGRootElement.addEventListener("SVGZoom",map.Event.doDefaultZoom,!1),SVGRootElement.addEventListener("SVGScroll",map.Event.doDefaultPan,!1),SVGRootElement.addEventListener("SVGResize",map.Event.doDefaultResize,!1));map.Layer=new Map.Layer(a);antiZoomAndPanList=new AntiZoomAndPan(a);antiZoomAndPanList.initAntiZoomPattern(a,null);antiZoomAndPanList.initAntiZoomSymbols(null,SVGDocument.getElementById("symbolstore"));antiZoomAndPanList.initAntiZoomStyles(a);
map.Layer.initPatternScaling(a,null);map.Zoom=new Map.Zoom(map.Scale.initScale);map.Tiles=new Map.Tiles;map.Label=new Map.Label;map.Viewport=new Map.Viewport(a);map.Layer.switchScaleDependentLayer(a);map.Scale.refreshCSSStyles();map.pushAction("map.Layer.scaleLineDecorations(SVGRootElement,1)");try{map.Dom.clearGroup(contextMenu.firstChild)}catch(c){}try{HTMLWindow.ixmaps.htmlgui_setScaleSelect(String(__formatValue(Math.floor(map.Scale.nTrueMapScale*map.Scale.nZoomScale)),0,"BLANK"))}catch(b){}try{HTMLWindow.ixmaps.htmlgui_setCurrentEnvelope(map.Zoom.getEnvelopeString(),
!0)}catch(d){}try{HTMLWindow.ixmaps.htmlgui_queryMapFeatures()}catch(e){}fClipMap&&!fClipMapDynamic||map.Zoom.removeClipping();fPDFEmbed&&(map.Tiles.switchScaleDependentTiles(a),clearMessage());setTimeout("map.Zoom.init()",1E3);setTimeout("map.fadeLogo()",1E4);map.Layer.prepareCheckOverlap(a,map.Layer.layerNode);map.fInitializing=!1;HTMLWindow&&map.pushInitAction("HTMLWindow.ixmaps.htmlgui_onMapReady(window)");map.pushInitAction("map.showAll()");map.pushInitAction("nothing()")}
function load_includes(){try{loadSVGIncludes(null,"../../resources/svg"),"undefined"!=typeof HTMLWindow.ixmaps.SVGResources_includePath&&setTimeout("loadSVGIncludes(null,'"+HTMLWindow.ixmaps.SVGResources_includePath+"')")}catch(a){}}
function setSVGDocument(a,c){c?(fSVGEmbeded=!0,document.embeds[c]&&(SVGDocument=document.embeds[c].getSVGDocument(),EmbedHeight=document.embeds[c].height,EmbedWidth=document.embeds[c].width)):a&&(SVGDocument=a.target.ownerDocument);SVGDocument.getElementById("widgetstore")&&2<SVGDocument.getElementById("widgetstore").childNodes.length&&(fAllIncluded=!0);window.parent&&window.screen&&window.location||(fPDFEmbed=!0);fLocalHost=String(window.location).match(/localhost/);szViewer=navigator.appName;navigator.appName.match(/Adobe/)&&
navigator.appVersion.match(/6.0x/)?szViewer="Adobe6.0":navigator.appName.match(/Adobe/)&&navigator.appVersion.match(/3.0/)?szViewer="Adobe3.0":navigator.appName.match(/Opera/)?szViewer="Opera":navigator.appName.match(/Netscape/)&&(szViewer="Netscape");navigator.userAgent&&navigator.userAgent.match(/Chrome/)?szViewer="Chrome":navigator.userAgent&&navigator.userAgent.match(/Firefox/)&&(szViewer="Firefox");var b=SVGDocument.documentElement.getAttribute("xmlns:xmap");b&&3<b.length&&(szMapNs=b);window.parent&&
window.parent.window&&window.parent.window.ixmaps&&(HTMLWindow=window.parent.window)}var __execLaterA=[];function __executeMethodLater(a,c){__execLaterA.push({obj:a,szExec:c});setTimeout("__doExecuteMethodLater()",1)}function __doExecuteMethodLater(){var a=__execLaterA.shift();a&&eval("exec.obj."+a.szExec)}Map.Dom=function(a){this.targetDocument=SVGDocument;a&&(this.targetDocument=a.target.ownerDocument);this.rootElement=this.targetDocument.documentElement;this.idList=[];this.objStackA=[]};
Map.Dom.prototype=new Map;Map.Dom.prototype.setTargetDocument=function(a){a&&(this.targetDocument=a)};Map.Dom.prototype.setTargetGroup=function(a){a&&(this.targetGroup=a)};Map.Dom.prototype.newNode=function(a,c){var b=this.targetDocument.createElementNS(szSVG,a);(c||this.targetGroup).appendChild(b);return b};Map.Dom.prototype.newGroup=function(a,c){var b=this.newNode("g",a);b&&(c&&b.setAttribute("id",c),b.fu=new Methods(b));return b};
Map.Dom.prototype.newObject=function(a,c){var b=this.newNode(a,c);b&&(b.fu=new Methods(b));return b};Map.Dom.prototype.getObjectById=function(a){if(a=this.targetDocument.getElementById(a))a.fu=new Methods(a);return a};Map.Dom.prototype.clearGroup=function(a){if(a&&a.hasChildNodes())for(var c=a.childNodes,b=c.length-1;0<=b;b--)a.removeChild(c.item(b))};Map.Dom.prototype.removeElementById=function(a){(a=SVGDocument.getElementById(a))&&a.parentNode&&a.parentNode.removeChild(a)};
Map.Dom.prototype.constructNode=function(a,c,b){a=this.newObject(a,c);for(var d in b)d.match(/xlink/)?a.setAttributeNS("http://www.w3.org/1999/xlink",d,b[d]):a.setAttribute(d,b[d]);return a};Map.Dom.prototype.pushObj=function(a){var c="stackedObject"+String(Math.random());this.objStackA[c]=a;return c};Map.Dom.prototype.popObj=function(a){return this.objStackA[a]};
Map.Dom.prototype.newShape=function(a,c,b,d,e,f,g,h,k,l,n,m,p){h=null;switch(a){case "rect":isNaN(e)||0>=e||isNaN(f)||0>=f||(h={x:String(b),y:String(d),width:String(e),height:String(f),style:g});break;case "circle":isFinite(e)&&0<e&&(h={cx:String(b),cy:String(d),r:String(e),style:f});break;case "line":isFinite(b)&&isFinite(d)&&isFinite(e)&&isFinite(f)&&(h={x1:String(b),y1:String(d),x2:String(e),y2:String(f),style:g});break;case "path":h={d:String(b),style:d}}return h?this.constructNode(a,c,h):null};
Map.Dom.prototype.newText=function(a,c,b,d,e){if(!isFinite(c)||!isFinite(b))return null;e&&"undefined"!=typeof e||(e="(undefined)");e=String(e);if(fCreatTextLink&&e.substr(0,7)==szHTTP)return this.newTextLink(a,c,b,d,e);a=this.constructNode("text",a,{x:String(c),y:String(b),style:d});e=this.targetDocument.createTextNode(e);a.appendChild(e);return a};
Map.Dom.prototype.newTSpan=function(a,c,b){if("text"!=a.nodeName)return null;b||(b="(undefined)");a=this.constructNode("tspan",a,{style:c});b=this.targetDocument.createTextNode(b);a.appendChild(b);return a};
Map.Dom.prototype.newTextOnPath=function(a,c,b,d,e){b&&"undefined"!=typeof b||(b="(undefined)");b=String(b);var f=this.constructNode("text",a,{style:d});a=this.constructNode("textPath",a,{style:d});a.setAttributeNS(szXlink,"xlink:href","#"+c);a.setAttributeNS(null,"startOffset",e);c=this.targetDocument.createTextNode(b);a.appendChild(c);f.appendChild(a);return f};
Map.Dom.prototype.newTextLink=function(a,c,b,d,e,f){a=this.constructNode("a",a);a.setAttributeNS(szXlink,"xlink:href",f?f:e);a.setAttributeNS(null,"target",szLinkTarget);e&&30<e.length&&(e=e.substr(0,29)+" ...");c=this.constructNode("text",a,{x:String(c),y:String(b),style:d});e=this.targetDocument.createTextNode(e);c.appendChild(e);c.style.setProperty("fill","blue","");c.style.setProperty("text-decoration","underline","");return a};
Map.Dom.prototype.wrapText=function(a,c){var b=a.firstChild.data,d=a.style.getPropertyValue("font-size");if(b){var e=a.getAttributeNS(null,"x"),b=b.split(" ");a.removeChild(a.firstChild);var f=this.newTSpan(a,"",b[0]);f.setAttributeNS(null,"x",e);for(var g=1,h=1;h<b.length;h++){var k=f.firstChild.data.length;f.firstChild.data+=" "+b[h];f.getComputedTextLength()>c&&(f.firstChild.data=f.firstChild.data.slice(0,k),f=this.newTSpan(a,"",b[h]),f.setAttributeNS(null,"x",e),f.setAttributeNS(null,"dy",d),
g++)}return g}};Map.Dom.prototype.getAllIds=function(a,c){null===c&&(this.idList.length=0);if(a&&a.hasChildNodes()){if(a.hasAttributes){var b=a.getAttributeNS(null,"id");b&&(this.idList[this.idList.length]=b)}for(var b=a.childNodes,d=0;d<b.length;d++)this.getAllIds(b.item(d),1)}return this.idList};
Map.Dom.prototype.extendAllIds=function(a,c){if(a&&1==a.nodeType){var b=a.getAttributeNS(null,"id");a.setAttributeNS(null,"id",b+c);for(var b=a.childNodes,d=0;d<b.length;d++)this.extendAllIds(b.item(d),c)}};Map.Dom.prototype.getParentByNodename=function(a,c){var b=null;if(a)for(;b=a.parentNode;){if(b.nodeName==c)return b;a=b}return null};
Map.Dom.prototype.getAttributeByNodeOrParents=function(a,c,b){for(var d=null;a&&1==a.nodeType;)if(d=a.getAttributeNS(c,b),null===d||0===d.length)a=a.parentNode;else return d;return""};Map.Dom.prototype.getClipRect=function(a){var c=null;(a=a.getAttributeNS(null,"clip-path"))&&(a=a.match(urlRegExp))&&a[1]&&(a=SVGDocument.getElementById(a[1]))&&a.hasChildNodes&&(c=a.firstChild);return c};
Map.Dom.prototype.setClipRect=function(a,c){var b=this.getClipRect(a);if(!b){var d=a.getAttributeNS(null,"id"),b=map.Dom.newNode("clipPath",a.parentNode);b.setAttributeNS(null,"id",d+":clippath");b.setAttributeNS(null,"style","pointer-events:all");b=map.Dom.newShape("rect",b,0,0,1,1,"fill:none;stroke:none;opacity:0");b.setAttributeNS(null,"id",d+":cliprect");a.setAttributeNS(null,"clip-path","url(#"+d+":clippath)")}b.setAttributeNS(null,"x",c.x);b.setAttributeNS(null,"y",c.y);b.setAttributeNS(null,
"width",c.width);b.setAttributeNS(null,"height",c.height);return b};
Map.Scale=function(){fScaleToFullscreen&&!fPDFEmbed&&window.screen&&(SVGRootElement.currentScale=1,SVGRootElement.currentScale=Math.min(window.innerWidth/SVGWidth,window.innerHeight/SVGHeight));this.viewBox=new box(SVGViewBox[0],SVGViewBox[1],SVGViewBox[2],SVGViewBox[3]);this.szMapUnits=this.nMapScale=this.scaleNode=null;this.szMapProjection="UTM";this.mapPosition=new point(0,0);this.mapOffset=new point(0,0);this.offsetNode=SVGDocument.getElementById("mapoffset");this.canvasNode=SVGDocument.getElementById("mapcanvas");
this.zoomNode=SVGDocument.getElementById("mapzoomandpan");this.canvasNode&&(this.mapOffset=getTranslate(this.canvasNode));this.offsetNode&&(this.mapPosition=getTranslate(this.offsetNode));this.CSSStyleNodes=SVGDocument.getElementById("mapstyles");this.fCSSStyleNodeChanged=!1;this.scaledSymbolsA=[];this.rotatedSymbolsA=[];this.screenX=1024;this.screenY=768;this.nPPI=nScreenPPI;this.objectScaling_lastScale=this.symbolScaling_lastScale=this.featureScaling_lastScale=1;this.metadataNode=null;var a=SVGRootElement.getElementsByTagName("metadata");
if(this.metadataNode=a[a.length-1]){this.creationNode=this.metadataNode.getElementsByTagNameNS(szMapNs,"creation").item(0);if(this.extentNode=this.metadataNode.getElementsByTagNameNS(szMapNs,"extension").item(0))this.minBoundX=Number(this.extentNode.getAttribute("minboundx")),this.maxBoundX=Number(this.extentNode.getAttribute("maxboundx")),this.minBoundY=Number(this.extentNode.getAttribute("minboundy")),this.maxBoundY=Number(this.extentNode.getAttribute("maxboundy")),this.minX=Number(this.extentNode.getAttribute("minx")),
this.minY=Number(this.extentNode.getAttribute("miny")),this.maxX=Number(this.extentNode.getAttribute("maxx")),this.maxY=Number(this.extentNode.getAttribute("maxy")),this.bBox=new box(this.minX,this.minY,this.maxX-this.minX,this.maxY-this.minY),this.mapUnitsPPX=(this.maxBoundX-this.minBoundX)/(this.maxX-this.minX),this.mapUnitsPPY=(this.maxBoundY-this.minBoundY)/(this.maxY-this.minY),this.origMinX=this.minX,this.origMinY=this.minY;if(this.scaleNode=this.metadataNode.getElementsByTagNameNS(szMapNs,
"scale").item(0))this.nMapScale=Number(this.scaleNode.getAttribute("mapscale")),this.nMapPPI=Number(this.scaleNode.getAttribute("dpi")),this.nMapPPI||(this.nMapPPI=nStandardPPI),this.szMapUnits=this.scaleNode.getAttribute("mapunitsstr"),this.initScale=this.scaleNode.getAttribute("mapinitscale"),this.initZoomNode=this.metadataNode.getElementsByTagNameNS(szMapNs,"initzoom").item(0),this.nObjectScaling=this.nLabelScaling=this.nLineScaling=this.nBorderScaling=this.nFeatureScaling=1,this.nTrueMapScale=
this.getTrueMapScale(),this.nNormalSizeScale=this.nMapScale,this.nDynamicScalePow=3;if(this.coordsysNode=this.metadataNode.getElementsByTagNameNS(szMapNs,"coordsys").item(0))this.szMapProjection=this.coordsysNode.getAttribute("projection"),this.szDatum=this.coordsysNode.getAttribute("datum"),this.szUTMZone=this.coordsysNode.getAttribute("UTMZone"),this.nFalseEasting=Number(this.coordsysNode.getAttribute("falseeasting")),this.nFalseNorthing=Number(this.coordsysNode.getAttribute("falsenorthing")),this.nCorrectEasting=
Number(this.coordsysNode.getAttribute("correcteasting")),this.nCorrectNorthing=Number(this.coordsysNode.getAttribute("correctnorthing"));if(this.featuresNode=this.metadataNode.getElementsByTagNameNS(szMapNs,"features").item(0))(a=this.featuresNode.getAttributeNS(null,"mapfeatures"))&&1<a.length&&map.setFeatures(a),"true"==this.featuresNode.getAttributeNS(null,"cliptextpath")&&(fAdaptLabelToScaling="delayed"),"true"==this.featuresNode.getAttributeNS(null,"initlegendoff")&&(fInitLegendOff=!0),"true"==
this.featuresNode.getAttributeNS(null,"checklabeloverlap")&&(fCheckLabelOverlap=!0),"true"==this.featuresNode.getAttributeNS(null,"onlyonelabel")&&(fCheckLabelOnlyOne=!0),"true"==this.featuresNode.getAttributeNS(null,"tiletextnoclip")&&(fTileTextNoClip=!0),this.nFeatureScaling=Number(this.featuresNode.getAttribute("featurescaling")),this.nBorderScaling=Number(this.featuresNode.getAttribute("borderscaling")),this.nLineScaling=Number(this.featuresNode.getAttribute("linescaling")),this.nLabelScaling=
Number(this.featuresNode.getAttribute("labelscaling")),this.nObjectScaling=Number(this.featuresNode.getAttribute("objectscaling")),this.nFeatureScaling=this.nFeatureScaling?this.nFeatureScaling:1,this.nBorderScaling=this.nBorderScaling?this.nBorderScaling:1,this.nLineScaling=this.nLineScaling?this.nLineScaling:1,this.nLabelScaling=this.nLabelScaling?this.nLabelScaling:1,this.nObjectScaling=this.nObjectScaling?this.nObjectScaling:1}this.nButtonSize=nNormalButtonSize;this.nSymbolSize=nNormalSymbolSize;
this.nFontSize=nNormalFontSize;this.nScaleX=this.viewBox.width/this.getEmbedWidth()*this.getEmbedScale();this.nScaleY=this.viewBox.height/this.getEmbedHeight()*this.getEmbedScale();this.nZoomScale=1;this.mapCenter=new point(0,0);this.mapCanvasCenter=new point(this.mapPosition.x+this.bBox.width/2,this.mapPosition.y+this.bBox.height/2);this.setCanvasSize(0,0,window.innerWidth,window.innerHeight,"center")};Map.Scale.prototype=new Map;
Map.Scale.prototype.reset=function(){fScaleToFullscreen&&!fPDFEmbed&&window.screen&&(SVGRootElement.currentScale=1,SVGRootElement.currentScale=Math.min(window.innerWidth/SVGWidth,window.innerHeight/SVGHeight));this.canvasNode&&(this.mapOffset=getTranslate(this.canvasNode));this.offsetNode&&(this.mapPosition=getTranslate(this.offsetNode));this.mapCanvasCenter=new point(this.mapPosition.x+this.bBox.width/2,this.mapPosition.y+this.bBox.height/2);this.setCanvasSize(0,0,window.innerWidth,window.innerHeight,
"center")};
Map.Scale.prototype.setCanvasSize=function(a,c,b,d,e){var f=""+String(a)+" "+String(c)+" "+String(this.normalX(b))+" "+String(this.normalX(d))+"";a=this.normalX(b)-this.mapPosition.x;c=this.normalX(d)-this.mapPosition.y;var g=a-(this.maxX-this.minX),h=c-(this.maxY-this.minY);"extendmax"==e?(this.maxX+=g,this.maxY+=h,this.maxBoundX+=g*this.mapUnitsPPX,this.minBoundY-=h*this.mapUnitsPPY):(this.minX-=g/2,this.minY-=h/2,this.maxX+=g/2,this.maxY+=h/2,this.minBoundX-=g/2*this.mapUnitsPPX,this.maxBoundY+=h/
2*this.mapUnitsPPY,this.maxBoundX+=g/2*this.mapUnitsPPX,this.minBoundY-=h/2*this.mapUnitsPPY,this.canvasNode&&(setTranslate(this.canvasNode,this.maxX,this.maxY),this.mapOffset=getTranslate(this.canvasNode)));SVGWidth=b;SVGHeight=d;SVGRootElement.setAttribute("width",SVGWidth+"px");SVGRootElement.setAttribute("height",SVGHeight+"px");SVGRootElement.setAttribute("viewBox",f);SVGOrigViewBoxString=SVGRootElement.getAttribute("viewBox");SVGViewBox=SVGRootElement.getAttribute("viewBox").split(" ");SVGViewBox[0]=
Number(SVGViewBox[0]);SVGViewBox[1]=Number(SVGViewBox[1]);SVGViewBox[2]=Number(SVGViewBox[2]);SVGViewBox[3]=Number(SVGViewBox[3]);this.viewBox=new box(SVGViewBox[0],SVGViewBox[1],SVGViewBox[2],SVGViewBox[3]);this.bBox=new box(this.minX,this.minY,this.maxX-this.minX,this.maxY-this.minY);this.mapCanvasCenter=new point(this.mapPosition.x+this.bBox.width/2,this.mapPosition.y+this.bBox.height/2);this.nScaleX=this.viewBox.width/this.getEmbedWidth()*this.getEmbedScale();this.nScaleY=this.viewBox.height/
this.getEmbedHeight()*this.getEmbedScale();if(e=SVGDocument.getElementById("mapcliprect"))e.setAttributeNS(null,"width",a),e.setAttributeNS(null,"height",c);SVGDocument.getElementById("mapcliprect2");if(e=SVGDocument.getElementById("map:annotation"))e.fu=new Methods(e),a=e.fu.getBox(),e.fu.setPosition(this.normalX(b-2)-this.mapPosition.x,this.normalY(d)-this.mapPosition.y-2*a.height)};
Map.Scale.prototype.resizeCanvas=function(a,c,b,d,e){e||(e="center");this.setCanvasSize(a,c,b,d,e);try{map.Viewport.reformat(),map.Themes.reformat(),map.Themes.actualizeActiveTheme(!0),map.Legend.reformat()}catch(f){}try{displayScale(null,"bottom")}catch(g){}};
Map.Scale.prototype.getDistanceInMeter=function(a,c,b,d){var e=b-a,f=d-c,g=0;"Mercator"==this.szMapProjection&&(this.szMapUnits="degrees");switch(this.szMapUnits){case "feet":e/=3.2808399,f/=3.2808399;case "meter":case "meters":e=e*this.nZoomScale*this.mapUnitsPPX;f=f*this.nZoomScale*this.mapUnitsPPY;g=Math.sqrt(e*e+f*f);100<g&&(g=Math.round(g));g=10<g?Math.round(10*g)/10:Math.round(100*g)/100;break;default:a=map.Scale.getMapPosition(a,c),b=map.Scale.getMapPosition(b,d),a=map.Scale.getMapCoordinate(a.x,
a.y),c=map.Scale.getMapCoordinate(b.x,b.y),a=map.Scale.getGeoCoordinateOfPoint(a.x,a.y),c=map.Scale.getGeoCoordinateOfPoint(c.x,c.y),b=a.y/180*Math.PI,d=c.y/180*Math.PI,a=Math.abs(c.x/180*Math.PI-a.x/180*Math.PI),c=Math.abs(d-b),b=Math.pow(Math.sin(c/2),2)+Math.cos(b)*Math.cos(d)*Math.pow(Math.sin(a/2),2),g=12756776*Math.atan2(Math.sqrt(b),Math.sqrt(1-b))}return g};
Map.Scale.prototype.formatDistanceString=function(a){return 1E3<a?String(Math.round(a/100)/10)+" km":100<a?String(Math.round(10*a)/10)+" m":String(Math.round(100*a)/100)+" m"};Map.Scale.prototype.formatSurfaceString=function(a){var c="",c=1E6<a?String(Math.round(a/1E6*1E3)/1E3)+" km2":String(Math.round(1E3*a)/1E3)+" m2";a=c.split(".");1<a.length&&(c=a[0]+","+a[1]);return c};Map.Scale.prototype.getDeltaXofDistanceInMeter=function(a){return 1E3/this.getDistanceInMeter(1E3,1E3,2E3,1E3)*a};
Map.Scale.prototype.getDeltaYofDistanceInMeter=function(a){return 1E3/this.getDistanceInMeter(1E3,1E3,1E3,2E3)*a};Map.Scale.prototype.getMapCoordinate=function(a,c){var b=0,d=0;a+=this.mapOffset.x;c=this.maxY-this.minY-(c+this.mapOffset.y);switch(this.szMapUnits){case "feet":case "meter":case "meters":b=this.minBoundX+a*this.mapUnitsPPX;d=this.minBoundY+c*this.mapUnitsPPY;break;default:b=this.minBoundX+a*this.mapUnitsPPX,d=this.minBoundY+c*this.mapUnitsPPY}return new point(b,d)};
Map.Scale.prototype.getMapCoordinateUTM=function(a,c){var b=this.getMapCoordinate(a,c);"Mercator"==this.szMapProjection?b=_LLtoMercator(b.y,b.x):"WinkelTripel"==this.szMapProjection?b=_LLtoWinkelTripel(b.y,b.x):"feet"!=this.szMapUnits&&"meter"!=this.szMapUnits&&"meters"!=this.szMapUnits&&(b=_LLtoUTM("WGS84",b.y,b.x));return b};
Map.Scale.prototype.getMapPositionOfUTM=function(a,c,b,d){a=_UTMtoLL(b,a,c,d);a=map.Scale.getMapCoordinateOfLatLon(a.y,a.x);return{x:(a.x-map.Scale.minBoundX)/map.Scale.mapUnitsPPX-map.Scale.mapOffset.x,y:map.Scale.bBox.height-(a.y-map.Scale.minBoundY)/map.Scale.mapUnitsPPY-map.Scale.mapOffset.y}};
Map.Scale.prototype.getMapPositionOfLatLon=function(a,c){var b=map.Scale.getMapCoordinateOfLatLon(a,c);return{x:(b.x-map.Scale.minBoundX)/map.Scale.mapUnitsPPX-map.Scale.mapOffset.x,y:map.Scale.bBox.height-(b.y-map.Scale.minBoundY)/map.Scale.mapUnitsPPY-map.Scale.mapOffset.y}};
Map.Scale.prototype.getMapCoordinateOfLatLon=function(a,c){var b;if("Mercator"==this.szMapProjection)b=_LLtoMercator(a,c);else if("WinkelTripel"==this.szMapProjection)b=_LLtoWinkelTripel(a,c);else if("feet"==this.szMapUnits||"meter"==this.szMapUnits||"meters"==this.szMapUnits){if(!this.szDatum&&!this.szUTMZone)return null;b=_LLtoUTM(this.szDatum,a,c,this.szUTMZone);this.nFalseEasting&&(b.x+=this.nFalseEasting-5E5);b.y+=this.nFalseNorthing+this.nCorrectNorthing;b.x+=this.nCorrectEasting;b.y+=this.nCorrectNorthing}return b};
Map.Scale.prototype.getGeoCoordinateOfPoint=function(a,c){if("Mercator"==this.szMapProjection)return _MercatortoLL(c,a);if("feet"!=this.szMapUnits&&"meter"!=this.szMapUnits&&"meters"!=this.szMapUnits)return new point(a,c);if(!this.szDatum&&!this.szUTMZone)return null;var b=new point(a,c);this.nFalseEasting&&(b.x-=this.nFalseEasting-5E5);b.y-=this.nFalseNorthing+this.nCorrectNorthing;b.x-=this.nCorrectEasting;b.y-=this.nCorrectNorthing;return _UTMtoLL(this.szDatum,b.y,b.x,this.szUTMZone)};
Map.Scale.prototype.getMapPosition=function(a,c){var b=getMatrix(this.zoomNode),d=b[0],e=b[3],f=antiZoomAndPanList.getActualMatrix();a=a*f[0]+f[4];c=c*f[3]+f[5];a=a-this.mapPosition.x-this.mapOffset.x;c=c-this.mapPosition.y-this.mapOffset.y;a=(a-b[4])/d;c=(c-b[5])/e;return new point(a,c)};
Map.Scale.prototype.clipWidgetPositionToMap=function(a){a.x>=this.mapPosition.x+this.bBox.width&&(a.x=this.mapPosition.x+this.bBox.width);a.x<=this.mapPosition.x&&(a.x=this.mapPosition.x);a.y>=this.mapPosition.y+this.bBox.height&&(a.y=this.mapPosition.y+this.bBox.height);a.y<=this.mapPosition.y&&(a.y=this.mapPosition.y);return a};
Map.Scale.prototype.isWidgetPositionInMap=function(a){return a.x>this.mapPosition.x+this.bBox.width||a.x<this.mapPosition.x||a.y>this.mapPosition.y+this.bBox.height||a.y<this.mapPosition.y?!1:!0};Map.Scale.prototype.clipWidgetObjectToMap=function(a,c,b){a=map.Dom.getBox(a);c.x+b.x+a.width>this.mapPosition.x+this.bBox.width&&(c.x-=a.width+2*b.x);c.y+b.y+a.height>this.mapPosition.y+this.bBox.height&&(c.y-=a.height+2*b.y);return new point(c.x+b.x,c.y+b.y)};
Map.Scale.prototype.clipWidgetObjectToSVG=function(a,c,b,d){d||(d=map.Dom.getBox(a));a.getAttributeNS(null,"clip-path")&&(a=a.getAttributeNS(null,"clip-path"),a.match(/url/)&&(a=a.substr(5,a.length-6),a=SVGDocument.getElementById(a)))&&(a=a.firstChild,d.x=Number(a.getAttributeNS(null,"x")),d.y=Number(a.getAttributeNS(null,"y")),d.width=Number(a.getAttributeNS(null,"width")),d.height=Number(a.getAttributeNS(null,"height")));a=new point(c.x+b.x,c.y+b.y);a.x+d.width>this.viewBox.width&&(a.x=c.x-d.width-
b.x);0>a.x&&(a.x=map.Scale.normalX(5),0>=b.y&&(a.y-=b.y,b.y=map.Scale.normalY(20),a.y+=b.y));a.y+d.height>this.viewBox.height&&(a.y=c.y-d.height-b.y);0>a.y&&(a.y=map.Scale.normalX(5));return a};
Map.Scale.prototype.getEmbedWidth=function(){if("undefined"!=typeof HTMLDocument&&null!=HTMLDocument)try{var a=HTMLDocument.embeds[szEmbedName].clientWidth,c=a/HTMLDocument.embeds[szEmbedName].clientHeight,b=SVGWidth/SVGHeight;return c<b?a:b/c*a}catch(d){return SVGWidth}return fSVGEmbeded&&fEmbedScale?-1!=EmbedWidth.indexOf("%")?document.embeds.svgMain.clientWidth:EmbedWidth:fPDFEmbed?(c=window.innerWidth/window.innerHeight,b=SVGWidth/SVGHeight,c<b?window.innerWidth:b/c*window.innerWidth):SVGWidth};
Map.Scale.prototype.getEmbedHeight=function(){if("undefined"!=typeof HTMLDocument&&null!=HTMLDocument)try{var a=HTMLDocument.embeds[szEmbedName].clientHeight,c=HTMLDocument.embeds[szEmbedName].clientWidth/a,b=SVGWidth/SVGHeight;return b<c?a:c/b*a}catch(d){return SVGHeight}return fSVGEmbeded&&fEmbedScale?-1!=EmbedHeight.indexOf("%")?document.embeds.svgMain.clientHeight:EmbedHeight:fPDFEmbed?(c=window.innerWidth/window.innerHeight,b=SVGWidth/SVGHeight,b<c?window.innerHeight:c/b*window.innerHeight):
SVGHeight};Map.Scale.prototype.getEmbedScale=function(){if("undefined"!=typeof HTMLDocument&&null!=HTMLDocument)try{var a=HTMLDocument.embeds[szEmbedName].clientWidth,c=HTMLDocument.embeds[szEmbedName].clientHeight,b=SVGWidth/SVGHeight;return b<a/c?c/SVGHeight:a/SVGWidth}catch(d){return 1}return fPDFEmbed?(a=window.innerWidth/window.innerHeight,b=SVGWidth/SVGHeight,b<a?window.innerHeight/SVGHeight:window.innerWidth/SVGWidth):1};
Map.Scale.prototype.getTrueMapScale=function(){return fAdaptMapScaleToSize?this.nMapScale/this.getEmbedScale()*this.nPPI/this.nMapPPI:this.nMapScale*this.nPPI/this.nMapPPI};Map.Scale.prototype.normalX=function(a){return a*this.nScaleX};Map.Scale.prototype.normalY=function(a){return a*this.nScaleY};Map.Scale.prototype.embedX=function(a){return a/this.nScaleX};Map.Scale.prototype.embedY=function(a){return a/this.nScaleY};
Map.Scale.prototype.scaleX=function(a){return a/SVGRootElement.currentScale*this.viewBox.width/this.getEmbedWidth()};Map.Scale.prototype.scaleY=function(a){return a/SVGRootElement.currentScale*this.viewBox.height/this.getEmbedHeight()};Map.Scale.prototype.toSVGx=function(a){return this.scaleX(a*SVGRootElement.currentScale-SVGRootElement.currentTranslate.x)+this.viewBox.x};Map.Scale.prototype.toSVGy=function(a){return this.scaleY(a*SVGRootElement.currentScale-SVGRootElement.currentTranslate.y)+this.viewBox.y};
Map.Scale.prototype.toScreenX=function(a){return(a-this.scaleX(-SVGRootElement.currentTranslate.x)+Number(viewBox[0]))/SVGRootElement.currentScale/viewBoxScale};Map.Scale.prototype.toScreenY=function(a){return(a-this.scaleY(-SVGRootElement.currentTranslate.y)+Number(viewBox[3]))/SVGRootElement.currentScale/viewBoxScale};Map.Scale.prototype.toMapX=function(a){return(a-this.scaleX(-SVGRootElement.currentTranslate.x)+Number(viewBox[0]))/SVGRootElement.currentScale/viewBoxScale};
Map.Scale.prototype.toMapY=function(a){return(a-this.scaleY(-SVGRootElement.currentTranslate.y)+Number(viewBox[3]))/SVGRootElement.currentScale/viewBoxScale};Map.Scale.prototype.getSVGOffset=function(a){var c=a;"svg"!=c.nodeName&&(c=map.Dom.getParentByNodename(a,"svg"));return c&&c!=SVGRootElement&&(a=c.getAttribute("viewBox").split(" "),4==a.length)?new point(Number(a[0]),Number(a[1])):new point(0,0)};
Map.Scale.prototype.getGroupOffset=function(a){var c=null,b=new point(0,0);if(a)for(;c=a.parentNode;){if(c==map.Zoom.zoomNode||1!=c.nodeType)return b;a=getMatrix(c);b.x=b.x*a[0]+a[4];b.y=b.y*a[3]+a[5];a=c}return new point(0,0)};Map.Scale.prototype.getGroupScale=function(a){var c=new point(1,1);for(a=a.parentNode;a&&1==a.nodeType;){var b=getScale(a);b&&(c.x*=b.x,c.y*=b.y);a=a.parentNode}return c};
Map.Scale.prototype.getMapOffset=function(a){var c=this.getSVGOffset(a);a=this.getGroupOffset(a);return new point(-c.x+a.x,-c.y+a.y)};
Map.Scale.prototype.getScreenPosition=function(a){var c=this.getSVGOffset(a),b=this.getGroupOffset(a),d=getTranslate(a);if(a=map.Dom.getBox(a))d.x+=a.x+a.width/2,d.y+=a.y+a.height/2;a=antiZoomAndPanList.getActualMatrix();var e=getMatrix(this.zoomNode),d=map.Scale.rotatePoint(d,-1);return new point((this.mapPosition.x+this.mapOffset.x+e[4]+(d.x-c.x+b.x)*e[0]-a[4])*a[0],(this.mapPosition.y+this.mapOffset.y+e[5]+(d.y-c.y+b.y)*e[3]-a[5])*a[3])};
Map.Scale.prototype.getClientMousePosition=function(a,c){var b=null;if(a){var d=fEmbedScale;fEmbedScale=!0;if(c&&antiZoomAndPanList&&antiZoomAndPanList.isContained(c)){var b=new point(this.normalX(a.clientX),this.normalY(a.clientY)),e=new point(this.getEmbedScale(),this.getEmbedScale());b.x/=e.x;b.y/=e.y}else b=new point(this.toSVGx(a.clientX),this.toSVGy(a.clientY));c&&(e=map.Scale.getGroupScale(c),b.x/=e.x,b.y/=e.y);fEmbedScale=d}return b};
Map.Scale.prototype.refreshCSSStyles=function(){this.fCSSStyleNodeChanged&&(this.CSSStyleNodes.parentNode.parentNode.appendChild(this.CSSStyleNodes.parentNode),this.fCSSStyleNodeChanged=!1)};Map.Scale.prototype.normalizeSymbols=function(a){1==this.featureScaling_lastScale&&this.normalizeElements(a,/symbol/,nNormalSymbolSize);this.nSymbolSize=nNormalButtonSize};
Map.Scale.prototype.normalizeButtons=function(a){this.normalizeElements(a,/button/,nNormalButtonSize);this.normalizeElements(a,/icon/,nNormalButtonSize);this.nButtonSize=nNormalButtonSize};
Map.Scale.prototype.normalizeElements=function(a,c,b){if(a){var d=a.getElementsByTagName("g");a=[];for(var e=0;e<d.length;e++)a[e]=d.item(e);for(e=0;e<a.length;e++){var d=a[e],f=d.getAttributeNS(null,"id");if(f&&f.match(c)){var g=SVGDocument.getElementById(f);g&&g!=d&&g.parentNode.removeChild(g);d.fu=new Methods(d);g=map.Dom.getBox(d);0===g.width&&(g=map.Dom.constructNode("use",SVGTempGroup,{"xlink:href":"#"+f}),g=map.Dom.getBox(g));var h=this.normalX(b)/g.height;d.fu.setPosition((-g.x-g.width/2)*
h,(-g.y-g.height/2)*h);d.fu.scale(h,h);szViewer.match(/Firefox/i)&&(d.setAttributeNS(null,"id",""),g=map.Dom.newGroup(d.parentNode),g=d.parentNode.insertBefore(g,d),g.appendChild(d),g.setAttributeNS(null,"id",f))}}}map.Dom.clearGroup(SVGTempGroup)};
Map.Scale.prototype.changeRotation=function(a,c){var b=getRotateAttributeValue(map.Scale.canvasNode),b=(360+Number(b)+Number(c))%360;setRotate(map.Scale.canvasNode,b);map.Layer.setObjectRotate(a,-b);map.Layer.setPatternRotate(a,-b);map.Layer.setLabelRotate(a,-b)};
Map.Scale.prototype.setRotation=function(a,c){c=Math.floor(c);setRotate(map.Scale.canvasNode,c);map.Layer.setSymbolRotate(a,-c);map.Layer.setObjectRotate(a,-c);map.Layer.setPatternRotate(a,-c);map.Layer.setLabelRotate(a,-c);map.Themes&&map.Themes.resortCharts();map.Dom.clearGroup(SVGToolsGroup);map.Dom.clearGroup(SVGFixedGroup);map.removeAllHighlights()};
Map.Scale.prototype.rotatePoint=function(a,c){var b=getRotateAttributeValue(map.Scale.canvasNode)/180*Math.PI;if(b){-1==c&&(b=-b);var d=a.x,e=a.y;a.x=d*Math.cos(b)+e*Math.sin(b);a.y=-d*Math.sin(b)+e*Math.cos(b)}return a};
Map.Scale.prototype.createWidgetStyles=function(){if("string"!=typeof a)var a="font-family:arial;font-size:12px;fill:#444444;pointer-events:none;";if("string"!=typeof c)var c=a;if("string"!=typeof b)var b="font-family:arial;font-size:10px;fill:#888888;font-weight:bold;font-style:italic;pointer-events:none;";if("string"!=typeof d)var d="font-family:arial;font-size:11px;fill:#555555;;pointer-events:none;";if("string"!=typeof e)var e="font-family:arial;font-size:10px;fill:#444444;pointer-events:none;";
if("string"!=typeof f)var f="font-family:arial;font-size:11px;fill:darkgrey;font-style:italic;stroke:none;pointer-events:none;";if("string"!=typeof g)var g="font-family:arial;font-size:10px;fill:#798697;font-style:normal;stroke:none;pointer-events:none;";this.tStyle={};this.tStyle.ContainerTitle=this.createTextObject(a);this.tStyle.InfoContainerTitle=this.createTextObject(c);this.tStyle.Description=this.createTextObject(b);this.tStyle.Snippet=this.createTextObject(d);this.tStyle.Summary=this.createTextObject(e);
this.tStyle.Note=this.createTextObject(f);this.tStyle.Values=this.createTextObject(g)};Map.Scale.prototype.createTextObject=function(a){var c={};c.szStyle=__scaleStyleString(a,this.normalY(1));c.nFontHeight=__getFontHeightfromStyleString(c.szStyle);return c};
Map.Scale.prototype.getScaleParam=function(){var a={};this.nFeatureScaling&&1!=this.nFeatureScaling&&(a.featureScaling=this.nFeatureScaling);this.nBorderScaling&&1!=this.nBorderScaling&&(a.borderScaling=this.nBorderScaling);this.nLineScaling&&1!=this.nLineScaling&&(a.lineScaling=this.nLineScaling);this.nObjectScaling&&1!=this.nObjectScaling&&(a.objectScaling=this.nObjectScaling);this.nLabelScaling&&1!=this.nLabelScaling&&(a.labelScaling=this.nLabelScaling);this.nNormalSizeScale&&1!=this.nNormalSizeScale&&
(a.normalSizeScale=this.nNormalSizeScale);this.nDynamicScalePow&&3!=this.nDynamicScalePow&&(a.dynamicScalePow=this.nDynamicScalePow);return a};
Map.Scale.prototype.setScaleParam=function(a){var c=this.featureScaling_lastScale;a.featureScaling&&1!=a.featureScaling&&(this.nFeatureScaling=a.featureScaling);a.borderScaling&&1!=a.borderScaling&&(this.nBorderScaling=a.borderScaling);a.lineScaling&&1!=a.lineScaling&&(map.Layer.changeLineScaling(null,a.lineScaling/this.nLineScaling),this.featureScaling_lastScale=c);a.labelScaling&&1!=a.labelScaling&&(map.Layer.changeLabelScaling(null,a.labelScaling/this.nLabelScaling),this.featureScaling_lastScale=
c);a.objectScaling&&1!=a.objectScaling&&(this.nObjectScaling=a.objectScaling);a.normalSizeScale&&1!=a.normalSizeScale&&(this.nNormalSizeScale=Number(a.normalSizeScale));a.dynamicScalePow&&3!=a.dynamicScalePow&&(this.nDynamicScalePow=Number(a.dynamicScalePow))};
var matrixRegExp=/matrix\(([^,]*)\)/,matrixRegExp1=/matrix\(([^,]*)\)/,matrixRegExp2=/matrix\(([0-9., -e]*)\)/,translateRegExp1=/translate\(([^,]*)\)/,translateRegExp2=/translate\(([0-9., -e]*)\)/,rotateRegExp=/rotate\(([0-9]*)\)/,urlRegExp=/url\(#([a-zA-Z0-9\-\.\_\:]*)\)/;
function getMatrix(a){if(a){a=a.getAttribute("transform");var c=null;if(a&&(c=a.match(matrixRegExp1)))return a=c[1].split(" "),[Number(a[0]),Number(a[1]),Number(a[2]),Number(a[3]),Number(a[4]),parseFloat(a[5])];if(a&&(c=a.match(matrixRegExp2)))return a=c[1].split(","),[Number(a[0]),Number(a[1]),Number(a[2]),Number(a[3]),Number(a[4]),Number(a[5])]}return[1,0,0,1,0,0]}
function setMatrix(a,c,b){if(a&&6==c.length){var d=!0;c.forEach(function(a){isNaN(a)&&(d=!1)});if(d){var e=a.getAttributeNS(null,"transform");c="matrix("+c[0]+" "+c[1]+" "+c[2]+" "+c[3]+" "+c[4]+" "+c[5]+")";for(var e=e?e.split(")"):[],f=0;f<e.length;f++)3<e[f].length&&(e[f].match(/rotate/)||e[f].match(/scale/)||b&&e[f].match(/translate/))&&(c=c+" "+e[f]+")");a.setAttributeNS(null,"transform",c)}}}
function getTranslate(a){return a?(a=getMatrix(a),new point(Number(a[4]),Number(a[5]))):new point(0,0)}function setTranslate(a,c,b){var d=getMatrix(a);d[4]=c;d[5]=b;setMatrix(a,[d[0],d[1],d[2],d[3],d[4],d[5]])}
function getTranslateAttributeValue(a){if(a){a=a.getAttributeNS(null,"transform");var c=null;if(a&&(c=a.match(translateRegExp1)))return a=c[1].split(" "),new point(Number(a[0]),parseFloat(a[1]));if(a&&(c=a.match(translateRegExp2)))return a=c[1].split(","),new point(Number(a[0]),Number(a[1]))}return new point(0,0)}function getScale(a){return a?(a=getMatrix(a),new point(Number(a[0]),Number(a[3]))):new point(1,1)}
function setScale(a,c,b){if(a){var d=getMatrix(a);d[0]=c;d[3]=b;setMatrix(a,[d[0],d[1],d[2],d[3],d[4],d[5]],!0)}}function getRotateAttributeValue(a,c){c||(c="transform");if(a){var b=a.getAttributeNS(null,c),d=null;if(b&&(d=b.match(rotateRegExp)))return Number(d[1])}return 0}
function setRotate(a,c,b){b||(b="transform");if(a){for(var d=!1,e="",f=a.getAttributeNS(null,b),f=f?f.split(")"):[],g=0;g<f.length;g++)f[g].match(/rotate/)?(e=e+" rotate("+c+")",d=!0):3<f[g].length&&(e=e+" "+f[g]+")");d||(e=e+" rotate("+c+")");a.setAttributeNS(null,b,e)}}
function getPatternMatrix(a){if(a){if((a=a.getAttribute("patternTransform"))&&(a=a.match(matrixRegExp1)))return a=a[1].split(" "),[Number(a[0]),Number(a[1]),Number(a[2]),Number(a[3]),Number(a[4]),Number(a[5])];if(a&&(a=a.match(matrixRegExp2)))return a=a[1].split(","),[Number(a[0]),Number(a[1]),Number(a[2]),Number(a[3]),Number(a[4]),Number(a[5])]}return[1,0,0,1,0,0]}function point(a,c){this.x=a;this.y=c}
function box(a,c,b,d){this.x=Number(a);this.y=Number(c);this.width=Number(b);this.height=Number(d)}box.prototype.scale=function(a){var c=this.width*a;a*=this.height;this.x-=(c-this.width)/2;this.y-=(a-this.height)/2;this.width=c;this.height=a};box.prototype.check=function(){return isNaN(this.x)||isNaN(this.y)||isNaN(this.width)||isNaN(this.height)?!1:!0};function __boxDup(a){return new box(a.x,a.y,a.width,a.height)}
Map.Dom.prototype.getBox=function(a){try{return __boxDup(a.getBBox())}catch(c){return new box(0,0,0,0)}};function MapObject(a){if(1!=a.nodeType)return null;for(this.szId="";""===this.szId&&a.parentNode&&1==a.nodeType;)if(this.szId=a.getAttributeNS(null,"id"),"string"!=typeof this.szId||""===this.szId||this.szId.match(/noobject/))a=a.parentNode,this.szId="";this.objNode=a;this.fu=new Methods(a)}
MapObject.prototype.getContextMenuId=function(){for(var a=null,a=this.objNode;a;a=a.parentNode)if(1==a.nodeType){var c=a.getAttributeNS(szMapNs,"menu");if(c&&c.length)return c}return null};MapObject.prototype.setContextMenuId=function(a){this.objNode.setAttributeNS(szMapNs,"menu",a)};function Methods(a){this.nodeObj=a}Methods.prototype.setMatrix=function(a){setMatrix(this.nodeObj,a)};Methods.prototype.getPosition=function(){var a=getMatrix(this.nodeObj);return new point(Number(a[4]),Number(a[5]))};
Methods.prototype.setPosition=function(a,c){var b=getMatrix(this.nodeObj);b[4]=a;b[5]=c;setMatrix(this.nodeObj,[b[0],b[1],b[2],b[3],b[4],b[5]])};Methods.prototype.scale=function(a,c){var b=getMatrix(this.nodeObj);b[0]=a;b[3]=c;setMatrix(this.nodeObj,[b[0],b[1],b[2],b[3],b[4],b[5]])};
Methods.prototype.scaleBy=function(a,c){var b=this.getBox(),d=b.width/2+b.x,b=b.height/2+b.y,e=getMatrix(this.nodeObj);e[0]*=a;e[3]*=c;1<a?(e[4]-=d*a-d,e[5]-=b*c-b):(e[4]-=d-d/a,e[5]-=b-b/c);setMatrix(this.nodeObj,[e[0],e[1],e[2],e[3],e[4],e[5]])};Methods.prototype.getScale=function(){var a=getMatrix(this.nodeObj);return new point(Number(a[0]),Number(a[3]))};Methods.prototype.getParentScale=function(){var a=getMatrix(this.nodeObj.parentNode);return new point(Number(a[0]),Number(a[3]))};
Methods.prototype.getGroupScale=function(){return map.Scale.getGroupScale(this.nodeObj)};Methods.prototype.scaleTo=function(a,c){var b=this.getBox();a&&c?this.scaleBy(a/b.width,c/b.height):a?this.scaleBy(a/b.width,a/b.width):c&&this.scaleBy(c/b.height,c/b.height)};Methods.prototype.getBox=function(){var a=map.Dom.getBox(this.nodeObj),c=this.getScale(),a=new box(a.x,a.y,a.width,a.height);a.x*=c.x;a.y*=c.y;a.width*=c.x;a.height*=c.y;return a};
Methods.prototype.getTextLength=function(){return"text"==this.nodeObj.nodeName?this.nodeObj.getComputedTextLength():0};Methods.prototype.focus=function(a,c,b){setMatrix(this.nodeObj,[b,0,0,b,Number(a*b),Number(c*b)])};Methods.prototype.clear=function(){map.Dom.clearGroup(this.nodeObj)};Methods.prototype.isContained=function(a){for(;a=a.parentNode;)if(a==this.nodeObj)return!0;return!1};Methods.prototype.extendAllIds=function(a){map.Dom.extendAllIds(this.objNode,a)};
Map.CSS=function(a){this.stylesA=[];a=a.firstChild.nextSibling.nodeValue.split("}");for(var c=0;c<a.length;c++){var b=a[c].split("{")[0],b=b.split(".")[1];this.stylesA[b]=__getStyleArray(a[c].split("{")[1])}};Map.CSS.prototype.getStyleString=function(){var a="",c;for(c in this.stylesA){var a=a+(" ."+c+"{"),b;for(b in this.stylesA[c])a+=b+":"+this.stylesA[c][b]+";";a+="}"}return a};Map.CSS.prototype.setStyle=function(a,c,b){try{this.stylesA[a][c]=b}catch(d){}};
function __scaleStyleString(a,c){if(!a||!c)return null;for(var b=a.split(";"),d=null,e=0;e<b.length;e++)if(b[e].match(/stroke-width/))d=b[e].split(":"),d[1]=String(parseFloat(d[1])*c),b[e]=d.join(":");else if(b[e].match(/font-size/))d=b[e].split(":"),d[1]=String(parseFloat(d[1])*c)+"px",b[e]=d.join(":");else if(b[e].match(/stroke-dashoffset/))d=b[e].split(":"),d[1]=String(parseFloat(d[1])*c),b[e]=d.join(":");else if(b[e].match(/stroke-dasharray/)){var d=b[e].split(":"),f=d[1].split(",");1<f.length||
(f=d[1].split(" "));b[e]=d[0]+":";for(d=0;d<f.length;d++)f[d]=String(parseFloat(f[d])*c),b[e]+=f[d],d<f.length-1&&(b[e]+=",")}return b.join(";")}
function __scaleLineStyleString(a,c){if(!a||!c)return null;for(var b=a.split(";"),d=null,e=0;e<b.length;e++)if(b[e].match(/stroke-width/))d=b[e].split(":"),d[1]=String(parseFloat(d[1])*c),b[e]=d.join(":");else if(b[e].match(/stroke-dashoffset/))d=b[e].split(":"),d[1]=String(parseFloat(d[1])*c),b[e]=d.join(":");else if(b[e].match(/stroke-dasharray/)){var d=b[e].split(":"),f=d[1].split(",");1<f.length||(f=d[1].split(" "));b[e]=d[0]+":";for(d=0;d<f.length;d++)f[d]=String(parseFloat(f[d])*c),b[e]+=f[d],
d<f.length-1&&(b[e]+=",")}return b.join(";")}function __scaleTextStyleString(a,c){if(!a||!c)return null;for(var b=a.split(";"),d=null,e=0;e<b.length;e++)b[e].match(/font-size/)&&(d=b[e].split(":"),d[1]=String(parseFloat(d[1])*c)+"px",b[e]=d.join(":"));return b.join(";")}function __getFontHeightfromStyleString(a){if(!a)return-1;a=a.split(";");for(var c=0;c<a.length;c++)if(a[c].match(/font-size/))return a=a[c].split(":"),parseFloat(a[1]);return-1}var __idSetRotationTimeout=null,__nOldAngle=0;
function __setRotation(a,c){c!=__nOldAngle&&(__nOldAngle=c,__idSetRotationTimeout&&clearTimeout(__idSetRotationTimeout),__idSetRotationTimeout=setTimeout("__doSetRotation("+c+")",200))}function __doSetRotation(a){executeWithMessage("map.Scale.setRotation(null,"+a+")","...");__idSetRotationTimeout=null}function AntiZoomAndPan(a){this.listA=[];this.buildList(a)}AntiZoomAndPan.prototype.addGroup=function(a){this.listA[this.listA.length]=a};
AntiZoomAndPan.prototype.buildList=function(a){a=SVGRootElement.childNodes;for(var c=0;c<a.length;c++)try{"1"==a.item(c).nodeType&&a.item(c).getAttributeNS(null,"id").match(/antizoomandpan/)&&this.addGroup(a.item(c))}catch(b){}};AntiZoomAndPan.prototype.isContained=function(a){for(;a;){if(this.checkGroup(a))return!0;a=a.parentNode}return!1};AntiZoomAndPan.prototype.checkGroup=function(a){for(var c=0;c<this.listA.length;c++)if(a==this.listA[c])return!0;return!1};
AntiZoomAndPan.prototype.adjustGroups=function(a){if(fAntiZoomAndPan){a=SVGRootElement.getAttribute("viewBox").split(" ");for(var c=SVGOrigViewBoxString.split(" "),c=Number(c[2])/Number(a[2]),b,d=0;d<this.listA.length;d++){var e=this.listA[d];if(b=getMatrix(e))b[0]=1/SVGRootElement.currentScale/c,b[3]=1/SVGRootElement.currentScale/c,b[4]=map.Scale.scaleX(-SVGRootElement.currentTranslate.x)+Number(a[0]),b[5]=map.Scale.scaleY(-SVGRootElement.currentTranslate.y)+Number(a[1]),setMatrix(e,b)}}};
AntiZoomAndPan.prototype.getActualMatrix=function(a){return getMatrix(this.listA[0])};AntiZoomAndPan.prototype.setDisplay=function(a,c){for(var b=0;b<this.listA.length;b++)this.listA[b].style.setProperty("display",c,"")};
AntiZoomAndPan.prototype.initAntiZoomPattern=function(a,c){null===c&&(c=SVGDocument);a&&(c=a.target.ownerDocument);var b=c.getElementsByTagName("pattern");if(null!==b&&0!==b.length){for(var d=b.length,e=b.item(0).parentNode,f,g=0;g<d;g++)b.item(g).getAttributeNS(null,"id").match(/antizoomandpan/)||(f=b.item(g).cloneNode(1E3),f.setAttributeNS(null,"id",f.getAttributeNS(null,"id")+":antizoomandpan"),e.appendChild(f));e.parentNode.appendChild(e)}};
AntiZoomAndPan.prototype.initAntiZoomSymbols=function(a,c){if(null!==c){var b=c.getElementsByTagName("g");if(null!==b&&0!==b.length){for(var d=b.length,e=b.item(0).parentNode,f,g=0;g<d;g++){var h=b.item(g).getAttributeNS(null,"id");h&&h.length&&h.match(/symbol/)&&!h.match(/antizoomandpan/)&&(f=b.item(g).cloneNode(1E3),f.setAttributeNS(null,"id",h+":antizoomandpan"),e.appendChild(f))}e.parentNode.appendChild(e)}}};
AntiZoomAndPan.prototype.extendAllPatternStyles=function(a,c,b){c&&1==c.nodeType&&(a=c.style.getPropertyValue("fill"))&&1<a.length&&a.match(/url/)&&(a=a.split(")")[0]+b+")",c.style.setProperty("fill",a,""))};AntiZoomAndPan.prototype.initAntiZoomStyles=function(a){var c=SVGDocument.getElementById("widgets:antizoomandpan");this.extendAllPatternStyles(a,c,":antizoomandpan")};
function activateTheme(a){if(!a.match(/:label/)&&(a=map.Tiles.getMasterId(a),_activeTheme!=a&&"mapcanvas"!=a)){var c=SVGDocument.getElementById("legend:ident:"+a);if(c){clearThemes();_legendIdent=c;if((c=_legendIdent.nextSibling.nextSibling)&&"text"==c.nodeName)try{var b=map.Dom.getBox(c);_legendIdent.setAttributeNS(null,"width",b.width+map.Scale.normalX(10))}catch(d){}_legendIdent.style.setProperty("display","inline","");_activeTheme=a;if(fActiveThemeInfo){b=new point(map.Scale.mapPosition.x,map.Scale.mapPosition.y+
map.Scale.normalX(nToolMarginTop));map.Viewport.szPopupAlignment.match(/TOP/)&&(b.y=map.Scale.bBox.height+map.Scale.mapPosition.y-map.Scale.normalY(38));b=new InfoContainer(SVGDocument,SVGMenuGroup,"movable",b,{x:map.Scale.normalX(5),y:map.Scale.normalY(5)},"fix");b.frameNode.style.setProperty("fill","#fafafa","");b.setTitle("info on");b.setOnRemove("clearThemes()");var e=map.Scale.tStyle.Description.szStyle;map.Dom.newText(b.workspaceNode,map.Scale.normalX(5),map.Scale.tStyle.Description.nFontHeight,
e,c.firstChild.nodeValue);b.reformat()}try{HTMLWindow.ixmaps.htmlgui_setActiveTheme(a)}catch(f){}try{map.Themes.redrawInfoAll(null)}catch(g){}}else{clearThemes();_removeInfo(null);_activeTheme=a;try{HTMLWindow.ixmaps.htmlgui_setActiveTheme(a)}catch(h){}try{map.Themes.redrawInfoAll(null)}catch(k){}}map.Layer.setPointerEvents(_activeTheme);_activeItem=null}}function getActiveTheme(){return _activeTheme}function isActiveTheme(a){return a==_activeTheme}
function deactivateTheme(a){isActiveTheme(a)&&clearThemes()}function clearThemes(){_legendIdent&&(_legendIdent.style.setProperty("display","none",""),_legendIdent=null);_activeTheme=null;highLightList.removeAll()}var __highlightedTheme=null;
function highlightTheme(a){for(;a&&"g"!=a.objNode.nodeName&&a.objNode.parentNode;)if(null===(a=new MapObject(a.objNode.parentNode)))return;var c=a.szId;map.Tiles&&(c=map.Tiles.getMasterId(c));var b=a.objNode.getAttributeNS(szMapNs,"value");(!b||1>b.length)&&a.objNode.firstChild&&a.objNode.firstChild.nextSibling&&(b=a.objNode.firstChild.nextSibling.getAttributeNS(szMapNs,"value"));b&&b.length&&(c=c.split("::")[0]+"::"+b);if(__highlightedTheme=SVGDocument.getElementById("legend:ident:"+c))(a=__highlightedTheme.nextSibling.nextSibling)&&
"text"==a.nodeName&&(a=map.Dom.getBox(a),__highlightedTheme.setAttributeNS(null,"width",a.width+map.Scale.normalX(10))),__highlightedTheme.style.setProperty("display","inline","")}function highlightThemeRemove(){__highlightedTheme&&(__highlightedTheme.style.setProperty("display","none",""),__highlightedTheme=null)}
function displayTooltip(a,c){if(c&&1==c.nodeType){for(var b=c.getAttributeNS(szMapNs,"tooltip")||"";null!=(c=c.parentNode)&&"g"==c.nodeName;){var d=c.getAttributeNS(szMapNs,"tooltip");d&&d.length&&(b=d)}if(b&&b.length){try{b=map.User.onTooltipDisplay(null,b,c)}catch(e){}try{b=HTMLWindow.ixmaps.htmlgui_onTooltipDisplay(b,c)}catch(f){}d=map.Scale.getClientMousePosition(a,SVGPopupGroup);killTooltip();idTooltipTimeout=setTimeout('doDisplayTooltip("'+__stripQuotes(b)+'",'+d.x+","+d.y+")",nTooltipTimeout);
return!0}}return!1}function displayTooltipText(a,c){if(c&&c.length){var b=map.Scale.getClientMousePosition(a,SVGPopupGroup);killTooltip();idTooltipTimeout=setTimeout("doDisplayTooltip('"+__stripQuotes(c)+"',"+b.x+","+b.y+")",nTooltipTimeout)}}function __stripQuotes(a){var c=a.split('"');a=c[0];for(var b=1;b<c.length;b++)a+="``"+c[b];return a}function __encodeSingleQuote(a){var c=a.split("'");a=c[0];for(var b=1;b<c.length;b++)a+="`"+c[b];return a}
function __encodeDoubleQuotes(a){return a.replace(/\\/gi,"\\\\").replace(/\"/gi,'\\"')}function __decodeSingleQuote(a){var c=a.split("`");a=c[0];for(var b=1;b<c.length;b++)a+="'"+c[b];return a}
function doDisplayTooltip(a,c,b){idTooltipTimeout=null;if(a&&a.length&&(SVGTltipGroup.fu.clear(),c=new point(c,b),a.length)){a=map.Dictionary.getLocalText(a);b=new point(map.Scale.normalX(20),map.Scale.normalY(20));a=createTextField(SVGDocument,SVGTltipGroup,"tooltip",a);a.style.setProperty("pointer-events","none","");var d=map.Dom.getBox(a);SVGPopupGroup.hasChildNodes&&(c.y-=map.Scale.normalY(20));c.x+b.x+d.width>map.Scale.viewBox.width&&(c.x-=c.x+b.x+d.width-map.Scale.viewBox.width,c.y+=d.height);
c.y+b.y+d.height>map.Scale.viewBox.height&&(c.y-=d.height+2*b.y);a.fu.setPosition(c.x+b.x,Math.max(c.y+b.y,100));_tooltip=a}}function killTooltip(){idTooltipTimeout&&clearTimeout(idTooltipTimeout);_tooltip&&(SVGTltipGroup.fu.clear(),_tooltip=null)}var Dictionary=function(){this.szDictionary=[]};map.Dictionary=new Dictionary;Dictionary.prototype.add=function(a,c){this.szDictionary[a]||(this.szDictionary[a]=c)};Dictionary.prototype.replace=function(a,c){this.szDictionary[a]=c};
Dictionary.prototype.getLocalText=function(a){try{if("undefined"!=typeof this.szDictionary[a])return String(this.szDictionary[a]);for(var c="",b=a.split(" "),d=0;d<b.length;d++)var e=this.szDictionary["'"+b[d]+"'"],c=c+String(e?e:b[d]),c=c+(d<b.length-1?" ":"");return c}catch(f){return a}};Dictionary.prototype.applyToNode=function(a){a=a.getElementsByTagName("text");for(var c=0;c<a.length;c++)a.item(c).firstChild.nodeValue=this.getLocalText(a.item(c).firstChild.nodeValue)};
var tClearMessage=null,tClearNotify=null;
function displayMessage(a,c,b){if("notify"!=b||fNotify)if("string"!=typeof a||0===a.length)SVGMessageGroup.fu.clear();else{tClearMessage&&(clearTimeout(tClearMessage),tClearMessage=null);a=map.Dictionary.getLocalText(a);if("notify"!=b&&"big"!=b)if(map.isInitializing())try{HTMLWindow.ixmaps.htmlgui_displayInfo(a);return}catch(d){}else try{if(HTMLWindow.ixmaps.htmlgui_isInfoDisplay()){HTMLWindow.ixmaps.htmlgui_displayInfo(a);c&&clearMessage(c);return}}catch(e){}if("big"==b)var f=64,g="transparent",
h=new point(map.Scale.bBox.width/2+map.Scale.mapPosition.x,map.Scale.normalY(38));else"notify"==b?(f=24,g="flat",h=new point(map.Scale.bBox.width/2+map.Scale.mapPosition.x,map.Scale.mapPosition.y+(map.Scale.normalY(2*f/3)+nToolMarginTop))):"top"==b?(f=24,g="flat",h=new point(map.Scale.bBox.width/2+map.Scale.mapPosition.x,map.Scale.mapPosition.y+(map.Scale.normalY(2*f/3)+nToolMarginTop))):(f=36,g="flat",h=new point(map.Scale.bBox.width/2+map.Scale.mapPosition.x,map.Scale.bBox.height/2+map.Scale.mapPosition.y-
map.Scale.normalX(f/2)));if(SVGDocument&&SVGMessageGroup&&("notify"==b?SVGNotifyGroup.fu.clear():SVGMessageGroup.fu.clear(),a&&a.length)){var k=null;try{var l=new TextField(null,"notify"==b?SVGNotifyGroup:SVGMessageGroup,g,f);l.setText(a);var k=l.textGroup,n=k.fu.getBox();k.fu.setPosition(h.x-n.width/2,h.y+n.height/2)}catch(m){k=createTextField(SVGDocument,"notify"==b?SVGNotifyGroup:SVGMessageGroup,"popup_message",a,f);try{n=k.fu.getBox(),k.fu.setPosition(h.x-n.width/2,h.y+n.height/2)}catch(p){k.fu.setPosition(h.x-
map.Scale.normalX(50),h.y+map.Scale.normalX(10))}}}c&&("notify"==b?clearNotify(c):clearMessage(c))}}function clearMessage(a){tClearMessage&&!a||do_clearMessage(a||0)}function do_clearMessage(a){if(a)tClearMessage&&clearTimeout(tClearMessage),tClearMessage=setTimeout("do_clearMessage()",a);else{try{HTMLWindow.ixmaps.htmlgui_killInfo()}catch(c){}SVGMessageGroup.fu.clear()}}
function clearNotify(a){a?(tClearNotify&&clearTimeout(tClearNotify),tClearNotify=setTimeout("clearNotify()",a)):SVGNotifyGroup.fu.clear()}
function displayProgressBarOld(a,c,b,d,e,f){var g=new point(map.Scale.bBox.width/2+map.Scale.mapPosition.x,map.Scale.mapPosition.y+map.Scale.normalX((fMapBorder3D?6:0)+nToolMarginTop));if(SVGDocument&&SVGMessageGroup){b||(b="");b=map.Dictionary.getLocalText(b);var h=null,k=null,l=new TextField(null,SVGMessageGroup,fPDFEmbed?"":"light",13);l?(l.setText(b),h=l.textGroup,k=l.workspaceNode):k=h=createTextField(SVGDocument,SVGMessageGroup,"popup_message",b,24);var n=100/c,m=13*b.length/2,p=b.length?-9.36:
0;if(b.length){var q=map.Dom.getBox(k);q.width&&(m=q.width+10)}map.Dom.newShape("rect",k,m,p,c*n,13,"fill:none;stroke:grey;");map.Dom.newShape("rect",k,m,p,a*n,13,"fill:#3787D7;stroke:none;");e&&(b=new Button(k,"","BUTTON","#delete_button",e,"","cancel operation"),b.scale(1/map.Scale.normalX(1),1/map.Scale.normalY(1)),b.setPosition(m+100+20,-3));f&&a&&(m=map.Dictionary.getLocalText("done")+" "+a+" "+map.Dictionary.getLocalText("/")+" "+c+" "+map.Dictionary.getLocalText("in")+" "+__formatTime(f)+" ",
m+=map.Dictionary.getLocalText("estimated time left")+": "+__formatTime(f/a*c-f),map.Dom.newText(k,0,15.6,"font-family:arial;font-size:13px;fill:gray;",m));l&&l.resizeField();try{q=h.fu.getBox(),h.fu.setPosition(g.x-q.width/2,g.y+map.Scale.normalY(13*1.3))}catch(r){}}d&&clearMessage(d)}
function displayProgressBar(a,c,b,d,e,f){SVGDocument&&SVGMessageGroup&&(b=map.Dom.newGroup(SVGMessageGroup,"popup_progressbar"),b.fu.setPosition(0,0),b.fu.scale(20,20),map.Dom.newShape("rect",b,0,0,SVGWidth/c*a,3,"fill:#3787D7;stroke:none;"));d&&clearMessage(d)}var debugLine=0,lastDate=new Date;
function _TRACE(a){if("undefined"!=typeof console&&"undefined"!=typeof console.log)lastDate=new Date;else if(!fPDFEmbed||fDebug)try{TRACE(a)}catch(c){if(fDebug)try{SVGDocument&&SVGMenuGroup&&(createTextField(SVGDocument,SVGMenuGroup,"message",a).fu.setPosition(map.Scale.normalX(0),map.Scale.normalY(18*debugLine)),20<++debugLine&&(debugLine=0,SVGMenuGroup.fu.clear()))}catch(b){}}}
function _LOG(a){if("undefined"!=typeof console&&"undefined"!=typeof console.log){var c=new Date,c=c.getMinutes()+":"+String(c.getSeconds())+"."+String(c.getMilliseconds());console.log("_LOG: time["+c+"] "+a)}}
function _STATUS(a){if(fStatus){var c=map.Dom.getObjectById("legend:statusgroup");c||(c=map.Dom.getObjectById("legend:scalegroup"),c=map.Dom.newGroup(c,"legend:statusgroup"));map.Dom.clearGroup(c);map.Dom.newText(c,map.Scale.normalX(220),map.Scale.normalY(12),"font-family:arial;font-size:"+map.Scale.normalY(12)+"px;fill:black",a)}}
function _INFO(a){try{HTMLWindow.ixmaps.htmlgui_displayInfo(a)}catch(c){fDebug&&SVGDocument&&SVGMessageGroup&&createTextField(SVGDocument,SVGMessageGroup,"message",a).fu.setPosition(map.Scale.normalX(0),map.Scale.normalY(0))}}function _KILLINFO(){try{HTMLWindow.ixmaps.htmlgui_killInfo()}catch(a){}}
function _ERROR(a){try{HTMLWindow.ixmaps.htmlgui_errorLog(a)}catch(c){fDebug&&SVGDocument&&SVGMessageGroup&&createTextField(SVGDocument,SVGMessageGroup,"message",a).fu.setPosition(map.Scale.normalX(0),map.Scale.normalY(0))}}var __textField_group=null,__textField_frame=null,__textField_shadow=null,__textField_fontheight=12;
function createTextField(a,c,b,d,e){e||(e=12);if(a&&c)return a=map.Dom.newGroup(c,b),c=map.Dom.newShape("rect",a,1,1,1,1,"fill:#444444;opacity:0.5;stroke:none"),b=map.Dom.newShape("rect",a,1,1,1,1,"fill:#fefeff;stroke:#444444;stroke-width:"+map.Scale.normalX(.2)+""),map.Dom.newText(a,0,map.Scale.normalY(1.25*e),"font-family:arial;font-size:"+map.Scale.normalY(e)+"px;fill:"+szInfoBodyColor+"",d),__textField_group=a,__textField_frame=b,__textField_shadow=c,__textField_fontheight=e,sizeTextField(),a}
function sizeTextField(){var a=__textField_fontheight,c=map.Dom.getBox(__textField_group);__textField_frame.setAttributeNS(null,"rx",map.Scale.normalX(2));__textField_frame.setAttributeNS(null,"ry",map.Scale.normalX(2));__textField_frame.setAttributeNS(null,"x",-map.Scale.normalX(.75*a));__textField_frame.setAttributeNS(null,"y",-map.Scale.normalY(1));__textField_frame.setAttributeNS(null,"width",c.width+map.Scale.normalX(1.5*a));__textField_frame.setAttributeNS(null,"height",c.height+map.Scale.normalY(a)/
2);__textField_shadow.setAttributeNS(null,"rx",map.Scale.normalX(4));__textField_shadow.setAttributeNS(null,"ry",map.Scale.normalX(4));__textField_shadow.setAttributeNS(null,"x",-map.Scale.normalX(.75*a)+map.Scale.normalX(2));__textField_shadow.setAttributeNS(null,"y",map.Scale.normalY(2));__textField_shadow.setAttributeNS(null,"width",c.width+map.Scale.normalX(1.5*a)+map.Scale.normalX(1.5));__textField_shadow.setAttributeNS(null,"height",c.height+map.Scale.normalX(a)/2-map.Scale.normalX(0))}
function executeWithMessage(a,c,b){fExecuteSilent||("undefined"==typeof b&&(b=250),displayMessage(c,null,szMessagePosition));setTimeout('doExecuteWithMessage("'+__encodeDoubleQuotes(a)+'")',b)}function doExecuteWithMessage(a){map.isIdle();try{eval(a)}catch(c){alert("error '"+c+"' on: "+a)}}function executeWithProgressBar(a,c,b,d,e,f){displayProgressBar(c,b,d,0,e,f);setTimeout(a,1)}
function __doGetPolygonSurface(a,c){for(var b in a){if(c)var d=map.Scale.getMapPosition(a[b].x,a[b].y),d=map.Scale.getMapCoordinate(d.x,d.y),d=map.Scale.getGeoCoordinateOfPoint(d.x,d.y),d=_LLtoUTM("WGS84",d.y,d.x);else d=map.Scale.getMapCoordinateUTM(a[b].x,a[b].y);a[b].x=d.x;a[b].y=d.y}d=b=0;a[a.length]=a[0];for(var e=0;e<a.length-1;e++)d=a[e].x*a[e+1].y-a[e+1].x*a[e].y,b+=d;return b/2}
function __doGetPolygonCenter(a){var c=new point(0,0),b;for(b in a)c.x+=a[b].x,c.y+=a[b].y;c.x/=a.length;c.y/=a.length;return c}function __getStyleObj(a){if(null===a||2>a.length)return null;try{map.styleObj={};for(var c=a.split(";"),b=0;b<c.length;b++)if(c[b].length){var d=c[b].split(":"),e=d[0].length+1,f=c[b].substr(e,c[b].length-e);try{map.styleObj[d[0].trim()]=JSON.parse(f)}catch(g){map.styleObj[d[0].trim()]=f}}return map.styleObj}catch(h){alert("ERROR parsing: "+a)}return null}
function __getStyleArray(a){if("undefined"==typeof a||null==a||2>a.length)return null;try{for(var c=[],b=a.split(";"),d=0;d<b.length;d++)if(b[d].length){var e=b[d].split(":");c[e[0]]=e[1]}return c}catch(f){alert("ERROR parsing: "+a)}return null}var __timer_nMillisec=0;function __timer_reset(){__timer_nMillisec=(new Date).getTime()}function __timer_getMS(){return(new Date).getTime()-__timer_nMillisec}function __timer_getSEC(){return((new Date).getTime()-__timer_nMillisec)/1E3}
function __formatTime(a){var c=Math.floor(a/3600);a-=3600*c;var b=Math.floor(a/60);a-=60*b;return c?String(c+" hr "+b+" min "+Math.floor(a)+" sec"):b?String(b+" min "+Math.floor(a)+" sec"):String(Math.floor(a)+" sec")}
function __formatValue(a,c,b){a=Number(a);if(!isFinite(a)||!isFinite(c)||0===a||1E12<a||-1E12>a)return String(a);fDecimalPointComma||(b+="|BLANK");c||(c=0);c=Math.max(0,c);if(1E-7<a&&0<c)for(;0===a.toFixed(c);)c++;a=a.toFixed(c+1);var d=Math.pow(10,c);a=b&&b.match(/CEIL/)?Math.ceil(a*d)/d:b&&b.match(/FLOOR/)?Math.floor(a*d)/d:Math.round(a*d)/d;d=String(a);for(d=d.match(/\./)?d.split(".")[1]:"";d.length<c;)d+="0";c=0>a?"-":"";var e="";a=Math.floor(Math.abs(a));if(!b||!b.match(/NOBREAKS/)){for(var f=
1E3;a>f;)f*=1E3;for(var f=f/1E3,g=0,h=" ";1E3<=f;)g=Math.floor(a/f),c+=__maptheme_formatpart(g,e),a%=f,f/=1E3,g&&(e="0",h=b&&b.match(/BLANK/)?" ":"."),c+=h;c+=__maptheme_formatpart(a,e);c.length&&"-"!=c||(c+="0");d.length&&(c+=(b&&b.match(/BLANK/)?".":",")+d)}return c}function __maptheme_formatpart(a,c){c||(c="");var b="";100>a&&(b+=c);10>a&&(b+=c);return b=0===a?b+c:b+String(a)}
function SVGLoader(){this.szUrlA=[];this.stackA=[];this.nPending=0;this.importSVGFile=function(a,c,b,d){if(this.szUrlA[a]==b)return!1;this.doImportSVGFile(a,c,b,d)};this.push=function(a,c,b,d){this.stackA.push({szUrl:a,svgDocument:c,targetGroup:b,callback:d})};this.pop=function(){if(!this.isWaiting()){var a=this.stackA.shift();a&&this.doImportSVGFile(a.szUrl,a.svgDocument,a.targetGroup,a.callback)}};this.doImportSVGFile=function(a,c,b,d){function e(a){this.parent=a}this.nPending++;e.prototype.operationComplete=
function(b,c,d){this.parent.nPending--;this.parent.pop();c&&200==b&&(this.processImported(c.documentElement),_LOG("SVGLoader: "+a+" (loaded)"))};e.prototype.processImported=function(c){if(a.match(/widget/))for(var d=map.Dom.getAllIds(c),e=0;e<d.length;e++){var k=SVGDocument.getElementById(d[e]);k&&k.parentNode.removeChild(k)}a.match(/pattern/)&&(b=map.Dom.newGroup(b,String(Math.random())));b.appendChild(c);if(!this.initMenu(b)){this.initCSS(b);this.initScripts(b);a.match(/widget/)&&this.initToolbar(b);
a.match(/logo/)&&this.initLogo(b);this.loadScripts(b);try{antiZoomAndPanList.initAntiZoomPattern(null,b),map.Layer.initPatternScaling(null,b)}catch(l){}a.match(/symbol/)&&map.Scale.normalizeSymbols(b);a.match(/widget/)&&map.Scale.normalizeButtons(b)}};e.prototype.initMenu=function(a){a=a.getElementsByTagName("menu");if(a.length){for(var b=0;b<a.length;b++){var c=a.item(b).getAttributeNS(null,"id");(c=SVGDocument.getElementById(c))&&c!=a.item(b)&&(c.parentNode.removeChild(c),b--)}return!0}return!1};
e.prototype.initToolbar=function(a){try{map.Toolbar.init(),map.Legend.init()}catch(b){}return!0};e.prototype.initLogo=function(a){var b=SVGDocument.getElementById("mapbackground:logo");null===b&&(b=map.Dom.newGroup(SVGDocument.getElementById("mapbackground"),"mapbackground:logo"));if(b){map.Dom.clearGroup(b);a=a.getElementsByTagName("svg").item(0).childNodes;for(var c=0;c<a.length;c++)b.appendChild(a.item(c)),c--}return!0};e.prototype.loadScripts=function(a){a=a.getElementsByTagName("script");for(var b=
0;b<a.length;b++){var c=a.item(b).getAttributeNS(szXlink,"href");c&&c.length&&(new JSLoader).loadScript(c)}return!0};e.prototype.initScripts=function(a){a=a.getElementsByTagName("script");for(var b=0;b<a.length;b++)if(a.item(b).firstChild){var c=a.item(b).firstChild.nodeValue;try{eval(c)}catch(d){_LOG("ERROR: could not eval loaded script!")}}return!0};e.prototype.initCSS=function(a){return a.getElementsByTagName("style").length?(SVGDocument.getElementById("mapstyles"),!0):!1};0<a.length&&getData(a,
new e(this))};this.isWaiting=function(){return this.nPending}}
function loadSVGIncludes(a,c,b){a=a?a.target.ownerDocument:SVGDocument;var d=a.getElementById("mapinclude");if(d){if(c&&1<c.length){var e=c.substr(c.length-1,1);"\\"!=e&&"/"!=e&&(c+="/")}d=d.getElementsByTagName("g");for(e=0;e<d.length;e++){var f=d.item(e),g=f.getAttribute("xlink:href");!g||g.match(/maplocal/)||g.match(/mapmenu/)||g.match(/mapimages/)||g.match(/mappattern/)||g.match(/mapfilter/)||!(g&&1<g.length)||b&&g!=b||(g=c+g,new SVGLoader,map.Loader.importSVGFile(g,a,f,null))}}}
var __svgLoaderTiles=null;
function SVGLoaderTiles(){this.szUrlA=[];this.stackA=[];this.nToLoad=this.nRequest=this.nPending=0;__svgLoaderTiles=this;this.importSVGFile=function(a,c,b,d){a=(map.mapRoot||"")+a;if(this.szUrlA[a]==b)return!1;this.nRequest++;this.nToLoad++;fLoadingSilent?this.doImportSVGFile(a,c,b,d):!fLoadMultiTiles&&this.isWaiting()?this.push(a,c,b,d):(displayProgressBar(0,1,map.Dictionary.getLocalText("loading map elements")),this.push(a,c,b,d),setTimeout("__svgLoaderTiles.pop()",10));return!0};this.push=function(a,
c,b,d){this.isStacked(a,c,b)||this.stackA.push({szUrl:a,svgDocument:c,targetGroup:b,callback:d})};this.pop=function(){if(!this.isWaiting()){var a=this.stackA.shift();a?(displayProgressBar(this.nToLoad-this.nPending-this.stackA.length,this.nToLoad,map.Dictionary.getLocalText("loading map elements")),this.doImportSVGFile(a.szUrl,a.svgDocument,a.targetGroup,a.callback)):this.nToLoad=this.nRequest=0}};this.isStacked=function(a,c,b){for(var d=0;d<this.stackA.length;d++)if(this.stackA[d].szUrl==a&&this.stackA[d].svgDocument==
c&&this.stackA[d].targetGroup==b)return!0;return!1};this.isAnyStacked=function(){return this.stackA.length};this.doImportSVGFile=function(a,c,b,d){function e(a){this.parent=a}if(this.szUrlA[a]==b)return!1;this.szUrlA[a]=b;this.nPending++;e.prototype.operationComplete=function(b,c,d){this.parent.szUrlA[a]=null;this.parent.nPending--;this.parent.nRequest--;c&&200==b&&this.processImported(c.documentElement);this.parent.pop()};e.prototype.processImported=function(a){if(b.childNodes.length)_STATUS("Tiling: doppio tile !!!");
else{b.appendChild(a);if(map&&map.Layer){for(var c in map.Layer.listA){a=map.Layer.listA[c];if("undefined"!=typeof a.nState){var d=b.getAttributeNS(null,"id"),d=a.szName+"#"+d.substr(d.length-6,6);map.Layer.switchLayerByFeature(d,a.nState)}for(var e in a.categoryA)d=b.getAttributeNS(null,"id"),d=a.szName+"#"+d.substr(d.length-6,6)+"::"+e,map.Layer.switchLayerByFeature(d,"inline"==a.categoryA[e].display)}fSwitchByCSS&&map.Scale.CSSStyleNodes||map.Layer.switchScaleDependentLayer(null,b)}if(map&&map.Zoom){if(1!=
map.Zoom.nZoom){c=null;c=b.getElementsByTagName("g");for(a=0;a<c.length;a++){var l=c.item(a).getAttributeNS(null,"style");l&&l.length&&(l=__scaleStyleString(l,map.Layer.nFeatureScale*map.Scale.nLineScaling),c.item(a).setAttributeNS(null,"style",l),b.setAttributeNS(szMapNs,"deltaTBD","1"),b.setAttributeNS(szMapNs,"scale",String(map.Layer.nFeatureScale*map.Scale.nLineScaling)));d=c.item(a).childNodes;for(e=0;e<d.length;e++)"text"==d.item(e).nodeName&&(l=d.item(e).getAttributeNS(null,"style"))&&l.length&&
(l=__scaleStyleString(l,map.Layer.nFeatureScale*map.Scale.nLabelScaling),d.item(e).setAttributeNS(null,"style",l))}map.Layer.scaleTextOffsets(b,1/map.Zoom.nZoomX,1/map.Zoom.nZoomY,!0)}map.Layer.adaptLabel(null,b)}map&&map.Themes&&(map.Themes.addToThemeNodesCache(b),0===this.parent.nPending+this.parent.stackA.length&&map.Themes.actualizeActiveTheme(!0))}};return 0<a.length?(getData(a,new e(this)),!0):!1};this.isWaiting=function(){return this.nPending};this.isLoading=function(){return this.nPending|
this.isAnyStacked()}}var __svgLoaderMap=null;
function SVGLoaderMap(){this.szUrlA=[];this.stackA=[];this.nToLoad=this.nRequest=this.nPending=0;__svgLoaderMap=this;this.importSVGFile=function(a,c,b,d){if(b&&this.szUrlA[a]==b)return!1;this.nRequest++;this.nToLoad++;fLoadingSilent?this.doImportSVGFile(a,c,b,d):!fLoadMultiTiles&&this.isWaiting()?this.push(a,c,b,d):(displayMessage(map.Dictionary.getLocalText("loading map")),displayProgressBar(0,1,map.Dictionary.getLocalText("loading map")),this.push(a,c,b,d),setTimeout("__svgLoaderMap.pop()",10));
return!0};this.push=function(a,c,b,d){this.isStacked(a,c,b)||this.stackA.push({szUrl:a,svgDocument:c,targetGroup:b,callback:d})};this.pop=function(){if(!this.isWaiting()){var a=this.stackA.shift();a?(displayProgressBar(this.nToLoad-this.nPending-this.stackA.length,this.nToLoad,map.Dictionary.getLocalText("loading map elements")),this.doImportSVGFile(a.szUrl,a.svgDocument,a.targetGroup,a.callback)):this.nToLoad=this.nRequest=0}};this.isStacked=function(a,c,b){for(var d=0;d<this.stackA.length;d++)if(this.stackA[d].szUrl==
a&&this.stackA[d].svgDocument==c&&this.stackA[d].targetGroup==b)return!0;return!1};this.isAnyStacked=function(){return this.stackA.length};this.doImportSVGFile=function(a,c,b,d){function e(a){this.parent=a}if(b&&this.szUrlA[a]==b)return!1;this.szUrlA[a]=b;this.nPending++;e.prototype.operationComplete=function(b,c,d){this.parent.szUrlA[a]=null;this.parent.nPending--;this.parent.nRequest--;c&&200==b?this.processImported(c.documentElement):displayMessage("error loading map");this.parent.pop()};e.prototype.processImported=
function(a){var b=function(a,b){b&&a?(a.parentNode.insertBefore(b,a),a.parentNode.removeChild(a)):b?SVGRootElement.appendChild(b):a&&a.parentNode.removeChild(a)};map.hideAll();b(SVGDocument.getElementsByTagName("metadata")[2],a.getElementsByTagName("metadata")[0]);b(SVGDocument.getElementById("maplayer"),a.getElementById("maplayer"));b(SVGDocument.getElementById("extension"),a.getElementById("extension"));b(SVGDocument.getElementById("mapclipdef"),a.getElementById("mapclipdef"));b(SVGDocument.getElementById("mapstyles"),
a.getElementById("mapstyles"));(b=a.getElementsByTagName("pattern"))&&b[0]&&(a=a.getElementsByTagName("pattern")[0].parentNode,SVGRootElement.appendChild(a));map.Scale=new Map.Scale(null);map.Scale.superclass=map;map.Scale.createWidgetStyles();map.Scale.normalizeSymbols(SVGDocument.getElementById("symbolstore"));map.Scale.normalizeButtons(SVGDocument.getElementById("widgetstore"));map.Layer=new Map.Layer(null);map.Layer.initPatternScaling(null,null);map.Zoom=new Map.Zoom(map.Scale.initScale);map.Tiles=
new Map.Tiles;map.Label=new Map.Label;map.Viewport=new Map.Viewport;map.Query=new Map.Query;a=map.Zoom.getBox();a=map.Scale.getMapCoordinate(a.x+a.width/2,a.y+a.height/2);map.Zoom.doSetCenterByParentMap(a.x,a.y);map.Layer.switchScaleDependentLayer();map.Scale.refreshCSSStyles();HTMLWindow.ixmaps.htmlgui_onMapReady(window);setTimeout("map.showAll()",1E3)};console.log("*** load new map ***");console.log(a);console.log("********************");return 0<a.length?(getData(a,new e(this)),!0):!1};this.isWaiting=
function(){return this.nPending};this.isLoading=function(){return this.nPending|this.isAnyStacked()}}var scriptLoaderPool=new JSLoaderPool;function JSLoaderPool(){this.loaderA=[];this.szSuffix=".js";this.loadedUrlA=[];this.loadingUrlA=[];this.errorUrlA=[]}JSLoaderPool.prototype.add=function(a){this.loaderA[this.loaderA.length]=a};
JSLoaderPool.prototype.evalScripts=function(){if(!1===this.isLoading()){for(var a=0;a<this.loaderA.length;a++)for(var c=this.loaderA[a],b=0;b<c.loadedScripts.length;b++)this.isScriptLoaded(c.szUrl)||(this.evalScript(c.loadedScripts[b]),this.setScriptLoaded(c.szUrl));this.loaderA.length=0}};JSLoaderPool.prototype.evalScript=function(a){eval(a)};JSLoaderPool.prototype.setScriptError=function(a){this.errorUrlA[this.errorUrlA.length]=a};
JSLoaderPool.prototype.setScriptLoaded=function(a){this.loadedUrlA[this.loadedUrlA.length]=a};JSLoaderPool.prototype.setScriptLoading=function(a){this.loadingUrlA[this.loadingUrlA.length]=a};JSLoaderPool.prototype.isScriptLoaded=function(a){for(var c=0;c<this.loadedUrlA.length;c++)if(this.loadedUrlA[c]==a)return!0;return!1};JSLoaderPool.prototype.isScriptLoading=function(a){for(var c=0;c<this.loadingUrlA.length;c++)if(this.loadingUrlA[c]==a)return!0;return!1};
JSLoaderPool.prototype.isScriptError=function(a){for(var c=0;c<this.errorUrlA.length;c++)if(this.errorUrlA[c]==a)return!0;return!1};JSLoaderPool.prototype.resetScriptLoading=function(a){for(var c=0;c<this.loadingUrlA.length;c++)this.loadingUrlA[c]==a&&(this.loadingUrlA[c]="");for(c=0;c<this.loadedUrlA.length;c++)this.loadedUrlA[c]==a&&(this.loadedUrlA[c]="");for(c=0;c<this.errorUrlA.length;c++)this.errorUrlA[c]==a&&(this.errorUrlA[c]="")};
JSLoaderPool.prototype.isLoading=function(){var a;for(a=0;a<this.loaderA.length;a++)if(0<this.loaderA[a].reqCnt)return!0;return!1};function JSLoader(){this.loadedScripts=[];this.reqCnt=0;this.isLoading=!1;this.finishedCallback=this.errorCallback=null;this.szMessage="... loading ...";this.pool=scriptLoaderPool;this.pool.add(this)}
JSLoader.prototype.loadScript=function(a,c){c&&this.pool.resetScriptLoading(a);try{a.match(/./)||(a+=this.pool.szSuffix),this.szUrl=a,this.pool.isScriptError(this.szUrl)?eval(this.errorCallback):this.pool.isScriptLoaded(this.szUrl)?eval(this.finishedCallback):this.pool.isScriptLoading(this.szUrl)||(this.isLoading=!0,this.reqCnt++,this.pool.setScriptLoading(this.szUrl),getData(a,this))}catch(b){}};
JSLoader.prototype.operationComplete=function(a,c,b){200!=a||!c&&!b?(this.pool.setScriptError(this.szUrl),this.errorCallback&&(this.finishedCallback=null,eval(this.errorCallback))):this.loadedScripts.push(b);this.reqCnt--;0>=this.reqCnt&&this.evalScripts()};JSLoader.prototype.processImported=function(a){alert(a)};JSLoader.prototype.evalScripts=function(){this.pool.evalScripts();this.isLoading=!1;this.finishedCallback&&eval(this.finishedCallback)};JSLoader.prototype.isLoading=function(){return 0<this.reqCnt};
function getData(a,c){if(window.getURL)window.getURL(a,c);else if(window.XMLHttpRequest){var b=function(){4==d.readyState&&c.operationComplete(d.status,d.responseXML,d.responseText)};try{var d=null,d=new XMLHttpRequest;d.open("GET",a,!0);d.onreadystatechange=b;d.send(null)}catch(e){}}else alert("your browser/svg viewer neither supports window.getURL nor window.XMLHttpRequest!")}
var _deg2rad=Math.PI/180,_rad2deg=180/Math.PI,_maxLat=Math.atan(sinh(Math.PI))*_rad2deg,_refEllipsoid={WGS84:{_EquatorialRadius:6378137,_eccentricitySquared:.00669438},Airy:{_EquatorialRadius:6377563,_eccentricitySquared:.00667054},"Australian National":{_EquatorialRadius:6378160,_eccentricitySquared:.006694542},"Bessel 1841":{_EquatorialRadius:6377397,_eccentricitySquared:.006674372},"Bessel 1841 (Nambia]":{_EquatorialRadius:6377484,_eccentricitySquared:.006674372},"Clarke 1866":{_EquatorialRadius:6378206,
_eccentricitySquared:.006768658},"Clarke 1880":{_EquatorialRadius:6378249,_eccentricitySquared:.006803511},Everest:{_EquatorialRadius:6377276,_eccentricitySquared:.006637847},"Fischer 1960 (Mercury]":{_EquatorialRadius:6378166,_eccentricitySquared:.006693422},"Fischer 1968":{_EquatorialRadius:6378150,_eccentricitySquared:.006693422},"GRS 1967":{_EquatorialRadius:6378160,_eccentricitySquared:.006694605},"GRS 1980":{_EquatorialRadius:6378137,_eccentricitySquared:.00669438},"Helmert 1906":{_EquatorialRadius:6378200,
_eccentricitySquared:.006693422},Hough:{_EquatorialRadius:6378270,_eccentricitySquared:.00672267},International:{_EquatorialRadius:6378388,_eccentricitySquared:.00672267},Krassovsky:{_EquatorialRadius:6378245,_eccentricitySquared:.006693422},"Modified Airy":{_EquatorialRadius:6377340,_eccentricitySquared:.00667054},"Modified Everest":{_EquatorialRadius:6377304,_eccentricitySquared:.006637847},"Modified Fischer 1960":{_EquatorialRadius:6378155,_eccentricitySquared:.006693422},"South American 1969":{_EquatorialRadius:6378160,
_eccentricitySquared:.006694542},"WGS 60":{_EquatorialRadius:6378165,_eccentricitySquared:.006693422},"WGS 66":{_EquatorialRadius:6378145,_eccentricitySquared:.006694542},"WGS-72":{_EquatorialRadius:6378135,_eccentricitySquared:.006694318},"WGS-84":{_EquatorialRadius:6378137,_eccentricitySquared:.00669438}};
function _LLtoUTM(a,c,b,d){_refEllipsoid[a]||(a="WGS84");var e=_refEllipsoid[a]._EquatorialRadius;a=_refEllipsoid[a]._eccentricitySquared;var f=b+180-360*Math.floor((b+180)/360)-180;b=c*_deg2rad;var g=f*_deg2rad,h=Math.floor((f+180)/6)+1;56<=c&&64>c&&3<=f&&12>f&&(h=32);72<=c&&84>c&&(0<=f&&9>f?h=31:9<=f&&21>f?h=33:21<=f&&33>f?h=35:33<=f&&42>f&&(h=37));d&&d.length&&(h=parseInt(d));var k=(6*(h-1)-180+3)*_deg2rad;_UTMLetterDesignator(c);d=a/(1-a);var f=e/Math.sqrt(1-a*Math.sin(b)*Math.sin(b)),h=Math.tan(b)*
Math.tan(b),l=d*Math.cos(b)*Math.cos(b),g=Math.cos(b)*(g-k);a=e*((1-a/4-3*a*a/64-5*a*a*a/256)*b-(3*a/8+3*a*a/32+45*a*a*a/1024)*Math.sin(2*b)+(15*a*a/256+45*a*a*a/1024)*Math.sin(4*b)-35*a*a*a/3072*Math.sin(6*b));e=.9996*f*(g+(1-h+l)*g*g*g/6+(5-18*h+h*h+72*l-58*d)*g*g*g*g*g/120)+5E5;b=.9996*(a+f*Math.tan(b)*(g*g/2+(5-h+9*l+4*l*l)*g*g*g*g/24+(61-58*h+h*h+600*l-330*d)*g*g*g*g*g*g/720));0>c&&(b+=1E7);return new point(e,b)}
function _UTMLetterDesignator(a){return 84>=a>=72?"X":72>a>=64?"W":64>a>=56?"V":56>a>=48?"U":48>a>=40?"T":40>a>=32?"S":32>a>=24?"R":24>a>=16?"Q":16>a>=8?"P":8>a>=0?"N":0>a>=-8?"M":-8>a>=-16?"L":-16>a>=-24?"K":-24>a>=-32?"J":-32>a>=-40?"H":-40>a>=-48?"G":-48>a>=-56?"F":-56>a>=-64?"E":-64>a>=-72?"D":-72>a>=-80?"C":"Z"}
function _UTMtoLL(a,c,b,d){_refEllipsoid[a]||(a="WGS84");if(!d)return null;var e=_refEllipsoid[a]._EquatorialRadius;a=_refEllipsoid[a]._eccentricitySquared;var f=(1-Math.sqrt(1-a))/(1+Math.sqrt(1-a));b-=5E5;var g=c;c=parseInt(d);"N"<=d.substr(d.length-1,1)||(g-=1E7);d=6*(c-1)-180+3;c=a/(1-a);var g=g/.9996/(e*(1-a/4-3*a*a/64-5*a*a*a/256)),f=g+(3*f/2-27*f*f*f/32)*Math.sin(2*g)+(21*f*f/16-55*f*f*f*f/32)*Math.sin(4*g)+151*f*f*f/96*Math.sin(6*g),g=e/Math.sqrt(1-a*Math.sin(f)*Math.sin(f)),h=Math.tan(f)*
Math.tan(f),k=c*Math.cos(f)*Math.cos(f),e=e*(1-a)/Math.pow(1-a*Math.sin(f)*Math.sin(f),1.5);a=b/(.9996*g);var l=b=0;b=f-g*Math.tan(f)/e*(a*a/2-(5+3*h+10*k-4*k*k-9*c)*a*a*a*a/24+(61+90*h+298*k+45*h*h-252*c-3*k*k)*a*a*a*a*a*a/720);b*=_rad2deg;l=(a-(1+2*h+k)*a*a*a/6+(5-2*k+28*h-3*k*k+8*c+24*h*h)*a*a*a*a*a/120)/Math.cos(f);l=d+l*_rad2deg;return new point(l,b)}function sinh(a){return(Math.exp(a)-Math.exp(-a))/2}
function _LLtoMercator(a,c){a>=_maxLat&&(a=_maxLat);a<-_maxLat&&(a=-_maxLat);var b=a*_deg2rad,b=.5*Math.log((1+Math.sin(b))/(1-Math.sin(b)))*_rad2deg;return new point(c,b)}function _MercatortoLL(a,c){var b=Math.atan(sinh(a*_deg2rad))*_rad2deg;return new point(c,b)}function _copysign(a,c){return 0>a&&0<c||0<a&&0>c?-a:a}var WGS_84_EQ_RAD=6378137,CENTRAL_MERIDIAN=0;
function _LLtoWinkelTripel(a,c){var b,d,e;-180>c-CENTRAL_MERIDIAN&&(c=-180+CENTRAL_MERIDIAN);180<c-CENTRAL_MERIDIAN&&(c=180+CENTRAL_MERIDIAN);c-=CENTRAL_MERIDIAN;a*=_deg2rad;c=.5*c*_deg2rad;d=Math.acos(Math.cos(a)*Math.cos(c));0===d?e=d=0:(b=Math.sin(a)/Math.sin(d),d*=WGS_84_EQ_RAD,e=_copysign(2*d*Math.sqrt(1-b*b),c),d*=b);b=2*WGS_84_EQ_RAD*c*Math.cos(50.467);return new point(.5*(e+b),.5*(d+WGS_84_EQ_RAD*a))};
