var mapSelection=null;Map.Selections=function(){};Map.Selections.prototype=new Map;"string"==typeof thisversion&&map.checkVersion(thisversion)?map.Selections=new Map.Selections:alert("Map.Themes incompatible !");
Map.Selections.prototype.newSelection=function(a,b,e,c){if(null==b)return displayMessage("empty selection",1E3),null;var f=null;null==e&&(e="type:circle");if(f=(f=e.split("style="))&&1<f.length?__getStyleObj(f[1]):__getStyleObj(e)){"activeLayer"==a&&(a=getActiveTheme(),null==a&&map.Themes.activeTheme&&(a=map.Themes.activeTheme.szThemes));if(null==a)return displayMessage("please activate a layer",1E3),null;mapSelection=new MapSelection(a,b,"SELECTION|"+f.type,c);f.buffersize&&(mapSelection.nBufferSize=
f.buffersize)}mapSelection.parent=map.Themes;map.Themes.addTheme(mapSelection);mapSelection.fRealize=!0;executeWithMessage("map.Themes.execute()","please wait ...");return mapSelection};
function MapSelection(a,b,e,c){this.nSelected=this.nCount=0;this.szThemes=a;this.szThemesA=a.split("|");this.szSelectShape=b;this.highLightList=new HighLight;this.szTitle=c?c:"["+b+"] - "+a;this.szTitle=map.Dictionary.getLocalText(this.szTitle);this.szOrigFlag=this.szFlag=e?e:"";this.nRefreshTimeout=0;this.szId="theme"+String(Math.random());this.szShapeType="polygon"}
MapSelection.prototype.initValues=function(){this.nSelectedArea=this.nSelected=this.nThemeItems=this.nTested=this.nCount=this.nNodes=0;this.activeTheme=map.Themes.getTheme("selectme")||map.Themes.getTheme();this.activeTheme.szFlag.match(/CHART/)&&!this.activeTheme.szFlag.match(/MULTIPLE/)&&(this.szThemes="generic");this.themeNodesA=[];if("generic"==this.szThemes){var a=this.activeTheme;this.themeRootNodesA=a.filterNodesA&&a.filterNodesA!=this.szSelectShape?myclone(a.filterNodesA):myclone(a.indexA);
this.nCount=this.nNodes=this.nThemeItems=this.themeRootNodesA.length}else{this.themeRootNodesA=[];for(a=0;a<this.szThemesA.length;a++){var b=map.Layer.getLayerObj(this.szThemesA[a]);if(b&&b.szSelection&&0!==b.szSelection.length){this.szThemeType=b.szType;this.nThemeItems+=b.nItems;var e=[];b.szFlag.match(/tiled/)?e=map.Tiles.getTileNodes(this.szThemesA[a]):e[0]=SVGDocument.getElementById(this.szThemesA[a]);if(b.nRenderer&1&&b.szRenderer&&b.szRenderer.length)for(b=0;b<e.length;b++)for(var c=e[b].childNodes,
f=0;f<c.length;f++)1==c.item(f).nodeType&&c.item(f).hasChildNodes()&&(this.themeRootNodesA[this.themeRootNodesA.length]=c.item(f));else for(b=0;b<e.length;b++)this.themeRootNodesA[this.themeRootNodesA.length]=e[b]}}if(0===this.themeRootNodesA.length)return!1;for(a=0;a<this.themeRootNodesA.length;a++)this.nNodes+=this.themeRootNodesA[a].childNodes.length;this.nCount=this.nNodes}if("queryresult"==this.szSelectShape)return!0;if("object"==typeof this.szSelectShape){this.queryResultA=this.szSelectShape;
if("generic"==this.szThemes)for(a=0;a<this.szSelectShape.length;a++)this.themeRootNodesA[a]=this.szSelectShape[a];else for(a=0;a<this.szSelectShape.length;a++)this.themeRootNodesA[a]=this.szSelectShape[a].node.parentNode;this.nNodes=this.themeRootNodesA.length=this.szSelectShape.length;this.szSelectShape="queryresult";this.szSelectQuery=this.szTitle;this.markGroup||(this.markGroup=map.Dom.newGroup(map.Layer.objectGroup,this.szId+":markgroup"));return!0}if("activeBuffer"==this.szSelectShape){e=map.Themes.activeBuffer;
if(null!=e){b=[];a=e.chartGroup;c=a.getElementsByTagName("path");f=a.getElementsByTagName("circle");for(a=0;a<c.length;a++)b[b.length]=c.item(a);for(a=0;a<f.length;a++)b[b.length]=f.item(a);this.selectCenterA=[];for(a=0;a<b.length;a++)this.selectCenterA[this.selectCenterA.length]=map.Scale.getMapOffset(b[a]);this.selectBufferSize=e.nBufferSize/map.Scale.mapUnitsPPX;this.selectScale=e.nScale;this.markGroup||(this.markGroup=map.Dom.newGroup(map.Layer.objectGroup,this.szId+":markgroup"));return!0}alert("error: no active theme/buffer to select with");
return!1}this.selectCenterA=[];b=SVGDocument.getElementById(this.szSelectShape);if(!b)return!1;b.fu=new Methods(b);if(this.szFlag.match(/shape/))a=b.fu.getPosition(),e=b.fu.getBox(),console.log(a),console.log(e),this.selectionCenter=new point(e.x+e.width/2,e.y+e.height/2),this.selectCenterA[this.selectCenterA.length]=this.selectionCenter,this.selectBufferSize=Math.max(e.width/2,e.height/2),this.selectBufferSize/=map.Scale.nZoomScale;else if(this.szFlag.match(/circle/)){a=b.fu.getPosition();a.x=Number(b.getAttributeNS(null,
"cx"));a.y=Number(b.getAttributeNS(null,"cy"));this.selectionCenter=new point(a.x,a.y);this.selectCenterA[this.selectCenterA.length]=map.Scale.getMapPosition(a.x,a.y);map.Scale.getMapPosition(a.x,a.y);this.selectBufferSize=b.getAttributeNS(null,"r");if(0===this.selectBufferSize)return!1;a=antiZoomAndPanList.getActualMatrix();this.selectBufferSize*=a[0]}else if(this.szFlag.match(/square/)){a=b.fu.getPosition();a.x=Number(b.getAttributeNS(null,"x"));a.y=Number(b.getAttributeNS(null,"y"));e=Number(b.getAttributeNS(null,
"width"));b=Number(b.getAttributeNS(null,"height"));this.selectionCenter=new point(a.x+e/2,a.y+b/2);this.selectCenterA[this.selectCenterA.length]=map.Scale.getMapPosition(a.x+e/2,a.y+b/2);map.Scale.getMapPosition(a.x+e/2,a.y+b/2);this.selectBufferSizeX=e/2;this.selectBufferSizeY=b/2;if(0===this.selectBufferSizeX||0===this.selectBufferSizeY)return!1;a=antiZoomAndPanList.getActualMatrix();this.selectBufferSizeX*=a[0];this.selectBufferSizeY*=a[0]}this.selectScale=map.Scale.nZoomScale;this.markGroup||
(this.markGroup=map.Dom.newGroup(map.Layer.objectGroup,this.szId+":markgroup"));return!0};function __inRange(a,b,e,c){if(a&&b&&e){var f=b.x-a.x;a=b.y-a.y;return c?Math.abs(f)<=e&&Math.abs(a)<=c:Math.sqrt(f*f+a*a)<=e}return!1}
MapSelection.prototype.realize=function(){this.fShowProgressBar=!0;this.initValues()?(this.nSkipCount=this.nDoneCount=0,activeSelection=this,this.mapSleep=new Map.Sleep("activeSelection.selectShapes",100,map.Dictionary.getLocalText("do selection")),this.mapSleep.fShowProgressBar=!0,this.mapSleep.nCount=this.nCount,this.mapSleep.szCancel="activeSelection.cancel()",this.selectShapes()):(this.remove(),displayMessage("Selection could not be done",3E3))};MapSelection.prototype.realizeContinue=function(a){this.selectShapes(a)};
MapSelection.prototype.realizeDone=function(){this.nRefreshTimeout&&setTimeout("map.Themes.refreshTheme('"+this.szId+"')",this.nRefreshTimeout)};MapSelection.prototype.redraw=function(){};MapSelection.prototype.removeValues=function(){};MapSelection.prototype.disable=function(){};MapSelection.prototype.cancel=function(){this.fCancel=!0};activeSelection=null;
MapSelection.prototype.nextThemeNode=function(a){if("generic"==this.szThemes||"queryresult"==this.szSelectShape)return this.themeRootNodesA[a];if(0===a)return this.nRootIndex=0,this.actNode=this.themeRootNodesA[this.nRootIndex].firstChild;if(!this.actNode)return null;this.actNode=this.actNode.nextSibling;if(!this.actNode){if(++this.nRootIndex>=this.themeRootNodesA.length)return null;this.actNode=this.themeRootNodesA[this.nRootIndex].firstChild}return this.actNode};
function myclone(a){if(a){var b=a instanceof Array?[]:{},e;for(e in a)"clone"!=e&&(b[e]=a[e]&&"object"==typeof a[e]?myclone(a[e]):a[e]);return b}return null}
MapSelection.prototype.selectShapes=function(a){if(!a||0===a)if(a=0,this.testA=[],this.itemA=[],this.chartPosA=[],this.exactCountA=[],this.exactSizeA=[],this.activeTheme||(this.activeTheme=map.Themes.activeTheme),this.activeTheme&&this.szThemesA[0]+" == "+this.activeTheme.szThemesA[0]){this.nPartsA=myclone(this.activeTheme.nPartsA);this.partsA=myclone(this.activeTheme.partsA);this.origColorScheme=myclone(this.activeTheme.origColorScheme);this.colorScheme=myclone(this.activeTheme.colorScheme);this.szFieldsA=
myclone(this.activeTheme.szFieldsA);this.szLabelA=myclone(this.activeTheme.szLabelA);this.szLegendLabelA=myclone(this.activeTheme.szLegendLabelA);this.szXaxisA=myclone(this.activeTheme.szXaxisA);this.szSymbolsA=myclone(this.activeTheme.szSymbolsA);this.szRanges=this.activeTheme.szRanges;this.szSizeField=this.activeTheme.szSizeField;this.nMeanA=myclone(this.activeTheme.nMeanA);this.nMedianA=myclone(this.activeTheme.nMedianA);this.nDeviationA=myclone(this.activeTheme.nDeviationA);this.nFilterA=myclone(this.activeTheme.nFilterA);
this.nOrigSumA=myclone(this.activeTheme.nOrigSumA);this.szUnit=this.activeTheme.szUnit;this.formatValue=this.activeTheme.formatValue;this.nMin100=this.activeTheme.nMin100;this.nMax100=this.activeTheme.nMax100;this.nClipFrames=this.activeTheme.nClipFrames;this.nActualFrame=this.activeTheme.nActualFrame;this.sortIndexDown=this.activeTheme.sortIndexDown;this.sortIndexUp=this.activeTheme.sortIndexUp;this.shuffleArray=this.activeTheme.shuffleArray;this.removeDefinition=this.activeTheme.removeDefinition;
this.szValuesTextStyle=this.activeTheme.szValuesTextStyle;this.nOrigValuesSumA=[];this.nValuesSumA=[];this.nValuesMinA=[];this.nValuesMaxA=[];this.nExactCount=this.nCount=this.nSum=this.nSum100=0;this.nMin=Number.MAX_VALUE;this.nMax=-Number.MAX_VALUE;this.nMinSize=Number.MAX_VALUE;this.nMaxSize=-Number.MAX_VALUE;for(var b=this.nSumSize=0;b<this.activeTheme.szFieldsA.length;b++)this.nOrigValuesSumA[b]=0,this.nValuesSumA[b]=0,this.nValuesMinA[b]=Number.MAX_VALUE,this.nValuesMaxA[b]=-Number.MAX_VALUE;
for(var e=0;e<this.partsA.length;e++)this.partsA[e].nCount=0,this.partsA[e].nSum=0,this.exactSizeA[e]=0}if(this.nNodes){var c,f=null,g=null,k=this.selectBufferSize*this.selectScale,h=null;this.selectBufferSizeX&&(k=this.selectBufferSizeX*this.selectScale,h=this.selectBufferSizeY*this.selectScale);for(e=a;e<this.nNodes;e++){this.mapSleep.nDoneCount=this.nDoneCount;if(this.mapSleep.checkSleep(e,10))return;if("generic"==this.szThemes){a=this.nextThemeNode(e);this.nDoneCount++;var d=!1;if("queryresult"==
this.szSelectShape)d=!0;else for(c=0;c<this.selectCenterA.length;c++)if(__inRange(this.activeTheme.getNodePosition(a),this.selectCenterA[c],k,h)){d=!0;break}}else{f=this.nextThemeNode(e);this.nDoneCount++;if(!f||1!=f.nodeType)continue;if(f.getAttributeNS(null,"id").match(/:paint/))continue;a=map.Tiles.getMasterId(f.getAttributeNS(null,"id"));this.testA&&!this.testA[a]&&(this.testA[a]=f,this.nTested++);d=!1;if("queryresult"==this.szSelectShape)for(this.selectionCenter||(this.selectionCenter=new point(0,
0)),c=0;c<this.queryResultA.length;c++){if(this.queryResultA[c].node.parentNode==f){d=!0;(c=f.getAttributeNS(szMapNs,"center"))&&2<c.length&&(g=c.split(","),g=new point(Number(g[0].split(":")[1]),Number(g[1].split(":")[1])));g||(g=map.Dom.getBox(f),g=new point(g.x,g.y));c=map.Scale.mapCanvasCenter;b=map.Scale.getMapOffset(f);g.x+=c.x;g.y+=c.y;this.selectionCenter.x+=g.x/this.queryResultA.length;this.selectionCenter.y+=g.y/this.queryResultA.length;break}}else if((c=f.getAttributeNS(szMapNs,"center"))&&
2<c.length&&(g=c.split(","),g=new point(Number(g[0].split(":")[1]),Number(g[1].split(":")[1]))),g||(g=map.Dom.getBox(f),g=new point(g.x,g.y)),g)for(b=map.Scale.getMapOffset(f),g.x+=b.x,g.y+=b.y,map.Scale.rotatePoint(g,-1),c=0;c<this.selectCenterA.length;c++)if(__inRange(g,this.selectCenterA[c],k,h)){d=!0;break}}if(d){if("generic"==this.szThemes)this.itemA[a]=null,this.nSelected++;else{"point"==this.szThemeType&&(this.markGroup?map.Dom.newShape("circle",this.markGroup,g.x,g.y,map.Scale.normalX(1)*
map.Scale.nZoomScale,"fill:yellow;stroke:none;"):f&&f.style.setProperty("opacity","0.0"));d=f.getAttributeNS(szMapNs,"area");if(this.itemA&&this.itemA[a])continue;this.itemA[a]=f;this.nSelected++;this.nSelectedArea+=Number(d)}if(this.activeTheme)for(d=[],this.activeTheme.itemA[a]?d.push(this.activeTheme.itemA[a]):this.activeTheme.posItemA[a]&&(d=this.activeTheme.posItemA[a]),a=0;a<d.length;a++)if(c=d[a],1!=c.nValuesA.length||!(isNaN(c.nValuesA[0])||0===c.nValuesA[0]&!this.activeTheme.szFlag.match(/ZEROISVALUE/))){this.nCount++;
for(b=0;b<c.nValuesA.length;b++)isNaN(c.nValuesA[b])||(this.nOrigValuesSumA[b]+=c.nOrigValuesA[b],this.nValuesSumA[b]+=c.nValuesA[b],this.nValuesMinA[b]=Math.min(this.nValuesMinA[b],c.nValuesA[b]),this.nValuesMaxA[b]=Math.max(this.nValuesMaxA[b],c.nValuesA[b]),this.nMin=Math.min(this.nMin,c.nValuesA[b]),this.nMax=Math.max(this.nMax,c.nValuesA[b]),this.nMinSize=Math.min(this.nMinSize,c.nSize||this.nMinSize),this.nMaxSize=Math.max(this.nMaxSize,c.nSize||this.nMaxSize),this.nSumSize+=c.nSize);c.nValue100&&
(this.nSum100+=c.nValue100);if(this.activeTheme.szFlag.match(/CATEGORICAL/))for(b=0;b<c.nValuesA.length;b++)for(var l=0;l<this.partsA.length;l++){if(c.nValuesA[b]==this.partsA[l].min){this.partsA[l].nCount++;this.partsA[l].nSum+=c.nValuesA[b];this.nSum+=c.nValuesA[b];this.nExactCount++;this.exactSizeA[l]+=c.nSize||1;break}}else if(this.activeTheme.szFlag.match(/SEQUENCE/)||this.activeTheme.szFlag.match(/CHART/))for(l=0;l<this.partsA.length;l++)this.partsA[l].nCount++,this.partsA[l].nSum+=c.nValuesA[l],
this.nSum+=c.nValuesA[l];else if(this.activeTheme.szFlag.match(/CLIP/)&&this.activeTheme.nClipFrames)this.nSum=this.nClipFrames==c.nValuesA.length?this.nSum+Number(c.nValuesA[this.nActualFrame]):this.nSum+Number(c.nValuesA[0]*(this.nClipFrames-this.nActualFrame)/this.nClipFrames+c.nValuesA[c.nValuesA.length-1]*this.nActualFrame/this.nClipFrames);else for(b=0;b<c.nValuesA.length;b++)for(l=0;l<this.partsA.length;l++)if(c.nValuesA[b]<this.partsA[l].max){this.partsA[l].nCount++;this.partsA[l].nSum+=c.nValuesA[b];
this.nSum+=c.nValuesA[b];break}}}if(this.fCancel){this.fShowProgressBar=!1;this.showInfo(!1);clearMessage();return}}}0===this.nThemeItems&&(this.nThemeItems=this.nTested);if("generic"!=this.szThemes&&"point"!=this.szThemeType)for(var m in this.itemA)if((e=map.Tiles.getTileNodes(m))&&e.length)for(var n in e)this.highLightList.addItem(e[n]),this.highLightList.lock();else this.highLightList.addItem(this.itemA[m]),this.highLightList.lock();this.isVisible=!0;this.realizeDone();this.fShowProgressBar=!1;
clearMessage();if(HTMLWindow.ixmaps.htmlgui_onSelection(this.szId))return null;this.showInfo(!0)};
MapSelection.prototype.showInfo=function(a){if(0===this.nCount)displayMessage("Selection: no values found !",1E3),this.remove();else if(0===this.nSelected)displayMessage("Selection is empty !",1E3),this.remove();else if(!this.widgetNode||this.fRedrawInfo){this.fRedrawInfo=!1;var b=this.szId+":display:widget",e=map.Dictionary.getLocalText("Selection");"undefined"==typeof a||a||(e+=" ("+map.Dictionary.getLocalText("incomplete")+"!)");this.selectionCenter||(this.selectionCenter=map.Scale.mapCanvasCenter);
this.widgetNode?(a=this.widgetNode,a.clear()):a=new InfoContainer(SVGDocument,SVGFixedGroup,b+":movable",this.selectionCenter,new point(-map.Scale.normalX(55),map.Scale.normalY(50)),"fixed|pointer",e);a.frameNode.style.setProperty("fill","#e8e8e8","");e=szTextGridStyle;szTextGridStyle="firstgray";this.widgetNode=a;a.fClipped=!1;var c=a.workspaceNode;a.setOnRemove("map.Themes.removeTheme(evt,'"+this.szId+"')");var f=this.szSelectShape,g=0;if("activeBuffer"==this.szSelectShape){var f=map.Themes.activeBuffer.szTitle,
k=[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected by"),map.Dictionary.getLocalText("selected items"),1==this.szThemesA.length?String(map.Layer.listA[this.szThemesA[0]].szLegendName):"(multiple)",String(f),String(this.nSelected)+" / "+String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"],h=Array(3);h[0]="font-weight:bold;fill:#ffffff;";h[1]="font-weight:bold;fill:#ffffff;";h[2]="font-weight:bold;fill:#ffffff;";g+=50}else"queryresult"==
this.szSelectShape?(f=this.szThemes,1<this.szThemesA.length?f="(multiple)":"generic"!=this.szThemes&&(f=String(map.Layer.listA[this.szThemesA[0]].szLegendName)),k=[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected by"),map.Dictionary.getLocalText("selected items"),f,this.szSelectQuery,String(this.nSelected)+" / "+String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"],h=Array(3),h[0]="font-weight:bold;fill:#ffffff;",h[1]="font-weight:bold;fill:#ffffff;",
h[2]="font-weight:bold;fill:#ffffff;",g+=50):(k="generic"==this.szThemes?[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected items"),"(generic)",String(this.nSelected)+" / "+String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"]:[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected items"),1==this.szThemesA.length?String(map.Layer.listA[this.szThemesA[0]].szLegendName):"(multiple)",String(this.nSelected)+" / "+
String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"],h=Array(2),h[0]="font-weight:bold;fill:#ffffff;",h[1]="font-weight:bold;fill:#ffffff;",g+=40);var d=map.Dom.newGroup(c,"");d.fu.setPosition(map.Scale.normalY(3),map.Scale.normalY(3));createTextGrid(SVGDocument,d,b+":textgrid",k,2,11,h,"fill:#bbbbbb;");f=[];if(this.activeTheme){k=d=null;g+=14;map.Dom.newText(c,map.Scale.normalX(3),map.Scale.normalY(g),"font-family:arial;font-weight:bold;font-size:"+map.Scale.normalY(11)+
"px;fill:#555555;pointer-events:none",map.Dictionary.getLocalText("Theme")+": "+this.activeTheme.szTitle);g+=8;d=map.Dom.newGroup(c,"");d.fu.setPosition(map.Scale.normalY(3),map.Scale.normalY(g));this.drawDonutText=this.activeTheme.drawDonutText;this.drawTextforOneQuadrant=this.activeTheme.drawTextforOneQuadrant;this.createTextLabel=this.activeTheme.createTextLabel;if(1==this.nValuesSumA.length){this.addItemValues=this.activeTheme.addItemValues;this.szFieldsA=this.activeTheme.szFieldsA;this.fField100=
this.activeTheme.fField100;var l=this.szFlag;this.szFlag=this.activeTheme.szFlag;this.itemA=[];k=[];for(h=0;h<this.nOrigValuesSumA.length;h++)k[h]=this.nOrigValuesSumA[h];this.addItemValues("selection",k,this.nSum100);this.szFlag=l;if(this.activeTheme.szFlag.match(/CATEGORICAL/))k=[map.Dictionary.getLocalText("selected items"),String(__formatValue(Number(this.nCount,2)))],h=Array(2),h[0]="font-weight:bold;fill:#7996D7;",h[1]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,
d,b+":textgrid",k,2,11,h),g+=d.fu.getBox().height/map.Scale.normalX(1)+5;else if(this.activeTheme.szAggregation&&this.activeTheme.szAggregation.match(/sum/)||this.activeTheme.szFlag.match(/SUM/)){if(k=[map.Dictionary.getLocalText("value of selection"),map.Dictionary.getLocalText("% of total value")," ",map.Dictionary.getLocalText("min"),map.Dictionary.getLocalText("max"),map.Dictionary.getLocalText("average"),String(__formatValue(Number(this.itemA.selection.nValuesA[0]),2))+" "+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/
Number(this.activeTheme.nOrigSumA[0])*100,2))+" %"," ",String(__formatValue(Number(this.nValuesMinA[0]),2))+" "+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+" "+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+" "+this.szUnit],h=Array(12),h[0]="font-weight:bold;fill:#7996D7;",h[6]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,d,b+":textgrid",k,2,11,h),g+=d.fu.getBox().height/map.Scale.normalX(1)+5,d=map.Dom.newGroup(c,""),
f.push(d),b=DonutCharts.newChart(SVGDocument,d,map.Scale.normalX(55),map.Scale.normalY(55),0,0),b.setRadInner(0),b.setRadOuter(map.Scale.normalX(55)),b.setCenter(map.Scale.normalX(80),map.Scale.normalY(100)),k=Number(this.nValuesSumA[0])/Number(this.activeTheme.nOrigSumA[0])*100,b.addPart(k,map.Scale.normalY(20),"#ddddee",0,this.formatValue(k,2)+"%","selection: "+this.formatValue(k,2)+"% of total value"),b.addPart(100-k,map.Scale.normalY(20),"#f8f8ff",0,this.formatValue(100-k,2)+"%",this.formatValue(100-
k,2)+"%"),b.realize(),map.Dom.newText(d,map.Scale.normalX(80),map.Scale.normalX(82),"font-size:"+map.Scale.normalX(10)/.66+"px;text-anchor:middle;baseline-shift:-60%;fill:darkgrey;stroke:none;pointer-events:none",this.formatValue(k,0)+" % of total"),this.activeTheme.szFlag.match(/BUBBLE/)||this.activeTheme.szFlag.match(/SQUARE/)||this.activeTheme.szFlag.match(/SYMBOL/))this.getOverviewChart=this.activeTheme.getOverviewChart,this.szOverviewChart=this.activeTheme.szOverviewChart,this.drawChart=this.activeTheme.drawChart,
this.getOverviewChart&&(b=map.Dom.newGroup(c,""),d=map.Dom.newGroup(b,""),f.push(b),b=this.szFlag,this.szFlag=this.activeTheme.szFlag,this.nOrigSumA=this.nOrigValuesSumA,this.nMaxA=this.nValuesMaxA,this.nMinA=this.nValuesMinA,this.szAggregation=this.activeTheme.szAggregation,this.getOverviewChart(d),this.szFlag=b,d.fu.scale(1.3,1.3),d.fu.setPosition(map.Scale.normalX(-35),map.Scale.normalY(35)))}else this.fField100?(k=[map.Dictionary.getLocalText("value of selection")," ",map.Dictionary.getLocalText("min value"),
map.Dictionary.getLocalText("max value"),map.Dictionary.getLocalText("mean value"),String(__formatValue(Number(this.itemA.selection.nValuesA[0]),2))+this.szUnit," ",String(__formatValue(Number(this.nValuesMinA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+this.szUnit],h=Array(10),h[0]="font-weight:bold;fill:#7996D7;",h[5]="font-weight:bold;fill:#000000;font-size:240px;"):this.activeTheme.szFlag.match(/DENSITY/)?
(k=[map.Dictionary.getLocalText("value of selection")," ",map.Dictionary.getLocalText("min value"),map.Dictionary.getLocalText("max value"),map.Dictionary.getLocalText("mean value"),String(__formatValue(Number(this.itemA.selection.nValuesA[0]),2))+this.szUnit," ",String(__formatValue(Number(this.nValuesMinA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+this.szUnit],h=Array(10),h[0]="font-weight:bold;fill:#7996D7;",
h[5]="font-weight:bold;fill:#000000;font-size:240px;"):(k=[map.Dictionary.getLocalText("mean value"),map.Dictionary.getLocalText(" "),map.Dictionary.getLocalText("min value"),map.Dictionary.getLocalText("max value"),String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+this.szUnit,map.Dictionary.getLocalText(" "),String(__formatValue(Number(this.nValuesMinA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+this.szUnit],h=Array(8),h[0]="font-weight:bold;fill:#7996D7;",
h[4]="font-weight:bold;fill:#000000;font-size:240px;"),createTextGrid(SVGDocument,d,b+":textgrid",k,2,11,h),g+=d.fu.getBox().height/map.Scale.normalX(1)+5;this.getOverviewChart=this.activeTheme.getOverviewChart;this.szOverviewChart=this.activeTheme.szOverviewChart;if(2<this.activeTheme.colorScheme.length||this.activeTheme.szFlag.match(/CATEGORICAL/)||!this.activeTheme.szFlag.match(/CHART/)&&!this.activeTheme.szFlag.match(/DOMINANT/))this.szOverviewChart=5<this.nOrigSumA.length?"BAR":"PIE";this.szOverviewChart&&
(d=map.Dom.newGroup(c,""),f.push(d),this.getOverviewChart(d),this.szOverviewChart.match(/PIE/)&&this.activeTheme.szAggregation.match(/sum/)&&(this.szOverviewChart+="|PERCENTOFVALUE",d=map.Dom.newGroup(c,""),f.push(d),this.getOverviewChart(d)));!this.activeTheme.szFlag.match(/CHART/)||this.activeTheme.szAggregation&&this.activeTheme.szAggregation.match(/sum/)||(this.getOverviewChart=this.activeTheme.getOverviewChart,this.szOverviewChart=null,this.drawChart=this.activeTheme.drawChart,this.getOverviewChart&&
(b=map.Dom.newGroup(c,""),d=map.Dom.newGroup(b,""),f.push(b),b=this.szFlag,this.szFlag=this.activeTheme.szFlag,this.nOrigSumA=this.nOrigValuesSumA,this.nMaxA=this.nValuesMaxA,this.nMinA=this.nValuesMinA,this.nOverrideMax=this.activeTheme.nMax,this.szAggregation=this.activeTheme.szAggregation,this.getOverviewChart(d),this.szFlag=b,this.activeTheme.szFlag.match(/BAR/)?(d.fu.scale(2.5,2.5),d.fu.setPosition(map.Scale.normalX(55),map.Scale.normalY(65))):(d.fu.scale(1.3,1.3),d.fu.setPosition(map.Scale.normalX(-35),
map.Scale.normalY(35))),b=this.szFlag,this.szFlag=this.activeTheme.szFlag,this.szOverviewChart+="|PERCENTOFVALUE",d=map.Dom.newGroup(c,""),f.push(d),this.getOverviewChart(d),this.szFlag=b))}else{if(this.activeTheme.szAggregation.match(/sum/)||this.activeTheme.szFlag.match(/SUM/))l=this.nSum100?this.nSum100:this.activeTheme.szFlag.match(/CATEGORICAL/)?this.nExactCount:this.nSum,k=this.activeTheme.nSum100?this.activeTheme.nSum100:this.activeTheme.szFlag.match(/CATEGORICAL/)?this.activeTheme.nExactCount:
this.activeTheme.nSum,k=[map.Dictionary.getLocalText("total of selection"),String(__formatValue(l,2))+" ("+String(__formatValue(Number(l)/Number(k)*100,2))+" %)"],h=Array(2),h[0]="font-weight:bold;fill:#7996D7;",h[1]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,d,b+":textgrid",k,2,11,h),g+=d.fu.getBox().height/map.Scale.normalX(1)+5;this.nSum100&&(l=this.nSum100,this.activeTheme.szFlag.match(/DOMINANT/)||this.activeTheme.szAggregation.match(/sum/)||(l/=this.nSelected),
k=this.activeTheme.nSum100,k=[map.Dictionary.getLocalText("total of selection"),String(__formatValue(l,2))+" ("+String(__formatValue(Number(l)/Number(k)*100,2))+" %)"],h=Array(2),h[0]="font-weight:bold;fill:#7996D7;",h[1]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,d,b+":textgrid",k,2,11,h),g+=d.fu.getBox().height/map.Scale.normalX(1)+5);this.drawChart=this.activeTheme.drawChart;this.getOverviewChart=this.activeTheme.getOverviewChart;this.szOverviewChart=this.activeTheme.szOverviewChart;
if(this.activeTheme.szFlag.match(/CATEGORICAL/)||!this.activeTheme.szFlag.match(/CHART/)&&!this.activeTheme.szFlag.match(/DOMINANT/))this.szOverviewChart="PIE";this.nOrigSumA=this.nOrigValuesSumA;this.nMaxA=this.nValuesMaxA;this.nMinA=this.nValuesMinA;l=this.szFlag;this.szFlag=this.activeTheme.szFlag;this.szAggregation=this.activeTheme.szAggregation;this.szOverviewChart?(d=map.Dom.newGroup(c,""),f.push(d),this.getOverviewChart(d),this.szOverviewChart.match(/PIE/)&&this.activeTheme.szAggregation.match(/sum/)&&
(this.szOverviewChart+="|PERCENTOFVALUE",d=map.Dom.newGroup(c,""),f.push(d),this.getOverviewChart(d))):(d=map.Dom.newGroup(c,""),this.nMin=this.activeTheme.nMin,this.nMax=this.activeTheme.nMax,c=1.8,this.szFlag.match(/DOMINANT/)&&(c=1.8),this.drawColorSchemeLegend=this.activeTheme.drawColorSchemeLegend,this.nOrigSumA=this.activeTheme.nOrigSumA,this.nSum=this.activeTheme.nSum,this.szField100=this.activeTheme.szField100,this.drawColorSchemeLegend(d,"test").fu.scale(.9/c,.9/c),k=map.Dom.getBox(d),0<
k.width&&0<k.height&&(d.fu.scale(c,c),d.fu.setPosition(map.Scale.normalX(10)-k.x*c,map.Scale.normalY(g)+map.Scale.normalY(5)-k.y*c),map.Dom.newText(d,k.x,k.y+k.height+map.Scale.normalX(6),"font-family:Arial;font-style:italic;font-size:"+map.Scale.normalY(6)+"px;fill:#888888;pointer-events:none",this.activeTheme.fField100||this.activeTheme.szAggregation.match(/sum/)?map.Dictionary.getLocalText("* summary over selected area"):map.Dictionary.getLocalText("* arithmetic mean over selected area"))))}this.szFlag=
l}__formatValue(100/this.nThemeItems*this.nSelected,2);__chartArrayReformat(f,map.Scale.normalX(g),2);a.reformat();szTextGridStyle=e}};
function __chartArrayReformat(a,b,e){for(var c=0,f=0,f=1E3,g=0,k=0,h=0,d=0;d<a.length;d++){var l=a[d];l.fu.scale(.8,.8);var m=l.fu.getBox(),f=Math.min(f,m.x),g=Math.min(g,m.y),k=Math.max(k,m.width)}f=b-g+40;for(d=0;d<a.length;d++)l=a[d],m=l.fu.getBox(),0===d?c=map.Scale.normalX(2)-0:e&&0===d%e&&(f+=map.Scale.normalX(20)+h,c=map.Scale.normalX(2)-m.x,h=0),h=Math.max(h,m.height),l.fu.setPosition(c,f),c+=k-map.Scale.normalX(10)}MapSelection.prototype.markClass=function(a){};
MapSelection.prototype.unmarkClass=function(a){};MapSelection.prototype.remove=function(a){this.parent.removeTheme(a,this.szId)};MapSelection.prototype.removeElements=function(a){this.markGroup&&(this.markGroup.style.setProperty("display","none",""),setTimeout("map.Dom.removeElementById('"+this.markGroup.getAttributeNS(null,"id")+"')",1E4));try{this.mapTool.remove()}catch(b){}this.highLightList.unlock();this.highLightList.removeAll()};MapSelection.prototype.getItemNodes=function(a){return[]};
MapSelection.prototype.getNodeArea=function(a){return this.nSelectedArea?this.nSelectedArea/1E6:1};
