var mapSelection=null;Map.Selections=function(){};Map.Selections.prototype=new Map;"string"==typeof thisversion&&map.checkVersion(thisversion)?map.Selections=new Map.Selections:alert("Map.Themes incompatible !");
Map.Selections.prototype.newSelection=function(a,b,g,d){if(null==b)return displayMessage("empty selection",1E3),null;var e=null;null==g&&(g="type:circle");if(e=(e=g.split("style="))&&1<e.length?__getStyleObj(e[1]):__getStyleObj(g)){"activeLayer"==a&&(a=getActiveTheme(),null==a&&map.Themes.activeTheme&&(a=map.Themes.activeTheme.szThemes));if(null==a)return displayMessage("nothing to select!",1E3),null;mapSelection=new MapSelection(a,b,"SELECTION|"+e.type,d);e.buffersize&&(mapSelection.nBufferSize=
e.buffersize)}mapSelection.parent=map.Themes;map.Themes.addTheme(mapSelection);mapSelection.fRealize=!0;executeWithMessage("map.Themes.execute()","please wait ...");return mapSelection};
function MapSelection(a,b,g,d){this.nSelected=this.nCount=0;this.szThemes=a;this.szThemesA=a.split("|");this.szSelectShape=b;this.highLightList=new HighLight;this.szTitle=d?d:"["+b+"] - "+a;this.szTitle=map.Dictionary.getLocalText(this.szTitle);this.szOrigFlag=this.szFlag=g?g:"";this.nRefreshTimeout=0;this.szId="theme"+String(Math.random());this.szShapeType="polygon"}
MapSelection.prototype.initValues=function(){this.nSelectedArea=this.nSelected=this.nThemeItems=this.nTested=this.nCount=this.nNodes=0;this.activeTheme=map.Themes.getTheme(this.szThemes)||map.Themes.getTheme();this.activeTheme.szThemes!=this.szThemes&&this.activeTheme.szId!=this.szThemes||!this.activeTheme.szFlag.match(/CHART/)||this.activeTheme.szFlag.match(/MULTIPLE/)||(this.szThemes="generic");this.themeNodesA=[];if("generic"==this.szThemes){var a=this.activeTheme;this.themeRootNodesA=a.filterNodesA&&
a.filterNodesA!=this.szSelectShape?myclone(a.filterNodesA):myclone(a.indexA);this.nCount=this.nNodes=this.nThemeItems=this.themeRootNodesA.length}else{this.themeRootNodesA=[];for(a=0;a<this.szThemesA.length;a++){var b=map.Layer.getLayerObj(this.szThemesA[a]);if(b&&b.szSelection&&0!==b.szSelection.length){this.szThemeType=b.szType;this.nThemeItems+=b.nItems;var g=[];b.szFlag.match(/tiled/)?g=map.Tiles.getTileNodes(this.szThemesA[a]):g[0]=SVGDocument.getElementById(b.szName);if(b.nRenderer&1&&b.szRenderer&&
b.szRenderer.length)for(b=0;b<g.length;b++)for(var d=g[b].childNodes,e=0;e<d.length;e++)1==d.item(e).nodeType&&d.item(e).hasChildNodes()&&(this.themeRootNodesA[this.themeRootNodesA.length]=d.item(e));else for(b=0;b<g.length;b++)this.themeRootNodesA[this.themeRootNodesA.length]=g[b]}}if(0===this.themeRootNodesA.length)return!1;for(a=0;a<this.themeRootNodesA.length;a++)this.nNodes+=this.themeRootNodesA[a].childNodes.length;this.nCount=this.nNodes}if("queryresult"==this.szSelectShape)return!0;if("object"==
typeof this.szSelectShape){this.queryResultA=this.szSelectShape;if("generic"==this.szThemes)for(a=0;a<this.szSelectShape.length;a++)this.themeRootNodesA[a]=this.szSelectShape[a];else for(a=0;a<this.szSelectShape.length;a++)this.themeRootNodesA[a]=this.szSelectShape[a].node.parentNode;this.nNodes=this.themeRootNodesA.length=this.szSelectShape.length;this.szSelectShape="queryresult";this.szSelectQuery=this.szTitle;this.markGroup||(this.markGroup=map.Dom.newGroup(map.Layer.objectGroup,this.szId+":markgroup"));
return!0}if("activeBuffer"==this.szSelectShape){g=map.Themes.activeBuffer;if(null!=g){b=[];a=g.chartGroup;d=a.getElementsByTagName("path");e=a.getElementsByTagName("circle");for(a=0;a<d.length;a++)b[b.length]=d.item(a);for(a=0;a<e.length;a++)b[b.length]=e.item(a);this.selectCenterA=[];for(a=0;a<b.length;a++)this.selectCenterA[this.selectCenterA.length]=map.Scale.getMapOffset(b[a]);this.selectBufferSize=g.nBufferSize/map.Scale.mapUnitsPPX;this.selectScale=g.nScale;this.markGroup||(this.markGroup=map.Dom.newGroup(map.Layer.objectGroup,
this.szId+":markgroup"));return!0}alert("error: no active theme/buffer to select with");return!1}if("mapbounds"==this.szSelectShape)a=map.Zoom.getBox(),this.selectCenterA=[],this.selectionCenter=new point(a.x+a.width/2,a.y+a.height/2),this.selectCenterA.push(this.selectionCenter),this.selectBufferSizeX=a.width/2,this.selectBufferSizeY=a.height/2,this.selectScale=1;else{this.selectCenterA=[];b=SVGDocument.getElementById(this.szSelectShape);if(!b)return!1;b.fu=new Methods(b);if(this.szFlag.match(/shape/))a=
b.fu.getPosition(),a=b.fu.getBox(),this.selectionCenter=new point(a.x+a.width/2,a.y+a.height/2),this.selectCenterA[this.selectCenterA.length]=this.selectionCenter,this.selectBufferSize=Math.max(a.width/2,a.height/2),this.selectBufferSize/=map.Scale.nZoomScale;else if(this.szFlag.match(/circle/)){a=b.fu.getPosition();a.x=Number(b.getAttributeNS(null,"cx"));a.y=Number(b.getAttributeNS(null,"cy"));this.selectionCenter=new point(a.x,a.y);this.selectCenterA[this.selectCenterA.length]=map.Scale.getMapPosition(a.x,
a.y);map.Scale.getMapPosition(a.x,a.y);this.selectBufferSize=b.getAttributeNS(null,"r");if(0===this.selectBufferSize)return!1;a=antiZoomAndPanList.getActualMatrix();this.selectBufferSize*=a[0]}else if(this.szFlag.match(/square/)){a=b.fu.getPosition();a.x=Number(b.getAttributeNS(null,"x"));a.y=Number(b.getAttributeNS(null,"y"));g=Number(b.getAttributeNS(null,"width"));b=Number(b.getAttributeNS(null,"height"));this.selectionCenter=new point(a.x+g/2,a.y+b/2);this.selectCenterA[this.selectCenterA.length]=
map.Scale.getMapPosition(a.x+g/2,a.y+b/2);map.Scale.getMapPosition(a.x+g/2,a.y+b/2);this.selectBufferSizeX=g/2;this.selectBufferSizeY=b/2;if(0===this.selectBufferSizeX||0===this.selectBufferSizeY)return!1;a=antiZoomAndPanList.getActualMatrix();this.selectBufferSizeX*=a[0];this.selectBufferSizeY*=a[0]}this.selectScale=map.Scale.nZoomScale;this.markGroup||(this.markGroup=map.Dom.newGroup(map.Layer.objectGroup,this.szId+":markgroup"))}return!0};
function __inRange(a,b,g,d){if(a&&b&&g){var e=b.x-a.x;a=b.y-a.y;return d?Math.abs(e)<=g&&Math.abs(a)<=d:Math.sqrt(e*e+a*a)<=g}return!1}function __isPointInPoly(a,b){for(var g=a.x,d=a.y,e=!1,l=0,h=b.length-1;l<b.length;h=l++){var k=b[l].x,c=b[l].y,f=b[h].x,h=b[h].y;c>d!=h>d&&g<(f-k)*(d-c)/(h-c)+k&&(e=!e)}return e}
MapSelection.prototype.realize=function(){this.fShowProgressBar=!0;this.initValues()?(this.nSkipCount=this.nDoneCount=0,activeSelection=this,this.mapSleep=new Map.Sleep("activeSelection.selectShapes",100,map.Dictionary.getLocalText("do selection")),this.mapSleep.fShowProgressBar=!0,this.mapSleep.nCount=this.nCount,this.mapSleep.szCancel="activeSelection.cancel()",this.selectShapes()):(this.remove(),displayMessage("Selection could not be done",3E3))};MapSelection.prototype.realizeContinue=function(a){this.selectShapes(a)};
MapSelection.prototype.realizeDone=function(){this.nRefreshTimeout&&setTimeout("map.Themes.refreshTheme('"+this.szId+"')",this.nRefreshTimeout)};MapSelection.prototype.redraw=function(){};MapSelection.prototype.removeValues=function(){};MapSelection.prototype.disable=function(){};MapSelection.prototype.cancel=function(){this.fCancel=!0};activeSelection=null;
MapSelection.prototype.nextThemeNode=function(a){if("generic"==this.szThemes||"queryresult"==this.szSelectShape)return this.themeRootNodesA[a];if(0===a)return this.nRootIndex=0,this.actNode=this.themeRootNodesA[this.nRootIndex].firstChild;if(!this.actNode)return null;this.actNode=this.actNode.nextSibling;if(!this.actNode){if(++this.nRootIndex>=this.themeRootNodesA.length)return null;this.actNode=this.themeRootNodesA[this.nRootIndex].firstChild}return this.actNode};
function myclone(a){if(a){var b=a instanceof Array?[]:{},g;for(g in a)"clone"!=g&&(b[g]=a[g]&&"object"==typeof a[g]?myclone(a[g]):a[g]);return b}return null}
MapSelection.prototype.selectShapes=function(a){if(!a||0===a)if(a=0,this.testA=[],this.itemA=[],this.chartPosA=[],this.exactCountA=[],this.exactSizeA=[],this.activeTheme||(this.activeTheme=map.Themes.activeTheme),this.activeTheme&&this.szThemesA[0]+" == "+this.activeTheme.szThemesA[0]){this.nPartsA=myclone(this.activeTheme.nPartsA);this.partsA=myclone(this.activeTheme.partsA);this.origColorScheme=myclone(this.activeTheme.origColorScheme);this.colorScheme=myclone(this.activeTheme.colorScheme);this.szFieldsA=
myclone(this.activeTheme.szFieldsA);this.szLabelA=myclone(this.activeTheme.szLabelA);this.szLegendLabelA=myclone(this.activeTheme.szLegendLabelA);this.szXaxisA=myclone(this.activeTheme.szXaxisA);this.szSymbolsA=myclone(this.activeTheme.szSymbolsA);this.szRanges=this.activeTheme.szRanges;this.szSizeField=this.activeTheme.szSizeField;this.nMeanA=myclone(this.activeTheme.nMeanA);this.nMedianA=myclone(this.activeTheme.nMedianA);this.nDeviationA=myclone(this.activeTheme.nDeviationA);this.nFilterA=myclone(this.activeTheme.nFilterA);
this.nOrigSumA=myclone(this.activeTheme.nOrigSumA);this.szUnit=this.activeTheme.szUnit;this.formatValue=this.activeTheme.formatValue;this.nMin100=this.activeTheme.nMin100;this.nMax100=this.activeTheme.nMax100;this.nClipFrames=this.activeTheme.nClipFrames;this.nActualFrame=this.activeTheme.nActualFrame;this.sortIndexDown=this.activeTheme.sortIndexDown;this.sortIndexUp=this.activeTheme.sortIndexUp;this.shuffleArray=this.activeTheme.shuffleArray;this.removeDefinition=this.activeTheme.removeDefinition;
this.szValuesTextStyle=this.activeTheme.szValuesTextStyle;this.nOrigValuesSumA=[];this.nValuesSumA=[];this.nValuesMinA=[];this.nValuesMaxA=[];this.nExactCount=this.nCount=this.nSum=this.nSum100=0;this.nMin=Number.MAX_VALUE;this.nMax=-Number.MAX_VALUE;this.nMinSize=Number.MAX_VALUE;this.nMaxSize=-Number.MAX_VALUE;for(var b=this.nSumSize=0;b<this.activeTheme.szFieldsA.length;b++)this.nOrigValuesSumA[b]=0,this.nValuesSumA[b]=0,this.nValuesMinA[b]=Number.MAX_VALUE,this.nValuesMaxA[b]=-Number.MAX_VALUE;
for(var g=0;g<this.partsA.length;g++)this.partsA[g].nCount=0,this.partsA[g].nSum=0,this.exactSizeA[g]=0}if(this.nNodes){var d,e=null,l=null,h=this.selectBufferSize*this.selectScale,k=null;this.selectBufferSizeX&&(h=this.selectBufferSizeX*this.selectScale,k=this.selectBufferSizeY*this.selectScale);for(g=a;g<this.nNodes;g++){this.mapSleep.nDoneCount=this.nDoneCount;if(this.mapSleep.checkSleep(g,10))return;if("generic"==this.szThemes)if(b=this.nextThemeNode(g),this.nDoneCount++,a=!1,"queryresult"==this.szSelectShape)a=
!0;else if(this.szFlag.match(/shape/))a=SVGDocument.getElementById(this.szSelectShape),d=map.Api.getShapePoints(a.firstChild),a=__isPointInPoly(this.activeTheme.getNodePosition(b),d);else for(d=0;d<this.selectCenterA.length;d++){if(__inRange(this.activeTheme.getNodePosition(b),this.selectCenterA[d],h,k)){a=!0;break}}else{e=this.nextThemeNode(g);this.nDoneCount++;if(!e||1!=e.nodeType)continue;if(e.getAttributeNS(null,"id").match(/:paint/))continue;b=map.Tiles.getMasterId(e.getAttributeNS(null,"id"));
this.testA&&!this.testA[b]&&(this.testA[b]=e,this.nTested++);a=!1;if("queryresult"==this.szSelectShape)for(this.selectionCenter||(this.selectionCenter=new point(0,0)),d=0;d<this.queryResultA.length;d++){if(this.queryResultA[d].node.parentNode==e){a=!0;(d=e.getAttributeNS(szMapNs,"center"))&&2<d.length&&(l=d.split(","),l=new point(Number(l[0].split(":")[1]),Number(l[1].split(":")[1])));if(!l)var c=map.Dom.getBox(e),l=new point(c.x,c.y);c=map.Scale.mapCanvasCenter;d=map.Scale.getMapOffset(e);l.x+=c.x;
l.y+=c.y;this.selectionCenter.x+=l.x/this.queryResultA.length;this.selectionCenter.y+=l.y/this.queryResultA.length;break}}else if(c=map.Dom.getBox(e),d=map.Scale.getMapOffset(e),c.x+=d.x,c.y+=d.y,c.x>this.selectCenterA[0].x+h||c.y>this.selectCenterA[0].y+k||c.x+c.width<this.selectCenterA[0].x-h||c.y+c.height<this.selectCenterA[0].y-k)a=!1;else if(c.x<this.selectCenterA[0].x-h&&c.y<this.selectCenterA[0].y-k&&c.x+c.width>this.selectCenterA[0].x+h&&c.y+c.height>this.selectCenterA[0].y+k){d=e.getElementsByTagName("path");
d=map.Api.getShapePoints(d.item(0));c=map.Scale.getMapOffset(e);for(f in d)d[f].x+=c.x,d[f].y+=c.y;a=__isPointInPoly(new point(this.selectCenterA[0].x,this.selectCenterA[0].y),d)}else for(f in a=!1,d=e.getElementsByTagName("path"),d=map.Api.getShapePoints(d.item(0)),c=map.Scale.getMapOffset(e),d)if(d[f].x+c.x<=this.selectCenterA[0].x+h&&d[f].y+c.y<=this.selectCenterA[0].y+k&&d[f].x+c.x>=this.selectCenterA[0].x-h&&d[f].y+c.y>=this.selectCenterA[0].y-k){a=!0;break}}if(a){if("generic"==this.szThemes)this.itemA[b]=
this.activeTheme.itemA[b],this.nSelected++;else{"point"==this.szThemeType&&(this.markGroup?map.Dom.newShape("circle",this.markGroup,l.x,l.y,map.Scale.normalX(1)*map.Scale.nZoomScale,"fill:yellow;stroke:none;"):e&&e.style.setProperty("opacity","0.0"));a=e.getAttributeNS(szMapNs,"area");if(this.itemA&&this.itemA[b])continue;this.itemA[b]=e;this.nSelected++;this.nSelectedArea+=Number(a)}if(this.activeTheme)for(a=[],this.activeTheme.itemA[b]?a.push(this.activeTheme.itemA[b]):this.activeTheme.posItemA[b]&&
(a=this.activeTheme.posItemA[b]),d=0;d<a.length;d++)if(c=a[d],1!=c.nValuesA.length||!(isNaN(c.nValuesA[0])||0===c.nValuesA[0]&!this.activeTheme.szFlag.match(/ZEROISVALUE/))){this.nCount++;for(b=0;b<c.nValuesA.length;b++)isNaN(c.nValuesA[b])||(this.nOrigValuesSumA[b]+=c.nOrigValuesA[b],this.nValuesSumA[b]+=c.nValuesA[b],this.nValuesMinA[b]=Math.min(this.nValuesMinA[b],c.nValuesA[b]),this.nValuesMaxA[b]=Math.max(this.nValuesMaxA[b],c.nValuesA[b]),this.nMin=Math.min(this.nMin,c.nValuesA[b]),this.nMax=
Math.max(this.nMax,c.nValuesA[b]),this.nMinSize=Math.min(this.nMinSize,c.nSize||this.nMinSize),this.nMaxSize=Math.max(this.nMaxSize,c.nSize||this.nMaxSize),this.nSumSize+=c.nSize);c.nValue100&&(this.nSum100+=c.nValue100);if(this.activeTheme.szFlag.match(/AGGREGATE/)&&this.activeTheme.szFlag.match(/CATEGORICAL/)){console.log(c.nValuesA);for(var f=0;f<this.partsA.length;f++)this.partsA[f].nCount+=c.nValuesA[f]?1:0,this.partsA[f].nSum+=c.nValuesA[f]||0,this.nSum+=c.nValuesA[f],this.nExactCount++,this.exactSizeA[f]+=
c.nSize||1}else if(this.activeTheme.szFlag.match(/CATEGORICAL/))for(b=0;b<c.nValuesA.length;b++)for(f=0;f<this.partsA.length;f++){if(c.nValuesA[b]==this.partsA[f].min){this.partsA[f].nCount++;this.partsA[f].nSum+=c.nValuesA[b];this.nSum+=c.nValuesA[b];this.nExactCount++;this.exactSizeA[f]+=c.nSize||1;break}}else if(this.activeTheme.szFlag.match(/SEQUENCE/)||this.activeTheme.szFlag.match(/CHART/))for(f=0;f<this.partsA.length;f++)this.partsA[f].nCount++,this.partsA[f].nSum+=c.nValuesA[f],this.nSum+=
c.nValuesA[f];else if(this.activeTheme.szFlag.match(/CLIP/)&&this.activeTheme.nClipFrames)this.nSum=this.nClipFrames==c.nValuesA.length?this.nSum+Number(c.nValuesA[this.nActualFrame]):this.nSum+Number(c.nValuesA[0]*(this.nClipFrames-this.nActualFrame)/this.nClipFrames+c.nValuesA[c.nValuesA.length-1]*this.nActualFrame/this.nClipFrames);else for(b=0;b<c.nValuesA.length;b++)for(f=0;f<this.partsA.length;f++)if(c.nValuesA[b]<this.partsA[f].max){this.partsA[f].nCount++;this.partsA[f].nSum+=c.nValuesA[b];
this.nSum+=c.nValuesA[b];break}}}if(this.fCancel){this.fShowProgressBar=!1;this.showInfo(!1);clearMessage();return}}}0===this.nThemeItems&&(this.nThemeItems=this.nTested);if("generic"!=this.szThemes&&"point"!=this.szThemeType)for(var m in this.itemA)if((g=map.Tiles.getTileNodes(m))&&g.length)for(var n in g)this.highLightList.addItem(g[n]),this.highLightList.lock();else this.highLightList.addItem(this.itemA[m]),this.highLightList.lock();this.isVisible=!0;this.realizeDone();this.fShowProgressBar=!1;
clearMessage();if(HTMLWindow.ixmaps.htmlgui_onSelection(this.szId))return null;this.showInfo(!0)};
MapSelection.prototype.showInfo=function(a){if(0===this.nCount)displayMessage("Selection: no values found !",1E3),this.remove();else if(0===this.nSelected)displayMessage("Selection is empty !",1E3),this.remove();else if(!this.widgetNode||this.fRedrawInfo){this.fRedrawInfo=!1;var b=this.szId+":display:widget",g=map.Dictionary.getLocalText("Selection");"undefined"==typeof a||a||(g+=" ("+map.Dictionary.getLocalText("incomplete")+"!)");this.selectionCenter||(this.selectionCenter=map.Scale.mapCanvasCenter);
this.widgetNode?(a=this.widgetNode,a.clear()):a=new InfoContainer(SVGDocument,SVGFixedGroup,b+":movable",this.selectionCenter,new point(-map.Scale.normalX(55),map.Scale.normalY(50)),"fixed|pointer",g);a.frameNode.style.setProperty("fill","#e8e8e8","");g=szTextGridStyle;szTextGridStyle="firstgray";this.widgetNode=a;a.fClipped=!1;var d=a.workspaceNode;a.setOnRemove("map.Themes.removeTheme(evt,'"+this.szId+"')");var e=this.szSelectShape,l=0;if("activeBuffer"==this.szSelectShape){var e=map.Themes.activeBuffer.szTitle,
h=[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected by"),map.Dictionary.getLocalText("selected items"),1==this.szThemesA.length?String(map.Layer.listA[this.szThemesA[0]].szLegendName):"(multiple)",String(e),String(this.nSelected)+" / "+String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"],k=Array(3);k[0]="font-weight:bold;fill:#ffffff;";k[1]="font-weight:bold;fill:#ffffff;";k[2]="font-weight:bold;fill:#ffffff;";l+=50}else"queryresult"==
this.szSelectShape?(e=this.szThemes,1<this.szThemesA.length?e="(multiple)":"generic"!=this.szThemes&&(e=String(map.Layer.listA[this.szThemesA[0]].szLegendName)),h=[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected by"),map.Dictionary.getLocalText("selected items"),e,this.szSelectQuery,String(this.nSelected)+" / "+String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"],k=Array(3),k[0]="font-weight:bold;fill:#ffffff;",k[1]="font-weight:bold;fill:#ffffff;",
k[2]="font-weight:bold;fill:#ffffff;",l+=50):(h="generic"==this.szThemes?[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected items"),"(generic)",String(this.nSelected)+" / "+String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"]:[map.Dictionary.getLocalText("layer"),map.Dictionary.getLocalText("selected items"),1==this.szThemesA.length?String(map.Layer.listA[this.szThemesA[0]].szLegendName):"(multiple)",String(this.nSelected)+" / "+
String(this.nThemeItems)+"  ("+String(__formatValue(100/this.nThemeItems*this.nSelected,2))+"%)"],k=Array(2),k[0]="font-weight:bold;fill:#ffffff;",k[1]="font-weight:bold;fill:#ffffff;",l+=40);var c=map.Dom.newGroup(d,"");c.fu.setPosition(map.Scale.normalY(3),map.Scale.normalY(3));createTextGrid(SVGDocument,c,b+":textgrid",h,2,11,k,"fill:#bbbbbb;");e=[];if(this.activeTheme){h=c=null;l+=14;map.Dom.newText(d,map.Scale.normalX(3),map.Scale.normalY(l),"font-family:arial;font-weight:bold;font-size:"+map.Scale.normalY(11)+
"px;fill:#555555;pointer-events:none",map.Dictionary.getLocalText("Theme")+": "+this.activeTheme.szTitle);l+=8;c=map.Dom.newGroup(d,"");c.fu.setPosition(map.Scale.normalY(3),map.Scale.normalY(l));this.drawDonutText=this.activeTheme.drawDonutText;this.drawTextforOneQuadrant=this.activeTheme.drawTextforOneQuadrant;this.createTextLabel=this.activeTheme.createTextLabel;if(1==this.nValuesSumA.length){this.addItemValues=this.activeTheme.addItemValues;this.szFieldsA=this.activeTheme.szFieldsA;this.fField100=
this.activeTheme.fField100;var f=this.szFlag;this.szFlag=this.activeTheme.szFlag;this.itemA=[];h=[];for(k=0;k<this.nOrigValuesSumA.length;k++)h[k]=this.nOrigValuesSumA[k];this.addItemValues("selection",h,this.nSum100);this.szFlag=f;if(this.activeTheme.szFlag.match(/CATEGORICAL/))h=[map.Dictionary.getLocalText("selected items"),String(__formatValue(Number(this.nCount,2)))],k=Array(2),k[0]="font-weight:bold;fill:#7996D7;",k[1]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,
c,b+":textgrid",h,2,11,k),l+=c.fu.getBox().height/map.Scale.normalX(1)+5;else if(this.activeTheme.szAggregation&&this.activeTheme.szAggregation.match(/sum/)||this.activeTheme.szFlag.match(/SUM/)){if(h=[map.Dictionary.getLocalText("value of selection"),map.Dictionary.getLocalText("% of total value")," ",map.Dictionary.getLocalText("min"),map.Dictionary.getLocalText("max"),map.Dictionary.getLocalText("average"),String(__formatValue(Number(this.itemA.selection.nValuesA[0]),2))+" "+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/
Number(this.activeTheme.nOrigSumA[0])*100,2))+" %"," ",String(__formatValue(Number(this.nValuesMinA[0]),2))+" "+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+" "+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+" "+this.szUnit],k=Array(12),k[0]="font-weight:bold;fill:#7996D7;",k[6]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,c,b+":textgrid",h,2,11,k),l+=c.fu.getBox().height/map.Scale.normalX(1)+5,c=map.Dom.newGroup(d,""),
e.push(c),b=DonutCharts.newChart(SVGDocument,c,map.Scale.normalX(55),map.Scale.normalY(55),0,0),b.setRadInner(0),b.setRadOuter(map.Scale.normalX(55)),b.setCenter(map.Scale.normalX(80),map.Scale.normalY(100)),h=Number(this.nValuesSumA[0])/Number(this.activeTheme.nOrigSumA[0])*100,b.addPart(h,map.Scale.normalY(20),"#ddddee",0,this.formatValue(h,2)+"%","selection: "+this.formatValue(h,2)+"% of total value"),b.addPart(100-h,map.Scale.normalY(20),"#f8f8ff",0,this.formatValue(100-h,2)+"%",this.formatValue(100-
h,2)+"%"),b.realize(),map.Dom.newText(c,map.Scale.normalX(80),map.Scale.normalX(82),"font-size:"+map.Scale.normalX(10)/.66+"px;text-anchor:middle;baseline-shift:-60%;fill:darkgrey;stroke:none;pointer-events:none",this.formatValue(h,0)+" % of total"),this.activeTheme.szFlag.match(/BUBBLE/)||this.activeTheme.szFlag.match(/SQUARE/)||this.activeTheme.szFlag.match(/SYMBOL/))this.getOverviewChart=this.activeTheme.getOverviewChart,this.szOverviewChart=this.activeTheme.szOverviewChart,this.drawChart=this.activeTheme.drawChart,
this.getOverviewChart&&(b=map.Dom.newGroup(d,""),c=map.Dom.newGroup(b,""),e.push(b),b=this.szFlag,this.szFlag=this.activeTheme.szFlag,this.nOrigSumA=this.nOrigValuesSumA,this.nMaxA=this.nValuesMaxA,this.nMinA=this.nValuesMinA,this.szAggregation=this.activeTheme.szAggregation,this.getOverviewChart(c),this.szFlag=b,c.fu.scale(1.3,1.3),c.fu.setPosition(map.Scale.normalX(-35),map.Scale.normalY(35)))}else this.fField100?(h=[map.Dictionary.getLocalText("value of selection")," ",map.Dictionary.getLocalText("min value"),
map.Dictionary.getLocalText("max value"),map.Dictionary.getLocalText("mean value"),String(__formatValue(Number(this.itemA.selection.nValuesA[0]),2))+this.szUnit," ",String(__formatValue(Number(this.nValuesMinA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+this.szUnit],k=Array(10),k[0]="font-weight:bold;fill:#7996D7;",k[5]="font-weight:bold;fill:#000000;font-size:240px;"):this.activeTheme.szFlag.match(/DENSITY/)?
(h=[map.Dictionary.getLocalText("value of selection")," ",map.Dictionary.getLocalText("min value"),map.Dictionary.getLocalText("max value"),map.Dictionary.getLocalText("mean value"),String(__formatValue(Number(this.itemA.selection.nValuesA[0]),2))+this.szUnit," ",String(__formatValue(Number(this.nValuesMinA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+this.szUnit],k=Array(10),k[0]="font-weight:bold;fill:#7996D7;",
k[5]="font-weight:bold;fill:#000000;font-size:240px;"):(h=[map.Dictionary.getLocalText("mean value"),map.Dictionary.getLocalText(" "),map.Dictionary.getLocalText("min value"),map.Dictionary.getLocalText("max value"),String(__formatValue(Number(this.nValuesSumA[0])/this.nCount,2))+this.szUnit,map.Dictionary.getLocalText(" "),String(__formatValue(Number(this.nValuesMinA[0]),2))+this.szUnit,String(__formatValue(Number(this.nValuesMaxA[0]),2))+this.szUnit],k=Array(8),k[0]="font-weight:bold;fill:#7996D7;",
k[4]="font-weight:bold;fill:#000000;font-size:240px;"),createTextGrid(SVGDocument,c,b+":textgrid",h,2,11,k),l+=c.fu.getBox().height/map.Scale.normalX(1)+5;this.getOverviewChart=this.activeTheme.getOverviewChart;this.szOverviewChart=this.activeTheme.szOverviewChart;if(2<this.activeTheme.colorScheme.length||this.activeTheme.szFlag.match(/CATEGORICAL/)||!this.activeTheme.szFlag.match(/CHART/)&&!this.activeTheme.szFlag.match(/DOMINANT/))this.szOverviewChart=5<this.nOrigSumA.length?"BAR":"PIE";this.szOverviewChart&&
(c=map.Dom.newGroup(d,""),e.push(c),this.getOverviewChart(c),this.szOverviewChart.match(/PIE/)&&this.activeTheme.szAggregation.match(/sum/)&&(this.szOverviewChart+="|PERCENTOFVALUE",c=map.Dom.newGroup(d,""),e.push(c),this.getOverviewChart(c)));!this.activeTheme.szFlag.match(/CHART/)||this.activeTheme.szAggregation&&this.activeTheme.szAggregation.match(/sum/)||(this.getOverviewChart=this.activeTheme.getOverviewChart,this.szOverviewChart=null,this.drawChart=this.activeTheme.drawChart,this.getOverviewChart&&
(b=map.Dom.newGroup(d,""),c=map.Dom.newGroup(b,""),e.push(b),b=this.szFlag,this.szFlag=this.activeTheme.szFlag,this.nOrigSumA=this.nOrigValuesSumA,this.nMaxA=this.nValuesMaxA,this.nMinA=this.nValuesMinA,this.nOverrideMax=this.activeTheme.nMax,this.szAggregation=this.activeTheme.szAggregation,this.getOverviewChart(c),this.szFlag=b,this.activeTheme.szFlag.match(/BAR/)?(c.fu.scale(2.5,2.5),c.fu.setPosition(map.Scale.normalX(55),map.Scale.normalY(65))):(c.fu.scale(1.3,1.3),c.fu.setPosition(map.Scale.normalX(-35),
map.Scale.normalY(35))),b=this.szFlag,this.szFlag=this.activeTheme.szFlag,this.szOverviewChart+="|PERCENTOFVALUE",c=map.Dom.newGroup(d,""),e.push(c),this.getOverviewChart(c),this.szFlag=b))}else{if(this.activeTheme.szAggregation.match(/sum/)||this.activeTheme.szFlag.match(/SUM/))f=this.nSum100?this.nSum100:this.activeTheme.szFlag.match(/CATEGORICAL/)?this.nExactCount:this.nSum,h=this.activeTheme.nSum100?this.activeTheme.nSum100:this.activeTheme.szFlag.match(/CATEGORICAL/)?this.activeTheme.nExactCount:
this.activeTheme.nSum,h=[map.Dictionary.getLocalText("total of selection"),String(__formatValue(f,2))+" ("+String(__formatValue(Number(f)/Number(h)*100,2))+" %)"],k=Array(2),k[0]="font-weight:bold;fill:#7996D7;",k[1]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,c,b+":textgrid",h,2,11,k),l+=c.fu.getBox().height/map.Scale.normalX(1)+5;this.nSum100&&(f=this.nSum100,this.activeTheme.szFlag.match(/DOMINANT/)||this.activeTheme.szAggregation.match(/sum/)||(f/=this.nSelected),
h=this.activeTheme.nSum100,h=[map.Dictionary.getLocalText("total of selection"),String(__formatValue(f,2))+" ("+String(__formatValue(Number(f)/Number(h)*100,2))+" %)"],k=Array(2),k[0]="font-weight:bold;fill:#7996D7;",k[1]="font-weight:bold;fill:#000000;font-size:240px;",createTextGrid(SVGDocument,c,b+":textgrid",h,2,11,k),l+=c.fu.getBox().height/map.Scale.normalX(1)+5);this.drawChart=this.activeTheme.drawChart;this.getOverviewChart=this.activeTheme.getOverviewChart;this.szOverviewChart=this.activeTheme.szOverviewChart;
if(this.activeTheme.szFlag.match(/CATEGORICAL/)||!this.activeTheme.szFlag.match(/CHART/)&&!this.activeTheme.szFlag.match(/DOMINANT/))this.szOverviewChart="PIE";this.nOrigSumA=this.nOrigValuesSumA;this.nMaxA=this.nValuesMaxA;this.nMinA=this.nValuesMinA;f=this.szFlag;this.szFlag=this.activeTheme.szFlag;this.szAggregation=this.activeTheme.szAggregation;this.szOverviewChart?(c=map.Dom.newGroup(d,""),e.push(c),this.getOverviewChart(c),this.szOverviewChart.match(/PIE/)&&this.activeTheme.szAggregation.match(/sum/)&&
(this.szOverviewChart+="|PERCENTOFVALUE",c=map.Dom.newGroup(d,""),e.push(c),this.getOverviewChart(c))):(c=map.Dom.newGroup(d,""),this.nMin=this.activeTheme.nMin,this.nMax=this.activeTheme.nMax,d=1.8,this.szFlag.match(/DOMINANT/)&&(d=1.8),this.drawColorSchemeLegend=this.activeTheme.drawColorSchemeLegend,this.nOrigSumA=this.activeTheme.nOrigSumA,this.nSum=this.activeTheme.nSum,this.szField100=this.activeTheme.szField100,this.drawColorSchemeLegend(c,"test").fu.scale(.9/d,.9/d),h=map.Dom.getBox(c),0<
h.width&&0<h.height&&(c.fu.scale(d,d),c.fu.setPosition(map.Scale.normalX(10)-h.x*d,map.Scale.normalY(l)+map.Scale.normalY(5)-h.y*d),map.Dom.newText(c,h.x,h.y+h.height+map.Scale.normalX(6),"font-family:Arial;font-style:italic;font-size:"+map.Scale.normalY(6)+"px;fill:#888888;pointer-events:none",this.activeTheme.fField100||this.activeTheme.szAggregation.match(/sum/)?map.Dictionary.getLocalText("* summary over selected area"):map.Dictionary.getLocalText("* arithmetic mean over selected area"))))}this.szFlag=
f}__formatValue(100/this.nThemeItems*this.nSelected,2);__chartArrayReformat(e,map.Scale.normalX(l),2);a.reformat();szTextGridStyle=g}};
function __chartArrayReformat(a,b,g){for(var d=0,e=0,e=1E3,l=0,h=0,k=0,c=0;c<a.length;c++){var f=a[c];f.fu.scale(.8,.8);var m=f.fu.getBox(),e=Math.min(e,m.x),l=Math.min(l,m.y),h=Math.max(h,m.width)}e=b-l+40;for(c=0;c<a.length;c++)f=a[c],m=f.fu.getBox(),0===c?d=map.Scale.normalX(2)-0:g&&0===c%g&&(e+=map.Scale.normalX(20)+k,d=map.Scale.normalX(2)-m.x,k=0),k=Math.max(k,m.height),f.fu.setPosition(d,e),d+=h-map.Scale.normalX(10)}MapSelection.prototype.markClass=function(a){};
MapSelection.prototype.unmarkClass=function(a){};MapSelection.prototype.remove=function(a){this.parent.removeTheme(a,this.szId)};MapSelection.prototype.removeElements=function(a){this.markGroup&&(this.markGroup.style.setProperty("display","none",""),setTimeout("map.Dom.removeElementById('"+this.markGroup.getAttributeNS(null,"id")+"')",1E4));try{this.mapTool.remove()}catch(b){}this.highLightList.unlock();this.highLightList.removeAll()};MapSelection.prototype.getItemNodes=function(a){return[]};
MapSelection.prototype.getNodeArea=function(a){return this.nSelectedArea?this.nSelectedArea/1E6:1};
