var SVGDocument=null,rootGroup=null,nNodesCreated=0,fObjectPseudoShadow=!0,fEmbedScale=!1,fSVGEmbeded=!1,HTMLWindow=null,SVGRootElement=null,SVGToolsGroup=null,SVGThemeGroup=null,SVGFixedGroup=null,SVGPopupGroup=null,SVGMessageGroup=null,SVGMenuGroup=null,SVGTltipGroup=null,SVGHiddenGroup=null,fTransparentMap=!1,fClipMap=!0,fClipMapDynamic=!1,fZoomByViewer=!1,fPDFEmbed=!1,fAllIncluded=!1,fSwitchByCSS=!0,szViewer="Adobe3.0",fLocalHost=!1,fLoadIncludes=!0,fDynamicLayer=!0,fDynamicTiles=!0,fTilesLoaded=
!1,fDiscardTiles="delayed",fLoadMultiTiles=!0,fMarkTiles=!1,fLoadingSilent=!1,fExecuteSilent=!1,fNotify=!1,szObjectGroupId="mapobjects",szShadowFilterId="DropShadowFilterObjects:antizoomandpan",szShadowFilterToolsId="DropShadowFilterTools:antizoomandpan",szShadowFilterShapeId="DropShadowFilterShape",fAntiZoomAndPan=!0,fFeatureScaling=!0,fObjectScaling=!0,fSymbolScalingDynamic=!0,fFeatureScalingDynamic=!1,fAdaptLabelToScaling=!0,fCheckLabelOverlap=!0,fCheckLabelSpace=!1,nCheckLabelSpace=.8,fCheckLabelSqueeze=
!0,fCheckLabelSize=!0,fKillOverlappingLabel=!1,fCheckLabelOnlyOne=!1,fCheckOverlapImplicit=!0,fCheckOverlapAllLayer=!0,fCheckOverlapClipOnTiles=!1,fTileTextNoClip=!1,fFeatureScalingByLayer=!0,fFroozeDynamicContent=!1,fPendingNewGeoBounds=!1,fPanByViewer=!1,fPanToolByViewer=!0,fPanHideTools=!0,fEndPan="normal",fRotateOnMouseMove=!1,fTriggerMouseMoveForPan=!0,fPreserveMapRatio=!0,fInitLegendOff=!1,fMapBorder=!1,fMapBorder3D=!1,nMapBorderWidth=1,szMapBorderColor="#B6BAC0",szMapPanBorderStyle="fill:#E0E5F0;stroke:white",
szMapPanBorderOnoverStyle="fill:#d0d5e0;stroke:white",szMapBackgroundStyle=null,szMapBackgroundColor=null,fClipMapToLegend=!1,fLegendToggleButtons=!1,fNorthArrow="rotatable",szNorthArrowPosition="INMAP",szLocalPopupAlignment=null,szMessagePosition="center",nToolMarginTop=0,nFixedInfoScale=1,fScaleBar=!0,fDebug=!1,fStatus=!1,fSetToolCursor=!1,fActivateInfoOnClick=!1,szTextGridStyle="background:#dddddd",fCheckSublayerCollapse=!1,fCreatTextLink=!0,nClipTextLink=30,nInfoOffsetX=25,nInfoOffsetY=-25,szInfoTitleColor=
"#000000",szInfoTitleBgColor="#ffffff",szInfoBodyColor="#444444",szInfoBodyBgColor="#FFFFDD",nInfoRoundRect=2,fInfoShowShape=!1,fActiveThemeInfo=!1,fDecimalPointComma=!1,nNormalSymbolSize=20,nNormalButtonSize=10,nNormalFontSize=12,nHighlightToggle=0,fLoadExternalData=!1,fScaleToFullscreen=!1,fHighlightHint=!0,fAdaptMapScaleToSize=!0,fLimitMapToExtent=!1,nStandardPPI=72,nScreenPPI=96,nInch=2.54,idTooltipTimeout=null,nTooltipTimeout=500,idInfoTimeout=null,nInfoTimeout=250,szMapToolType="",szSVG="http://www.w3.org/2000/svg",
szMapNs="http://www.medienobjekte.de",szXlink="http://www.w3.org/1999/xlink",szHTTP="http://",szLinkTarget="_blank",szEmbedName="SVGMap",newShape=null,_legendIdent=null,_activeTheme=null,_activeItem=null,_tooltip=null;if("undefined"==typeof printNode){var szFunct="function printNode(node){",szFunct=szFunct+"var serializer = new XMLSerializer();",szFunct=szFunct+"var xml = serializer.serializeToString(node);",szFunct=szFunct+"return xml;",szFunct=szFunct+"}";eval(szFunct)}
var map=null,antiZoomAndPanList=null,mouseObject=null,mapTool=null,mapTiles=null,bookmarkList=null,zoomAndPanHistory=null,highLightList=null;Map=function(){this.fInitializing=!1;this.Api=this.Viewport=this.Toolbar=this.Legend=this.Themes=this.Query=this.Zoom=this.Tiles=this.Layer=this.Scale=this.Event=null;this.mapRoot="";this.Loader=new SVGLoader;this.initActionA=[];this.initMessageA=[];this.actionA=[];this.messageA=[]};
Map.prototype.setFeatures=function(b){this.szFeatures=(this.szFeatures||"")+";"+b;b=b.split(";");for(i in b){var d=b[i].split(":");switch(d[0]){case "featurescaling":"dynamic"==d[1]?fFeatureScalingDynamic=fFeatureScaling=!0:(fFeatureScaling="false"==d[1]?!1:d[1],fFeatureScalingDynamic=!1);break;case "objectscaling":fObjectScaling="dynamic"==d[1]?"dynamic":"false"==d[1]?!1:d[1];break;case "objectlayer":szObjectGroupId="belowlabel"==d[1]?"mapobjects_below_label":d[1];break;case "dynamiclabel":(fAdaptLabelToScaling=
"false"==d[1]?!1:d[1])?(fCheckLabelSqueeze=fCheckLabelSpace=fCheckLabelOverlap=!0,fCheckLabelOnlyOne=fKillOverlappingLabel=!1,d[1].match(/CHECKSPACE/)&&(fCheckLabelSpace=!0),d[1].match(/NOCHECKSPACE/)&&(fCheckLabelSpace=!1),d[1].match(/NOREPOSITIONING/)&&(fKillOverlappingLabel=fCheckLabelOverlap=!0),d[1].match(/CHECKOVERLAP/)&&(fCheckLabelOverlap=!0),d[1].match(/NOCHECKOVERLAP/)&&(fCheckLabelOverlap=!1),d[1].match(/ONLYONE/)&&(fCheckLabelOnlyOne=!0),d[1].match(/SQUEEZE/)&&(fCheckLabelSpace=!0),d[1].match(/NOSQUEEZE/)&&
(fCheckLabelSqueeze=!1),d[1].match(/SIZE/)&&(fCheckLabelSize=!0),d[1].match(/NOSIZE/)&&(fCheckLabelSize=!1),d[1].match(/CLIPONTILES/)&&(fCheckOverlapClipOnTiles=!0),d[1].match(/NOCLIPONTILES/)&&(fCheckOverlapClipOnTiles=!1)):fCheckLabelOnlyOne=fKillOverlappingLabel=fCheckLabelSize=fCheckLabelSqueeze=fCheckLabelSpace=fCheckLabelOverlap=!1;break;case "dynamiclayer":fDynamicLayer="false"==d[1]?!1:d[1];break;case "dynamictiles":fDynamicTiles="false"==d[1]?!1:d[1];break;case "discardtiles":fDiscardTiles=
"false"==d[1]?!1:d[1];break;case "loadmultitiles":fLoadMultiTiles="false"==d[1]?!1:d[1];break;case "loadexternaldata":fLoadExternalData="false"==d[1]?!1:d[1];break;case "loadincludes":fLoadIncludes="false"==d[1]?!1:d[1];break;case "loadsilent":fLoadingSilent="false"==d[1]?!1:d[1];break;case "worksilent":fExecuteSilent="false"==d[1]?!1:d[1];break;case "notify":fNotify="false"==d[1]?!1:d[1];break;case "fastpan":fPanToolByViewer="false"==d[1]?!1:d[1];break;case "fullscreen":fScaleToFullscreen="false"==
d[1]?!1:d[1];break;case "realtimerotate":fRotateOnMouseMove="false"==d[1]?!1:d[1];break;case "tooltipdelay":nTooltipTimeout=Number(d[1]);break;case "popupdelay":nInfoTimeout=Number(d[1]);break;case "popupgridstyle":szTextGridStyle=d[1];break;case "buttonsize":nNormalButtonSize=Number(d[1]);break;case "symbolsize":nNormalSymbolSize=Number(d[1]);break;case "panborder":fMapBorder=!0;nMapBorderWidth=Number(d[1]);break;case "sidebarbuttons":fLegendToggleButtons="false"==d[1]?!1:d[1];break;case "3Dborder":fMapBorder3D=
"false"==d[1]?!1:d[1];break;case "mapbackgroundstyle":szMapBackgroundStyle=d[1];break;case "mapbackgroundcolor":szMapBackgroundColor=d[1];break;case "transparent":case "transparentbackground":fTransparentMap=!0;break;case "mapopacity":this.nOpacity=parseFloat(d[1]);this.setOpacity(this.nOpacity,"absolute");break;case "clipmap":"dynamic"==d[1]?fClipMapDynamic=fClipMap=!0:(fClipMap="false"==d[1]?!1:d[1],fClipMapDynamic=!1);break;case "checklabeloverlap":fCheckLabelOverlap="false"==d[1]?!1:d[1];break;
case "onlyonelabel":fCheckLabelOnlyOne="false"==d[1]?!1:d[1];break;case "labelspace":nCheckLabelSpace=parseFloat(d[1]);break;case "decimalpoint":fDecimalPointComma=","==d[1]||"komma"==d[1]||"Komma"==d[1]||"comma"==d[1]?!0:!1;break;case "dynamicscale":fAdaptMapScaleToSize="false"==d[1]?!1:d[1];break;case "toolcursor":fSetToolCursor="false"==d[1]?!1:d[1];break;case "scalebar":fScaleBar="false"==d[1]?!1:d[1];break;case "northarrow":fNorthArrow="false"==d[1]?!1:d[1];break;case "northarrowposition":szNorthArrowPosition=
d[1];break;case "screenppi":(nScreenPPI=Number(d[1]))||(nScreenPPI=96);break;case "embedname":szEmbedName=d[1];break;case "debug":fDebug=d[1];break;case "marktiles":fMarkTiles=d[1];break;case "popupalignment":szLocalPopupAlignment=d[1];break;case "toolmargintop":nToolMarginTop=Number(d[1]);break;case "messageposition":szMessagePosition=d[1];break;case "maxThemeCharts":this.Themes.nMaxThemeCharts=Number(d[1]);break;case "maxShadowCharts":this.Themes.nMaxShadowCharts=Number(d[1]);break;case "flushPaintShape":this.Themes.nflushPaintShape=
Number(d[1]);break;case "flushChartDraw":this.Themes.nflushChartDraw=Number(d[1]);this.Themes.activeTheme&&(this.Themes.activeTheme.nflushChartDraw=Number(d[1]));break;case "flushLabelDraw":this.Label.nflushLabelDraw=Number(d[1]);break;case "activeThemeInfo":fActiveThemeInfo=d[1];break;case "fixedInfoScale":nFixedInfoScale=Number(d[1]);break;case "normalSizeScale":map.Scale.nNormalSizeScale=Number(d[1])}}fClipMap&&!fClipMapDynamic||map.Zoom.removeClipping()};
Map.prototype.getFeatures=function(){return this.szFeatures+=";mapopacity:"+String(this.nOpacity||1)};Map.prototype.isLoading=function(){return this.Loader&&this.Loader.isWaiting()||this.mapLoader&&this.mapLoader.isWaiting()||map.Tiles&&map.Tiles.isLoading()||scriptLoaderPool.isLoading()?!0:!1};Map.prototype.isInitializing=function(){return this.fInitializing||this.Legend&&this.Legend.fInitializing||!this.Scale?!0:!1};
Map.prototype.isIdle=function(){return this.isInitializing()||this.isLoading()||0!=this.actionA.length||0!=this.initActionA.length?!1:!0};
Map.prototype.pushAction=function(b,d){if(b.match(/geobounds/i)){for(var e=0;e<this.actionA.length;e++)this.actionA[e].match(/geobounds/i)&&(this.actionA[e].slice(e,1),this.messageA[e]&&this.messageA[e].slice(e,1));fPendingNewGeoBounds=!0}if(b.match(/toview/i)){for(e=0;e<this.actionA.length;e++)this.actionA[e].match(/toview/i)&&(this.actionA[e].slice(e,1),this.messageA[e]&&this.messageA[e].slice(e,1));fPendingNewGeoBounds=!0}this.actionA.push(b);this.messageA.push(d);this.isInitializing()||1!=this.actionA.length||
setTimeout("map.popAction()",10)};Map.prototype.pushInitAction=function(b,d){this.initActionA.push(b);this.initMessageA.push(d);1==this.initActionA.length&&setTimeout("map.popInitAction()",10)};
Map.prototype.popAction=function(){if(0==this.actionA.length)clearMessage();else if(this.isLoading()||this.isInitializing())if(this.isLoading()?this.npopActionWaitInit=0:this.npopActionWaitInit++,100>this.npopActionWaitInit)setTimeout("map.popAction()",500);else{alert("Error at initializing !\nResource missing or corrupted ?\n");this.actionA.length=0;this.initActionA.length=0;this.fInitializing=!1;try{HTMLWindow&&HTMLWindow.ixmaps.htmlgui_onMapError(window)}catch(b){}}else{var d=this.actionA.shift(),
e=this.messageA.shift();e&&displayMessage(e,1E3);try{eval(d)}catch(f){f&&"undefined"!=typeof f&&f.description&&"undefined"!=typeof f.description&&alert("Error: "+f.description+":\n\n"+d)}setTimeout("map.popAction()",10)}};Map.prototype.popInitAction=function(){if(0==this.initActionA.length)map.npopActionWaitInit=0,map.popAction();else{if(!this.isLoading()){var b=this.initActionA.shift(),d=this.initMessageA.shift();d&&displayMessage(d,1E3);try{eval(b)}catch(e){}}setTimeout("map.popInitAction()",10)}};
Map.prototype.checkVersion=function(b){return null==b||b!=this.version?!1:!0};Map.prototype.fadeLogo=function(){var b=SVGDocument.getElementById("mapbackground:logo");b&&b.parentNode.removeChild(b)};Map.prototype.hideAll=function(){var b=SVGDocument.getElementById("mapcanvas");b&&b.style.setProperty("display","none","")};Map.prototype.showAll=function(){var b=SVGDocument.getElementById("mapcanvas");b&&b.style.setProperty("display","inline","")};
Map.prototype.hideMap=function(){if(!this.fHidden){var b=SVGDocument.getElementById("maplayer");b&&b.style.setProperty("display","none","");(b=SVGDocument.getElementById("mapobjects"))&&b.style.setProperty("display","none","");this.fHidden=!0}};Map.prototype.showMap=function(){if(this.fHidden){var b=SVGDocument.getElementById("maplayer");b&&b.style.setProperty("display","inline","");(b=SVGDocument.getElementById("mapobjects"))&&b.style.setProperty("display","inline","");this.fHidden=!1}};
Map.prototype.setOpacity=function(b,d){var e=SVGDocument.getElementById("maplayer");if(e)if("absolute"==d)e.style.setProperty("opacity",b,""),this.nOpacity=b;else{var f=e.style.getPropertyValue("opacity");if(null==f||0==f.length)f="1";f=parseFloat(f);this.nOpacity=f=Math.min(Math.max(f+b,0),1);e.style.setProperty("opacity",f,"")}};
Map.prototype.toggleOpacity=function(){var b=SVGDocument.getElementById("maplayer");if(b){var d=b.style.getPropertyValue("opacity");if(null==d||0==d.length)d="1";d=parseFloat(d);b.style.setProperty("opacity",1>d?1:0,"")}};Map.prototype.clearAll=function(){map.Dom.clearGroup(SVGToolsGroup);map.Dom.clearGroup(SVGFixedGroup);map.removeAllHighlights();this.Themes.removeAll();setMapTool("");this.Scale.nObjectScaling=1};
Map.prototype.loadMap=function(b){this.mapLoader||(this.mapLoader=new SVGLoaderMap);this.mapLoader.importSVGFile(b,SVGDocument)&&(b.match(/http/)?(szUrlA=b.split(/\//),szUrlA.splice(-1),b=szUrlA.join("/"),this.mapRoot=b+"/"):this.mapRoot="")};var thisversion="0.9",map=new Map;map.version=thisversion;
function initAll(b,d){console.log("*** iXMaps mapscript version: "+map.version);console.log("*** some .svg or .js files may not be found, this is normal and due to hierarchical location files ***");setSVGDocument(b,null);setTimeout("delayedInitAll(null,'"+d+"')",10)}var init=0;
function delayedInitAll(b,d){if(!map.fInitializing){map.fInitializing=!0;setSVGDocument(b,null);map.hideAll();map.Dom=new Map.Dom(b);SVGRootElement=SVGDocument.documentElement;if(fSVGEmbeded){var e=map.Dom.newNode("g",SVGRootElement);e.setAttribute("id","embed");e.setAttribute("name",d)}rootGroup=map.Dom.newGroup(SVGRootElement,"objects:antizoomandpan");SVGToolsGroup=map.Dom.newGroup(rootGroup,"ToolsGroup");SVGFixedGroup=map.Dom.newGroup(rootGroup,"FixedGroup");SVGThemeGroup=map.Dom.newGroup(rootGroup,
"ThemeGroup");SVGThemeGroup.style.setProperty("display","none","");SVGPopupGroup=map.Dom.newGroup(rootGroup,"PopupGroup");SVGNotifyGroup=map.Dom.newGroup(rootGroup,"NotifyGroup");SVGMessageGroup=map.Dom.newGroup(rootGroup,"MessageGroup");SVGMenuGroup=map.Dom.newGroup(rootGroup,"MenuGroup");SVGTltipGroup=map.Dom.newGroup(rootGroup,"TltipGroup");SVGHiddenGroup=map.Dom.newGroup(rootGroup,"HiddenGroup");SVGHiddenGroup.style.setProperty("display","none","");SVGTempGroup=map.Dom.newGroup(rootGroup,"TempGroup");
SVGWidth=parseInt(SVGRootElement.getAttribute("width"));SVGHeight=parseInt(SVGRootElement.getAttribute("height"));SVGOrigViewBoxString=SVGRootElement.getAttribute("viewBox");SVGViewBox=SVGRootElement.getAttribute("viewBox").split(" ");SVGViewBox[0]=Number(SVGViewBox[0]);SVGViewBox[1]=Number(SVGViewBox[1]);SVGViewBox[2]=Number(SVGViewBox[2]);SVGViewBox[3]=Number(SVGViewBox[3]);map.Scale=new Map.Scale;if(map.Scale.scaleNode&&map.Scale.extentNode){map.Scale.superclass=map;if(fAllIncluded||fPDFEmbed)map.Scale.createWidgetStyles(),
map.Scale.normalizeSymbols(SVGDocument.getElementById("symbolstore")),map.Scale.normalizeButtons(SVGDocument.getElementById("widgetstore")),map.Event=new Map.Event,map.Event.initUseNodes(SVGDocument.getElementById("widgetstore"));else{map.pushAction("map.Scale.createWidgetStyles()");map.pushAction('map.Scale.normalizeSymbols(SVGDocument.getElementById("symbolstore"))');map.pushAction('map.Scale.normalizeButtons(SVGDocument.getElementById("widgetstore"))');try{"undefined"!=typeof HTMLWindow.ixmaps.SVGResources_includePath?
map.Loader.importSVGFile(HTMLWindow.ixmaps.SVGResources_includePath+"/maplocal.svg",SVGDocument,SVGTempGroup,null):map.Loader.importSVGFile("../../resources/svg/maplocal.svg",SVGDocument,SVGTempGroup,null)}catch(f){}}if(!SVGDocument.getElementById(szShadowFilterToolsId)){var g=map.Dom.newNode("filter",rootGroup);g.setAttributeNS(null,"id",szShadowFilterToolsId);g.setAttributeNS(null,"filterUnits","objectBoundingBox");g.setAttributeNS(null,"x","-50%");g.setAttributeNS(null,"y","-50%");g.setAttributeNS(null,
"width","200%");g.setAttributeNS(null,"height","200%");e=map.Dom.newNode("feGaussianBlur",g);e.setAttributeNS(null,"stdDeviation","50");e.setAttributeNS(null,"result","BlurAlpha");e=map.Dom.newNode("feOffset",g);e.setAttributeNS(null,"in","BlurAlpha");e.setAttributeNS(null,"dx","20");e.setAttributeNS(null,"dy","20");e.setAttributeNS(null,"result","OffsetBlurAlpha");e=map.Dom.newNode("feColorMatrix",g);e.setAttributeNS(null,"in","OffsetBlurAlpha");e.setAttributeNS(null,"type","matrix");e.setAttributeNS(null,
"values","0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.3 0");e.setAttributeNS(null,"result","matrixOut");e=map.Dom.newNode("feMerge",g);g=map.Dom.newNode("feMergeNode",e);g.setAttributeNS(null,"in","matrixOut");g=map.Dom.newNode("feMergeNode",e);g.setAttributeNS(null,"in","SourceGraphic")}szViewer.match(/Firefox/i)&&(map.pushAction('map.Scale.normalizeSymbols(SVGDocument.getElementById("symbolstore"))'),map.pushAction('map.Scale.normalizeButtons(SVGDocument.getElementById("widgetstore"))'));init++;fLoadIncludes&&
("delayed"==fLoadIncludes?map.pushInitAction("load_includes()"):load_includes());fAllIncluded||fPDFEmbed?doInitAll_2():map.pushInitAction("doInitAll_2(null)"," ... ")}else alert("SVG source not valid SVGGIS map !")}}
function doInitAll_2(b){HTMLWindow&&map.pushInitAction("HTMLWindow.ixmaps.htmlgui_onMapInit(window)");map.Event=new Map.Event;SVGRootElement.setAttribute("onmouseover","map.Event.defaultMouseOver(evt)");SVGRootElement.setAttribute("onmouseout","map.Event.defaultMouseOut(evt)");SVGRootElement.setAttribute("onmousedown","map.Event.defaultMouseDown(evt)");SVGRootElement.setAttribute("ontouchstart","map.Event.defaultMouseDown(evt)");SVGRootElement.setAttribute("onmouseup","map.Event.defaultMouseUp(evt)");
SVGRootElement.setAttribute("ontouchend","map.Event.defaultMouseUp(evt);map.Event.defaultMouseClick(evt)");SVGRootElement.setAttribute("onmousemove","map.Event.defaultMouseMove(evt)");SVGRootElement.setAttribute("ontouchmove","map.Event.defaultMouseUp(evt);map.Event.defaultMouseMove(evt);HTMLWindow.ixmaps.htmlgui_onSVGPointerIdle()");SVGRootElement.setAttribute("onclick","map.Event.defaultMouseClick(evt)");SVGRootElement.setAttribute("onkeydown","map.Event.defaultKeyDown(evt)");SVGRootElement.setAttribute("onkeyup",
"map.Event.defaultKeyUp(evt)");"function"==typeof map.Event.doDefaultZoom&&(SVGRootElement.addEventListener("SVGZoom",map.Event.doDefaultZoom,!1),SVGRootElement.addEventListener("SVGScroll",map.Event.doDefaultPan,!1),SVGRootElement.addEventListener("SVGResize",map.Event.doDefaultResize,!1));map.Layer=new Map.Layer(b);antiZoomAndPanList=new AntiZoomAndPan(b);antiZoomAndPanList.initAntiZoomPattern(b,null);antiZoomAndPanList.initAntiZoomSymbols(null,SVGDocument.getElementById("symbolstore"));antiZoomAndPanList.initAntiZoomStyles(b);
map.Layer.initPatternScaling(b,null);map.Zoom=new Map.Zoom(map.Scale.initScale);map.Tiles=new Map.Tiles;map.Label=new Map.Label;map.Viewport=new Map.Viewport(b);map.Layer.switchScaleDependentLayer(b);map.Scale.refreshCSSStyles();map.pushAction("map.Layer.scaleLineDecorations(SVGRootElement,1)");try{map.Dom.clearGroup(contextMenu.firstChild)}catch(d){}try{HTMLWindow.ixmaps.htmlgui_setScaleSelect(String(__formatValue(Math.floor(map.Scale.nTrueMapScale*map.Scale.nZoomScale)),0,"BLANK"))}catch(e){}try{HTMLWindow.ixmaps.htmlgui_setCurrentEnvelope(map.Zoom.getEnvelopeString(),
!0)}catch(f){}try{HTMLWindow.ixmaps.htmlgui_queryMapFeatures()}catch(g){}fClipMap&&!fClipMapDynamic||map.Zoom.removeClipping();fPDFEmbed&&(map.Tiles.switchScaleDependentTiles(b),clearMessage());setTimeout("map.showAll()",1500);setTimeout("map.Zoom.init()",1E3);setTimeout("map.fadeLogo()",1E4);map.Layer.prepareCheckOverlap(b,map.Layer.layerNode);map.fInitializing=!1;HTMLWindow&&map.pushInitAction("HTMLWindow.ixmaps.htmlgui_onMapReady(window)");map.pushInitAction("nothing()")}
function load_includes(){try{loadSVGIncludes(null,"../../resources/svg"),"undefined"!=typeof HTMLWindow.ixmaps.SVGResources_includePath&&setTimeout("loadSVGIncludes(null,'"+HTMLWindow.ixmaps.SVGResources_includePath+"')")}catch(b){}}
function setSVGDocument(b,d){d?(fSVGEmbeded=!0,document.embeds[d]&&(SVGDocument=document.embeds[d].getSVGDocument(),EmbedHeight=document.embeds[d].height,EmbedWidth=document.embeds[d].width)):b&&(SVGDocument=b.target.ownerDocument);SVGDocument.getElementById("widgetstore")&&2<SVGDocument.getElementById("widgetstore").childNodes.length&&(fAllIncluded=!0);window.parent&&window.screen&&window.location||(fPDFEmbed=!0);fLocalHost=String(window.location).match(/localhost/);szViewer=navigator.appName;navigator.appName.match(/Adobe/)&&
navigator.appVersion.match(/6.0x/)?szViewer="Adobe6.0":navigator.appName.match(/Adobe/)&&navigator.appVersion.match(/3.0/)?szViewer="Adobe3.0":navigator.appName.match(/Opera/)?szViewer="Opera":navigator.appName.match(/Netscape/)&&(szViewer="Netscape");navigator.userAgent&&navigator.userAgent.match(/Chrome/)?szViewer="Chrome":navigator.userAgent&&navigator.userAgent.match(/Firefox/)&&(szViewer="Firefox");var e=SVGDocument.documentElement.getAttribute("xmlns:xmap");e&&3<e.length&&(szMapNs=e);window.parent&&
window.parent.window&&window.parent.window.ixmaps&&(HTMLWindow=window.parent.window)}var __execLaterA=[];function __executeMethodLater(b,d){__execLaterA.push({obj:b,szExec:d});setTimeout("__doExecuteMethodLater()",1)}function __doExecuteMethodLater(){var b=__execLaterA.shift();b&&eval("exec.obj."+b.szExec)}Map.Dom=function(b){this.targetDocument=SVGDocument;b&&(this.targetDocument=b.target.ownerDocument);this.rootElement=this.targetDocument.documentElement;this.idList=[];this.objStackA=[]};
Map.Dom.prototype=new Map;Map.Dom.prototype.setTargetDocument=function(b){b&&(this.targetDocument=b)};Map.Dom.prototype.setTargetGroup=function(b){b&&(this.targetGroup=b)};Map.Dom.prototype.newNode=function(b,d){var e=this.targetDocument.createElementNS(szSVG,b);(d||this.targetGroup).appendChild(e);return e};Map.Dom.prototype.newGroup=function(b,d){var e=this.newNode("g",b);e&&(d&&e.setAttribute("id",d),e.fu=new Methods(e));return e};
Map.Dom.prototype.newObject=function(b,d){var e=this.newNode(b,d);e&&(e.fu=new Methods(e));return e};Map.Dom.prototype.getObjectById=function(b){if(b=this.targetDocument.getElementById(b))b.fu=new Methods(b);return b};Map.Dom.prototype.clearGroup=function(b){if(b&&b.hasChildNodes())for(var d=b.childNodes,e=d.length-1;0<=e;e--)b.removeChild(d.item(e))};Map.Dom.prototype.removeElementById=function(b){(b=SVGDocument.getElementById(b))&&b.parentNode&&b.parentNode.removeChild(b)};
Map.Dom.prototype.constructNode=function(b,d,e){b=this.newObject(b,d);for(var f in e)f.match(/xlink/)?b.setAttributeNS("http://www.w3.org/1999/xlink",f,e[f]):b.setAttribute(f,e[f]);return b};Map.Dom.prototype.pushObj=function(b){var d="stackedObject"+String(Math.random());this.objStackA[d]=b;return d};Map.Dom.prototype.popObj=function(b){return this.objStackA[b]};
Map.Dom.prototype.newShape=function(b,d,e,f,g,h,k,l,m,p,q,r,t){l=null;switch(b){case "rect":isNaN(g)||0>=g||isNaN(h)||0>=h||(l={x:String(e),y:String(f),width:String(g),height:String(h),style:k});break;case "circle":isFinite(g)&&0<g&&(l={cx:String(e),cy:String(f),r:String(g),style:h});break;case "line":isFinite(e)&&isFinite(f)&&isFinite(g)&&isFinite(h)&&(l={x1:String(e),y1:String(f),x2:String(g),y2:String(h),style:k});break;case "path":l={d:String(e),style:f}}return l?this.constructNode(b,d,l):null};
Map.Dom.prototype.newText=function(b,d,e,f,g){if(!isFinite(d)||!isFinite(e))return null;g&&"undefined"!=typeof g||(g="(undefined)");g=String(g);if(fCreatTextLink&&g.substr(0,7)==szHTTP)return this.newTextLink(b,d,e,f,g);nT=this.constructNode("text",b,{x:String(d),y:String(e),style:f});atext=this.targetDocument.createTextNode(g);nT.appendChild(atext);return nT};
Map.Dom.prototype.newTSpan=function(b,d,e){if("text"!=b.nodeName)return null;e||(e="(undefined)");nT=this.constructNode("tspan",b,{style:d});atext=this.targetDocument.createTextNode(e);nT.appendChild(atext);return nT};
Map.Dom.prototype.newTextLink=function(b,d,e,f,g,h){nL=this.constructNode("a",b);nL.setAttributeNS(szXlink,"xlink:href",h?h:g);nL.setAttributeNS(null,"target",szLinkTarget);g&&30<g.length&&(g=g.substr(0,29)+" ...");nT=this.constructNode("text",nL,{x:String(d),y:String(e),style:f});atext=this.targetDocument.createTextNode(g);nT.appendChild(atext);nT.style.setProperty("fill","blue","");nT.style.setProperty("text-decoration","underline","");return nL};
Map.Dom.prototype.wrapText=function(b,d){var e=b.firstChild.data;if(e){e=e.split(" ");b.removeChild(b.firstChild);for(var f=this.newTSpan(b,"",e[0]),g=1;g<e.length;g++){var h=f.firstChild.data.length;f.firstChild.data+=" "+e[g];f.getComputedTextLength()>d&&(f.firstChild.data=f.firstChild.data.slice(0,h),f=this.newTSpan(b,"",e[g]),f.setAttributeNS(null,"x",0),f.setAttributeNS(null,"dy",300))}}};
Map.Dom.prototype.getAllIds=function(b,d){null==d&&(this.idList.length=0);if(b&&b.hasChildNodes()){if(b.hasAttributes){var e=b.getAttributeNS(null,"id");e&&(this.idList[this.idList.length]=e)}for(var e=b.childNodes,f=0;f<e.length;f++)this.getAllIds(e.item(f),1)}return this.idList};Map.Dom.prototype.extendAllIds=function(b,d){if(b&&1==b.nodeType){var e=b.getAttributeNS(null,"id");b.setAttributeNS(null,"id",e+d);for(var e=b.childNodes,f=0;f<e.length;f++)this.extendAllIds(e.item(f),d)}};
Map.Dom.prototype.getParentByNodename=function(b,d){var e=null;if(b)for(;e=b.parentNode;){if(e.nodeName==d)return e;b=e}return null};Map.Dom.prototype.getAttributeByNodeOrParents=function(b,d,e){for(var f=null;b&&1==b.nodeType;)if(f=b.getAttributeNS(d,e),null==f||0==f.length)b=b.parentNode;else return f;return""};
Map.Dom.prototype.getClipRect=function(b){var d=null;(b=b.getAttributeNS(null,"clip-path"))&&(b=b.match(urlRegExp))&&b[1]&&(b=SVGDocument.getElementById(b[1]))&&b.hasChildNodes&&(d=b.firstChild);return d};
Map.Dom.prototype.setClipRect=function(b,d){var e=this.getClipRect(b);if(!e){var f=b.getAttributeNS(null,"id"),e=map.Dom.newNode("clipPath",b.parentNode);e.setAttributeNS(null,"id",f+":clippath");e.setAttributeNS(null,"style","pointer-events:all");e=map.Dom.newShape("rect",e,0,0,1,1,"fill:none;stroke:none;opacity:0");e.setAttributeNS(null,"id",f+":cliprect");b.setAttributeNS(null,"clip-path","url(#"+f+":clippath)")}e.setAttributeNS(null,"x",d.x);e.setAttributeNS(null,"y",d.y);e.setAttributeNS(null,
"width",d.width);e.setAttributeNS(null,"height",d.height);return e};
Map.Scale=function(){fScaleToFullscreen&&!fPDFEmbed&&window.screen&&(SVGRootElement.currentScale=1,SVGRootElement.currentScale=Math.min(window.innerWidth/SVGWidth,window.innerHeight/SVGHeight));this.viewBox=new box(SVGViewBox[0],SVGViewBox[1],SVGViewBox[2],SVGViewBox[3]);this.szMapUnits=this.nMapScale=this.scaleNode=null;this.szMapProjection="UTM";this.mapPosition=new point(0,0);this.mapOffset=new point(0,0);this.offsetNode=SVGDocument.getElementById("mapoffset");this.canvasNode=SVGDocument.getElementById("mapcanvas");
this.zoomNode=SVGDocument.getElementById("mapzoomandpan");this.canvasNode&&(this.mapOffset=getTranslate(this.canvasNode));this.offsetNode&&(this.mapPosition=getTranslate(this.offsetNode));this.CSSStyleNodes=SVGDocument.getElementById("mapstyles");this.fCSSStyleNodeChanged=!1;this.scaledSymbolsA=[];this.rotatedSymbolsA=[];this.screenX=1024;this.screenY=768;this.nPPI=nScreenPPI;this.objectScaling_lastScale=this.symbolScaling_lastScale=this.featureScaling_lastScale=1;this.metadataNode=null;var b=SVGRootElement.getElementsByTagName("metadata");
if(this.metadataNode=b[b.length-1]){this.creationNode=this.metadataNode.getElementsByTagNameNS(szMapNs,"creation").item(0);if(this.extentNode=this.metadataNode.getElementsByTagNameNS(szMapNs,"extension").item(0))this.minBoundX=Number(this.extentNode.getAttribute("minboundx")),this.maxBoundX=Number(this.extentNode.getAttribute("maxboundx")),this.minBoundY=Number(this.extentNode.getAttribute("minboundy")),this.maxBoundY=Number(this.extentNode.getAttribute("maxboundy")),this.minX=Number(this.extentNode.getAttribute("minx")),
this.minY=Number(this.extentNode.getAttribute("miny")),this.maxX=Number(this.extentNode.getAttribute("maxx")),this.maxY=Number(this.extentNode.getAttribute("maxy")),this.bBox=new box(this.minX,this.minY,this.maxX-this.minX,this.maxY-this.minY),this.mapUnitsPPX=(this.maxBoundX-this.minBoundX)/(this.maxX-this.minX),this.mapUnitsPPY=(this.maxBoundY-this.minBoundY)/(this.maxY-this.minY),this.origMinX=this.minX,this.origMinY=this.minY;if(this.scaleNode=this.metadataNode.getElementsByTagNameNS(szMapNs,
"scale").item(0))this.nMapScale=Number(this.scaleNode.getAttribute("mapscale")),this.nMapPPI=Number(this.scaleNode.getAttribute("dpi")),this.nMapPPI||(this.nMapPPI=nStandardPPI),this.szMapUnits=this.scaleNode.getAttribute("mapunitsstr"),this.initScale=this.scaleNode.getAttribute("mapinitscale"),this.initZoomNode=this.metadataNode.getElementsByTagNameNS(szMapNs,"initzoom").item(0),this.nObjectScaling=this.nLabelScaling=this.nLineScaling=this.nBorderScaling=this.nFeatureScaling=1,this.nTrueMapScale=
this.getTrueMapScale(),this.nNormalSizeScale=this.nMapScale,this.nDynamicScalePow=3;if(this.coordsysNode=this.metadataNode.getElementsByTagNameNS(szMapNs,"coordsys").item(0))this.szMapProjection=this.coordsysNode.getAttribute("projection"),this.szDatum=this.coordsysNode.getAttribute("datum"),this.szUTMZone=this.coordsysNode.getAttribute("UTMZone"),this.nFalseEasting=Number(this.coordsysNode.getAttribute("falseeasting")),this.nFalseNorthing=Number(this.coordsysNode.getAttribute("falsenorthing")),this.nCorrectEasting=
Number(this.coordsysNode.getAttribute("correcteasting")),this.nCorrectNorthing=Number(this.coordsysNode.getAttribute("correctnorthing"));if(this.featuresNode=this.metadataNode.getElementsByTagNameNS(szMapNs,"features").item(0))(b=this.featuresNode.getAttributeNS(null,"mapfeatures"))&&1<b.length&&map.setFeatures(b),"true"==this.featuresNode.getAttributeNS(null,"cliptextpath")&&(fAdaptLabelToScaling="delayed"),"true"==this.featuresNode.getAttributeNS(null,"initlegendoff")&&(fInitLegendOff=!0),"true"==
this.featuresNode.getAttributeNS(null,"checklabeloverlap")&&(fCheckLabelOverlap=!0),"true"==this.featuresNode.getAttributeNS(null,"onlyonelabel")&&(fCheckLabelOnlyOne=!0),"true"==this.featuresNode.getAttributeNS(null,"tiletextnoclip")&&(fTileTextNoClip=!0),this.nFeatureScaling=Number(this.featuresNode.getAttribute("featurescaling")),this.nBorderScaling=Number(this.featuresNode.getAttribute("borderscaling")),this.nLineScaling=Number(this.featuresNode.getAttribute("linescaling")),this.nLabelScaling=
Number(this.featuresNode.getAttribute("labelscaling")),this.nObjectScaling=Number(this.featuresNode.getAttribute("objectscaling")),this.nFeatureScaling=this.nFeatureScaling?this.nFeatureScaling:1,this.nBorderScaling=this.nBorderScaling?this.nBorderScaling:1,this.nLineScaling=this.nLineScaling?this.nLineScaling:1,this.nLabelScaling=this.nLabelScaling?this.nLabelScaling:1,this.nObjectScaling=this.nObjectScaling?this.nObjectScaling:1}this.nButtonSize=nNormalButtonSize;this.nSymbolSize=nNormalSymbolSize;
this.nFontSize=nNormalFontSize;this.nScaleX=this.viewBox.width/this.getEmbedWidth()*this.getEmbedScale();this.nScaleY=this.viewBox.height/this.getEmbedHeight()*this.getEmbedScale();this.nZoomScale=1;this.mapCenter=new point(0,0);this.mapCanvasCenter=new point(this.mapPosition.x+this.bBox.width/2,this.mapPosition.y+this.bBox.height/2);this.setCanvasSize(0,0,window.innerWidth,window.innerHeight,"center")};Map.Scale.prototype=new Map;
Map.Scale.prototype.reset=function(){fScaleToFullscreen&&!fPDFEmbed&&window.screen&&(SVGRootElement.currentScale=1,SVGRootElement.currentScale=Math.min(window.innerWidth/SVGWidth,window.innerHeight/SVGHeight));this.canvasNode&&(this.mapOffset=getTranslate(this.canvasNode));this.offsetNode&&(this.mapPosition=getTranslate(this.offsetNode));this.mapCanvasCenter=new point(this.mapPosition.x+this.bBox.width/2,this.mapPosition.y+this.bBox.height/2);this.setCanvasSize(0,0,window.innerWidth,window.innerHeight,
"center")};
Map.Scale.prototype.setCanvasSize=function(b,d,e,f,g){var h=""+String(b)+" "+String(d)+" "+String(this.normalX(e))+" "+String(this.normalX(f))+"";b=this.normalX(e)-this.mapPosition.x;d=this.normalX(f)-this.mapPosition.y;var k=b-(this.maxX-this.minX),l=d-(this.maxY-this.minY);"extendmax"==g?(this.maxX+=k,this.maxY+=l,this.maxBoundX+=k*this.mapUnitsPPX,this.minBoundY-=l*this.mapUnitsPPY):(this.minX-=k/2,this.minY-=l/2,this.maxX+=k/2,this.maxY+=l/2,this.minBoundX-=k/2*this.mapUnitsPPX,this.maxBoundY+=l/
2*this.mapUnitsPPY,this.maxBoundX+=k/2*this.mapUnitsPPX,this.minBoundY-=l/2*this.mapUnitsPPY,this.canvasNode&&(setTranslate(this.canvasNode,this.maxX,this.maxY),this.mapOffset=getTranslate(this.canvasNode)));SVGWidth=e;SVGHeight=f;SVGRootElement.setAttribute("width",SVGWidth+"px");SVGRootElement.setAttribute("height",SVGHeight+"px");SVGRootElement.setAttribute("viewBox",h);SVGOrigViewBoxString=SVGRootElement.getAttribute("viewBox");SVGViewBox=SVGRootElement.getAttribute("viewBox").split(" ");SVGViewBox[0]=
Number(SVGViewBox[0]);SVGViewBox[1]=Number(SVGViewBox[1]);SVGViewBox[2]=Number(SVGViewBox[2]);SVGViewBox[3]=Number(SVGViewBox[3]);this.viewBox=new box(SVGViewBox[0],SVGViewBox[1],SVGViewBox[2],SVGViewBox[3]);this.bBox=new box(this.minX,this.minY,this.maxX-this.minX,this.maxY-this.minY);this.mapCanvasCenter=new point(this.mapPosition.x+this.bBox.width/2,this.mapPosition.y+this.bBox.height/2);this.nScaleX=this.viewBox.width/this.getEmbedWidth()*this.getEmbedScale();this.nScaleY=this.viewBox.height/
this.getEmbedHeight()*this.getEmbedScale();if(g=SVGDocument.getElementById("mapcliprect"))g.setAttributeNS(null,"width",b),g.setAttributeNS(null,"height",d);SVGDocument.getElementById("mapcliprect2");if(g=SVGDocument.getElementById("map:annotation"))g.fu=new Methods(g),b=g.fu.getBox(),g.fu.setPosition(this.normalX(e-2)-this.mapPosition.x,this.normalY(f)-this.mapPosition.y-2*b.height)};
Map.Scale.prototype.resizeCanvas=function(b,d,e,f,g){g||(g="center");this.setCanvasSize(b,d,e,f,g);try{map.Viewport.reformat(),map.Themes.reformat(),map.Themes.actualizeActiveTheme(!0),map.Legend.reformat()}catch(h){}try{displayScale(null,"bottom")}catch(k){}};
Map.Scale.prototype.getDistanceInMeter=function(b,d,e,f){var g=e-b,h=f-d,k=0;"Mercator"==this.szMapProjection&&(this.szMapUnits="degrees");switch(this.szMapUnits){case "feet":g/=3.2808399,h/=3.2808399;case "meter":case "meters":g=g*this.nZoomScale*this.mapUnitsPPX;h=h*this.nZoomScale*this.mapUnitsPPY;k=Math.sqrt(g*g+h*h);100<k&&(k=Math.round(k));k=10<k?Math.round(10*k)/10:Math.round(100*k)/100;break;default:b=map.Scale.getMapPosition(b,d),e=map.Scale.getMapPosition(e,f),b=map.Scale.getMapCoordinate(b.x,
b.y),d=map.Scale.getMapCoordinate(e.x,e.y),b=map.Scale.getGeoCoordinateOfPoint(b.x,b.y),d=map.Scale.getGeoCoordinateOfPoint(d.x,d.y),e=b.y/180*Math.PI,f=d.y/180*Math.PI,b=Math.abs(d.x/180*Math.PI-b.x/180*Math.PI),d=Math.abs(f-e),e=Math.pow(Math.sin(d/2),2)+Math.cos(e)*Math.cos(f)*Math.pow(Math.sin(b/2),2),k=12756776*Math.atan2(Math.sqrt(e),Math.sqrt(1-e))}return k};
Map.Scale.prototype.formatDistanceString=function(b){return 1E3<b?String(Math.round(b/100)/10)+" km":100<b?String(Math.round(10*b)/10)+" m":String(Math.round(100*b)/100)+" m"};Map.Scale.prototype.formatSurfaceString=function(b){var d="",d=1E6<b?String(Math.round(b/1E6*1E3)/1E3)+" km2":String(Math.round(1E3*b)/1E3)+" m2";szValueA=d.split(".");1<szValueA.length&&(d=szValueA[0]+","+szValueA[1]);return d};
Map.Scale.prototype.getDeltaXofDistanceInMeter=function(b){return 1E3/this.getDistanceInMeter(1E3,1E3,2E3,1E3)*b};Map.Scale.prototype.getDeltaYofDistanceInMeter=function(b){return 1E3/this.getDistanceInMeter(1E3,1E3,1E3,2E3)*b};
Map.Scale.prototype.getMapCoordinate=function(b,d){var e=0,f=0;b+=this.mapOffset.x;d=this.maxY-this.minY-(d+this.mapOffset.y);switch(this.szMapUnits){case "feet":case "meter":case "meters":e=this.minBoundX+b*this.mapUnitsPPX;f=this.minBoundY+d*this.mapUnitsPPY;break;default:e=this.minBoundX+b*this.mapUnitsPPX,f=this.minBoundY+d*this.mapUnitsPPY}return new point(e,f)};
Map.Scale.prototype.getMapCoordinateUTM=function(b,d){var e=this.getMapCoordinate(b,d);"Mercator"==this.szMapProjection?e=_LLtoMercator(e.y,e.x):"feet"!=this.szMapUnits&&"meter"!=this.szMapUnits&&"meters"!=this.szMapUnits&&(e=_LLtoUTM("WGS84",e.y,e.x));return e};
Map.Scale.prototype.getMapPositionOfLatLon=function(b,d){ptOff=map.Scale.getMapCoordinateOfLatLon(b,d);return{x:(ptOff.x-map.Scale.minBoundX)/map.Scale.mapUnitsPPX-map.Scale.mapOffset.x,y:map.Scale.bBox.height-(ptOff.y-map.Scale.minBoundY)/map.Scale.mapUnitsPPY-map.Scale.mapOffset.y}};
Map.Scale.prototype.getMapCoordinateOfLatLon=function(b,d){var e;if("Mercator"==this.szMapProjection)e=_LLtoMercator(b,d);else if("feet"==this.szMapUnits||"meter"==this.szMapUnits||"meters"==this.szMapUnits){if(!this.szDatum&&!this.szUTMZone)return null;e=_LLtoUTM(this.szDatum,b,d,this.szUTMZone);this.nFalseEasting&&(e.x+=this.nFalseEasting-5E5);e.y+=this.nFalseNorthing+this.nCorrectNorthing;e.x+=this.nCorrectEasting;e.y+=this.nCorrectNorthing}return e};
Map.Scale.prototype.getGeoCoordinateOfPoint=function(b,d){if("Mercator"==this.szMapProjection)return _MercatortoLL(d,b);if("feet"!=this.szMapUnits&&"meter"!=this.szMapUnits&&"meters"!=this.szMapUnits)return new point(b,d);if(!this.szDatum&&!this.szUTMZone)return null;var e=new point(b,d);this.nFalseEasting&&(e.x-=this.nFalseEasting-5E5);e.y-=this.nFalseNorthing+this.nCorrectNorthing;e.x-=this.nCorrectEasting;e.y-=this.nCorrectNorthing;return _UTMtoLL(this.szDatum,e.y,e.x,this.szUTMZone)};
Map.Scale.prototype.getMapPosition=function(b,d){var e=getMatrix(this.zoomNode),f=e[0],g=e[3],h=antiZoomAndPanList.getActualMatrix();b=b*h[0]+h[4];d=d*h[3]+h[5];b=b-this.mapPosition.x-this.mapOffset.x;d=d-this.mapPosition.y-this.mapOffset.y;b=(b-e[4])/f;d=(d-e[5])/g;return new point(b,d)};
Map.Scale.prototype.clipWidgetPositionToMap=function(b){b.x>=this.mapPosition.x+this.bBox.width&&(b.x=this.mapPosition.x+this.bBox.width);b.x<=this.mapPosition.x&&(b.x=this.mapPosition.x);b.y>=this.mapPosition.y+this.bBox.height&&(b.y=this.mapPosition.y+this.bBox.height);b.y<=this.mapPosition.y&&(b.y=this.mapPosition.y);return b};
Map.Scale.prototype.isWidgetPositionInMap=function(b){return b.x>this.mapPosition.x+this.bBox.width||b.x<this.mapPosition.x||b.y>this.mapPosition.y+this.bBox.height||b.y<this.mapPosition.y?!1:!0};Map.Scale.prototype.clipWidgetObjectToMap=function(b,d,e){b=map.Dom.getBox(b);d.x+e.x+b.width>this.mapPosition.x+this.bBox.width&&(d.x-=b.width+2*e.x);d.y+e.y+b.height>this.mapPosition.y+this.bBox.height&&(d.y-=b.height+2*e.y);return new point(d.x+e.x,d.y+e.y)};
Map.Scale.prototype.clipWidgetObjectToSVG=function(b,d,e,f){f||(f=map.Dom.getBox(b));b.getAttributeNS(null,"clip-path")&&(szClipPath=b.getAttributeNS(null,"clip-path"),szClipPath.match(/url/)&&(szClipPath=szClipPath.substr(5,szClipPath.length-6),b=SVGDocument.getElementById(szClipPath)))&&(b=b.firstChild,f.x=Number(b.getAttributeNS(null,"x")),f.y=Number(b.getAttributeNS(null,"y")),f.width=Number(b.getAttributeNS(null,"width")),f.height=Number(b.getAttributeNS(null,"height")));b=new point(d.x+e.x,
d.y+e.y);b.x+f.width>this.viewBox.width&&(b.x=d.x-f.width-e.x);0>b.x&&(b.x=map.Scale.normalX(5),0>=e.y&&(b.y-=e.y,e.y=map.Scale.normalY(20),b.y+=e.y));b.y+f.height>this.viewBox.height&&(b.y=d.y-f.height-e.y);0>b.y&&(b.y=map.Scale.normalX(5));return b};
Map.Scale.prototype.getEmbedWidth=function(){if("undefined"!=typeof HTMLDocument&&null!=HTMLDocument)try{var b=HTMLDocument.embeds[szEmbedName].clientWidth,d=b/HTMLDocument.embeds[szEmbedName].clientHeight,e=SVGWidth/SVGHeight;return d<e?b:e/d*b}catch(f){return SVGWidth}return fSVGEmbeded&&fEmbedScale?-1!=EmbedWidth.indexOf("%")?document.embeds.svgMain.clientWidth:EmbedWidth:fPDFEmbed?(d=window.innerWidth/window.innerHeight,e=SVGWidth/SVGHeight,d<e?window.innerWidth:e/d*window.innerWidth):SVGWidth};
Map.Scale.prototype.getEmbedHeight=function(){if("undefined"!=typeof HTMLDocument&&null!=HTMLDocument)try{var b=HTMLDocument.embeds[szEmbedName].clientHeight,d=HTMLDocument.embeds[szEmbedName].clientWidth/b,e=SVGWidth/SVGHeight;return e<d?b:d/e*b}catch(f){return SVGHeight}return fSVGEmbeded&&fEmbedScale?-1!=EmbedHeight.indexOf("%")?document.embeds.svgMain.clientHeight:EmbedHeight:fPDFEmbed?(d=window.innerWidth/window.innerHeight,e=SVGWidth/SVGHeight,e<d?window.innerHeight:d/e*window.innerHeight):
SVGHeight};Map.Scale.prototype.getEmbedScale=function(){if("undefined"!=typeof HTMLDocument&&null!=HTMLDocument)try{var b=HTMLDocument.embeds[szEmbedName].clientWidth,d=HTMLDocument.embeds[szEmbedName].clientHeight,e=SVGWidth/SVGHeight;return e<b/d?d/SVGHeight:b/SVGWidth}catch(f){return 1}return fPDFEmbed?(b=window.innerWidth/window.innerHeight,e=SVGWidth/SVGHeight,e<b?window.innerHeight/SVGHeight:window.innerWidth/SVGWidth):1};
Map.Scale.prototype.getTrueMapScale=function(){return fAdaptMapScaleToSize?this.nMapScale/this.getEmbedScale()*this.nPPI/this.nMapPPI:this.nMapScale*this.nPPI/this.nMapPPI};Map.Scale.prototype.normalX=function(b){return b*this.nScaleX};Map.Scale.prototype.normalY=function(b){return b*this.nScaleY};Map.Scale.prototype.embedX=function(b){return b/this.nScaleX};Map.Scale.prototype.embedY=function(b){return b/this.nScaleY};
Map.Scale.prototype.scaleX=function(b){return b/SVGRootElement.currentScale*this.viewBox.width/this.getEmbedWidth()};Map.Scale.prototype.scaleY=function(b){return b/SVGRootElement.currentScale*this.viewBox.height/this.getEmbedHeight()};Map.Scale.prototype.toSVGx=function(b){return this.scaleX(b*SVGRootElement.currentScale-SVGRootElement.currentTranslate.x)+this.viewBox.x};Map.Scale.prototype.toSVGy=function(b){return this.scaleY(b*SVGRootElement.currentScale-SVGRootElement.currentTranslate.y)+this.viewBox.y};
Map.Scale.prototype.toScreenX=function(b){return(b-this.scaleX(-SVGRootElement.currentTranslate.x)+Number(viewBox[0]))/SVGRootElement.currentScale/viewBoxScale};Map.Scale.prototype.toScreenY=function(b){return(b-this.scaleY(-SVGRootElement.currentTranslate.y)+Number(viewBox[3]))/SVGRootElement.currentScale/viewBoxScale};Map.Scale.prototype.toMapX=function(b){return(b-this.scaleX(-SVGRootElement.currentTranslate.x)+Number(viewBox[0]))/SVGRootElement.currentScale/viewBoxScale};
Map.Scale.prototype.toMapY=function(b){return(b-this.scaleY(-SVGRootElement.currentTranslate.y)+Number(viewBox[3]))/SVGRootElement.currentScale/viewBoxScale};Map.Scale.prototype.getSVGOffset=function(b){var d=b;"svg"!=d.nodeName&&(d=map.Dom.getParentByNodename(b,"svg"));return d&&d!=SVGRootElement&&(b=d.getAttribute("viewBox").split(" "),4==b.length)?new point(Number(b[0]),Number(b[1])):new point(0,0)};
Map.Scale.prototype.getGroupOffset=function(b){var d=null,e=new point(0,0);if(b)for(;d=b.parentNode;){if(d==map.Zoom.zoomNode||1!=d.nodeType)return e;b=getMatrix(d);e.x=e.x*b[0]+b[4];e.y=e.y*b[3]+b[5];b=d}return new point(0,0)};Map.Scale.prototype.getGroupScale=function(b){var d=new point(1,1);for(b=b.parentNode;b&&1==b.nodeType;){var e=getScale(b);e&&(d.x*=e.x,d.y*=e.y);b=b.parentNode}return d};
Map.Scale.prototype.getMapOffset=function(b){var d=this.getSVGOffset(b);b=this.getGroupOffset(b);return new point(-d.x+b.x,-d.y+b.y)};
Map.Scale.prototype.getScreenPosition=function(b){var d=this.getSVGOffset(b),e=this.getGroupOffset(b),f=getTranslate(b);if(b=map.Dom.getBox(b))f.x+=b.x+b.width/2,f.y+=b.y+b.height/2;b=antiZoomAndPanList.getActualMatrix();var g=getMatrix(this.zoomNode),f=map.Scale.rotatePoint(f,-1);return new point((this.mapPosition.x+this.mapOffset.x+g[4]+(f.x-d.x+e.x)*g[0]-b[4])*b[0],(this.mapPosition.y+this.mapOffset.y+g[5]+(f.y-d.y+e.y)*g[3]-b[5])*b[3])};
Map.Scale.prototype.getClientMousePosition=function(b,d){var e=null;if(b){var f=fEmbedScale;fEmbedScale=!0;if(d&&antiZoomAndPanList&&antiZoomAndPanList.isContained(d)){var e=new point(this.normalX(b.clientX),this.normalY(b.clientY)),g=new point(this.getEmbedScale(),this.getEmbedScale());e.x/=g.x;e.y/=g.y}else e=new point(this.toSVGx(b.clientX),this.toSVGy(b.clientY));d&&(g=map.Scale.getGroupScale(d),e.x/=g.x,e.y/=g.y);fEmbedScale=f}return e};
Map.Scale.prototype.refreshCSSStyles=function(){this.fCSSStyleNodeChanged&&(this.CSSStyleNodes.parentNode.parentNode.appendChild(this.CSSStyleNodes.parentNode),this.fCSSStyleNodeChanged=!1)};Map.Scale.prototype.normalizeSymbols=function(b){1==this.featureScaling_lastScale&&this.normalizeElements(b,/symbol/,nNormalSymbolSize);this.nSymbolSize=nNormalButtonSize};
Map.Scale.prototype.normalizeButtons=function(b){this.normalizeElements(b,/button/,nNormalButtonSize);this.normalizeElements(b,/icon/,nNormalButtonSize);this.nButtonSize=nNormalButtonSize};
Map.Scale.prototype.normalizeElements=function(b,d,e){if(b){var f=b.getElementsByTagName("g");b=[];for(var g=0;g<f.length;g++)b[g]=f.item(g);for(g=0;g<b.length;g++){var f=b[g],h=f.getAttributeNS(null,"id");if(h&&h.match(d)){var k=SVGDocument.getElementById(h);k&&k!=f&&k.parentNode.removeChild(k);f.fu=new Methods(f);k=map.Dom.getBox(f);0==k.width&&(k=map.Dom.constructNode("use",SVGTempGroup,{"xlink:href":"#"+h}),k=map.Dom.getBox(k));var l=this.normalX(e)/k.height;f.fu.setPosition((-k.x-k.width/2)*
l,(-k.y-k.height/2)*l);f.fu.scale(l,l);szViewer.match(/Firefox/i)&&(f.setAttributeNS(null,"id",""),k=map.Dom.newGroup(f.parentNode),k=f.parentNode.insertBefore(k,f),k.appendChild(f),k.setAttributeNS(null,"id",h))}}}map.Dom.clearGroup(SVGTempGroup)};
Map.Scale.prototype.changeRotation=function(b,d){var e=getRotateAttributeValue(map.Scale.canvasNode),e=(360+Number(e)+Number(d))%360;setRotate(map.Scale.canvasNode,e);map.Layer.setObjectRotate(b,-e);map.Layer.setPatternRotate(b,-e);map.Layer.setLabelRotate(b,-e)};
Map.Scale.prototype.setRotation=function(b,d){d=Math.floor(d);setRotate(map.Scale.canvasNode,d);map.Layer.setSymbolRotate(b,-d);map.Layer.setObjectRotate(b,-d);map.Layer.setPatternRotate(b,-d);map.Layer.setLabelRotate(b,-d);map.Themes&&map.Themes.resortCharts();map.Dom.clearGroup(SVGToolsGroup);map.Dom.clearGroup(SVGFixedGroup);map.removeAllHighlights()};
Map.Scale.prototype.rotatePoint=function(b,d){var e=getRotateAttributeValue(map.Scale.canvasNode)/180*Math.PI;if(e){-1==d&&(e=-e);var f=b.x,g=b.y;b.x=f*Math.cos(e)+g*Math.sin(e);b.y=-f*Math.sin(e)+g*Math.cos(e)}return b};
Map.Scale.prototype.createWidgetStyles=function(){"string"!=typeof szContainerTitle&&(szContainerTitle="font-family:arial;font-size:12px;fill:#444444;pointer-events:none;");"string"!=typeof szInfoContainerTitle&&(szInfoContainerTitle=szContainerTitle);"string"!=typeof szDescription&&(szDescription="font-family:arial;font-size:10px;fill:#888888;font-weight:bold;font-style:italic;pointer-events:none;");"string"!=typeof szSnippet&&(szSnippet="font-family:arial;font-size:11px;fill:#555555;;pointer-events:none;");
"string"!=typeof szSummary&&(szSummary="font-family:arial;font-size:10px;fill:#444444;pointer-events:none;");"string"!=typeof szNote&&(szNote="font-family:arial;font-size:11px;fill:darkgrey;font-style:italic;stroke:none;pointer-events:none;");"string"!=typeof szValues&&(szValues="font-family:arial;font-size:10px;fill:#798697;font-style:normal;stroke:none;pointer-events:none;");this.tStyle={};this.tStyle.ContainerTitle=this.createTextObject(szContainerTitle);this.tStyle.InfoContainerTitle=this.createTextObject(szInfoContainerTitle);
this.tStyle.Description=this.createTextObject(szDescription);this.tStyle.Snippet=this.createTextObject(szSnippet);this.tStyle.Summary=this.createTextObject(szSummary);this.tStyle.Note=this.createTextObject(szNote);this.tStyle.Values=this.createTextObject(szValues)};Map.Scale.prototype.createTextObject=function(b){nFontHeight=this.normalY(10);var d={};d.szStyle=__scaleStyleString(b,this.normalY(1));d.nFontHeight=__getFontHeightfromStyleString(d.szStyle);return d};
Map.Scale.prototype.getScaleParam=function(){var b={};this.nFeatureScaling&&1!=this.nFeatureScaling&&(b.featureScaling=this.nFeatureScaling);this.nBorderScaling&&1!=this.nBorderScaling&&(b.borderScaling=this.nBorderScaling);this.nLineScaling&&1!=this.nLineScaling&&(b.lineScaling=this.nLineScaling);this.nObjectScaling&&1!=this.nObjectScaling&&(b.objectScaling=this.nObjectScaling);this.nLabelScaling&&1!=this.nLabelScaling&&(b.labelScaling=this.nLabelScaling);this.nNormalSizeScale&&1!=this.nNormalSizeScale&&
(b.normalSizeScale=this.nNormalSizeScale);this.nDynamicScalePow&&3!=this.nDynamicScalePow&&(b.dynamicScalePow=this.nDynamicScalePow);return b};
Map.Scale.prototype.setScaleParam=function(b){var d=this.featureScaling_lastScale;b.featureScaling&&1!=b.featureScaling&&(this.nFeatureScaling=b.featureScaling);b.borderScaling&&1!=b.borderScaling&&(this.nBorderScaling=b.borderScaling);b.lineScaling&&1!=b.lineScaling&&(map.Layer.changeLineScaling(null,b.lineScaling/this.nLineScaling),this.featureScaling_lastScale=d);b.labelScaling&&1!=b.labelScaling&&(map.Layer.changeLabelScaling(null,b.labelScaling/this.nLabelScaling),this.featureScaling_lastScale=
d);b.objectScaling&&1!=b.objectScaling&&(this.nObjectScaling=b.objectScaling);b.normalSizeScale&&1!=b.normalSizeScale&&(this.nNormalSizeScale=Number(b.normalSizeScale));b.dynamicScalePow&&3!=b.dynamicScalePow&&(this.nDynamicScalePow=Number(b.dynamicScalePow))};matrixRegExp=/matrix\(([^,]*)\)/;matrixRegExp1=/matrix\(([^,]*)\)/;matrixRegExp2=/matrix\(([0-9., -e]*)\)/;translateRegExp1=/translate\(([^,]*)\)/;translateRegExp2=/translate\(([0-9., -e]*)\)/;rotateRegExp=/rotate\(([0-9]*)\)/;urlRegExp=/url\(#([a-zA-Z0-9\-\.\_\:]*)\)/;
function getMatrix(b){if(b){b=b.getAttribute("transform");var d=null;if(b&&(d=b.match(matrixRegExp1)))return b=d[1].split(" "),[Number(b[0]),Number(b[1]),Number(b[2]),Number(b[3]),Number(b[4]),parseFloat(b[5])];if(b&&(d=b.match(matrixRegExp2)))return b=d[1].split(","),[Number(b[0]),Number(b[1]),Number(b[2]),Number(b[3]),Number(b[4]),Number(b[5])]}return[1,0,0,1,0,0]}
function setMatrix(b,d,e){if(b&&6==d.length){var f=!0;d.forEach(function(b){isNaN(b)&&(f=!1)});if(f){var g=b.getAttributeNS(null,"transform");d="matrix("+d[0]+" "+d[1]+" "+d[2]+" "+d[3]+" "+d[4]+" "+d[5]+")";for(var g=g?g.split(")"):[],h=0;h<g.length;h++)3<g[h].length&&(g[h].match(/rotate/)||g[h].match(/scale/)||e&&g[h].match(/translate/))&&(d=d+" "+g[h]+")");b.setAttributeNS(null,"transform",d)}}}
function getTranslate(b){return b?(b=getMatrix(b),new point(Number(b[4]),Number(b[5]))):new point(0,0)}function setTranslate(b,d,e){var f=getMatrix(b);f[4]=d;f[5]=e;setMatrix(b,[f[0],f[1],f[2],f[3],f[4],f[5]])}
function getTranslateAttributeValue(b){if(b){b=b.getAttributeNS(null,"transform");var d=null;if(b&&(d=b.match(translateRegExp1)))return b=d[1].split(" "),new point(Number(b[0]),parseFloat(b[1]));if(b&&(d=b.match(translateRegExp2)))return b=d[1].split(","),new point(Number(b[0]),Number(b[1]))}return new point(0,0)}function getScale(b){return b?(b=getMatrix(b),new point(Number(b[0]),Number(b[3]))):new point(1,1)}
function setScale(b,d,e){if(b){var f=getMatrix(b);f[0]=d;f[3]=e;setMatrix(b,[f[0],f[1],f[2],f[3],f[4],f[5]],!0)}}function getRotateAttributeValue(b,d){d||(d="transform");if(b){var e=b.getAttributeNS(null,d),f=null;if(e&&(f=e.match(rotateRegExp)))return Number(f[1])}return 0}
function setRotate(b,d,e){e||(e="transform");if(b){for(var f=!1,g="",h=b.getAttributeNS(null,e),h=h?h.split(")"):[],k=0;k<h.length;k++)h[k].match(/rotate/)?(g=g+" rotate("+d+")",f=!0):3<h[k].length&&(g=g+" "+h[k]+")");f||(g=g+" rotate("+d+")");b.setAttributeNS(null,e,g)}}
function getPatternMatrix(b){if(b){if((b=b.getAttribute("patternTransform"))&&(b=b.match(matrixRegExp1)))return b=b[1].split(" "),[Number(b[0]),Number(b[1]),Number(b[2]),Number(b[3]),Number(b[4]),Number(b[5])];if(b&&(b=b.match(matrixRegExp2)))return b=b[1].split(","),[Number(b[0]),Number(b[1]),Number(b[2]),Number(b[3]),Number(b[4]),Number(b[5])]}return[1,0,0,1,0,0]}function point(b,d){this.x=b;this.y=d}
function box(b,d,e,f){this.x=Number(b);this.y=Number(d);this.width=Number(e);this.height=Number(f)}box.prototype.scale=function(b){var d=this.width*b;b*=this.height;this.x-=(d-this.width)/2;this.y-=(b-this.height)/2;this.width=d;this.height=b};box.prototype.check=function(){return isNaN(x)||isNaN(y)||isNaN(width)||isNaN(height)?!1:!0};function __boxDup(b){return new box(b.x,b.y,b.width,b.height)}Map.Dom.prototype.getBox=function(b){try{return __boxDup(b.getBBox())}catch(d){return new box(0,0,0,0)}};
function MapObject(b){if(1!=b.nodeType)return null;for(this.szId="";""==this.szId&&b.parentNode&&1==b.nodeType;)if(this.szId=b.getAttributeNS(null,"id"),"string"!=typeof this.szId||""==this.szId||this.szId.match(/noobject/))b=b.parentNode,this.szId="";this.objNode=b;this.fu=new Methods(b)}MapObject.prototype.getContextMenuId=function(){for(var b=null,b=this.objNode;b;b=b.parentNode)if(1==b.nodeType){var d=b.getAttributeNS(szMapNs,"menu");if(d&&d.length)return d}return null};
MapObject.prototype.setContextMenuId=function(b){this.objNode.setAttributeNS(szMapNs,"menu",b)};function Methods(b){this.nodeObj=b}Methods.prototype.setMatrix=function(b){setMatrix(this.nodeObj,b)};Methods.prototype.getPosition=function(){var b=getMatrix(this.nodeObj);return new point(Number(b[4]),Number(b[5]))};Methods.prototype.setPosition=function(b,d){var e=getMatrix(this.nodeObj);e[4]=b;e[5]=d;setMatrix(this.nodeObj,[e[0],e[1],e[2],e[3],e[4],e[5]])};
Methods.prototype.scale=function(b,d){var e=getMatrix(this.nodeObj);e[0]=b;e[3]=d;setMatrix(this.nodeObj,[e[0],e[1],e[2],e[3],e[4],e[5]])};Methods.prototype.scaleBy=function(b,d){var e=this.getBox(),f=e.width/2+e.x,e=e.height/2+e.y,g=getMatrix(this.nodeObj);g[0]*=b;g[3]*=d;1<b?(g[4]-=f*b-f,g[5]-=e*d-e):(g[4]-=f-f/b,g[5]-=e-e/d);setMatrix(this.nodeObj,[g[0],g[1],g[2],g[3],g[4],g[5]])};Methods.prototype.getScale=function(){var b=getMatrix(this.nodeObj);return new point(Number(b[0]),Number(b[3]))};
Methods.prototype.getParentScale=function(){var b=getMatrix(this.nodeObj.parentNode);return new point(Number(b[0]),Number(b[3]))};Methods.prototype.getGroupScale=function(){return map.Scale.getGroupScale(this.nodeObj)};Methods.prototype.scaleTo=function(b,d){var e=this.getBox();b&&d?this.scaleBy(b/e.width,d/e.height):b?this.scaleBy(b/e.width,b/e.width):d&&this.scaleBy(d/e.height,d/e.height)};
Methods.prototype.getBox=function(){var b=map.Dom.getBox(this.nodeObj),d=this.getScale(),b=new box(b.x,b.y,b.width,b.height);b.x*=d.x;b.y*=d.y;b.width*=d.x;b.height*=d.y;return b};Methods.prototype.getTextLength=function(){return"text"==this.nodeObj.nodeName?this.nodeObj.getComputedTextLength():0};Methods.prototype.focus=function(b,d,e){setMatrix(this.nodeObj,[e,0,0,e,Number(b*e),Number(d*e)])};Methods.prototype.clear=function(){map.Dom.clearGroup(this.nodeObj)};
Methods.prototype.isContained=function(b){for(;b=b.parentNode;)if(b==this.nodeObj)return!0;return!1};Methods.prototype.extendAllIds=function(b){map.Dom.extendAllIds(objNode,b)};Map.CSS=function(b){this.stylesA=[];b=b.firstChild.nextSibling.nodeValue.split("}");for(var d=0;d<b.length;d++){var e=b[d].split("{")[0],e=e.split(".")[1];this.stylesA[e]=__getStyleArray(b[d].split("{")[1])}};
Map.CSS.prototype.getStyleString=function(){var b="";for(a in this.stylesA){b+=" ."+a+"{";for(s in this.stylesA[a])b+=s+":"+this.stylesA[a][s]+";";b+="}"}return b};Map.CSS.prototype.setStyle=function(b,d,e){try{this.stylesA[b][d]=e}catch(f){}};
function __scaleStyleString(b,d){if(!b||!d)return null;for(var e=b.split(";"),f=null,g=0;g<e.length;g++)if(e[g].match(/stroke-width/))f=e[g].split(":"),f[1]=String(parseFloat(f[1])*d),e[g]=f.join(":");else if(e[g].match(/font-size/))f=e[g].split(":"),f[1]=String(parseFloat(f[1])*d)+"px",e[g]=f.join(":");else if(e[g].match(/stroke-dashoffset/))f=e[g].split(":"),f[1]=String(parseFloat(f[1])*d),e[g]=f.join(":");else if(e[g].match(/stroke-dasharray/)){var f=e[g].split(":"),h=f[1].split(",");1<h.length||
(h=f[1].split(" "));e[g]=f[0]+":";for(f=0;f<h.length;f++)h[f]=String(parseFloat(h[f])*d),e[g]+=h[f],f<h.length-1&&(e[g]+=",")}return e.join(";")}
function __scaleLineStyleString(b,d){if(!b||!d)return null;for(var e=b.split(";"),f=null,g=0;g<e.length;g++)if(e[g].match(/stroke-width/))f=e[g].split(":"),f[1]=String(parseFloat(f[1])*d),e[g]=f.join(":");else if(e[g].match(/stroke-dashoffset/))f=e[g].split(":"),f[1]=String(parseFloat(f[1])*d),e[g]=f.join(":");else if(e[g].match(/stroke-dasharray/)){var f=e[g].split(":"),h=f[1].split(",");1<h.length||(h=f[1].split(" "));e[g]=f[0]+":";for(f=0;f<h.length;f++)h[f]=String(parseFloat(h[f])*d),e[g]+=h[f],
f<h.length-1&&(e[g]+=",")}return e.join(";")}function __scaleTextStyleString(b,d){if(!b||!d)return null;for(var e=b.split(";"),f=null,g=0;g<e.length;g++)e[g].match(/font-size/)&&(f=e[g].split(":"),f[1]=String(parseFloat(f[1])*d)+"px",e[g]=f.join(":"));return e.join(";")}function __getFontHeightfromStyleString(b){if(!b)return-1;b=b.split(";");for(var d=0;d<b.length;d++)if(b[d].match(/font-size/))return styleA=b[d].split(":"),parseFloat(styleA[1]);return-1}
var __idSetRotationTimeout=null,__nOldAngle=0;function __setRotation(b,d){d!=__nOldAngle&&(__nOldAngle=d,__idSetRotationTimeout&&clearTimeout(__idSetRotationTimeout),__idSetRotationTimeout=setTimeout("__doSetRotation("+d+")",200))}function __doSetRotation(b){executeWithMessage("map.Scale.setRotation(null,"+b+")","...");__idSetRotationTimeout=null}function AntiZoomAndPan(b){this.listA=[];this.buildList(b)}AntiZoomAndPan.prototype.addGroup=function(b){this.listA[this.listA.length]=b};
AntiZoomAndPan.prototype.buildList=function(b){b=SVGRootElement.childNodes;for(var d=0;d<b.length;d++)try{"1"==b.item(d).nodeType&&b.item(d).getAttributeNS(null,"id").match(/antizoomandpan/)&&this.addGroup(b.item(d))}catch(e){}};AntiZoomAndPan.prototype.isContained=function(b){for(;b;){if(this.checkGroup(b))return!0;b=b.parentNode}return!1};AntiZoomAndPan.prototype.checkGroup=function(b){for(var d=0;d<this.listA.length;d++)if(b==this.listA[d])return!0;return!1};
AntiZoomAndPan.prototype.adjustGroups=function(b){if(fAntiZoomAndPan){b=SVGRootElement.getAttribute("viewBox").split(" ");for(var d=SVGOrigViewBoxString.split(" "),d=Number(d[2])/Number(b[2]),e,f=0;f<this.listA.length;f++){var g=this.listA[f];if(e=getMatrix(g))e[0]=1/SVGRootElement.currentScale/d,e[3]=1/SVGRootElement.currentScale/d,e[4]=map.Scale.scaleX(-SVGRootElement.currentTranslate.x)+Number(b[0]),e[5]=map.Scale.scaleY(-SVGRootElement.currentTranslate.y)+Number(b[1]),setMatrix(g,e)}}};
AntiZoomAndPan.prototype.getActualMatrix=function(b){return getMatrix(this.listA[0])};AntiZoomAndPan.prototype.setDisplay=function(b,d){for(var e=0;e<this.listA.length;e++)this.listA[e].style.setProperty("display",d,"")};
AntiZoomAndPan.prototype.initAntiZoomPattern=function(b,d){null==d&&(d=SVGDocument);b&&(d=b.target.ownerDocument);var e=d.getElementsByTagName("pattern");if(null!=e&&0!=e.length){for(var f=e.length,g=e.item(0).parentNode,h,k=0;k<f;k++)e.item(k).getAttributeNS(null,"id").match(/antizoomandpan/)||(h=e.item(k).cloneNode(1E3),h.setAttributeNS(null,"id",h.getAttributeNS(null,"id")+":antizoomandpan"),g.appendChild(h));g.parentNode.appendChild(g)}};
AntiZoomAndPan.prototype.initAntiZoomSymbols=function(b,d){if(null!=d){var e=d.getElementsByTagName("g");if(null!=e&&0!=e.length){for(var f=e.length,g=e.item(0).parentNode,h,k=0;k<f;k++){var l=e.item(k).getAttributeNS(null,"id");l&&l.length&&l.match(/symbol/)&&!l.match(/antizoomandpan/)&&(h=e.item(k).cloneNode(1E3),h.setAttributeNS(null,"id",l+":antizoomandpan"),g.appendChild(h))}g.parentNode.appendChild(g)}}};
AntiZoomAndPan.prototype.extendAllPatternStyles=function(b,d,e){d&&1==d.nodeType&&(b=d.style.getPropertyValue("fill"))&&1<b.length&&b.match(/url/)&&(b=b.split(")")[0]+e+")",d.style.setProperty("fill",b,""))};AntiZoomAndPan.prototype.initAntiZoomStyles=function(b){var d=SVGDocument.getElementById("widgets:antizoomandpan");this.extendAllPatternStyles(b,d,":antizoomandpan")};
function activateTheme(b){if(!b.match(/:label/)&&(b=map.Tiles.getMasterId(b),_activeTheme!=b&&"mapcanvas"!=b)){var d=SVGDocument.getElementById("legend:ident:"+b);if(d){clearThemes();_legendIdent=d;if((d=_legendIdent.nextSibling.nextSibling)&&"text"==d.nodeName)try{var e=map.Dom.getBox(d);_legendIdent.setAttributeNS(null,"width",e.width+map.Scale.normalX(10))}catch(f){}_legendIdent.style.setProperty("display","inline","");_activeTheme=b;if(fActiveThemeInfo){e=new point(map.Scale.mapPosition.x,map.Scale.mapPosition.y+
map.Scale.normalX(nToolMarginTop));map.Viewport.szPopupAlignment.match(/TOP/)&&(e.y=map.Scale.bBox.height+map.Scale.mapPosition.y-map.Scale.normalY(38));e=new InfoContainer(SVGDocument,SVGMenuGroup,"movable",e,{x:map.Scale.normalX(5),y:map.Scale.normalY(5)},"fix");e.frameNode.style.setProperty("fill","#fafafa","");e.setTitle("info on");e.setOnRemove("clearThemes()");var g=map.Scale.tStyle.Description.szStyle;map.Dom.newText(e.workspaceNode,map.Scale.normalX(5),map.Scale.tStyle.Description.nFontHeight,
g,d.firstChild.nodeValue);e.reformat()}try{HTMLWindow.ixmaps.htmlgui_setActiveTheme(b)}catch(h){}try{map.Themes.redrawInfoAll(null)}catch(k){}}else{clearThemes();_removeInfo(null);_activeTheme=b;try{HTMLWindow.ixmaps.htmlgui_setActiveTheme(b)}catch(l){}try{map.Themes.redrawInfoAll(null)}catch(m){}}map.Layer.setPointerEvents(_activeTheme);_activeItem=null}}function getActiveTheme(){return _activeTheme}function isActiveTheme(b){return b==_activeTheme}
function deactivateTheme(b){isActiveTheme(b)&&clearThemes()}function clearThemes(){_legendIdent&&(_legendIdent.style.setProperty("display","none",""),_legendIdent=null);_activeTheme=null;highLightList.removeAll()}__highlightedTheme=null;
function highlightTheme(b){for(;b&&"g"!=b.objNode.nodeName&&b.objNode.parentNode;)if(null==(b=new MapObject(b.objNode.parentNode)))return;var d=b.szId;map.Tiles&&(d=map.Tiles.getMasterId(d));var e=b.objNode.getAttributeNS(szMapNs,"value");(!e||1>e.length)&&b.objNode.firstChild&&b.objNode.firstChild.nextSibling&&(e=b.objNode.firstChild.nextSibling.getAttributeNS(szMapNs,"value"));e&&e.length&&(d=d.split("::")[0]+"::"+e);if(__highlightedTheme=SVGDocument.getElementById("legend:ident:"+d))(b=__highlightedTheme.nextSibling.nextSibling)&&
"text"==b.nodeName&&(b=map.Dom.getBox(b),__highlightedTheme.setAttributeNS(null,"width",b.width+map.Scale.normalX(10))),__highlightedTheme.style.setProperty("display","inline","")}function highlightThemeRemove(){__highlightedTheme&&(__highlightedTheme.style.setProperty("display","none",""),__highlightedTheme=null)}
function displayTooltip(b,d){if(d&&1==d.nodeType){for(var e=d.getAttributeNS(szMapNs,"tooltip")||"";null!=(d=d.parentNode)&&"g"==d.nodeName;){var f=d.getAttributeNS(szMapNs,"tooltip");f&&f.length&&(e+=(e.length?String.fromCharCode(32,160):"")+f)}if(e&&e.length){try{e=map.User.onTooltipDisplay(null,e,d)}catch(g){}try{e=HTMLWindow.ixmaps.htmlgui_onTooltipDisplay(e,d)}catch(h){}f=map.Scale.getClientMousePosition(b,SVGPopupGroup);killTooltip();idTooltipTimeout=setTimeout('doDisplayTooltip("'+__stripQuotes(e)+
'",'+f.x+","+f.y+")",nTooltipTimeout);return!0}}return!1}function displayTooltipText(b,d){if(d&&d.length){var e=map.Scale.getClientMousePosition(b,SVGPopupGroup);killTooltip();idTooltipTimeout=setTimeout("doDisplayTooltip('"+__stripQuotes(d)+"',"+e.x+","+e.y+")",nTooltipTimeout)}}function __stripQuotes(b){var d=b.split('"');b=d[0];for(var e=1;e<d.length;e++)b+="``"+d[e];return b}function __encodeSingleQuote(b){var d=b.split("'");b=d[0];for(var e=1;e<d.length;e++)b+="`"+d[e];return b}
function __encodeDoubleQuotes(b){return b.replace(/\\/gi,"\\\\").replace(/\"/gi,'\\"')}function __decodeSingleQuote(b){var d=b.split("`");b=d[0];for(var e=1;e<d.length;e++)b+="'"+d[e];return b}
function doDisplayTooltip(b,d,e){idTooltipTimeout=null;if(b&&b.length&&(SVGTltipGroup.fu.clear(),d=new point(d,e),b.length)){b=map.Dictionary.getLocalText(b);e=new point(map.Scale.normalX(20),map.Scale.normalY(20));b=createTextField(SVGDocument,SVGTltipGroup,"tooltip",b);b.style.setProperty("pointer-events","none","");var f=map.Dom.getBox(b);SVGPopupGroup.hasChildNodes&&(d.y-=map.Scale.normalY(20));d.x+e.x+f.width>map.Scale.viewBox.width&&(d.x-=d.x+e.x+f.width-map.Scale.viewBox.width,d.y+=f.height);
d.y+e.y+f.height>map.Scale.viewBox.height&&(d.y-=f.height+2*e.y);b.fu.setPosition(d.x+e.x,Math.max(d.y+e.y,100));_tooltip=b}}function killTooltip(){idTooltipTimeout&&clearTimeout(idTooltipTimeout);_tooltip&&(SVGTltipGroup.fu.clear(),_tooltip=null)}Dictionary=function(){this.szDictionary=[]};map.Dictionary=new Dictionary;Dictionary.prototype.add=function(b,d){this.szDictionary[b]||(this.szDictionary[b]=d)};Dictionary.prototype.replace=function(b,d){this.szDictionary[b]=d};
Dictionary.prototype.getLocalText=function(b){try{if("undefined"!=typeof this.szDictionary[b])return String(this.szDictionary[b]);for(var d="",e=b.split(" "),f=0;f<e.length;f++)var g=this.szDictionary["'"+e[f]+"'"],d=d+String(g?g:e[f]),d=d+(f<e.length-1?" ":"");return d}catch(h){return b}};Dictionary.prototype.applyToNode=function(b){b=b.getElementsByTagName("text");for(var d=0;d<b.length;d++)b.item(d).firstChild.nodeValue=this.getLocalText(b.item(d).firstChild.nodeValue)};
var tClearMessage=null,tClearNotify=null;
function displayMessage(b,d,e){if("notify"!=e||fNotify)if("string"!=typeof b||0==b.length)SVGMessageGroup.fu.clear();else{tClearMessage&&(clearTimeout(tClearMessage),tClearMessage=null);b=map.Dictionary.getLocalText(b);if("notify"!=e)if(map.isInitializing())try{HTMLWindow.ixmaps.htmlgui_displayInfo(b);return}catch(f){}else try{if(HTMLWindow.ixmaps.htmlgui_isInfoDisplay()){HTMLWindow.ixmaps.htmlgui_displayInfo(b);return}}catch(g){}if("big"==e)var h=64,k="transparent",l=new point(map.Scale.bBox.width/
2+map.Scale.mapPosition.x,map.Scale.normalY(64));else"notify"==e?(h=24,k="flat",l=new point(map.Scale.bBox.width/2+map.Scale.mapPosition.x,map.Scale.mapPosition.y+(map.Scale.normalY(2*h/3)+nToolMarginTop))):"top"==e?(h=24,k="flat",l=new point(map.Scale.bBox.width/2+map.Scale.mapPosition.x,map.Scale.mapPosition.y+(map.Scale.normalY(2*h/3)+nToolMarginTop))):(h=36,k="flat",l=new point(map.Scale.bBox.width/2+map.Scale.mapPosition.x,map.Scale.bBox.height/2+map.Scale.mapPosition.y-map.Scale.normalX(h/2)));
if(SVGDocument&&SVGMessageGroup&&("notify"==e?SVGNotifyGroup.fu.clear():SVGMessageGroup.fu.clear(),b&&b.length)){var m=null;try{var p=new TextField(null,"notify"==e?SVGNotifyGroup:SVGMessageGroup,k,h);p.setText(b);var m=p.textGroup,q=m.fu.getBox();m.fu.setPosition(l.x-q.width/2,l.y+q.height/2)}catch(r){m=createTextField(SVGDocument,"notify"==e?SVGNotifyGroup:SVGMessageGroup,"popup_message",b,h);try{q=m.fu.getBox(),m.fu.setPosition(l.x-q.width/2,l.y+q.height/2)}catch(t){m.fu.setPosition(l.x-map.Scale.normalX(50),
l.y+map.Scale.normalX(10))}}}d&&("notify"==e?clearNotify(d):clearMessage(d))}}function clearMessage(b){do_clearMessage(b||0)}function do_clearMessage(b){if(b)tClearMessage&&clearTimeout(tClearMessage),tClearMessage=setTimeout("do_clearMessage()",b);else{try{HTMLWindow.ixmaps.htmlgui_killInfo()}catch(d){}SVGMessageGroup.fu.clear()}}function clearNotify(b){b?(tClearNotify&&clearTimeout(tClearNotify),tClearNotify=setTimeout("clearNotify()",b)):SVGNotifyGroup.fu.clear()}
function displayProgressBarOld(b,d,e,f,g,h){var k=new point(map.Scale.bBox.width/2+map.Scale.mapPosition.x,map.Scale.mapPosition.y+map.Scale.normalX((fMapBorder3D?6:0)+nToolMarginTop));if(SVGDocument&&SVGMessageGroup){e||(e="");e=map.Dictionary.getLocalText(e);var l=null,m=null,p=new TextField(null,SVGMessageGroup,fPDFEmbed?"":"light",13);p?(p.setText(e),l=p.textGroup,m=p.workspaceNode):m=l=createTextField(SVGDocument,SVGMessageGroup,"popup_message",e,24);var q=100/d,r=13*e.length/2,t=e.length?-9.36:
0;if(e.length){var u=map.Dom.getBox(m);u.width&&(r=u.width+10)}map.Dom.newShape("rect",m,r,t,d*q,13,"fill:none;stroke:grey;");map.Dom.newShape("rect",m,r,t,b*q,13,"fill:#3787D7;stroke:none;");g&&(buttonObj=new Button(m,"","BUTTON","#delete_button",g,"","cancel operation"),buttonObj.scale(1/map.Scale.normalX(1),1/map.Scale.normalY(1)),buttonObj.setPosition(r+100+20,-3));h&&b&&(e=map.Dictionary.getLocalText("done")+" "+b+" "+map.Dictionary.getLocalText("/")+" "+d+" "+map.Dictionary.getLocalText("in")+
" "+__formatTime(h)+" ",e+=map.Dictionary.getLocalText("estimated time left")+": "+__formatTime(h/b*d-h),map.Dom.newText(m,0,15.6,"font-family:arial;font-size:13px;fill:gray;",e));p&&p.resizeField();try{u=l.fu.getBox(),l.fu.setPosition(k.x-u.width/2,k.y+map.Scale.normalY(13*1.3))}catch(v){}}f&&clearMessage(f)}
function displayProgressBar(b,d,e,f,g,h){SVGDocument&&SVGMessageGroup&&(e=map.Dom.newGroup(SVGMessageGroup,"popup_progressbar"),e.fu.setPosition(0,0),e.fu.scale(20,20),map.Dom.newShape("rect",e,0,0,SVGWidth/d*b,3,"fill:#3787D7;stroke:none;"));f&&clearMessage(f)}var debugLine=0,lastDate=new Date;
function _TRACE(b){if("undefined"!=typeof console&&"undefined"!=typeof console.log)lastDate=new Date;else if(!fPDFEmbed||fDebug)try{TRACE(b)}catch(d){if(fDebug)try{SVGDocument&&SVGMenuGroup&&(createTextField(SVGDocument,SVGMenuGroup,"message",b).fu.setPosition(map.Scale.normalX(0),map.Scale.normalY(18*debugLine)),20<++debugLine&&(debugLine=0,SVGMenuGroup.fu.clear()))}catch(e){}}}
function _LOG(b){if("undefined"!=typeof console&&"undefined"!=typeof console.log){var d=new Date,d=d.getMinutes()+":"+String(d.getSeconds())+"."+String(d.getMilliseconds());console.log("_LOG: time["+d+"] "+b)}}
function _STATUS(b){if(fStatus){var d=map.Dom.getObjectById("legend:statusgroup");d||(d=map.Dom.getObjectById("legend:scalegroup"),d=map.Dom.newGroup(d,"legend:statusgroup"));map.Dom.clearGroup(d);map.Dom.newText(d,map.Scale.normalX(220),map.Scale.normalY(12),"font-family:arial;font-size:"+map.Scale.normalY(12)+"px;fill:black",b)}}
function _INFO(b){try{HTMLWindow.ixmaps.htmlgui_displayInfo(b)}catch(d){fDebug&&SVGDocument&&SVGMessageGroup&&createTextField(SVGDocument,SVGMessageGroup,"message",b).fu.setPosition(map.Scale.normalX(0),map.Scale.normalY(0))}}function _KILLINFO(){try{HTMLWindow.ixmaps.htmlgui_killInfo()}catch(b){}}
function _ERROR(b){try{HTMLWindow.ixmaps.htmlgui_errorLog(b)}catch(d){fDebug&&SVGDocument&&SVGMessageGroup&&createTextField(SVGDocument,SVGMessageGroup,"message",b).fu.setPosition(map.Scale.normalX(0),map.Scale.normalY(0))}}var __textField_group=null,__textField_frame=null,__textField_shadow=null,__textField_fontheight=12;
function createTextField(b,d,e,f,g){g||(g=12);if(b&&d)return b=map.Dom.newGroup(d,e),d=map.Dom.newShape("rect",b,1,1,1,1,"fill:#444444;opacity:0.5;stroke:none"),e=map.Dom.newShape("rect",b,1,1,1,1,"fill:#fefeff;stroke:#444444;stroke-width:"+map.Scale.normalX(.2)+""),map.Dom.newText(b,0,map.Scale.normalY(1.25*g),"font-family:arial;font-size:"+map.Scale.normalY(g)+"px;fill:"+szInfoBodyColor+"",f),__textField_group=b,__textField_frame=e,__textField_shadow=d,__textField_fontheight=g,sizeTextField(),b}
function sizeTextField(){var b=__textField_fontheight,d=map.Dom.getBox(__textField_group);__textField_frame.setAttributeNS(null,"rx",map.Scale.normalX(2));__textField_frame.setAttributeNS(null,"ry",map.Scale.normalX(2));__textField_frame.setAttributeNS(null,"x",-map.Scale.normalX(.75*b));__textField_frame.setAttributeNS(null,"y",-map.Scale.normalY(1));__textField_frame.setAttributeNS(null,"width",d.width+map.Scale.normalX(1.5*b));__textField_frame.setAttributeNS(null,"height",d.height+map.Scale.normalY(b)/
2);__textField_shadow.setAttributeNS(null,"rx",map.Scale.normalX(4));__textField_shadow.setAttributeNS(null,"ry",map.Scale.normalX(4));__textField_shadow.setAttributeNS(null,"x",-map.Scale.normalX(.75*b)+map.Scale.normalX(2));__textField_shadow.setAttributeNS(null,"y",map.Scale.normalY(2));__textField_shadow.setAttributeNS(null,"width",d.width+map.Scale.normalX(1.5*b)+map.Scale.normalX(1.5));__textField_shadow.setAttributeNS(null,"height",d.height+map.Scale.normalX(b)/2-map.Scale.normalX(0))}
function executeWithMessage(b,d,e){fExecuteSilent||("undefined"==typeof e&&(e=250),displayMessage(d,null,szMessagePosition));setTimeout('doExecuteWithMessage("'+__encodeDoubleQuotes(b)+'")',e)}function doExecuteWithMessage(b){map.isIdle()&&clearMessage(250);try{eval(b)}catch(d){alert("error '"+d+"' on: "+b)}}function executeWithProgressBar(b,d,e,f,g,h){displayProgressBar(d,e,f,0,g,h);setTimeout(b,1)}
function __doGetPolygonSurface(b,d){for(a in b){if(d)var e=map.Scale.getMapPosition(b[a].x,b[a].y),e=map.Scale.getMapCoordinate(e.x,e.y),e=map.Scale.getGeoCoordinateOfPoint(e.x,e.y),e=_LLtoUTM("WGS84",e.y,e.x);else e=map.Scale.getMapCoordinateUTM(b[a].x,b[a].y);b[a].x=e.x;b[a].y=e.y}var f=e=0;b[b.length]=b[0];for(i=0;i<b.length-1;i++)f=b[i].x*b[i+1].y-b[i+1].x*b[i].y,e+=f;return e/2}
function __doGetPolygonCenter(b){var d=new point(0,0);for(a in b)d.x+=b[a].x,d.y+=b[a].y;d.x/=b.length;d.y/=b.length;return d}function __getStyleObj(b){if(null==b||2>b.length)return null;try{map.styleObj={};for(var d=b.split(";"),e=0;e<d.length;e++)if(d[e].length){var f=d[e].split(":"),g=f[0].length+1,h=d[e].substr(g,d[e].length-g);try{map.styleObj[f[0].trim()]=JSON.parse(h)}catch(k){map.styleObj[f[0].trim()]=h}}return map.styleObj}catch(l){alert("ERROR parsing: "+b)}return null}
function __getStyleArray(b){if(null==b||2>b.length)return null;try{for(var d=[],e=b.split(";"),f=0;f<e.length;f++)if(e[f].length){var g=e[f].split(":");d[g[0]]=g[1]}return d}catch(h){alert("ERROR parsing: "+b)}return null}var __timer_nMillisec=0;function __timer_reset(){__timer_nMillisec=(new Date).getTime()}function __timer_getMS(){return(new Date).getTime()-__timer_nMillisec}function __timer_getSEC(){return((new Date).getTime()-__timer_nMillisec)/1E3}
function __formatTime(b){var d=Math.floor(b/3600);b-=3600*d;var e=Math.floor(b/60);b-=60*e;return d?String(d+" hr "+e+" min "+Math.floor(b)+" sec"):e?String(e+" min "+Math.floor(b)+" sec"):String(Math.floor(b)+" sec")}
function __formatValue(b,d,e){b=Number(b);if(!isFinite(b)||!isFinite(d)||0==b)return String(b);fDecimalPointComma||(e+="|BLANK");d||(d=0);d=Math.max(0,d);if(1E-7<b&&0<d)for(;0==b.toFixed(d);)d++;b=b.toFixed(d+1);nClipDecimal=Math.pow(10,d);b=e&&e.match(/CEIL/)?Math.ceil(b*nClipDecimal)/nClipDecimal:e&&e.match(/FLOOR/)?Math.floor(b*nClipDecimal)/nClipDecimal:Math.round(b*nClipDecimal)/nClipDecimal;for(var f=String(b),f=f.match(/\./)?f.split(".")[1]:"";f.length<d;)f+="0";d=0>b?"-":"";var g="";b=Math.floor(Math.abs(b));
if(!e||!e.match(/NOBREAKS/)){for(var h=1E3;b>h;)h*=1E3;for(var h=h/1E3,k=0,l=" ";1E3<=h;)k=Math.floor(b/h),d+=__maptheme_formatpart(k,g),b%=h,h/=1E3,k&&(g="0",l=e&&e.match(/BLANK/)?" ":"."),d+=l;d+=__maptheme_formatpart(b,g);d.length&&"-"!=d||(d+="0");f.length&&(d+=(e&&e.match(/BLANK/)?".":",")+f)}return d}function __maptheme_formatpart(b,d){d||(d="");var e="";100>b&&(e+=d);10>b&&(e+=d);return e=0==b?e+d:e+String(b)}
function SVGLoader(){this.szUrlA=[];this.stackA=[];this.nPending=0;this.importSVGFile=function(b,d,e,f){if(this.szUrlA[b]==e)return!1;this.doImportSVGFile(b,d,e,f)};this.push=function(b,d,e,f){this.stackA.push({szUrl:b,svgDocument:d,targetGroup:e,callback:f})};this.pop=function(){if(!this.isWaiting()){var b=this.stackA.shift();b&&this.doImportSVGFile(b.szUrl,b.svgDocument,b.targetGroup,b.callback)}};this.doImportSVGFile=function(b,d,e,f){function g(b){this.parent=b}this.nPending++;g.prototype.operationComplete=
function(d,e,f){this.parent.nPending--;this.parent.pop();e&&200==d&&(this.processImported(e.documentElement),_LOG("SVGLoader: "+b+" (loaded)"))};g.prototype.processImported=function(d){try{d=SVGDocument.importNode(d,!0)}catch(f){}if(b.match(/widget/))for(var g=map.Dom.getAllIds(d),m=0;m<g.length;m++){var p=SVGDocument.getElementById(g[m]);p&&p.parentNode.removeChild(p)}b.match(/pattern/)&&(e=map.Dom.newGroup(e,String(Math.random())));e.appendChild(d);if(!this.initMenu(e)){this.initCSS(e);this.initScripts(e);
b.match(/widget/)&&this.initToolbar(e);b.match(/logo/)&&this.initLogo(e);this.loadScripts(e);try{antiZoomAndPanList.initAntiZoomPattern(null,e),map.Layer.initPatternScaling(evt,e)}catch(q){}b.match(/symbol/)&&map.Scale.normalizeSymbols(e);b.match(/widget/)&&map.Scale.normalizeButtons(e)}};g.prototype.initMenu=function(b){b=b.getElementsByTagName("menu");if(b.length){for(var d=0;d<b.length;d++){var e=b.item(d).getAttributeNS(null,"id");(e=SVGDocument.getElementById(e))&&e!=b.item(d)&&(e.parentNode.removeChild(e),
d--)}return!0}return!1};g.prototype.initToolbar=function(b){try{map.Toolbar.init(),map.Legend.init()}catch(d){}return!0};g.prototype.initLogo=function(b){var d=SVGDocument.getElementById("mapbackground:logo");null==d&&(d=map.Dom.newGroup(SVGDocument.getElementById("mapbackground"),"mapbackground:logo"));if(d){map.Dom.clearGroup(d);b=b.getElementsByTagName("svg").item(0).childNodes;for(var e=0;e<b.length;e++)d.appendChild(b.item(e)),e--}return!0};g.prototype.loadScripts=function(b){b=b.getElementsByTagName("script");
for(var d=0;d<b.length;d++){var e=b.item(d).getAttributeNS(szXlink,"href");e&&e.length&&(new JSLoader).loadScript(e)}return!0};g.prototype.initScripts=function(b){b=b.getElementsByTagName("script");for(var d=0;d<b.length;d++)if(b.item(d).firstChild){var e=b.item(d).firstChild.nodeValue;try{eval(e)}catch(f){_LOG("ERROR: could not eval loaded script!")}}return!0};g.prototype.initCSS=function(b){return b.getElementsByTagName("style").length?(SVGDocument.getElementById("mapstyles"),!0):!1};0<b.length&&
getData(b,new g(this))};this.isWaiting=function(){return this.nPending}}
function loadSVGIncludes(b,d,e){b=b?b.target.ownerDocument:SVGDocument;var f=b.getElementById("mapinclude");if(f){if(d&&1<d.length){var g=d.substr(d.length-1,1);"\\"!=g&&"/"!=g&&(d+="/")}f=f.getElementsByTagName("g");for(g=0;g<f.length;g++){var h=f.item(g),k=h.getAttribute("xlink:href");!k||k.match(/maplocal/)||k.match(/mapmenu/)||k.match(/mapimages/)||k.match(/mappattern/)||k.match(/mapfilter/)||!(k&&1<k.length)||e&&k!=e||(k=d+k,new SVGLoader,map.Loader.importSVGFile(k,b,h,null))}}}
var __svgLoaderTiles=null;
function SVGLoaderTiles(){this.szUrlA=[];this.stackA=[];this.nToLoad=this.nRequest=this.nPending=0;__svgLoaderTiles=this;this.importSVGFile=function(b,d,e,f){b=(map.mapRoot||"")+b;if(this.szUrlA[b]==e)return!1;this.nRequest++;this.nToLoad++;fLoadingSilent?this.doImportSVGFile(b,d,e,f):!fLoadMultiTiles&&this.isWaiting()?this.push(b,d,e,f):(displayProgressBar(0,1,map.Dictionary.getLocalText("loading map elements")),this.push(b,d,e,f),setTimeout("__svgLoaderTiles.pop()",10));return!0};this.push=function(b,
d,e,f){this.isStacked(b,d,e)||this.stackA.push({szUrl:b,svgDocument:d,targetGroup:e,callback:f})};this.pop=function(){if(!this.isWaiting()){var b=this.stackA.shift();b?(displayProgressBar(this.nToLoad-this.nPending-this.stackA.length,this.nToLoad,map.Dictionary.getLocalText("loading map elements")),this.doImportSVGFile(b.szUrl,b.svgDocument,b.targetGroup,b.callback)):(this.nToLoad=this.nRequest=0,clearMessage())}};this.isStacked=function(b,d,e){for(i=0;i<this.stackA.length;i++)if(this.stackA[i].szUrl==
b&&this.stackA[i].svgDocument==d&&this.stackA[i].targetGroup==e)return!0;return!1};this.isAnyStacked=function(){return this.stackA.length};this.doImportSVGFile=function(b,d,e,f){function g(b){this.parent=b}if(this.szUrlA[b]==e)return!1;this.szUrlA[b]=e;this.nPending++;g.prototype.operationComplete=function(d,e,f){this.parent.szUrlA[b]=null;this.parent.nPending--;this.parent.nRequest--;e&&200==d&&this.processImported(e.documentElement);this.parent.pop()};g.prototype.processImported=function(b){if(e.childNodes.length)_STATUS("Tiling: doppio tile !!!");
else{try{b=SVGDocument.importNode(b,!0)}catch(d){}e.appendChild(b);if(map&&map.Layer){for(a in map.Layer.listA){b=map.Layer.listA[a];if("undefined"!=typeof b.nState){var f=e.getAttributeNS(null,"id"),f=b.szName+"#"+f.substr(f.length-6,6);map.Layer.switchLayerByFeature(f,b.nState)}for(c in b.categoryA)f=e.getAttributeNS(null,"id"),f=b.szName+"#"+f.substr(f.length-6,6)+"::"+c,map.Layer.switchLayerByFeature(f,"inline"==b.categoryA[c].display)}fSwitchByCSS&&map.Scale.CSSStyleNodes||map.Layer.switchScaleDependentLayer(null,
e)}if(map&&map.Zoom){if(1!=map.Zoom.nZoom){b=null;b=e.getElementsByTagName("g");for(n=0;n<b.length;n++)for((f=b.item(n).getAttributeNS(null,"style"))&&f.length&&(szNewStylesValue=__scaleStyleString(f,map.Layer.nFeatureScale*map.Scale.nLineScaling),b.item(n).setAttributeNS(null,"style",szNewStylesValue),e.setAttributeNS(szMapNs,"deltaTBD","1"),e.setAttributeNS(szMapNs,"scale",String(map.Layer.nFeatureScale*map.Scale.nLineScaling))),childA=b.item(n).childNodes,c=0;c<childA.length;c++)"text"==childA.item(c).nodeName&&
(f=childA.item(c).getAttributeNS(null,"style"))&&f.length&&(szNewStylesValue=__scaleStyleString(f,map.Layer.nFeatureScale*map.Scale.nLabelScaling),childA.item(c).setAttributeNS(null,"style",szNewStylesValue));map.Layer.scaleTextOffsets(e,1/map.Zoom.nZoomX,1/map.Zoom.nZoomY,!0)}map.Layer.adaptLabel(null,e)}map&&map.Themes&&(map.Themes.addToThemeNodesCache(e),0==this.parent.nPending+this.parent.stackA.length&&map.Themes.actualizeActiveTheme(!0))}};return 0<b.length?(getData(b,new g(this)),!0):!1};this.isWaiting=
function(){return this.nPending};this.isLoading=function(){return this.nPending|this.isAnyStacked()}}var __svgLoaderMap=null;
function SVGLoaderMap(){this.szUrlA=[];this.stackA=[];this.nToLoad=this.nRequest=this.nPending=0;__svgLoaderMap=this;this.importSVGFile=function(b,d,e,f){if(e&&this.szUrlA[b]==e)return!1;this.nRequest++;this.nToLoad++;fLoadingSilent?this.doImportSVGFile(b,d,e,f):!fLoadMultiTiles&&this.isWaiting()?this.push(b,d,e,f):(displayMessage(map.Dictionary.getLocalText("loading map")),displayProgressBar(0,1,map.Dictionary.getLocalText("loading map")),this.push(b,d,e,f),setTimeout("__svgLoaderMap.pop()",10));
return!0};this.push=function(b,d,e,f){this.isStacked(b,d,e)||this.stackA.push({szUrl:b,svgDocument:d,targetGroup:e,callback:f})};this.pop=function(){if(!this.isWaiting()){var b=this.stackA.shift();b?(displayProgressBar(this.nToLoad-this.nPending-this.stackA.length,this.nToLoad,map.Dictionary.getLocalText("loading map elements")),this.doImportSVGFile(b.szUrl,b.svgDocument,b.targetGroup,b.callback)):(this.nToLoad=this.nRequest=0,clearMessage())}};this.isStacked=function(b,d,e){for(i=0;i<this.stackA.length;i++)if(this.stackA[i].szUrl==
b&&this.stackA[i].svgDocument==d&&this.stackA[i].targetGroup==e)return!0;return!1};this.isAnyStacked=function(){return this.stackA.length};this.doImportSVGFile=function(b,d,e,f){function g(b){this.parent=b}if(e&&this.szUrlA[b]==e)return!1;this.szUrlA[b]=e;this.nPending++;g.prototype.operationComplete=function(d,e,f){this.parent.szUrlA[b]=null;this.parent.nPending--;this.parent.nRequest--;e&&200==d?this.processImported(e.documentElement):displayMessage("error loading map");this.parent.pop()};g.prototype.processImported=
function(b){var d=function(b,d){d&&b?(b.parentNode.insertBefore(d,b),b.parentNode.removeChild(b)):d?SVGRootElement.appendChil(d):b&&b.parentNode.removeChild(b)};b=SVGDocument.importNode(b,!0);console.log(b);d(SVGDocument.getElementsByTagName("metadata")[2],b.getElementsByTagName("metadata")[0]);d(SVGDocument.getElementById("maplayer"),b.getElementById("maplayer"));d(SVGDocument.getElementById("extension"),b.getElementById("extension"));d(SVGDocument.getElementById("mapclipdef"),b.getElementById("mapclipdef"));
d(SVGDocument.getElementById("mapstyles"),b.getElementById("mapstyles"));(d=b.getElementsByTagName("pattern"))&&d[0]&&(b=b.getElementsByTagName("pattern")[0].parentNode,SVGRootElement.appendChild(b));map.Scale=new Map.Scale(null);map.Scale.superclass=map;map.Scale.createWidgetStyles();map.Scale.normalizeSymbols(SVGDocument.getElementById("symbolstore"));map.Scale.normalizeButtons(SVGDocument.getElementById("widgetstore"));map.Layer=new Map.Layer(null);map.Layer.initPatternScaling(null,null);map.Zoom=
new Map.Zoom(map.Scale.initScale);map.Tiles=new Map.Tiles;map.Label=new Map.Label;map.Viewport=new Map.Viewport;map.Query=new Map.Query;b=map.Zoom.getBox();b=map.Scale.getMapCoordinate(b.x+b.width/2,b.y+b.height/2);map.Zoom.doSetCenterByParentMap(b.x,b.y);map.Layer.switchScaleDependentLayer();map.Scale.refreshCSSStyles();HTMLWindow.ixmaps.htmlgui_onMapReady(window)};console.log("*** load new map ***");console.log(b);console.log("********************");return 0<b.length?(getData(b,new g(this)),!0):
!1};this.isWaiting=function(){return this.nPending};this.isLoading=function(){return this.nPending|this.isAnyStacked()}}var scriptLoaderPool=new JSLoaderPool;function JSLoaderPool(){this.loaderA=[];this.szSuffix=".js";this.loadedUrlA=[];this.loadingUrlA=[];this.errorUrlA=[]}JSLoaderPool.prototype.add=function(b){this.loaderA[this.loaderA.length]=b};
JSLoaderPool.prototype.evalScripts=function(){if(0==this.isLoading()){for(i=0;i<this.loaderA.length;i++)for(var b=this.loaderA[i],d=0;d<b.loadedScripts.length;d++)this.isScriptLoaded(b.szUrl)||(this.evalScript(b.loadedScripts[d]),this.setScriptLoaded(b.szUrl));this.loaderA.length=0}};JSLoaderPool.prototype.evalScript=function(b){eval(b)};JSLoaderPool.prototype.setScriptError=function(b){this.errorUrlA[this.errorUrlA.length]=b};
JSLoaderPool.prototype.setScriptLoaded=function(b){this.loadedUrlA[this.loadedUrlA.length]=b};JSLoaderPool.prototype.setScriptLoading=function(b){this.loadingUrlA[this.loadingUrlA.length]=b};JSLoaderPool.prototype.isScriptLoaded=function(b){for(var d=0;d<this.loadedUrlA.length;d++)if(this.loadedUrlA[d]==b)return!0;return!1};JSLoaderPool.prototype.isScriptLoading=function(b){for(var d=0;d<this.loadingUrlA.length;d++)if(this.loadingUrlA[d]==b)return!0;return!1};
JSLoaderPool.prototype.isScriptError=function(b){for(var d=0;d<this.errorUrlA.length;d++)if(this.errorUrlA[d]==b)return!0;return!1};JSLoaderPool.prototype.resetScriptLoading=function(b){for(var d=0;d<this.loadingUrlA.length;d++)this.loadingUrlA[d]==b&&(this.loadingUrlA[d]="");for(d=0;d<this.loadedUrlA.length;d++)this.loadedUrlA[d]==b&&(this.loadedUrlA[d]="");for(d=0;d<this.errorUrlA.length;d++)this.errorUrlA[d]==b&&(this.errorUrlA[d]="")};
JSLoaderPool.prototype.isLoading=function(){var b;for(b=0;b<this.loaderA.length;b++)if(0<this.loaderA[b].reqCnt)return!0;return!1};function JSLoader(){this.loadedScripts=[];this.reqCnt=0;this.isLoading=!1;this.finishedCallback=this.errorCallback=null;this.szMessage="... loading ...";this.pool=scriptLoaderPool;this.pool.add(this)}
JSLoader.prototype.loadScript=function(b,d){d&&this.pool.resetScriptLoading(b);try{b.match(/./)||(b+=this.pool.szSuffix),this.szUrl=b,this.pool.isScriptError(this.szUrl)?eval(this.errorCallback):this.pool.isScriptLoaded(this.szUrl)?eval(this.finishedCallback):this.pool.isScriptLoading(this.szUrl)||(this.isLoading=!0,this.reqCnt++,this.pool.setScriptLoading(this.szUrl),getData(b,this))}catch(e){}};
JSLoader.prototype.operationComplete=function(b,d,e){200!=b||!d&&!e?(this.pool.setScriptError(this.szUrl),this.errorCallback&&(this.finishedCallback=null,eval(this.errorCallback))):this.loadedScripts.push(e);this.reqCnt--;0>=this.reqCnt&&this.evalScripts()};JSLoader.prototype.processImported=function(b){alert(b)};JSLoader.prototype.evalScripts=function(){this.pool.evalScripts();this.isLoading=!1;this.finishedCallback&&eval(this.finishedCallback)};JSLoader.prototype.isLoading=function(){return 0<this.reqCnt};
function getData(b,d){if(window.getURL)getURL(b,d);else if(window.XMLHttpRequest){var e=function(){4==f.readyState&&d.operationComplete(f.status,f.responseXML,f.responseText)};try{var f=null,f=new XMLHttpRequest;f.open("GET",b,!0);f.onreadystatechange=e;f.send(null)}catch(g){}}else alert("your browser/svg viewer neither supports window.getURL nor window.XMLHttpRequest!")}
var _deg2rad=Math.PI/180,_rad2deg=180/Math.PI,_maxLat=Math.atan(sinh(Math.PI))*_rad2deg,_refEllipsoid={WGS84:{_EquatorialRadius:6378137,_eccentricitySquared:.00669438},Airy:{_EquatorialRadius:6377563,_eccentricitySquared:.00667054},"Australian National":{_EquatorialRadius:6378160,_eccentricitySquared:.006694542},"Bessel 1841":{_EquatorialRadius:6377397,_eccentricitySquared:.006674372},"Bessel 1841 (Nambia]":{_EquatorialRadius:6377484,_eccentricitySquared:.006674372},"Clarke 1866":{_EquatorialRadius:6378206,
_eccentricitySquared:.006768658},"Clarke 1880":{_EquatorialRadius:6378249,_eccentricitySquared:.006803511},Everest:{_EquatorialRadius:6377276,_eccentricitySquared:.006637847},"Fischer 1960 (Mercury]":{_EquatorialRadius:6378166,_eccentricitySquared:.006693422},"Fischer 1968":{_EquatorialRadius:6378150,_eccentricitySquared:.006693422},"GRS 1967":{_EquatorialRadius:6378160,_eccentricitySquared:.006694605},"GRS 1980":{_EquatorialRadius:6378137,_eccentricitySquared:.00669438},"Helmert 1906":{_EquatorialRadius:6378200,
_eccentricitySquared:.006693422},Hough:{_EquatorialRadius:6378270,_eccentricitySquared:.00672267},International:{_EquatorialRadius:6378388,_eccentricitySquared:.00672267},Krassovsky:{_EquatorialRadius:6378245,_eccentricitySquared:.006693422},"Modified Airy":{_EquatorialRadius:6377340,_eccentricitySquared:.00667054},"Modified Everest":{_EquatorialRadius:6377304,_eccentricitySquared:.006637847},"Modified Fischer 1960":{_EquatorialRadius:6378155,_eccentricitySquared:.006693422},"South American 1969":{_EquatorialRadius:6378160,
_eccentricitySquared:.006694542},"WGS 60":{_EquatorialRadius:6378165,_eccentricitySquared:.006693422},"WGS 66":{_EquatorialRadius:6378145,_eccentricitySquared:.006694542},"WGS-72":{_EquatorialRadius:6378135,_eccentricitySquared:.006694318},"WGS-84":{_EquatorialRadius:6378137,_eccentricitySquared:.00669438}};
function _LLtoUTM(b,d,e,f){_refEllipsoid[b]||(b="WGS84");var g=_refEllipsoid[b]._EquatorialRadius;b=_refEllipsoid[b]._eccentricitySquared;var h=e+180-360*Math.floor((e+180)/360)-180;e=d*_deg2rad;var k=h*_deg2rad,l=Math.floor((h+180)/6)+1;56<=d&&64>d&&3<=h&&12>h&&(l=32);72<=d&&84>d&&(0<=h&&9>h?l=31:9<=h&&21>h?l=33:21<=h&&33>h?l=35:33<=h&&42>h&&(l=37));f&&f.length&&(l=parseInt(f));var m=(6*(l-1)-180+3)*_deg2rad;szUTMZone=String(l+_UTMLetterDesignator(d));f=b/(1-b);var l=g/Math.sqrt(1-b*Math.sin(e)*
Math.sin(e)),h=Math.tan(e)*Math.tan(e),p=f*Math.cos(e)*Math.cos(e),k=Math.cos(e)*(k-m);b=g*((1-b/4-3*b*b/64-5*b*b*b/256)*e-(3*b/8+3*b*b/32+45*b*b*b/1024)*Math.sin(2*e)+(15*b*b/256+45*b*b*b/1024)*Math.sin(4*e)-35*b*b*b/3072*Math.sin(6*e));g=.9996*l*(k+(1-h+p)*k*k*k/6+(5-18*h+h*h+72*p-58*f)*k*k*k*k*k/120)+5E5;e=.9996*(b+l*Math.tan(e)*(k*k/2+(5-h+9*p+4*p*p)*k*k*k*k/24+(61-58*h+h*h+600*p-330*f)*k*k*k*k*k*k/720));0>d&&(e+=1E7);return new point(g,e)}
function _UTMLetterDesignator(b){return 84>=b>=72?"X":72>b>=64?"W":64>b>=56?"V":56>b>=48?"U":48>b>=40?"T":40>b>=32?"S":32>b>=24?"R":24>b>=16?"Q":16>b>=8?"P":8>b>=0?"N":0>b>=-8?"M":-8>b>=-16?"L":-16>b>=-24?"K":-24>b>=-32?"J":-32>b>=-40?"H":-40>b>=-48?"G":-48>b>=-56?"F":-56>b>=-64?"E":-64>b>=-72?"D":-72>b>=-80?"C":"Z"}
function _UTMtoLL(b,d,e,f){_refEllipsoid[b]||(b="WGS84");if(!f)return null;var g=_refEllipsoid[b]._EquatorialRadius;b=_refEllipsoid[b]._eccentricitySquared;var h=(1-Math.sqrt(1-b))/(1+Math.sqrt(1-b));e-=5E5;var k=d;d=parseInt(f);"N"<=f.substr(f.length-1,1)||(k-=1E7);f=6*(d-1)-180+3;d=b/(1-b);var k=k/.9996/(g*(1-b/4-3*b*b/64-5*b*b*b/256)),h=k+(3*h/2-27*h*h*h/32)*Math.sin(2*k)+(21*h*h/16-55*h*h*h*h/32)*Math.sin(4*k)+151*h*h*h/96*Math.sin(6*k),k=g/Math.sqrt(1-b*Math.sin(h)*Math.sin(h)),l=Math.tan(h)*
Math.tan(h),m=d*Math.cos(h)*Math.cos(h),g=g*(1-b)/Math.pow(1-b*Math.sin(h)*Math.sin(h),1.5);b=e/(.9996*k);var p=e=0;e=h-k*Math.tan(h)/g*(b*b/2-(5+3*l+10*m-4*m*m-9*d)*b*b*b*b/24+(61+90*l+298*m+45*l*l-252*d-3*m*m)*b*b*b*b*b*b/720);e*=_rad2deg;p=(b-(1+2*l+m)*b*b*b/6+(5-2*m+28*l-3*m*m+8*d+24*l*l)*b*b*b*b*b/120)/Math.cos(h);p=f+p*_rad2deg;return new point(p,e)}function sinh(b){return(Math.exp(b)-Math.exp(-b))/2}
function _LLtoMercator(b,d){b>=_maxLat&&(b=_maxLat);b<-_maxLat&&(b=-_maxLat);var e=b*_deg2rad,e=.5*Math.log((1+Math.sin(e))/(1-Math.sin(e)))*_rad2deg;return new point(d,e)}function _MercatortoLL(b,d){var e=Math.atan(sinh(b*_deg2rad))*_rad2deg;return new point(d,e)};
