DonutCharts=new _DonutCharts;function _DonutCharts(){this.newChart=function(c,d,b,f,g,a){return new DonutChart(c,d,b,f,g,a)};this.partOver=_crc_donutPartOver;this.partOut=_crc_donutPartOut;this.partDown=_crc_donutPartDown;this.partUp=_crc_donutPartUp;this.partDrawOut=_crc_donutPartDrawOut;this.partDrawIn=_crc_donutPartDrawIn}
function DonutChart(c,d,b,f,g,a){this.targetDocument=c;this.targetGroup=d;this.mX=isNaN(b)?0:b;this.mY=isNaN(f)?0:f;this.nRadOuter=isNaN(g)?0:g;this.nRadInner=isNaN(a)?0:a;this.szStyle="flat";this.szLine=null;this.nLineWidth=1;this.partsA=[]}DonutChart.prototype.setCenter=function(c,d){this.mX=c;this.mY=d};DonutChart.prototype.setRadOuter=function(c){this.nRadOuter=isNaN(c)?0:c};DonutChart.prototype.setRadInner=function(c){this.nRadInner=isNaN(c)?0:c};
DonutChart.prototype.setStyle=function(c){this.szStyle=c};DonutChart.prototype.addStyle=function(c){this.szStyle+="|"+c};DonutChart.prototype.setLine=function(c){this.szLine=c};DonutChart.prototype.setLineWidth=function(c){this.nLineWidth=c};DonutChart.prototype.setMaxValue=function(c){this.nMaxValue=c};
DonutChart.prototype.addPart=function(c,d,b,f,g,a,h,e){this.partsA[this.partsA.length]={nPercent:c,nInfoValue:c,nHeight:d,color:b,nOffset:f,szText:g,szInfo:a,szOver:h,szOut:e};return this.partsA[this.partsA.length-1]};
DonutChart.prototype.realize=function(){var c=0,d=360,b=null,c=this.partsA[0],b=0,f=this.partsA.length-1;this.donutPartsA=[];for(var g=!1,a=0;a<this.partsA.length;a++)0<this.partsA[a].nPercent&&(this.szStyle.match(/BIGTOTOP/)&&this.partsA[a].nPercent>b&&(c=this.partsA[a],b=this.partsA[a].nPercent),g=!0);if(g||this.szStyle.match(/AUTOCOMPLETE/)){var h=0,e=0,k=0,n=g=b=0,m=0;if(this.szStyle.match(/VOLUME/)||this.szStyle.match(/STARBURST/)){for(a=0;a<this.partsA.length;a++)e+=this.partsA[a].nPercent,
m=Math.max(m,this.partsA[a].nPercent),h+=Math.sqrt(this.partsA[a].nPercent);h=Math.sqrt(this.nMaxValue*this.partsA.length);for(a=0;a<this.partsA.length;a++)this.partsA[a].nPercent=100/h*Math.sqrt(this.partsA[a].nPercent),this.szStyle.match(/VOLUME/)&&(this.partsA[a].nHeight*=this.partsA[a].nPercent/25);k=100/h*Math.sqrt(this.nMaxValue||100);b=100/h*Math.sqrt(this.nMaxValue/4||50);g=100/h*Math.sqrt(this.nMaxValue/2||50);n=100/h*Math.sqrt(this.nMaxValue/4*3||50)}else{for(a=0;a<this.partsA.length;a++)e+=
this.partsA[a].nPercent;if(100!=e)if(this.szStyle.match(/AUTOCOMPLETE/)&&100>e)this.addPart(Math.floor(1E5*(100-e))/1E5,this.partsA[0]?this.partsA[0].nHeight:0,this.szNoDataColor||"#eeeeee",0,"");else for(a=0;a<this.partsA.length;a++)this.partsA[a].nPercent=this.partsA[a].nPercent/e*100}if(this.szStyle.match(/SYMMETRIC/))if(this.szStyle.match(/STARBURST/))d=360-Math.floor(360/this.partsA.length/2);else if(this.szStyle.match(/BIGTOTOP/)){d=360;for(a=0;a<this.partsA.length&&this.partsA[a]!=c;a++)d-=
100>this.partsA[a].nPercent?Math.floor(3.6*this.partsA[a].nPercent):0;d-=100>this.partsA[a].nPercent?Math.floor(1.8*c.nPercent):0}else 100>this.partsA[0].nPercent&&(d=360-Math.floor(1.8*this.partsA[0].nPercent));this.szStyle.match(/HALF/)&&(d=270);this.szStyle.match(/HALFPLUS10/)&&(d=260);this.szStyle.match(/HALFMINUS10/)&&(d=280);this.szStyle.match(/HALFPLUS20/)&&(d=250);this.szStyle.match(/HALFMINUS20/)&&(d=290);h=this.szStyle.match(/HALF/)?180:360;h=this.szStyle.match(/HALFPLUS10/)?200:h;h=this.szStyle.match(/HALFMINUS10/)?
160:h;h=this.szStyle.match(/HALFPLUS20/)?220:h;h=this.szStyle.match(/HALFMINUS20/)?140:h;m=e=0;this.szStyle.match(/STARBURST/)&&(e=h/this.partsA.length,this.nRadOuter+=this.nRadInner/this.partsA.length*3,this.szStyle.match(/XLRAYS/)?(e=Math.min(h/4,h/this.partsA.length),m=.1*e*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(5,this.nRadInner)):this.szStyle.match(/LRAYS/)?(e=Math.min(h/4,h/this.partsA.length),m=.2*e*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(5,this.nRadInner)):
this.szStyle.match(/XSRAYS/)?(e=Math.min(h/12,h/this.partsA.length),m=.4*e*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(5,this.nRadInner)):this.szStyle.match(/SRAYS/)?(e=Math.min(h/10,h/this.partsA.length),m=.33*e*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(5,this.nRadInner)):this.szStyle.match(/RAYS/)&&(e=h/this.partsA.length,m=.35*e*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(5,this.nRadInner)));for(a=this.nRadOuterMaxR=this.nRadOuterMaxL=0;a<this.partsA.length;a++)this.szStyle.match(/STARBURST/)||
(e=this.partsA[a].nPercent/100*h,m=0),c=d%360,d=c+e,360<d&&(d%=360),this.szStyle.match(/DIRECTION/)?this.donutPartsA[a]=this.partsA[a].nAngle?{nStartAngle:this.partsA[a].nAngle-1,nEndAngle:this.partsA[a].nAngle+1,color:this.partsA[a].color,nHeight:this.partsA[a].nHeight,nOffset:this.partsA[a].nOffset}:{}:this.donutPartsA[a]={nStartAngle:c+m,nEndAngle:d-m,color:this.partsA[a].color,nHeight:this.partsA[a].nHeight,nOffset:this.partsA[a].nOffset},this.szStyle.match(/3D/)||(this.donutPartsA[a].nHeight=
0),this.szStyle.match(/STARBURST/)&&(this.donutPartsA[a].nRadOuter=Math.max(1,this.nRadInner+Math.sqrt(this.partsA[a].nPercent*this.partsA.length)/10*(this.nRadOuter-Math.sqrt(this.nRadInner)))),180>=c&&180<=d&&(f=a),180>=c?this.nRadOuterMaxR=Math.max(this.nRadOuterMaxR,this.donutPartsA[a].nRadOuter):this.nRadOuterMaxL=Math.max(this.nRadOuterMaxL,this.donutPartsA[a].nRadOuter),this.partsA[a].nOpacity&&(this.donutPartsA[a].nOpacity=this.partsA[a].nOpacity);this.szStyle.match(/STARBURST/)&&this.szStyle.match(/POLAR/)&&
(d=Math.max(1,this.nRadInner+k/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:white;fill-opacity:0.25;stroke:#444444;stroke-width:1px;"),d.setAttributeNS(null,"tooltip","range "+String(.75*(this.nMaxValue||100))+"-"+String(1*(this.nMaxValue||100))),d=Math.max(1,this.nRadInner+n/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:none;stroke:#444444;stroke-width:3px;stroke-dasharray:50 50"),
d.setAttributeNS(null,"tooltip","range "+String(.5*(this.nMaxValue||100))+"-"+String(.75*(this.nMaxValue||100))),d=Math.max(1,this.nRadInner+g/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:none;stroke:#444444;stroke-width:1px;"),d.setAttributeNS(null,"tooltip","range "+String(.25*(this.nMaxValue||100))+"-"+String(.5*(this.nMaxValue||100))),d=Math.max(1,this.nRadInner+b/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),
d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:none;stroke:#444444;stroke-width:3px;stroke-dasharray:50 50"),d.setAttributeNS(null,"tooltip","range "+String(0*(this.nMaxValue||100))+"-"+String(.25*(this.nMaxValue||100))));if(this.szStyle.match(/HALF/))for(f=this.donutPartsA.length,a=0;a<f;a++)270<this.donutPartsA[a].nEndAngle&&(this.donutPartsA.push(this.donutPartsA.splice(a,1)[0]),this.partsA.push(this.partsA.splice(a,1)[0]),f--,a=-1);this.frameGroup=_crc_constructNode("g",
this.targetDocument,this.targetGroup,{});for(a=0;a<f;a++)b=_crc_drawDonut(this.targetDocument,this.frameGroup,this.mX,this.mY,this.donutPartsA[a].nRadOuter?this.donutPartsA[a].nRadOuter:this.nRadOuter,this.nRadInner,this.donutPartsA[a].nHeight,this.donutPartsA[a].nStartAngle,this.donutPartsA[a].nEndAngle,this.donutPartsA[a].color,null,null,this.szLine,this.nLineWidth*(this.donutPartsA[a].nRadOuter?this.donutPartsA[a].nRadOuter:this.nRadOuter)/300,this.szStyle,this.donutPartsA[a].nOffset,this.nBow),
this.szStyle.match(/SILENT/)||(b.setAttributeNS(szMapNs,"tooltip",this.partsA[a].szInfo?this.partsA[a].szText+this.partsA[a].szInfo:Math.round(10*this.partsA[a].nInfoValue)/10+" % "),this.partsA[a].szOver&&b.setAttributeNS(szMapNs,"onover",this.partsA[a].szOver),this.partsA[a].szOut&&b.setAttributeNS(szMapNs,"onout",this.partsA[a].szOut)),this.donutPartsA[a].nOpacity&&(b.style.setProperty("stroke-opacity","0.6",""),b.style.setProperty("fill-opacity","0.1","")),this.donutPartsA[a].objNode=b;for(a=
this.donutPartsA.length-1;a>=f;a--)b=_crc_drawDonut(this.targetDocument,this.frameGroup,this.mX,this.mY,this.donutPartsA[a].nRadOuter?this.donutPartsA[a].nRadOuter:this.nRadOuter,this.nRadInner,this.donutPartsA[a].nHeight,this.donutPartsA[a].nStartAngle,this.donutPartsA[a].nEndAngle,this.donutPartsA[a].color,null,null,this.szLine,this.nLineWidth*(this.donutPartsA[a].nRadOuter?this.donutPartsA[a].nRadOuter:this.nRadOuter)/300,this.szStyle,this.donutPartsA[a].nOffset,this.nBow),this.szStyle.match(/SILENT/)||
(b.setAttributeNS(szMapNs,"tooltip",this.partsA[a].szInfo?this.partsA[a].szText+this.partsA[a].szInfo:Math.round(10*this.partsA[a].nInfoValue)/10+" % "),this.partsA[a].szOver&&b.setAttributeNS(szMapNs,"onover",this.partsA[a].szOver),this.partsA[a].szOut&&b.setAttributeNS(szMapNs,"onout",this.partsA[a].szOut)),this.donutPartsA[a].nOpacity&&(b.style.setProperty("stroke-opacity","0.6",""),b.style.setProperty("fill-opacity","0.1","")),this.donutPartsA[a].objNode=b;this.szStyle.match(/3D/)&&this.frameGroup.setAttributeNS(null,
"transform","matrix(1 0 0 0.5 0 0)")}else _crc_constructNode("circle",this.targetDocument,this.targetGroup,{id:"emptypie",cx:this.mX,cy:this.mY,r:this.nRadOuter,style:"fill:none;stroke:gray"}),_crc_newText(this.targetDocument,this.targetGroup,this.mX,this.mY,"fill:gray;font-size:"+this.nRadOuter/5+";text-anchor:middle;","Pie error: no values !")};
DonutChart.prototype.getTextPosition=function(c){if(!this.donutPartsA[c])return null;var d=this.donutPartsA[c].nRadOuter?this.donutPartsA[c].nRadOuter:this.nRadOuter,b=this.nRadOuter,f=0,g=this.donutPartsA[c].nStartAngle,b=this.donutPartsA[c].nEndAngle;if(g==b)return null;var f=g<b?(g+b)/2:Math.min(360,(g+b+360)/2)%360,b=180>f?this.nRadOuterMaxR?this.nRadOuterMaxR+(this.nRadOuterMaxL>this.nRadOuterMaxR?Math.min(this.nRadOuterMaxR,(this.nRadOuterMaxL-this.nRadOuterMaxR)/2):0):this.nRadOuter:this.nRadOuterMaxL?
this.nRadOuterMaxL+(this.nRadOuterMaxR>this.nRadOuterMaxL?Math.min(this.nRadOuterMaxL,(this.nRadOuterMaxR-this.nRadOuterMaxL)/2):0):this.nRadOuter,g=Math.sin(f/180*Math.PI)*d,d=-Math.cos(f/180*Math.PI)*d-this.donutPartsA[c].nHeight,a=Math.sin(f/180*Math.PI)*b*1.1;c=-Math.cos(f/180*Math.PI)*b*1.1-this.donutPartsA[c].nHeight;return{x:a,y:c,lx:g,ly:d}};function _crc_createSingleNode(c,d,b){c=d.createElementNS("http://www.w3.org/2000/svg",c);b.appendChild(c);return c}
function _crc_constructNode(c,d,b,f){c=_crc_createSingleNode(c,d,b);for(var g in f)c.setAttribute(g,f[g]);return c}function _crc_newText(c,d,b,f,g,a){a||(a="(undefined)");d=_crc_constructNode("text",c,d,{x:String(b),y:String(f),style:g});c=c.createTextNode(a);d.appendChild(c);return d}
function _crc_drawDonut(c,d,b,f,g,a,h,e,k,n,m,p,q,t,r,l,v){null==l&&(l=0);var u=0,u=e<k?(e+k)/2:Math.max(360,(e+k+360)/2),w=Math.sin(u/180*Math.PI),u=-Math.cos(u/180*Math.PI);b+=l*w;f+=l*u;null==r&&(r="3D");null==n&&(n="#ffff00");null==m&&(m=ColorScheme.getDerivateColor(n,.7));null==p&&(p=ColorScheme.getDerivateColor(n,.7));null==q&&(q=ColorScheme.getBorderColor(n));d=r.match(/SILENT/)?_crc_constructNode("g",c,d,{}):_crc_constructNode("g",c,d,{onmouseover:"DonutCharts.partOver(evt)",onmouseout:"DonutCharts.partOut(evt)",
onmousedown:"DonutCharts.partDown(evt)",onmouseup:"DonutCharts.partUp(evt)"});if(0>e||0>k||e==k)return d;_crc_constructNode("rect",c,d,{id:"extractPoint",x:w*g/3,y:u*g/3,width:0,height:0,style:"fill:none;stroke:none"});r.match(/3D/)&&(e>k?(_crc_drawInnerWall(c,d,b,f,g,a,h,e,360,m,"none",0),_crc_drawInnerWall(c,d,b,f,g,a,h,0,k,m,"none",0)):_crc_drawInnerWall(c,d,b,f,g,a,h,e,k,m,q,t));r.match(/3D/)&&180<e&&(l=""+pathMoveToCirclePoint(b,f-h,g,e),l+=pathLineToCirclePoint(b,f-h,a,e),l+=pathLineToCirclePoint(b,
f,a,e),l+=pathLineToCirclePoint(b,f,g,e),l+=pathLineToCirclePoint(b,f-h,g,e),_crc_constructNode("path",c,d,{d:l,style:"stroke:"+q+";fill:"+p+";stroke-width:"+t+";"}));r.match(/3D/)&&180>k&&(l=""+pathMoveToCirclePoint(b,f-h,g,k),l+=pathLineToCirclePoint(b,f-h,a,k),l+=pathLineToCirclePoint(b,f,a,k),l+=pathLineToCirclePoint(b,f,g,k),l+=pathLineToCirclePoint(b,f-h,g,k),_crc_constructNode("path",c,d,{d:l,style:"stroke:"+q+";fill:"+p+";stroke-width:"+t+";"}));r.match(/3D/)&&(e>k?(_crc_drawOuterWall(c,d,
b,f,g,a,h,e,360,m,"none",0),_crc_drawOuterWall(c,d,b,f,g,a,h,0,k,m,"none",0)):_crc_drawOuterWall(c,d,b,f,g,a,h,e,k,m,q,t));360<=k-e?(l=""+pathMoveToCirclePoint(b,f-h,g,e),l+=pathDrawArc(b,f-h,g,e,k,v),l+=pathMoveToCirclePoint(b,f-h,a,k),a&&(l+=pathDrawArcCounterClock(b,f-h,a,k,e))):(l=""+pathMoveToCirclePoint(b,f-h,g,e),l+=pathDrawArc(b,f-h,g,e,k,v),l+=pathLineToCirclePoint(b,f-h,a,k),a&&(l+=pathDrawArcCounterClock(b,f-h,a,k,e)),l+=pathLineToCirclePoint(b,f-h,g,e));_crc_constructNode("path",c,d,{d:l,
style:"stroke:"+q+";fill:"+n+";stroke-width:"+t+";"});return d}function _crc_drawInnerWall(c,d,b,f,g,a,h,e,k,n,m,p){90<e&&270>e&&270>k||(g=""+pathMoveToCirclePoint(b,f-h,a,e),g+=pathDrawArc(b,f-h,a,e,k),g+=pathLineToCirclePoint(b,f,a,k),g+=pathDrawArcCounterClock(b,f,a,k,e),g+=pathLineToCirclePoint(b,f-h,a,e),_crc_constructNode("path",c,d,{d:g,style:"stroke:"+m+";fill:"+n+";stroke-width:"+p+";"}))}
function _crc_drawOuterWall(c,d,b,f,g,a,h,e,k,n,m,p){a=Math.max(e,90);k=Math.min(k,270);a>k||(e=""+pathMoveToCirclePoint(b,f-h,g,a),e+=pathDrawArc(b,f-h,g,a,k),e+=pathLineToCirclePoint(b,f,g,k),e+=pathDrawArcCounterClock(b,f,g,k,a),e+=pathLineToCirclePoint(b,f-h,g,a),_crc_constructNode("path",c,d,{d:e,style:"stroke:"+m+";fill:"+n+";stroke-width:"+p+";"}))}
function _crc_donutPartOver(c){var d=Number(c.currentTarget.firstChild.getAttributeNS(null,"x")),b=Number(c.currentTarget.firstChild.getAttributeNS(null,"y"));c.currentTarget.setAttribute("transform","translate("+d/25+","+b/25+")");try{eval(c.currentTarget.getAttribute("onover"))}catch(f){}}function _crc_donutPartOut(c){c.currentTarget.setAttribute("transform","translate(0,0)");try{eval(c.currentTarget.getAttribute("onout"))}catch(d){}}
function _crc_donutPartDown(c){var d=Number(c.currentTarget.firstChild.getAttributeNS(null,"x")),b=Number(c.currentTarget.firstChild.getAttributeNS(null,"y")),b=b+map.Scale.normalY(.1);c.currentTarget.setAttribute("transform","translate("+d/5+","+b/5+")")}function _crc_donutPartUp(c){var d=Number(c.currentTarget.firstChild.getAttributeNS(null,"x")),b=Number(c.currentTarget.firstChild.getAttributeNS(null,"y"));c.currentTarget.setAttribute("transform","translate("+d/5+","+b/5+")")}
function _crc_donutPartDrawOut(c){if(c.firstChild){var d=Number(c.firstChild.getAttributeNS(null,"x")),b=Number(c.firstChild.getAttributeNS(null,"y"));if(d&&b)return c.setAttribute("transform","translate("+d+","+b+")"),!0}return!1}function _crc_donutPartDrawIn(c){if(c.firstChild){var d=Number(c.firstChild.getAttributeNS(null,"x")),b=Number(c.firstChild.getAttributeNS(null,"y"));if(d&&b)return c.setAttribute("transform","translate(0,0)"),!0}return!1}
function pathDrawArc(c,d,b,f,g,a){var h,e,k,n,m,p,q,t,r,l,v,u=" ";f%=360;if(f>g)return u+=pathDrawArc(c,d,b,f,360,a),u+=pathDrawArc(c,d,b,0,g,a);for(v=1;8>=v;v++)if(!(f>45*v||g<45*(v-1))&&(n=Math.max(f,45*(v-1)),e=Math.min(g,45*v),n!=e)){180<n&&(n=360-n);90<n&&(n=180-n);45<n&&(n=90-n);180<e&&(e=360-e);90<e&&(e=180-e);45<e&&(e=90-e);p=Math.PI*n/180;m=Math.PI*e/180;h=b*Math.sin(p);k=b*Math.cos(p);e=b*Math.sin(m);n=b*Math.cos(m);h=k+Math.tan(p)*h;k=n+Math.tan(m)*e;m=(k-h)/(Math.tan(m)-Math.tan(p));p=
-Math.tan(p)*m+h;m*=a||1;p*=a||1;switch(v){case 1:q=e;r=m;t=-n;l=-p;break;case 2:q=n;r=p;t=-e;l=-m;break;case 3:q=n;r=p;t=e;l=m;break;case 4:q=e;r=m;t=n;l=p;break;case 5:q=-e;r=-m;t=n;l=p;break;case 6:q=-n;r=-p;t=e;l=m;break;case 7:q=-n;r=-p;t=-e;l=-m;break;case 8:q=-e,r=-m,t=-n,l=-p}u+="Q"+String(c+r)+","+String(d+l)+" "+String(c+q)+","+String(d+t)}return u}
function pathDrawArcCounterClock(c,d,b,f,g){var a;a=""+pathDrawArc(c,d,b,g,f);f="";a=a.split("Q");for(var h=a.length-1;0<h;h--)for(var e=a[h].split(" "),k=1;0<=k;k--)if(h!=a.length-1||1!=k)f=0===k?f+(" Q"+e[k]):f+(" "+e[k]);return f+=pathAddCirclePoint(c,d,b,g)}function pathMoveToCirclePoint(c,d,b,f){var g;g=Math.PI*f/180;f=b*Math.sin(g);b*=Math.cos(g);return"M"+String(c+f)+","+String(d+-b)}
function pathLineToCirclePoint(c,d,b,f){var g;g=Math.PI*f/180;f=b*Math.sin(g);b*=Math.cos(g);return"L"+String(c+f)+","+String(d+-b)}function pathAddCirclePoint(c,d,b,f){var g;g=Math.PI*f/180;f=b*Math.sin(g);b*=Math.cos(g);return" "+String(c+f)+","+String(d+-b)};
