var DonutCharts=new _DonutCharts;function _DonutCharts(){this.newChart=function(c,d,b,e,f,a){return new DonutChart(c,d,b,e,f,a)};this.partOver=_crc_donutPartOver;this.partOut=_crc_donutPartOut;this.partDown=_crc_donutPartDown;this.partUp=_crc_donutPartUp;this.partDrawOut=_crc_donutPartDrawOut;this.partDrawIn=_crc_donutPartDrawIn}
function DonutChart(c,d,b,e,f,a){this.targetDocument=c;this.targetGroup=d;this.mX=isNaN(b)?0:b;this.mY=isNaN(e)?0:e;this.nRadOuter=isNaN(f)?0:f;this.nRadInner=isNaN(a)?0:a;this.szStyle="flat";this.szLine=null;this.nLineWidth=1;this.partsA=[]}DonutChart.prototype.setCenter=function(c,d){this.mX=c;this.mY=d};DonutChart.prototype.setRadOuter=function(c){this.nRadOuter=isNaN(c)?0:c};DonutChart.prototype.setRadInner=function(c){this.nRadInner=isNaN(c)?0:c};
DonutChart.prototype.setStyle=function(c){this.szStyle=c};DonutChart.prototype.addStyle=function(c){this.szStyle+="|"+c};DonutChart.prototype.setLine=function(c){this.szLine=c};DonutChart.prototype.setLineWidth=function(c){this.nLineWidth=c};DonutChart.prototype.setMaxValue=function(c){this.nMaxValue=c};
DonutChart.prototype.addPart=function(c,d,b,e,f,a,g,h){this.partsA[this.partsA.length]={nPercent:c,nInfoValue:c,nHeight:d,color:b,nOffset:e,szText:f,szInfo:a,szOver:g,szOut:h};return this.partsA[this.partsA.length-1]};
DonutChart.prototype.realize=function(){var c=0,d=360,b=null,c=this.partsA[0],b=0,e=this.partsA.length-1;this.donutPartsA=[];for(var f=!1,a=0;a<this.partsA.length;a++)0<this.partsA[a].nPercent&&(this.szStyle.match(/BIGTOTOP/)&&this.partsA[a].nPercent>b&&(c=this.partsA[a],b=this.partsA[a].nPercent),f=!0);if(f||this.szStyle.match(/AUTOCOMPLETE/)){var g=0,h=0,k=0,n=f=b=0,m=0;if(this.szStyle.match(/VOLUME/)||this.szStyle.match(/STARBURST/)){for(a=0;a<this.partsA.length;a++)h+=this.partsA[a].nPercent,
m=Math.max(m,this.partsA[a].nPercent),g+=Math.sqrt(this.partsA[a].nPercent);g=Math.sqrt(this.nMaxValue*this.partsA.length);for(a=0;a<this.partsA.length;a++)this.partsA[a].nPercent=100/g*Math.sqrt(this.partsA[a].nPercent),this.szStyle.match(/VOLUME/)&&(this.partsA[a].nHeight*=this.partsA[a].nPercent/25);k=100/g*Math.sqrt(this.nMaxValue||100);b=100/g*Math.sqrt(this.nMaxValue/4||50);f=100/g*Math.sqrt(this.nMaxValue/2||50);n=100/g*Math.sqrt(this.nMaxValue/4*3||50)}else{for(a=0;a<this.partsA.length;a++)h+=
this.partsA[a].nPercent;if(100!=h)if(this.szStyle.match(/AUTOCOMPLETE/)&&100>h)this.addPart(Math.floor(1E5*(100-h))/1E5,this.partsA[0]?this.partsA[0].nHeight:0,"#eeeeee",0,"");else for(a=0;a<this.partsA.length;a++)this.partsA[a].nPercent=this.partsA[a].nPercent/h*100}if(this.szStyle.match(/SYMMETRIC/))if(this.szStyle.match(/STARBURST/))d=360-Math.floor(360/this.partsA.length/2);else if(this.szStyle.match(/BIGTOTOP/)){d=360;for(a=0;a<this.partsA.length&&this.partsA[a]!=c;a++)d-=100>this.partsA[a].nPercent?
Math.floor(3.6*this.partsA[a].nPercent):0;d-=100>this.partsA[a].nPercent?Math.floor(1.8*c.nPercent):0}else 100>this.partsA[0].nPercent&&(d=360-Math.floor(1.8*this.partsA[0].nPercent));this.szStyle.match(/HALF/)&&(d=270);g=this.szStyle.match(/HALF/)?180:360;m=h=0;this.szStyle.match(/STARBURST/)&&(h=g/this.partsA.length,this.nRadOuter+=this.nRadInner/this.partsA.length*3,this.szStyle.match(/XLRAYS/)?(h=Math.min(g/4,g/this.partsA.length),m=.1*h*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(35,
this.nRadInner)):this.szStyle.match(/LRAYS/)?(h=Math.min(g/4,g/this.partsA.length),m=.2*h*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(35,this.nRadInner)):this.szStyle.match(/XSRAYS/)?(h=Math.min(g/12,g/this.partsA.length),m=.4*h*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(35,this.nRadInner)):this.szStyle.match(/SRAYS/)?(h=Math.min(g/10,g/this.partsA.length),m=.33*h*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(35,this.nRadInner)):this.szStyle.match(/RAYS/)&&
(h=g/this.partsA.length,m=.35*h*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(35,this.nRadInner)));for(a=this.nRadOuterMaxR=this.nRadOuterMaxL=0;a<this.partsA.length;a++)this.szStyle.match(/STARBURST/)||(h=this.partsA[a].nPercent/100*g,m=0),c=d%360,d=c+h,360<d&&(d%=360),this.szStyle.match(/DIRECTION/)?this.donutPartsA[a]=this.partsA[a].nAngle?{nStartAngle:this.partsA[a].nAngle-1,nEndAngle:this.partsA[a].nAngle+1,color:this.partsA[a].color,nHeight:this.partsA[a].nHeight,nOffset:this.partsA[a].nOffset}:
{}:this.donutPartsA[a]={nStartAngle:c+m,nEndAngle:d-m,color:this.partsA[a].color,nHeight:this.partsA[a].nHeight,nOffset:this.partsA[a].nOffset},this.szStyle.match(/3D/)||(this.donutPartsA[a].nHeight=0),this.szStyle.match(/STARBURST/)&&(this.donutPartsA[a].nRadOuter=Math.max(1,this.nRadInner+this.partsA[a].nPercent/100*this.partsA.length*(this.nRadOuter-this.nRadInner))),180>=c&&180<=d&&(e=a),180>=c?this.nRadOuterMaxR=Math.max(this.nRadOuterMaxR,this.donutPartsA[a].nRadOuter):this.nRadOuterMaxL=Math.max(this.nRadOuterMaxL,
this.donutPartsA[a].nRadOuter),this.partsA[a].nOpacity&&(this.donutPartsA[a].nOpacity=this.partsA[a].nOpacity);this.szStyle.match(/STARBURST/)&&this.szStyle.match(/POLAR/)&&(d=Math.max(1,this.nRadInner+k/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:white;fill-opacity:1;stroke:#dddddd;stroke-width:20px;"),d.setAttributeNS(null,"tooltip","75-100"),d=Math.max(1,this.nRadInner+n/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),
d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:none;stroke:#dddddd;stroke-width:20px;stroke-dasharray:50 50"),d.setAttributeNS(null,"tooltip","50-75"),d=Math.max(1,this.nRadInner+f/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:none;stroke:#dddddd;stroke-width:10px;"),d.setAttributeNS(null,"tooltip","25-50"),d=Math.max(1,this.nRadInner+b/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),d=map.Dom.newShape("circle",
this.targetGroup,this.mX,this.mY,d,"fill:none;stroke:#dddddd;stroke-width:20px;stroke-dasharray:50 50"),d.setAttributeNS(null,"tooltip","0-25"));if(this.szStyle.match(/HALF/))for(e=this.donutPartsA.length,a=0;a<e;a++)270<this.donutPartsA[a].nEndAngle&&(this.donutPartsA.push(this.donutPartsA.splice(a,1)[0]),this.partsA.push(this.partsA.splice(a,1)[0]),e--,a=-1);this.frameGroup=_crc_constructNode("g",this.targetDocument,this.targetGroup,{});for(a=0;a<e;a++)b=_crc_drawDonut(this.targetDocument,this.frameGroup,
this.mX,this.mY,this.donutPartsA[a].nRadOuter?this.donutPartsA[a].nRadOuter:this.nRadOuter,this.nRadInner,this.donutPartsA[a].nHeight,this.donutPartsA[a].nStartAngle,this.donutPartsA[a].nEndAngle,this.donutPartsA[a].color,null,null,this.szLine,this.nLineWidth,this.szStyle,this.donutPartsA[a].nOffset),this.szStyle.match(/SILENT/)||(b.setAttributeNS(szMapNs,"tooltip",this.partsA[a].szInfo?this.partsA[a].szText+this.partsA[a].szInfo:Math.round(10*this.partsA[a].nInfoValue)/10+" % "),this.partsA[a].szOver&&
b.setAttributeNS(szMapNs,"onover",this.partsA[a].szOver),this.partsA[a].szOut&&b.setAttributeNS(szMapNs,"onout",this.partsA[a].szOut)),this.donutPartsA[a].nOpacity&&(b.style.setProperty("stroke-opacity","0.6",""),b.style.setProperty("fill-opacity","0.1","")),this.donutPartsA[a].objNode=b;for(a=this.donutPartsA.length-1;a>=e;a--)b=_crc_drawDonut(this.targetDocument,this.frameGroup,this.mX,this.mY,this.donutPartsA[a].nRadOuter?this.donutPartsA[a].nRadOuter:this.nRadOuter,this.nRadInner,this.donutPartsA[a].nHeight,
this.donutPartsA[a].nStartAngle,this.donutPartsA[a].nEndAngle,this.donutPartsA[a].color,null,null,this.szLine,this.nLineWidth,this.szStyle,this.donutPartsA[a].nOffset),this.szStyle.match(/SILENT/)||(b.setAttributeNS(szMapNs,"tooltip",this.partsA[a].szInfo?this.partsA[a].szText+this.partsA[a].szInfo:Math.round(10*this.partsA[a].nInfoValue)/10+" % "),this.partsA[a].szOver&&b.setAttributeNS(szMapNs,"onover",this.partsA[a].szOver),this.partsA[a].szOut&&b.setAttributeNS(szMapNs,"onout",this.partsA[a].szOut)),
this.donutPartsA[a].nOpacity&&(b.style.setProperty("stroke-opacity","0.6",""),b.style.setProperty("fill-opacity","0.1","")),this.donutPartsA[a].objNode=b;this.szStyle.match(/3D/)&&this.frameGroup.setAttributeNS(null,"transform","matrix(1 0 0 0.5 0 0)")}else _crc_constructNode("circle",this.targetDocument,this.targetGroup,{id:"emptypie",cx:this.mX,cy:this.mY,r:this.nRadOuter,style:"fill:none;stroke:gray"}),_crc_newText(this.targetDocument,this.targetGroup,this.mX,this.mY,"fill:gray;font-size:"+this.nRadOuter/
5+";text-anchor:middle;","Pie error: no values !")};
DonutChart.prototype.getTextPosition=function(c){if(!this.donutPartsA[c])return null;var d=this.donutPartsA[c].nRadOuter?this.donutPartsA[c].nRadOuter:this.nRadOuter,b=this.nRadOuter,e=0,f=this.donutPartsA[c].nStartAngle,b=this.donutPartsA[c].nEndAngle;if(f==b)return null;var e=f<b?(f+b)/2:Math.min(360,(f+b+360)/2)%360,b=180>e?this.nRadOuterMaxR?this.nRadOuterMaxR+(this.nRadOuterMaxL>this.nRadOuterMaxR?Math.min(this.nRadOuterMaxR,(this.nRadOuterMaxL-this.nRadOuterMaxR)/2):0):this.nRadOuter:this.nRadOuterMaxL?
this.nRadOuterMaxL+(this.nRadOuterMaxR>this.nRadOuterMaxL?Math.min(this.nRadOuterMaxL,(this.nRadOuterMaxR-this.nRadOuterMaxL)/2):0):this.nRadOuter,f=Math.sin(e/180*Math.PI)*d,d=-Math.cos(e/180*Math.PI)*d-this.donutPartsA[c].nHeight,a=Math.sin(e/180*Math.PI)*b*1.1;c=-Math.cos(e/180*Math.PI)*b*1.1-this.donutPartsA[c].nHeight;return{x:a,y:c,lx:f,ly:d}};function _crc_createSingleNode(c,d,b){c=d.createElementNS("http://www.w3.org/2000/svg",c);b.appendChild(c);return c}
function _crc_constructNode(c,d,b,e){c=_crc_createSingleNode(c,d,b);for(var f in e)c.setAttribute(f,e[f]);return c}function _crc_newText(c,d,b,e,f,a){a||(a="(undefined)");d=_crc_constructNode("text",c,d,{x:String(b),y:String(e),style:f});c=c.createTextNode(a);d.appendChild(c);return d}
function _crc_drawDonut(c,d,b,e,f,a,g,h,k,n,m,p,q,t,r,l){null==l&&(l=0);var u=0,u=h<k?(h+k)/2:Math.max(360,(h+k+360)/2),v=Math.sin(u/180*Math.PI),u=-Math.cos(u/180*Math.PI);b+=l*v;e+=l*u;null==r&&(r="3D");null==n&&(n="#ffff00");null==m&&(m=ColorScheme.getDerivateColor(n,.7));null==p&&(p=ColorScheme.getDerivateColor(n,.7));null==q&&(q=ColorScheme.getBorderColor(n));d=r.match(/SILENT/)?_crc_constructNode("g",c,d,{}):_crc_constructNode("g",c,d,{onmouseover:"DonutCharts.partOver(evt)",onmouseout:"DonutCharts.partOut(evt)",
onmousedown:"DonutCharts.partDown(evt)",onmouseup:"DonutCharts.partUp(evt)"});if(0>h||0>k||h==k)return d;_crc_constructNode("rect",c,d,{id:"extractPoint",x:v*f/3,y:u*f/3,width:0,height:0,style:"fill:none;stroke:none"});r.match(/3D/)&&(h>k?(_crc_drawInnerWall(c,d,b,e,f,a,g,h,360,m,"none",0),_crc_drawInnerWall(c,d,b,e,f,a,g,0,k,m,"none",0)):_crc_drawInnerWall(c,d,b,e,f,a,g,h,k,m,q,t));r.match(/3D/)&&180<h&&(l=""+pathMoveToCirclePoint(b,e-g,f,h),l+=pathLineToCirclePoint(b,e-g,a,h),l+=pathLineToCirclePoint(b,
e,a,h),l+=pathLineToCirclePoint(b,e,f,h),l+=pathLineToCirclePoint(b,e-g,f,h),_crc_constructNode("path",c,d,{d:l,style:"stroke:"+q+";fill:"+p+";stroke-width:"+t+";"}));r.match(/3D/)&&180>k&&(l=""+pathMoveToCirclePoint(b,e-g,f,k),l+=pathLineToCirclePoint(b,e-g,a,k),l+=pathLineToCirclePoint(b,e,a,k),l+=pathLineToCirclePoint(b,e,f,k),l+=pathLineToCirclePoint(b,e-g,f,k),_crc_constructNode("path",c,d,{d:l,style:"stroke:"+q+";fill:"+p+";stroke-width:"+t+";"}));r.match(/3D/)&&(h>k?(_crc_drawOuterWall(c,d,
b,e,f,a,g,h,360,m,"none",0),_crc_drawOuterWall(c,d,b,e,f,a,g,0,k,m,"none",0)):_crc_drawOuterWall(c,d,b,e,f,a,g,h,k,m,q,t));360<=k-h?(l=""+pathMoveToCirclePoint(b,e-g,f,h),l+=pathDrawArc(b,e-g,f,h,k),l+=pathMoveToCirclePoint(b,e-g,a,k),a&&(l+=pathDrawArcCounterClock(b,e-g,a,k,h))):(l=""+pathMoveToCirclePoint(b,e-g,f,h),l+=pathDrawArc(b,e-g,f,h,k),l+=pathLineToCirclePoint(b,e-g,a,k),a&&(l+=pathDrawArcCounterClock(b,e-g,a,k,h)),l+=pathLineToCirclePoint(b,e-g,f,h));_crc_constructNode("path",c,d,{d:l,
style:"stroke:"+q+";fill:"+n+";stroke-width:"+t+";"});return d}function _crc_drawInnerWall(c,d,b,e,f,a,g,h,k,n,m,p){90<h&&270>h&&270>k||(f=""+pathMoveToCirclePoint(b,e-g,a,h),f+=pathDrawArc(b,e-g,a,h,k),f+=pathLineToCirclePoint(b,e,a,k),f+=pathDrawArcCounterClock(b,e,a,k,h),f+=pathLineToCirclePoint(b,e-g,a,h),_crc_constructNode("path",c,d,{d:f,style:"stroke:"+m+";fill:"+n+";stroke-width:"+p+";"}))}
function _crc_drawOuterWall(c,d,b,e,f,a,g,h,k,n,m,p){a=Math.max(h,90);k=Math.min(k,270);a>k||(h=""+pathMoveToCirclePoint(b,e-g,f,a),h+=pathDrawArc(b,e-g,f,a,k),h+=pathLineToCirclePoint(b,e,f,k),h+=pathDrawArcCounterClock(b,e,f,k,a),h+=pathLineToCirclePoint(b,e-g,f,a),_crc_constructNode("path",c,d,{d:h,style:"stroke:"+m+";fill:"+n+";stroke-width:"+p+";"}))}
function _crc_donutPartOver(c){var d=Number(c.currentTarget.firstChild.getAttributeNS(null,"x")),b=Number(c.currentTarget.firstChild.getAttributeNS(null,"y"));c.currentTarget.setAttribute("transform","translate("+d/25+","+b/25+")");try{eval(c.currentTarget.getAttribute("onover"))}catch(e){}}function _crc_donutPartOut(c){c.currentTarget.setAttribute("transform","translate(0,0)");try{eval(c.currentTarget.getAttribute("onout"))}catch(d){}}
function _crc_donutPartDown(c){var d=Number(c.currentTarget.firstChild.getAttributeNS(null,"x")),b=Number(c.currentTarget.firstChild.getAttributeNS(null,"y")),b=b+map.Scale.normalY(.1);c.currentTarget.setAttribute("transform","translate("+d/5+","+b/5+")")}function _crc_donutPartUp(c){var d=Number(c.currentTarget.firstChild.getAttributeNS(null,"x")),b=Number(c.currentTarget.firstChild.getAttributeNS(null,"y"));c.currentTarget.setAttribute("transform","translate("+d/5+","+b/5+")")}
function _crc_donutPartDrawOut(c){if(c.firstChild){var d=Number(c.firstChild.getAttributeNS(null,"x")),b=Number(c.firstChild.getAttributeNS(null,"y"));if(d&&b)return c.setAttribute("transform","translate("+d+","+b+")"),!0}return!1}function _crc_donutPartDrawIn(c){if(c.firstChild){var d=Number(c.firstChild.getAttributeNS(null,"x")),b=Number(c.firstChild.getAttributeNS(null,"y"));if(d&&b)return c.setAttribute("transform","translate(0,0)"),!0}return!1}
function pathDrawArc(c,d,b,e,f){var a,g,h,k,n,m,p,q,t,r,l,u=" ";e%=360;if(e>f)return u+=pathDrawArc(c,d,b,e,360),u+=pathDrawArc(c,d,b,0,f);for(l=1;8>=l;l++)if(!(e>45*l||f<45*(l-1))&&(k=Math.max(e,45*(l-1)),g=Math.min(f,45*l),k!=g)){180<k&&(k=360-k);90<k&&(k=180-k);45<k&&(k=90-k);180<g&&(g=360-g);90<g&&(g=180-g);45<g&&(g=90-g);m=Math.PI*k/180;n=Math.PI*g/180;a=b*Math.sin(m);h=b*Math.cos(m);g=b*Math.sin(n);k=b*Math.cos(n);a=h+Math.tan(m)*a;h=k+Math.tan(n)*g;n=(h-a)/(Math.tan(n)-Math.tan(m));m=-Math.tan(m)*
n+a;switch(l){case 1:p=g;t=n;q=-k;r=-m;break;case 2:p=k;t=m;q=-g;r=-n;break;case 3:p=k;t=m;q=g;r=n;break;case 4:p=g;t=n;q=k;r=m;break;case 5:p=-g;t=-n;q=k;r=m;break;case 6:p=-k;t=-m;q=g;r=n;break;case 7:p=-k;t=-m;q=-g;r=-n;break;case 8:p=-g,t=-n,q=-k,r=-m}u+="Q"+String(c+t)+","+String(d+r)+" "+String(c+p)+","+String(d+q)}return u}
function pathDrawArcCounterClock(c,d,b,e,f){var a;a=""+pathDrawArc(c,d,b,f,e);e="";a=a.split("Q");for(var g=a.length-1;0<g;g--)for(var h=a[g].split(" "),k=1;0<=k;k--)if(g!=a.length-1||1!=k)e=0===k?e+(" Q"+h[k]):e+(" "+h[k]);return e+=pathAddCirclePoint(c,d,b,f)}function pathMoveToCirclePoint(c,d,b,e){var f;f=Math.PI*e/180;e=b*Math.sin(f);b*=Math.cos(f);return"M"+String(c+e)+","+String(d+-b)}
function pathLineToCirclePoint(c,d,b,e){var f;f=Math.PI*e/180;e=b*Math.sin(f);b*=Math.cos(f);return"L"+String(c+e)+","+String(d+-b)}function pathAddCirclePoint(c,d,b,e){var f;f=Math.PI*e/180;e=b*Math.sin(f);b*=Math.cos(f);return" "+String(c+e)+","+String(d+-b)};
