DonutCharts=new _DonutCharts;function _DonutCharts(){this.newChart=function(c,d,b,e,g,a){return new DonutChart(c,d,b,e,g,a)};this.partOver=_crc_donutPartOver;this.partOut=_crc_donutPartOut;this.partDown=_crc_donutPartDown;this.partUp=_crc_donutPartUp;this.partDrawOut=_crc_donutPartDrawOut;this.partDrawIn=_crc_donutPartDrawIn}
function DonutChart(c,d,b,e,g,a){this.targetDocument=c;this.targetGroup=d;this.mX=isNaN(b)?0:b;this.mY=isNaN(e)?0:e;this.nRadOuter=isNaN(g)?0:g;this.nRadInner=isNaN(a)?0:a;this.szStyle="flat";this.szLine=null;this.nLineWidth=1;this.partsA=[]}DonutChart.prototype.setCenter=function(c,d){this.mX=c;this.mY=d};DonutChart.prototype.setRadOuter=function(c){this.nRadOuter=isNaN(c)?0:c};DonutChart.prototype.setRadInner=function(c){this.nRadInner=isNaN(c)?0:c};
DonutChart.prototype.setStyle=function(c){this.szStyle=c};DonutChart.prototype.addStyle=function(c){this.szStyle+="|"+c};DonutChart.prototype.setLine=function(c){this.szLine=c};DonutChart.prototype.setLineWidth=function(c){this.nLineWidth=c};DonutChart.prototype.setMaxValue=function(c){this.nMaxValue=c};
DonutChart.prototype.addPart=function(c,d,b,e,g,a,f,k){this.partsA[this.partsA.length]={nPercent:c,nInfoValue:c,nHeight:d,color:b,nOffset:e,szText:g,szInfo:a,szOver:f,szOut:k};return this.partsA[this.partsA.length-1]};
DonutChart.prototype.realize=function(){var c=0,d=360,b=null,c=this.partsA[0],b=0,e=this.partsA.length-1;this.donutPartsA=[];for(var g=!1,a=0;a<this.partsA.length;a++)0<this.partsA[a].nPercent&&(this.szStyle.match(/BIGTOTOP/)&&this.partsA[a].nPercent>b&&(c=this.partsA[a],b=this.partsA[a].nPercent),g=!0);if(g||this.szStyle.match(/AUTOCOMPLETE/)){var f=0,k=0,h=0,m=g=b=0,l=0;if(this.szStyle.match(/VOLUME/)||this.szStyle.match(/STARBURST/)){for(a=0;a<this.partsA.length;a++)k+=this.partsA[a].nPercent,
l=Math.max(l,this.partsA[a].nPercent),f+=Math.sqrt(this.partsA[a].nPercent);f=Math.sqrt(this.nMaxValue*this.partsA.length);for(a=0;a<this.partsA.length;a++)this.partsA[a].nPercent=100/f*Math.sqrt(this.partsA[a].nPercent),this.szStyle.match(/VOLUME/)&&(this.partsA[a].nHeight*=this.partsA[a].nPercent/25);h=100/f*Math.sqrt(this.nMaxValue||100);b=100/f*Math.sqrt(this.nMaxValue/4||50);g=100/f*Math.sqrt(this.nMaxValue/2||50);m=100/f*Math.sqrt(this.nMaxValue/4*3||50)}else{for(a=0;a<this.partsA.length;a++)k+=
this.partsA[a].nPercent;if(100!=k)if(this.szStyle.match(/AUTOCOMPLETE/)&&100>k)this.addPart(Math.floor(1E5*(100-k))/1E5,this.partsA[0]?this.partsA[0].nHeight:0,"#eeeeee",0,"");else for(a=0;a<this.partsA.length;a++)this.partsA[a].nPercent=this.partsA[a].nPercent/k*100}if(this.szStyle.match(/SYMMETRIC/))if(this.szStyle.match(/STARBURST/))d=360-Math.floor(360/this.partsA.length/2);else if(this.szStyle.match(/BIGTOTOP/)){d=360;for(a=0;a<this.partsA.length&&this.partsA[a]!=c;a++)d-=100>this.partsA[a].nPercent?
Math.floor(3.6*this.partsA[a].nPercent):0;d-=100>this.partsA[a].nPercent?Math.floor(1.8*c.nPercent):0}else 100>this.partsA[0].nPercent&&(d=360-Math.floor(1.8*this.partsA[0].nPercent));this.szStyle.match(/HALF/)&&(d=270);nMaxAngle=this.szStyle.match(/HALF/)?180:360;k=f=0;this.szStyle.match(/STARBURST/)&&(f=nMaxAngle/this.partsA.length,this.nRadOuter+=this.nRadInner/this.partsA.length*3,this.szStyle.match(/XLRAYS/)?(f=Math.min(nMaxAngle/4,nMaxAngle/this.partsA.length),k=.1*f*(this.szStyle.match(/HALF/)?
.5:1),this.nRadInner=Math.max(35,this.nRadInner)):this.szStyle.match(/LRAYS/)?(f=Math.min(nMaxAngle/4,nMaxAngle/this.partsA.length),k=.2*f*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(35,this.nRadInner)):this.szStyle.match(/XSRAYS/)?(f=Math.min(nMaxAngle/12,nMaxAngle/this.partsA.length),k=.4*f*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(35,this.nRadInner)):this.szStyle.match(/SRAYS/)?(f=Math.min(nMaxAngle/10,nMaxAngle/this.partsA.length),k=.33*f*(this.szStyle.match(/HALF/)?
.5:1),this.nRadInner=Math.max(35,this.nRadInner)):this.szStyle.match(/RAYS/)&&(f=nMaxAngle/this.partsA.length,k=.35*f*(this.szStyle.match(/HALF/)?.5:1),this.nRadInner=Math.max(35,this.nRadInner)));for(a=this.nRadOuterMaxR=this.nRadOuterMaxL=0;a<this.partsA.length;a++)this.szStyle.match(/STARBURST/)||(f=this.partsA[a].nPercent/100*nMaxAngle,k=0),c=d%360,d=c+f,360<d&&(d%=360),this.szStyle.match(/DIRECTION/)?this.donutPartsA[a]=this.partsA[a].nAngle?{nStartAngle:this.partsA[a].nAngle-1,nEndAngle:this.partsA[a].nAngle+
1,color:this.partsA[a].color,nHeight:this.partsA[a].nHeight,nOffset:this.partsA[a].nOffset}:{}:this.donutPartsA[a]={nStartAngle:c+k,nEndAngle:d-k,color:this.partsA[a].color,nHeight:this.partsA[a].nHeight,nOffset:this.partsA[a].nOffset},this.szStyle.match(/3D/)||(this.donutPartsA[a].nHeight=0),this.szStyle.match(/STARBURST/)&&(this.donutPartsA[a].nRadOuter=Math.max(1,this.nRadInner+this.partsA[a].nPercent/100*this.partsA.length*(this.nRadOuter-this.nRadInner))),180>=c&&180<=d&&(e=a),180>=c?this.nRadOuterMaxR=
Math.max(this.nRadOuterMaxR,this.donutPartsA[a].nRadOuter):this.nRadOuterMaxL=Math.max(this.nRadOuterMaxL,this.donutPartsA[a].nRadOuter),this.partsA[a].nOpacity&&(this.donutPartsA[a].nOpacity=this.partsA[a].nOpacity);this.szStyle.match(/STARBURST/)&&this.szStyle.match(/POLAR/)&&(d=Math.max(1,this.nRadInner+h/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:white;fill-opacity:1;stroke:#dddddd;stroke-width:20px;"),d.setAttributeNS(null,
"tooltip","75-100"),d=Math.max(1,this.nRadInner+m/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:none;stroke:#dddddd;stroke-width:20px;stroke-dasharray:50 50"),d.setAttributeNS(null,"tooltip","50-75"),d=Math.max(1,this.nRadInner+g/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:none;stroke:#dddddd;stroke-width:10px;"),d.setAttributeNS(null,"tooltip",
"25-50"),d=Math.max(1,this.nRadInner+b/100*this.partsA.length*(this.nRadOuter-this.nRadInner)),d=map.Dom.newShape("circle",this.targetGroup,this.mX,this.mY,d,"fill:none;stroke:#dddddd;stroke-width:20px;stroke-dasharray:50 50"),d.setAttributeNS(null,"tooltip","0-25"));if(this.szStyle.match(/HALF/))for(e=this.donutPartsA.length,a=0;a<e;a++)270<this.donutPartsA[a].nEndAngle&&(this.donutPartsA.push(this.donutPartsA.splice(a,1)[0]),this.partsA.push(this.partsA.splice(a,1)[0]),e--,a=-1);this.frameGroup=
_crc_constructNode("g",this.targetDocument,this.targetGroup,{});for(a=0;a<e;a++)b=_crc_drawDonut(this.targetDocument,this.frameGroup,this.mX,this.mY,this.donutPartsA[a].nRadOuter?this.donutPartsA[a].nRadOuter:this.nRadOuter,this.nRadInner,this.donutPartsA[a].nHeight,this.donutPartsA[a].nStartAngle,this.donutPartsA[a].nEndAngle,this.donutPartsA[a].color,null,null,this.szLine,this.nLineWidth,this.szStyle,this.donutPartsA[a].nOffset),this.szStyle.match(/SILENT/)||(b.setAttributeNS(szMapNs,"tooltip",
this.partsA[a].szInfo?this.partsA[a].szText+this.partsA[a].szInfo:Math.round(10*this.partsA[a].nInfoValue)/10+" % "),this.partsA[a].szOver&&b.setAttributeNS(szMapNs,"onover",this.partsA[a].szOver),this.partsA[a].szOut&&b.setAttributeNS(szMapNs,"onout",this.partsA[a].szOut)),this.donutPartsA[a].nOpacity&&(b.style.setProperty("stroke-opacity","0.6",""),b.style.setProperty("fill-opacity","0.1","")),this.donutPartsA[a].objNode=b;for(a=this.donutPartsA.length-1;a>=e;a--)b=_crc_drawDonut(this.targetDocument,
this.frameGroup,this.mX,this.mY,this.donutPartsA[a].nRadOuter?this.donutPartsA[a].nRadOuter:this.nRadOuter,this.nRadInner,this.donutPartsA[a].nHeight,this.donutPartsA[a].nStartAngle,this.donutPartsA[a].nEndAngle,this.donutPartsA[a].color,null,null,this.szLine,this.nLineWidth,this.szStyle,this.donutPartsA[a].nOffset),this.szStyle.match(/SILENT/)||(b.setAttributeNS(szMapNs,"tooltip",this.partsA[a].szInfo?this.partsA[a].szText+this.partsA[a].szInfo:Math.round(10*this.partsA[a].nInfoValue)/10+" % "),
this.partsA[a].szOver&&b.setAttributeNS(szMapNs,"onover",this.partsA[a].szOver),this.partsA[a].szOut&&b.setAttributeNS(szMapNs,"onout",this.partsA[a].szOut)),this.donutPartsA[a].nOpacity&&(b.style.setProperty("stroke-opacity","0.6",""),b.style.setProperty("fill-opacity","0.1","")),this.donutPartsA[a].objNode=b;this.szStyle.match(/3D/)&&this.frameGroup.setAttributeNS(null,"transform","matrix(1 0 0 0.5 0 0)")}else _crc_constructNode("circle",this.targetDocument,this.targetGroup,{id:"emptypie",cx:this.mX,
cy:this.mY,r:this.nRadOuter,style:"fill:none;stroke:gray"}),_crc_newText(this.targetDocument,this.targetGroup,this.mX,this.mY,"fill:gray;font-size:"+this.nRadOuter/5+";text-anchor:middle;","Pie error: no values !")};
DonutChart.prototype.getTextPosition=function(c){if(!this.donutPartsA[c])return null;var d=this.donutPartsA[c].nRadOuter?this.donutPartsA[c].nRadOuter:this.nRadOuter,b=this.nRadOuter,e=0,g=this.donutPartsA[c].nStartAngle,b=this.donutPartsA[c].nEndAngle;if(g==b)return null;var e=g<b?(g+b)/2:Math.min(360,(g+b+360)/2)%360,b=180>e?this.nRadOuterMaxR?this.nRadOuterMaxR+(this.nRadOuterMaxL>this.nRadOuterMaxR?Math.min(this.nRadOuterMaxR,(this.nRadOuterMaxL-this.nRadOuterMaxR)/2):0):this.nRadOuter:this.nRadOuterMaxL?
this.nRadOuterMaxL+(this.nRadOuterMaxR>this.nRadOuterMaxL?Math.min(this.nRadOuterMaxL,(this.nRadOuterMaxR-this.nRadOuterMaxL)/2):0):this.nRadOuter,g=Math.sin(e/180*Math.PI)*d,d=-Math.cos(e/180*Math.PI)*d-this.donutPartsA[c].nHeight,a=Math.sin(e/180*Math.PI)*b*1.1;c=-Math.cos(e/180*Math.PI)*b*1.1-this.donutPartsA[c].nHeight;return{x:a,y:c,lx:g,ly:d}};function _crc_createSingleNode(c,d,b){c=d.createElementNS("http://www.w3.org/2000/svg",c);b.appendChild(c);return c}
function _crc_constructNode(c,d,b,e){c=_crc_createSingleNode(c,d,b);for(var g in e)c.setAttribute(g,e[g]);return c}function _crc_newText(c,d,b,e,g,a){a||(a="(undefined)");d=_crc_constructNode("text",c,d,{x:String(b),y:String(e),style:g});c=c.createTextNode(a);d.appendChild(c);return d}
function _crc_drawDonut(c,d,b,e,g,a,f,k,h,m,l,n,p,r,q,u){null==u&&(u=0);var t=0,t=k<h?(k+h)/2:Math.max(360,(k+h+360)/2),v=Math.sin(t/180*Math.PI),t=-Math.cos(t/180*Math.PI);b+=u*v;e+=u*t;null==q&&(q="3D");null==m&&(m="#ffff00");null==l&&(l=ColorScheme.getDerivateColor(m,.7));null==n&&(n=ColorScheme.getDerivateColor(m,.7));null==p&&(p=ColorScheme.getBorderColor(m));d=q.match(/SILENT/)?_crc_constructNode("g",c,d,{}):_crc_constructNode("g",c,d,{onmouseover:"DonutCharts.partOver(evt)",onmouseout:"DonutCharts.partOut(evt)",
onmousedown:"DonutCharts.partDown(evt)",onmouseup:"DonutCharts.partUp(evt)"});if(0>k||0>h||k==h)return d;_crc_constructNode("rect",c,d,{id:"extractPoint",x:v*g/3,y:t*g/3,width:0,height:0,style:"fill:none;stroke:none"});q.match(/3D/)&&(k>h?(_crc_drawInnerWall(c,d,b,e,g,a,f,k,360,l,"none",0),_crc_drawInnerWall(c,d,b,e,g,a,f,0,h,l,"none",0)):_crc_drawInnerWall(c,d,b,e,g,a,f,k,h,l,p,r));q.match(/3D/)&&180<k&&(szPathD="",szPathD+=pathMoveToCirclePoint(b,e-f,g,k),szPathD+=pathLineToCirclePoint(b,e-f,a,
k),szPathD+=pathLineToCirclePoint(b,e,a,k),szPathD+=pathLineToCirclePoint(b,e,g,k),szPathD+=pathLineToCirclePoint(b,e-f,g,k),newPath=_crc_constructNode("path",c,d,{d:szPathD,style:"stroke:"+p+";fill:"+n+";stroke-width:"+r+";"}));q.match(/3D/)&&180>h&&(szPathD="",szPathD+=pathMoveToCirclePoint(b,e-f,g,h),szPathD+=pathLineToCirclePoint(b,e-f,a,h),szPathD+=pathLineToCirclePoint(b,e,a,h),szPathD+=pathLineToCirclePoint(b,e,g,h),szPathD+=pathLineToCirclePoint(b,e-f,g,h),newPath=_crc_constructNode("path",
c,d,{d:szPathD,style:"stroke:"+p+";fill:"+n+";stroke-width:"+r+";"}));q.match(/3D/)&&(k>h?(_crc_drawOuterWall(c,d,b,e,g,a,f,k,360,l,"none",0),_crc_drawOuterWall(c,d,b,e,g,a,f,0,h,l,"none",0)):_crc_drawOuterWall(c,d,b,e,g,a,f,k,h,l,p,r));360<=h-k?(szPathD="",szPathD+=pathMoveToCirclePoint(b,e-f,g,k),szPathD+=pathDrawArc(b,e-f,g,k,h),szPathD+=pathMoveToCirclePoint(b,e-f,a,h),a&&(szPathD+=pathDrawArcCounterClock(b,e-f,a,h,k))):(szPathD="",szPathD+=pathMoveToCirclePoint(b,e-f,g,k),szPathD+=pathDrawArc(b,
e-f,g,k,h),szPathD+=pathLineToCirclePoint(b,e-f,a,h),a&&(szPathD+=pathDrawArcCounterClock(b,e-f,a,h,k)),szPathD+=pathLineToCirclePoint(b,e-f,g,k));newPath=_crc_constructNode("path",c,d,{d:szPathD,style:"stroke:"+p+";fill:"+m+";stroke-width:"+r+";"});return d}
function _crc_drawInnerWall(c,d,b,e,g,a,f,k,h,m,l,n){90<k&&270>k&&270>h||(szPathD="",szPathD+=pathMoveToCirclePoint(b,e-f,a,k),szPathD+=pathDrawArc(b,e-f,a,k,h),szPathD+=pathLineToCirclePoint(b,e,a,h),szPathD+=pathDrawArcCounterClock(b,e,a,h,k),szPathD+=pathLineToCirclePoint(b,e-f,a,k),newPath=_crc_constructNode("path",c,d,{d:szPathD,style:"stroke:"+l+";fill:"+m+";stroke-width:"+n+";"}))}
function _crc_drawOuterWall(c,d,b,e,g,a,f,k,h,m,l,n){a=Math.max(k,90);h=Math.min(h,270);a>h||(szPathD="",szPathD+=pathMoveToCirclePoint(b,e-f,g,a),szPathD+=pathDrawArc(b,e-f,g,a,h),szPathD+=pathLineToCirclePoint(b,e,g,h),szPathD+=pathDrawArcCounterClock(b,e,g,h,a),szPathD+=pathLineToCirclePoint(b,e-f,g,a),newPath=_crc_constructNode("path",c,d,{d:szPathD,style:"stroke:"+l+";fill:"+m+";stroke-width:"+n+";"}))}
function _crc_donutPartOver(c){var d=Number(c.currentTarget.firstChild.getAttributeNS(null,"x")),b=Number(c.currentTarget.firstChild.getAttributeNS(null,"y"));c.currentTarget.setAttribute("transform","translate("+d/25+","+b/25+")");try{eval(c.currentTarget.getAttribute("onover"))}catch(e){}}function _crc_donutPartOut(c){c.currentTarget.setAttribute("transform","translate(0,0)");try{eval(c.currentTarget.getAttribute("onout"))}catch(d){}}
function _crc_donutPartDown(c){var d=Number(c.currentTarget.firstChild.getAttributeNS(null,"x")),b=Number(c.currentTarget.firstChild.getAttributeNS(null,"y")),b=b+map.Scale.normalY(.1);c.currentTarget.setAttribute("transform","translate("+d/5+","+b/5+")")}function _crc_donutPartUp(c){var d=Number(c.currentTarget.firstChild.getAttributeNS(null,"x")),b=Number(c.currentTarget.firstChild.getAttributeNS(null,"y"));c.currentTarget.setAttribute("transform","translate("+d/5+","+b/5+")")}
function _crc_donutPartDrawOut(c){if(c.firstChild){var d=Number(c.firstChild.getAttributeNS(null,"x")),b=Number(c.firstChild.getAttributeNS(null,"y"));if(d&&b)return c.setAttribute("transform","translate("+d+","+b+")"),!0}return!1}function _crc_donutPartDrawIn(c){if(c.firstChild){var d=Number(c.firstChild.getAttributeNS(null,"x")),b=Number(c.firstChild.getAttributeNS(null,"y"));if(d&&b)return c.setAttribute("transform","translate(0,0)"),!0}return!1}
function pathDrawArc(c,d,b,e,g){var a,f,k,h,m,l,n,p,r,q,u,t=" ";e%=360;if(e>g)return t+=pathDrawArc(c,d,b,e,360),t+=pathDrawArc(c,d,b,0,g);for(u=1;8>=u;u++)if(!(e>45*u||g<45*(u-1))&&(h=Math.max(e,45*(u-1)),f=Math.min(g,45*u),h!=f)){180<h&&(h=360-h);90<h&&(h=180-h);45<h&&(h=90-h);180<f&&(f=360-f);90<f&&(f=180-f);45<f&&(f=90-f);l=Math.PI*h/180;m=Math.PI*f/180;a=b*Math.sin(l);k=b*Math.cos(l);f=b*Math.sin(m);h=b*Math.cos(m);a=k+Math.tan(l)*a;k=h+Math.tan(m)*f;m=(k-a)/(Math.tan(m)-Math.tan(l));l=-Math.tan(l)*
m+a;switch(u){case 1:n=f;r=m;p=-h;q=-l;break;case 2:n=h;r=l;p=-f;q=-m;break;case 3:n=h;r=l;p=f;q=m;break;case 4:n=f;r=m;p=h;q=l;break;case 5:n=-f;r=-m;p=h;q=l;break;case 6:n=-h;r=-l;p=f;q=m;break;case 7:n=-h;r=-l;p=-f;q=-m;break;case 8:n=-f,r=-m,p=-h,q=-l}t+="Q"+String(c+r)+","+String(d+q)+" "+String(c+n)+","+String(d+p)}return t}
function pathDrawArcCounterClock(c,d,b,e,g){var a;a=""+pathDrawArc(c,d,b,g,e);e="";a=a.split("Q");for(var f=a.length-1;0<f;f--)for(var k=a[f].split(" "),h=1;0<=h;h--)if(f!=a.length-1||1!=h)e=0==h?e+(" Q"+k[h]):e+(" "+k[h]);return e+=pathAddCirclePoint(c,d,b,g)}function pathMoveToCirclePoint(c,d,b,e){var g;g=Math.PI*e/180;e=b*Math.sin(g);b*=Math.cos(g);return"M"+String(c+e)+","+String(d+-b)}
function pathLineToCirclePoint(c,d,b,e){var g;g=Math.PI*e/180;e=b*Math.sin(g);b*=Math.cos(g);return"L"+String(c+e)+","+String(d+-b)}function pathAddCirclePoint(c,d,b,e){var g;g=Math.PI*e/180;e=b*Math.sin(g);b*=Math.cos(g);return" "+String(c+e)+","+String(d+-b)};
