	

	// -----------------------------------------------------------
	// T H E M E S 
	// -----------------------------------------------------------

	var num_totale_dyn = function(){return(
{
	"layer": "generic",
	"field": "$item$",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|EXACT|VALUES|AGGREGATE|RECT|SUM|RELOCATE",
		"colorscheme": [
			"#104482"],
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"units": "",
		"normalsizevalue": "10",
		"scale": "1",
		"linecolor": "white",
		"linewidth": "3",
		"gridwidthpx": "15",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Incidenti 2011 - 2015"
		}
	}
	)};
	
	var num_totale = function(){return(
{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|EXACT|GLOW|AGGREGATE|RECT|SUM|RELOCATE|VALUES",
		"colorscheme": [
			"18",
			"fruit"],
		"shadow": "false",
		"filter": "WHERE \\\"TIPO_VA\\\" = \\\"VELOCIPEDE\\\"",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "1",
		"linecolor": "black",
		"linewidth": "1",
		"gridwidth": "15px",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "2° veicolo coinvolto"
		}
	}
	)};


	var num_totale_II = function(){return(
	{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|CENTER|SORT|DOWN|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RELOCATE|EXACT|SUM|SUM",
		"colorscheme": [
			"17",
			"fruit"],
		"fillopacity": "0.5",
		"shadow": "false",
		"filter": "WHERE \\\"TIPO_VA\\\" = \\\"VELOCIPEDE\\\"",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"circle",
			"triangle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle"],
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "1.3",
		"linewidth": "5",
		"gridwidth": "15px",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"markclasses": [],
		"title": "2° veicolo coinvolto"
		}
	}
	)};

	var num_totale_III = function(){return(
	{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|STAR|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RELOCATE|EXACT|SUM|VALUES|VALUEBACKGROUND|SUM|SORT|DOWN",
		"colorscheme": [
			"18",
			"fruit"],
		"fillopacity": "0.6534",
		"shadow": "true",
		"filter": "WHERE \\\"TIPO_VA\\\" = \\\"VELOCIPEDE\\\"",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"circle",
			"triangle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle"],
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "50",
		"scale": "3.8890136246545195",
		"linewidth": "5",
		"clipparts": "3",
		"gridwidthpx": "25",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "2° veicolo coinvolto"
		}
	}
	)};

	var num_totale_IV = function(){return(
	{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|STAR|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RELOCATE|EXACT|SUM|VALUES|VALUEBACKGROUND|SUM|SORT|DOWN",
		"colorscheme": [
			"18",
			"fruit"],
		"fillopacity": "0.6534",
		"shadow": "true",
		"filter": "WHERE \\\"TIPO_VA\\\" = \\\"VELOCIPEDE\\\"",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"auto_symbol",
			"bus_symbol",
			"bus_symbol",
			"bus_symbol",
			"bus_symbol",
			"auto_symbol",
			"auto_symbol",
			"auto_symbol",
			"moto_symbol",
			"none",
			"moto_symbol",
			"moto_symbol",
			"moto_symbol",
			"moto_symbol",
			"bus_symbol",
			"auto_symbol",
			"bici_symbol",
			"none"],
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "50",
		"scale": "5.775185232611961",
		"linewidth": "5",
		"clipparts": "3",
		"gridwidthpx": "25",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"markclasses": [],
		"title": "2° veicolo coinvolto"
		}
	}
	)};



	var num_totale_heat = function(){return(
{
	"layer": "generic",
	"field": "$item$",
	"field100": "",
	"style": {
		"type": "RELOCATE|GLOW|VALUEBACKGROUND|NOINLINETEXT|VALUES|CHART|SYMBOLS|SIZE|CLEAR|LOG|AGGREGATE|RECT|SUM",
		"colorscheme": [
			"7",
			"RGB(54,166,177)",
			"RGB(185,64,35)",
			"3low",
			"RGB(221,167,41)"],
		"fillopacity": "0.4",
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "0.6468660000000002",
		"linecolor": "white",
		"linewidth": "3",
		"gridwidthpx": "15",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Numero incidenti per griglia fissa (schermo)"
		}
	}
	)};
	
	var num_totale_pericolosita = function(){return(
	{
	"layer": "generic",
	"field": "$item$",
	"field100": "",
	"style": {
		"type": "NORMALIZE|CHART|SYMBOL|EQUIDISTANT|ZEROISVALUE|NEGATIVEISVALUE|SUM|AGGREGATE|FILTER|DOPACITY|GRIDSIZE|DTEXT|VALUEBACKGROUND|VALUES",
		"colorscheme": [
			"red"],
		"fillopacity": "0.6534000000000001",
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"hexagon"],
		"units": "",
		"normalsizevalue": "10",
		"scale": "0.99",
		"linecolor": "black",
		"linewidth": "0.5",
		"valuedecimals": "2",
		"gridwidthpx": "28.07750572827257",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Incidenti 2011 - 2015"
		}
	}
	)};

	var num_totale_raw = function(){return(
{
	"layer": "generic",
	"field": "$item$",
	"field100": "",
	"style": {
		"name": "demo_raw",
		"type": "CHART|SYMBOL|VALUES|RECT|SUM|FORCE",
		"colorscheme": [
			"#104482"],
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"units": "",
		"normalsizevalue": "10",
		"scale": "1",
		"linecolor": "white",
		"linewidth": "3",
		"gridwidthpx": "15",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Incidenti 2011 - 2015"
		}
	}
	)};
	var num_totale_raw_grid = function(){return(
{
	"layer": "generic",
	"field": "$item$",
	"field100": "",
	"style": {
		"name": "demo_grid",
		"type": "CHART|SYMBOL|EQUIDISTANT|SUM|AGGREGATE|RECT|GRIDSIZE|NOLEGEND|FORCE",
		"colorscheme": [
			"gray"],
		"fillopacity": "0.00001",
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"square"],
		"units": "",
		"scale": "1",
		"linecolor": "black",
		"linewidth": "1",
		"gridwidthpx": "15",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Incidenti 2011 - 2015"
		}
	}
	)};


	var num_totale_donut = function(){return(
	{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|PIE|DONUT|SORT|SIZE|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RECT|EXACT|SUM|SUM",
		"colorscheme": [
			"17",
			"fruit"],
		"fillopacity": "0.99",
		"shadow": "true",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"circle",
			"triangle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle"],
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "1.2487748130000003",
		"linewidth": "5",
		"gridwidth": "1250.7760546875006",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"markclasses": [],
		"title": "2° veicolo coinvolto"
		}
	}
	)};

	var num_totale_donut_centervalue = function(){return(
{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|PIE|CENTERVALUE|SORT|SIZE|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RECT|EXACT|SUM|SUM",
		"colorscheme": [
			"17",
			"fruit"],
		"fillopacity": "0.99",
		"shadow": "true",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"circle",
			"triangle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle"],
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "1.2487748130000003",
		"linewidth": "5",
		"centerpart": "max",
		"gridwidth": "1250.7760546875006",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"markclasses": [],
		"title": "2° veicolo coinvolto"
		}
	}
	)};

	var num_totale_donuts_many = function(){return(
	{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|PIE|DONUT|SORT|SIZE|AGGREGATE|RELOCATE|EXACT|SUM",
		"colorscheme": [
			"17",
			"fruit"],
		"filter": "WHERE \\\"TIPO_VA\\\" is \\\"VELOCIPEDE\\\"",
		"fillopacity": "0.675",
		"shadow": "true",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"circle",
			"triangle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle"],
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "1.3",
		"linewidth": "5",
		"gridwidthpx": "30",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"markclasses": [],
		"title": "2° veicolo coinvolto"
		}
	}
	)};
	
	var num_totale_year_plot = function(){return(
	{
	"layer": "generic",
	"field": "ANNO",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|EXACT|PLOT|LINES|AREA|BOX|GRID|TITLE|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RECT|SUM|FIXSIZE|GRIDSIZE",
		"colorscheme": [
			"#bb2233",
			"#bb2233",
			"#bb2233"],
		"fillopacity": "0.2",
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"2012",
			"2013",
			"2014"],
		"xaxis": [
			"2012",
			"2013",
			"2014"],
		"units": "",
		"normalsizevalue": "4",
		"scale": "0.85",
		"linecolor": "black",
		"linewidth": "1",
		"bordercolor": "black",
		"boxopacity": "0.2",
		"boxmargin": "3",
		"gridwidthpx": "100",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Incidenti per anni"
		}
	}
	)};

	var num_totale_year_plot_lollipop = function(){return(
	{
	"layer": "generic",
	"field": "ANNO",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|EXACT|PLOT|LOLLIPOP|BOX|GRID|TITLE|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RECT|SUM|FIXSIZE|GRIDSIZE|VALUES|DTEXT|VALUEBACKGROUND",
		"colorscheme": [
			"3",
			"pastel"],
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"2012",
			"2013",
			"2014"],
		"xaxis": [
			"'12",
			"'13",
			"'14"],
		"units": "",
		"normalsizevalue": "1",
		"scale": "0.9",
		"rangescale": "0.9",
		"linecolor": "black",
		"linewidth": "1",
		"bordercolor": "black",
		"boxopacity": "0.2",
		"boxmargin": "3",
		"gridwidthpx": "100",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Incidenti per anni"
		}
	}
	)};

	var num_totale_year_2012_2014_compare_old = function(){return(
	{
	"layer": "generic",
	"field": "ANNO",
	"field100": "",
	"style": {
		"type": "CHART|BAR|TRENDLINE|SIZE|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RELOCATE|EXACT|SUM|VALUES|VALUEBACKGROUND|SUM",
		"colorscheme": [
			"2",
			"#5EB6BA",
			"#DD8356",
			"3colors",
			"#95B526"],
		"shadow": "false",
		"filter": "WHERE ANNO IN (2012,2014)",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"2012",
			"2014"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "0.9702990000000002",
		"linecolor": "white",
		"linewidth": "3",
		"gridwidthpx": "134.31453648828585",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Confronto incidenti 2012/2014"
		}
	}
	)};

	var num_totale_year_2012_2014_compare = function(){return(
{
	"layer": "generic",
	"field": "ANNO",
	"field100": "",
	"style": {
		"type": "CHART|BAR|3D|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RECT|RELOCATE|EXACT|SUM|VALUEBACKGROUND|SUM",
		"colorscheme": [
			"2",
			"#5EB6BA",
			"#DD8356",
			"3colors",
			"#95B526"],
		"shadow": "true",
		"filter": "WHERE ANNO IN (2012,2014)",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"2012",
			"2014"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "1.5",
		"rangescale": "0.5",
		"linecolor": "white",
		"linewidth": "3",
		"gridwidth": "500",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Confronto incidenti 2012/2014"
		}
	}
	)};

	var num_totale_year_2012_2013_2014_compare = function(){return(
{
	"layer": "generic",
	"field": "ANNO",
	"field100": "",
	"style": {
		"type": "CHART|BAR|3D|SPACED|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RECT|RELOCATE|EXACT|SUM|VALUEBACKGROUND|SUM",
		"colorscheme": [
			"3",
			"#5EB6BA",
			"#DD8356",
			"3colors",
			"#95B526"],
		"shadow": "true",
		"filter": "WHERE ANNO IN (2012,2013,2014)",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"2012",
			"2013",
			"2014"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "1.5",
		"rangescale": "0.5",
		"linecolor": "white",
		"linewidth": "3",
		"gridwidth": "500",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Confronto incidenti 2012/2013/2014"
		}
	}
	)};

	var num_totale_year_2012_2014_compare_II = function(){return(
{
	"layer": "generic",
	"field": "ANNO",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|BOTTOM|SORT|UP|RINGS|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RELOCATE|EXACT|SUM|VALUEBACKGROUND|SUM|DTEXT",
		"colorscheme": [
			"2",
			"#5EB6BA",
			"#DD8356",
			"3colors",
			"#95B526"],
		"shadow": "false",
		"filter": "WHERE ANNO IN (2012,2014)",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"2012",
			"2014"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "1.4408940150000005",
		"linecolor": "white",
		"linewidth": "3",
		"gridwidthpx": "15.373911405999971",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Confronto incidenti 2012/2014"
		}
	}
	)};

	var num_totale_year_2012_2014_compare_III = function(){return(
	{
	"layer": "generic",
	"field": "ANNO",
	"field100": "",
	"style": {
		"type": "GLOW|CHART|BUBBLE|EXACT|SUM",
		"colorscheme": [
			"2",
			"#DD8356",
			"#5EB6BA",
			"3colors",
			"#95B526"],
		"shadow": "false",
		"filter": "WHERE ANNO IN (2012,2014)",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"2012",
			"2014"],
		"units": "",
		"scale": "1.4264850748500002",
		"linecolor": "white",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Confronto incidenti 2012/2014"
		}
	}
	)};

	var num_totale_year_2012_2014_compare_IV = function(){return(
	{
	"layer": "generic",
	"field": "ANNO",
	"field100": "",
	"style": {
		"type": "GLOW|CHART|SYMBOL|EXACT|SEQUENCE|STAR|SORT|RANDOM|AGGREGATE|RECT|RELOCATE|SUM|VALUES",
		"colorscheme": [
			"2",
			"#5EB6BA",
			"#DD8356",
			"3colors",
			"#95B526"],
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"2012",
			"2014"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "1",
		"textcolor": "white",
		"linecolor": "white",
		"linewidth": "3",
		"gridwidthpx": "15.373911405999971",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Confronto incidenti 2012/2014"
		}
	}
	)};

	var num_totale_year_2012_2014_compare_V = function(){return(
	{
	"layer": "generic",
	"field": "ANNO",
	"field100": "",
	"style": {
		"type": "CHART|WAFFLE|EXACT|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RECT|SUM|GRIDSIZE",
		"colorscheme": [
			"#5EB6BA",
			"#DD8356"],
		"shadow": "false",
		"filter": "WHERE ANNO IN (2012,2014)",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"square"],
		"values": [
			"2012",
			"2014"],
		"units": "",
		"normalsizevalue": "0.5",
		"scale": "0.95",
		"linecolor": "white",
		"linewidth": "3",
		"gridwidthpx": "65",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Confronto incidenti 2012/2014"
		}
	}
	)};

	var num_totale_giorno_della_settimana = function(){return(
{
	"layer": "generic",
	"field": "GIORNO",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|EXACT|PLOT|LINES|AREA|BOX|GRID|TITLE|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RECT|SUM|FIXSIZE|GRIDSIZE",
		"colorscheme": [
			"#0079C6",
			"#0079C6",
			"#0079C6",
			"#0079C6",
			"#0079C6",
			"RGB(237,124,137)",
			"RGB(237,124,137)"],
		"fillopacity": "0.75",
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"LUNEDI'",
			"MARTEDI'",
			"MERCOLEDI'",
			"GIOVEDI'",
			"VENERDI'",
			"SABATO",
			"DOMENICA"],
		"xaxis": [
			"L",
			"M",
			"M",
			"G",
			"V",
			"S",
			"D"],
		"units": "",
		"normalsizevalue": "100",
		"scale": "0.9",
		"rangescale": "0.85",
		"linecolor": "black",
		"linewidth": "1",
		"bordercolor": "black",
		"boxopacity": "0.2",
		"boxmargin": "3",
		"gridwidthpx": "100",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Incidenti per giorno della settimana"
		}
	}
	)};

	var num_totale_mese = function(){return(
{
	"layer": "generic",
	"field": "MESE",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|EXACT|PLOT|LINES|AREA|BOX|GRID|TITLE|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|RECT|SUM|FIXSIZE|GRIDSIZE",
		"colorscheme": [
			"RGB(193,218,231)",
			"RGB(193,218,231)",
			"RGB(193,218,231)",
			"RGB(184,217,97)",
			"RGB(184,217,97)",
			"RGB(184,217,97)",
			"RGB(217,84,97)",
			"RGB(217,84,97)",
			"RGB(217,84,97)",
			"RGB(217,184,97)",
			"RGB(217,184,97)",
			"RGB(217,184,97)"],
		"fillopacity": "0.66",
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"GENNAIO",
			"FEBBRAIO",
			"MARZO",
			"APRILE",
			"MAGGIO",
			"GIUGNO",
			"LUGLIO",
			"AGOSTO",
			"SETTEMBRE",
			"OTTOBRE",
			"NOVEMBRE",
			"DICEMBRE"],
		"xaxis": [
			"G",
			"F",
			"M",
			"A",
			"M",
			"G",
			"L",
			"A",
			"S",
			"O",
			"N",
			"D"],
		"units": "",
		"normalsizevalue": "100",
		"scale": "0.9",
		"rangescale": "0.85",
		"linecolor": "black",
		"linewidth": "1",
		"bordercolor": "black",
		"boxopacity": "0.2",
		"boxmargin": "3",
		"gridwidthpx": "100",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Incidenti per mese"
		}
	}
	)};

	var num_totale_fasce_orarie = function(){return(
{
	"layer": "generic",
	"field": "ORA",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|EXACT|PLOT|LINES|AREA|BOX|GRID|TITLE|AGGREGATE|RECT|SUM|FIXSIZE|GRIDSIZE|NOSORT",
		"colorscheme": [
			"#5566dd",
			"#5566dd",
			"#5566dd",
			"#bbccff",
			"#bbccff",
			"#bbccff",
			"#5566dd",
			"#5566dd"],
		"fillopacity": "0.75",
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"dbtableExt": "preprocess.js",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"circle"],
		"values": [
			"0-3",
			"3-6",
			"6-9",
			"9-12",
			"12-15",
			"15-18",
			"18-21",
			"21-24"],
		"xaxis": [
			"0-3",
			"3-6",
			"6-9",
			"9-12",
			"12-15",
			"15-18",
			"18-21",
			"21-24"],
		"units": "",
		"normalsizevalue": "100",
		"scale": "0.9",
		"rangescale": "0.85",
		"linecolor": "black",
		"linewidth": "1",
		"bordercolor": "black",
		"boxopacity": "0.2",
		"boxmargin": "3",
		"gridwidth": "500",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Incidenti per fascia oraria"
		}
	}
	)};

	var num_totale_scacchi = function(){return(
	{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|SEQUENCE|CENTER|SORT|UP|RINGS|AGGREGATE|RECT|GAP|GRIDSIZE|EXACT|SUM|SUM",
		"colorscheme": [
			"18",
			"fruit"],
		"fillopacity": "0.6549518250000003",
		"shadow": "true",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"circle",
			"triangle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle"],
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "5",
		"scale": "1",
		"linewidth": "5",
		"gridwidthpx": "20",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"markclasses": [],
		"title": "2° veicolo coinvolto"
		}
	}
	)};

	var num_totale_quad = function(){return(
{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|EXACT|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|GROUP|RECT|SUM|NOSIZE|RELOCATE|MULTIGRID",
		"colorscheme": [
			"18",
			"fruit"],
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"showdata": "true",
		"symbols": [
			"square"],
		"values": [
			"VELOCIPEDE",
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"0"],
		"label": [
			"VELOCIPEDE",
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "0.5",
		"scale": "0.3",
		"linecolor": "black",
		"linewidth": "1",
		"gridwidth": "500",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"markclasses": [],
		"title": "2° veicolo coinvolto"
		}
	}
	)};

	var num_totale_multigrid = function(){return(
	{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|EXACT|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATEPOS|RECT|SUM|NOSIZE|MULTIGRID",
		"colorscheme": [
			"18",
			"fruit"],
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"showdata": "true",
		"symbols": [
			"square"],
		"values": [
			"VELOCIPEDE",
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"0"],
		"label": [
			"VELOCIPEDE",
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "1.5",
		"scale": "0.3939488318738355",
		"linecolor": "black",
		"linewidth": "1",
		"gridx": "10",
		"gridwidthpx": "150",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "2° veicolo coinvolto"
		}
	}
	)};

	var num_totale_multigrid_II = function(){return(
	{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"type": "CHART|SYMBOL|EXACT|ZEROISVALUE|NEGATIVEISVALUE|AGGREGATE|GROUP|RECT|SUM|NOSIZE|RELOCATE|MULTIGRID",
		"colorscheme": [
			"18",
			"fruit"],
		"shadow": "false",
		"filter": "WHERE \\\"TIPO_VA\\\" = \\\"VELOCIPEDE\\\"",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"showdata": "true",
		"symbols": [
			"square"],
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"normalsizevalue": "0.5",
		"scale": "0.43663455000000007",
		"linecolor": "black",
		"linewidth": "1",
		"gridwidth": "550",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"evidence": "isolate_gray",
		"markclasses": [],
		"title": "2° veicolo coinvolto"
		}
	}
	)};

	var num_totale_user = function(){return(
	{
	"layer": "generic",
	"field": "$item$",
	"field100": "",
	"style": {
		"name":"test_user_drawn_theme",
		"type": "CHART|BUBBLE|SURFACE|VALUES|AGGREGATE|RECT|SUM|RELOCATE|USER",
		"colorscheme": [
			"#DE7A1A","#FAE9D6"],
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"showdata": "true",
		"units": "",
		"units": "",
		"normalsizevalue": "10",
		"scale": "1",
		"linecolor": "white",
		"linewidth": "3",
		"gridwidthpx": "15",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"title": "Incidenti 2011 - 2015"
		}
	}
	)};

	var num_totale_waffle = function(){return(
	{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"name":"waffle",
		"type": "CHART|SORT|SIZE|AGGREGATE|RECT|GRIDSIZE|EXACT|SUM|WAFFLE",
		"colorscheme": [
			"17",
			"fruit"],
		"filter": "WHERE \\\"TIPO_VA\\\" is \\\"VELOCIPEDE\\\"",
		"fillopacity": "0.9",
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"scale":"1",
		"linewidth": "5",
		"gridwidth": "100px",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"evidence":"isolate_gray",
		"markclasses": [],
		"title": "2° veicolo coinvolto"
		}
	}
	)};

	var num_totale_multigrid_waffle = function(){return(
	{
	"layer": "generic",
	"field": "TIPO_VB",
	"field100": "",
	"style": {
		"name":"waffle",
		"type": "CHART|SORT|SIZE|AGGREGATE|RECT|GRIDSIZE|EXACT|SUM|USER",
		"colorscheme": [
			"17",
			"fruit"],
		"filter": "WHERE \\\"TIPO_VA\\\" is \\\"VELOCIPEDE\\\"",
		"fillopacity": "0.9",
		"shadow": "false",
		"dbtable": "themeDataObj",
		"dbtableUrl": "https://raw.githubusercontent.com/gjrichter/data/master/incidenti_sap_2011_2015.csv",
		"dbtableType": "csv",
		"datacache": "true",
		"itemfield": "Y|X",
		"lookupfield": "Y|X",
		"symbols": [
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"square",
			"circle",
			"triangle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle",
			"circle"],
		"values": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"0"],
		"label": [
			"AUTO IN SOSTA",
			"AUTOBUS DI LINEA O NON IN EXTRAURBANA",
			"AUTOBUS O FILOBUS IN SERVIZIO URBANO",
			"AUTOCARRO",
			"AUTOSNODATO O AUTOARTICOLATO",
			"AUTOVETTURA PRIVATA",
			"AUTOVETTURA PRIVATA CON RIMORCHIO",
			"AUTOVETTURA PUBBLICA",
			"CICLOMOTORE",
			"IGNOTO",
			"MOTOCICLO A SOLO",
			"MOTOCICLO CON PASSEGGERO",
			"MOTOCICLO IN SOSTA",
			"QUADRICICLO",
			"VEICOLI SPECIALI",
			"VEICOLO POLIZIA O MIN. DIFESA",
			"VELOCIPEDE",
			"[non definito]"],
		"units": "",
		"scale":"1",
		"linewidth": "5",
		"gridwidth": "100px",
		"dominantfilter": "mean",
		"dominantdfilter": "0",
		"markclasses": [],
		"title": "2° veicolo coinvolto"
		}
	}
	)};
